### ISSUE TITLE
Deploy in qa.inspirehep.net

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1005]
Invenio 3 branch (probably once it has become `master`) should be deployed in http://qa.inspirehep.net

Here we can keep track of actions needed operations-wise.

**Comment by kaplun** [comment]
Mmh. This opens up a tiny issue: Currently prodsync on legacy is pushing to redis all modified records. And `continuous`(yes!)`_migration` on labs is pulling the records. How would we push modified records also on QA?

**Comment by jalavik** [comment]
Can we run two pushers? One that push to QA and another to production?

**Comment by kaplun** [comment]
Would be a bit heavy for legacy but I guess it's the only viable thing

**Comment by jmartinm** [comment]
This was done for AB.
