### ISSUE TITLE
Facets are presenting raw names (and values)

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1007]
![sso1](https://cloud.githubusercontent.com/assets/119349/13814327/15dd6b66-eb86-11e5-9049-623e8e4c90de.png)

cc: @jmartinm 

P.s. on a side note: should the actual facet string being considered as HMTL label for the checkbox? (hence clicking on the string would activate corresponding checkbox?)

**Comment by jmartinm** [comment]
> P.s. on a side note: should the actual facet string being considered as HMTL label for the checkbox? (hence clicking on the string would activate corresponding checkbox?)

Yes, facets should act and look like in https://qa.inspirehep.net/search
