### ISSUE TITLE
No results when MathJax is not reachable 

### ISSUE THREAD

**Issue by jacenkow** [inspirehep/inspire-next#1025]
Apparently when `MathJax` is not reachable (we use an external source) all pages that use it crash.
It is caused by these few lines
```js
<script type="text/javascript">
  require([
    "jquery",
    ], function ($) {
      $(document).ready(function () {
        MathJax.Hub.Config({
          tex2jax: {inlineMath: [['$', '$'], ['\\(', '\\)']],
          processEscapes: true},
          showProcessingMessages: false,
          messageStyle: "none"
        });
        MathJax.Hub.Queue(["Typeset", MathJax.Hub]);
      })
    }
  );
</script>
```
since `MathJax` is not defined.

**Comment by eamonnmag** [comment]
This should never happen. You can wrap things with a try/catch but in reality it's not required.

**Comment by jacquerie** [comment]
SPOF! I'd wrap with a try/catch and fetch it from the filesystem if the CDN fails.

**Comment by jacenkow** [comment]
:+1: for @jacquerie

**Comment by jalavik** [comment]
Too cumbersome to worry about local copy of MathJax honestly, which is why we use CDN. Otherwise building assets takes forever. What about checking for existance of MathJax instead?

```javascript
if (window.MathJax !== undefined) {
    // do stuff
}
```

**Comment by jacenkow** [comment]
@jalavik yeah taking care of it

**Comment by jacenkow** [comment]
![mathjax](https://cloud.githubusercontent.com/assets/12476583/14171598/0f4e8172-f734-11e5-9e7e-02c702abf4d9.png)

@jalavik  It does not look so bad.

**Comment by jalavik** [comment]
Yeah, generally it will not fail, but yeah, fallback to none looks good.

**Comment by jacquerie** [comment]
> Otherwise building assets takes forever.

Ah yeah, now I remember... :fearful:
