### ISSUE TITLE
Use Literature as default collection when visiting /search

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1033]
Going to `/search` displays the search results for Literature, but the search bar and the collection bar do not correctly highlight the collection selected:

![screen shot 2016-04-05 at 2 48 22 pm](https://cloud.githubusercontent.com/assets/580727/14282214/b0ee7782-fb3d-11e5-8266-26bec9afd775.png)

**Comment by eamonnmag** [comment]
This should be fixed in the latest pushes by me.

**Comment by jmartinm** [comment]
There is a just an `else` missing in the following filter https://github.com/inspirehep/inspire-next/blob/invenio3/inspirehep/modules/theme/jinja2filters.py#L707
