### ISSUE TITLE
Detailed view: get record from ElascticSearch

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1038]
Now that the record class is configurable in `invenio-records-ui` (see https://github.com/inveniosoftware/invenio-records-ui/pull/35/files#diff-0), we should create our custom class that loads the record from ElasticSearch instead of from the database.

**Comment by kaplun** [comment]
@mihaibivol is it something you can look into?

**Comment by mihaibivol** [comment]
Will we ever need the db record ever again afterwards?

Currently we have this
https://github.com/inspirehep/inspire-next/blob/invenio3/inspirehep/utils/record_getter.py#L63 to get the record from ES.

Should we also add some `ESRecord` class that inherits from `invenio_records` `Record` in `modules/records` and use that as a wrapper?

**Comment by mihaibivol** [comment]
To be more precise.

We should still keep the helpers for any other use in which we have a `recid` and `record_type` and just plug in a class that on get_record does this https://github.com/inspirehep/inspire-next/blob/invenio3/inspirehep/utils/record_getter.py#L67-L72

This way, in the detailed view for any record we will always have the correct enriched ES record?

**Comment by kaplun** [comment]
> Will we ever need the db record ever again afterwards?

Yes, whenever the record is retrieved for modification.

**Comment by mihaibivol** [comment]
Summing up the discussions we had. We're building `modules/record/es_record.py` which will look something like this:

```python
class ESRecord(object):
  
    @classmethod
    def get_record(cls, object_uuid, deleted=False):
        # TODO get pid object from object_uuid (extra DB call don't know how to get around it)
        return record_getter.get_es_record(pid.pid_type, pid.pid_value)
```

@jmartinm Are there any exceptions that the detailed view catches in order to present 404 instead of 500 for example.

**Comment by jmartinm** [comment]
@mihaibivol  Yes, you can have a look here https://github.com/jirikuncar/invenio-records-ui/blob/8e74b5dcd846da1c691a94bfb164c5146c5b0955/invenio_records_ui/views.py#L123

**Comment by jmartinm** [comment]
I see now the reason why the references are not loaded properly is [here](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/utils/references.py#L480)

As the references are retrieved from ES with an `mget` call:

```
records_from_es = es.mget(body={
                    "ids": refs_to_get_from_es
                }, index="records-hep")['docs']
```

But as `ids` we are passing recids. The `ids` need to be `uuids` instead.

So now the issue is that all references contain a recid and not the uuid of the pointed record, so we cannot do an `mget` call to get them all efficiently it seems.

Shall we add `uuids` in the metadata?

**Comment by kaplun** [comment]
:boom: This is **the** question.

Right now we identify records with their legacy `recids`. In principle this doesn't add any benefit beside backward compatibility.

Shall we simply have UUIDs as canonical ID, and have `recids` supported as fallbacks, then? In such a proposal all linking should happen through UUIDs.

**Comment by mihaibivol** [comment]
But why don't we use a reference resolver over the whole `references` field there. We don't need to parse recids and do an ES query, we can just call replace_refs and have all the references fields for the datatables.
