### ISSUE TITLE
Clean dois function is missing

### ISSUE THREAD

**Issue by ioannistsanaktsidis** [inspirehep/inspire-next#1043]
We had this function for cleaning the duplicate dois before updating and inserting record. This needs to be merged in invenio3.
The previous version: https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/records/receivers.py

**Comment by ioannistsanaktsidis** [comment]
cc @kaplun @jmartinm .

**Comment by kaplun** [comment]
This is a more general problem of not allowing duplicate fields. We can write a generic before_record_update/insert receiver that removes duplicates everywhere...

@jacquerie what do you think? I just fear it might have performance impact...

**Comment by jacquerie** [comment]
It's not that big of a deal. Out of 40k validation errors only 713 were violations of `uniqueItems` constraints. The `dedupers` utils allow us to easily write DoJSON rules that don't add duplicates, which will cover the initial import and harvests/submissions. I don't think we need to do a lot more than that.
