### ISSUE TITLE
Make validation errors graceful during migration

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1045]
Currently any `jsonschema` validation error happening during migration causes an unhandled exception.
We should capture the error log it and continue.

This is a blocker for @nikpap & @tomaszgy

**Comment by jalavik** [comment]
FYI @bittirousku @tomaszgy (sorry I was telling the wrong things) 😞

**Comment by kaplun** [comment]
As discussed IRL with @tomaszgy this can be implemented by:
* [ ] patching `invenio-records` by introduce a flag to make validation optional
* [ ] improving migrator by first trying with validation, capturing exceptions, and then re-trying without validation while properly log the validation error.

**Comment by kaplun** [comment]
@tomaszgy you haven't yet started working on this, have you?

**Comment by jmartinm** [comment]
Not sure if this can be used https://github.com/inveniosoftware/invenio-records/pull/127/files#diff-0 for this PR.

**Comment by kaplun** [comment]
Not really because `invenio-index` relies on the schema being in JSON to then decide the index.

**Comment by kaplun** [comment]
BTW with @jacquerie we were discussing that in principle, dojson should always produce records that are passing the schema validation: 
* in case of not recognized fields in the input these are simply ignored
* in case of not valid enum for a given input we should:
  * try to normalize the value automatically
  * always have a `_raw` subfield for recording the unrecognized value.

Since this will take a bit of time to implement, for the time being, we can simply skip failing records, and log them.

**Comment by jmartinm** [comment]
Sounds good, so as we just discussed the 'solution'  to this issue will be, like in Invenio 2.x to have a migration table where we store the incoming MarcXML and a validation flag to be able to find the records that did not pass validation. Then dojson will be improved and records rerun

**Comment by jmartinm** [comment]
This is now merged.
