### ISSUE TITLE
Support for legacy /record/NNNN URLs

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1051]
- [ ] ~~PidStore for recid type~~ (Done in a different way)
- [x] Automatic permanent redirection to the corresponding /literature or /author or ... type

**Comment by kaplun** [comment]
@jacquerie your PR #1195 can refer/close this ticket.

**Comment by kaplun** [comment]
Sorry, forget about this. This is a redundant epic test

**Comment by jacquerie** [comment]
There's other stuff we need to port! URLs like `/record/N/exporters/xm` should be redirected to the appropriate things. So this can stay open.

**Comment by kaplun** [comment]
More importantly /author/profile/B.Storaci.1 should now redirect to /author/123. This are the user HTML visibile URLs, that might have been bookmarked. The other are more APIs like that would be a bonus to maintain, but not necessary (especially since we move away from MARCXML)

**Comment by jacquerie** [comment]
> More importantly /author/profile/B.Storaci.1 should now redirect to /author/123

I wonder if this is desired behaviour. The BAI is short and memorable, while the numeric ID is a little more impersonal...

In any case, it can be easily implemented by a query on `inspire_id` in the JSON blob and then a redirect.

**Comment by kaplun** [comment]
Yep, it's open to discussion. The thing is that BAI is not necessary permanent. Users can amend them. but they are indeed unique (hence we should also reserve it into the pidstore)

**Comment by jacquerie** [comment]
The more general discussion of legacy URLs redirection will be opened and specced elsewhere.
