### ISSUE TITLE
Improve PDF checking in literature suggestion form

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1057]
As suggested by @kaplun the following code can be added to the PDF validator:

``` python
import requests
import PyPDF2

try:
     PyPDF2.PdfFileReader(requests.get(url), strict=False)
except PyPDF2.utils.PdfReadError as err:
    raise StopValidation(err)
```

We just need to make sure that this validator runs async and probably disable it on form submission so that it does not delay the sending of the form.

**Comment by kaplun** [comment]
You mean: it has run by the time the user reaches the submit button then we are good otherwise too bad?

How far is the field from the submit button? I remember it was quite close, so most of the time such check will not have time to run, correct?

**Comment by jmartinm** [comment]
> How far is the field from the submit button? I remember it was quite close, so most of the time such check will not have time to run, correct?

It's actually quite at the top and not that close to the submit so might be fine. We could see if there is an ongoing request and when clicking on submit waiting for it to finish (to make sure all validators are done)

**Comment by kaplun** [comment]
> We could see if there is an ongoing request and when clicking on submit waiting for it to finish (to make sure all validators are done)

:+1: That would be ideal. You can gray out the submit button and put a message next to it: `... still checking for validity of the provided PDF...`

**Comment by kaplun** [comment]
cc: @jacquerie @david-caro this is a problem also when harvesting arXiv.

**Comment by kaplun** [comment]
E.g. with the current code:
https://dspace.library.uu.nl/bitstream/handle/1874/18575/jacobsohn_60_relations.pdf the server is replying mimetype `image/pdf`(sic!!!) which is then considered as invalid.
