### ISSUE TITLE
Update invenio-search, invenio-query-parser, invenio-records-rest

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1060]
After the changes in Invenio modules in order to use `elasticsearch-dsl`, update the search related packages and changes will have to made, for example in https://github.com/inspirehep/inspire-next/blob/invenio3/inspirehep/modules/search/query.py

(see example of `query` class config in https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/query.py)

Also note that we need to use our own query parser (see example here https://github.com/inveniosoftware/invenio-query-parser/blob/master/invenio_query_parser/contrib/elasticsearch/__init__.py)

**Comment by kaplun** [comment]
My understanding is that we have to wait 1 month or so in order to see stabilization... So we can better stay with our pinned version for the time being?

**Comment by jmartinm** [comment]
I think it might be better to move on to the new `elasticsearch-dsl` way early on. Otherwise it might become quite a difficult upgrade in a month. I will create a WIP branch to try it out.

**Comment by kaplun** [comment]
But won't it crash all the time due to their upgrades?  They are currently not having all packages aligned... Well hopefully the above mentioned one yes...

**Comment by jalavik** [comment]
I believe this has been completed now.
