### ISSUE TITLE
Development guidelines for beard-server

### ISSUE THREAD

**Issue by jacenkow** [inspirehep/inspire-next#1072]
As mentioned during today's Scrum meeting I would like to set some guidelines regarding development of `beard-server`.

As I understand, @jalavik would like to get rid of `beard` package from `inspire` machines, since the package itself is dependent on `scipy` and `numpy` and it seems pretty ineffective to keep them just in order to use one of `beard` features.

So from me, `beard-server` should serve first of all as a `Celery` worker to cluster `HEP` authors every, let's say, 3 days and as we know clustering is pretty a *data-intese* task thus choosing `Celery` in favour of `HTTP API` seems pretty reasonable.

The other task is calculating phonetic blocks on `before_record_index` signal (btw missing in `invenio3`). This can be also implemented as a `Celery` task.

However we can use our model and expose an `API` that would allow, for example, for calculating probabilities of belonging one signature to the same cluster as another one, which is pretty useful when one would like to match author from resource `A` to an author from resource `B`.

**Comment by jacenkow** [comment]
Sorry, thought that it is possible to assign more than one person.

CC: @kaplun

**Comment by kaplun** [comment]
> The other task is calculating phonetic blocks on before_record_index signal (btw missing in invenio3). This can be also implemented as a Celery task.

I believe this is one of those utils that don't need anything from scikit-learn/numpy/scipy, and can be hence factored out and left directly into inspire-next. Otherwise it would have a too big performance impact, in terms of all the thousands of requests, per every time a record is touched.

**Comment by jalavik** [comment]
@jacenkow Sounds good. Also agree with @kaplun that for minor utils which are stable used often we can copy them over to the overlay for simplicity.

Regarding the `beard` API, we should also have an endpoint for the prediction of various actions we use in workflows. I can provide more details on that next week.

**Comment by jacenkow** [comment]
@kaplun @jalavik I think we can close this issue and move to `beard-server` repo?

**Comment by jacenkow** [comment]
Closing.
