### ISSUE TITLE
Move to EOS

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1086]
Here's the recipe, courtesy of @lnielsen:
- [ ] install `xrootd-python` bindings (see below)
- [ ] install `XRootDPyFS`
- [ ] point `invenio-files-rest` to `root://eospublic.cern.ch//eos/<project>/`
- [ ] run `k5reauth -x -f -k /etc/<keytab> <user>@CERN.CH` on all the machines

Notes: 
- `k5reauth` as a service is being added to the puppet Invenio module: when a machine starts it will start `k5reauth`.
- a service account is assumed.
- To build `Xrootd` for a `virtualenv`: see https://gitlab.cern.ch/ai/it-puppet-hostgroup-zenodo/blob/qa/code/files/zenodo/tasks.py#L81
- To make sure `xrootdpyfs` is loaded: https://github.com/zenodo/zenodo/blob/master/zenodo/modules/xrootd/ext.py

**Comment by lnielsen** [comment]
Yum packages needed: 
https://gitlab.cern.ch/ai/it-puppet-hostgroup-zenodo/blob/qa/code/manifests/worker3.pp#L41-44

k5reauth must be run as the user running the WSGI application (note @egarbancho is working on making this into service that starts at boot time).

**Comment by egabancho** [comment]
https://gitlab.cern.ch/ai/it-puppet-module-invenio/merge_requests/5 💃
