### ISSUE TITLE
Conference alternative titles 711

### ISSUE THREAD

**Issue by bittirousku** [inspirehep/inspire-next#1095]
In **Conferences** collection we have MARC fields `711__a` and `711__b`. The following is from [Twiki](https://twiki.cern.ch/twiki/bin/view/Inspire/DevelopmentRecordMarkupConferences):

```
711 a  other-title   alternative titles, acronyms (for display)
    b                alternative titles, acronyms (for searching)
```

At the moment we have 462 records with `711__b` and 385 of them do not have `711__a`.
Total number of records with `711__a` is 6503 and 6426 of them do not have `711__b`.

**Question**: Do we want to keep the 711__b?

CC: @kaplun @inspirehep/inspire-dir

**Comment by kaplun** [comment]
cc: @inspirehep/inspire-dir

**Comment by kaplun** [comment]
We shall consider that it should be in principle possible to generate `711__b` automatically, if it contains really what it says. So the question is how it was actually used on production up to now?

**Comment by jacquerie** [comment]
AFAICT (I haven't looked at the data, just the descriptions!) `711__b` can be tricky to generate from `711__a`: think removing "the" and other stopwords, adding dashes and proper capitalization. Maybe a KB is what we want, rather than adding new fields to our data model?

**Comment by kaplun** [comment]
Yep yesterday at INSPIRE standup was discussed the issue. So indeed it might be that it's not possible to generate 711__b automatically from the record. However it opens up the question of expanding terms via synonims (e.g. cities having different names or different ways to call an institution).

IMHO this should be solved at indexing time (e.g. with KBs) at the same time we can still copy over this 711__b and then simply ignore it :-)

**Comment by aw-bib** [comment]
As stated in standup, my feeling is that most similar to adding a subfield in Marc is adding a new synonym by adding a field in an authority record. (From a cataloguers point of view.) Given an easy lookup/edit it would be almost seamless.

This also opens the possibility to add more than one form or some additional data helpful for retrieval. For conferences, the existing conference records could serve as such an authority record.

Looking e.g. at http://inspirehep.net/record/973801/export/hm

values from `411`, which I'd prefer for _other forms of name_, and `711` sound suitable (I do not understand `711`) as expansion for the indexer, as is 111 with the full form and details. Similarly `653` could be interesting.

**Comment by ksachs** [comment]
711 $$b in conferences is similar to 210$$a in HEP
Both fields include text/words that catalogers find useful for searching, but should not be visible to users (other than marc). It can contain variants for acronyms or spelling variations. Some of this can be created automatically. Please continue to provide a place for non-visible custom (i.e. cataloger maintained) name variations.

**Comment by kaplun** [comment]
@ksachs I guess we can keep on having these fields (and copy over the current value during migration). However they would be more effective if indeed such expansions were proposed in a more central place, such as a synonym table. In this way, by writing down the mapping once it can be used to search for free in all the records.

**Comment by ksachs** [comment]
You are absolutely right when it concerns standard synonyms. But a given acronym might have 2 different meanings - so a mapping doesn't work. For conferences it's often the FEL-2009 / FEL2009 / FEL 2009 variation (where the indexer might learn to be smarter).

**Comment by aw-bib** [comment]
If I get it right, you have some _also known as_ relation which might result from a spelling error or different usages of an acronym _in the wild_. I'd still propose to store those in the conference records (enabling the conference as such to be found by those misspellings as well) and expand them at indexing time from those records.

**Comment by david-caro** [comment]
@kaplun if you are not working on this, move back to ready and unassign :+1:

**Comment by jacquerie** [comment]
Again a content decision. @michamos, can you have a look?

**Comment by michamos** [comment]
We decided in inspirehep/inspire-schemas#141 to migrate them to `alternative_titles`, but discourage their future use. So this is solved.
