### ISSUE TITLE
Normalization routines

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1100]
As part of the regular record manipulation that can happen in several components of INSPIRE we should centralize the concept of normalization, e.g. by creating a central utility module. 

These utilities would be used both in a record and in the references and can be triggered via a `before_record_update/insert` signal.

Example of needed routines:
- [ ] `normalize_journal_title()`: Transforming journal title into its normative form (by looking up into Journal database) 
- [ ] `normalize_id()`: Normalizing isbn/issn/dois using `idutils`
- [ ] `normalize_author_name()`: again by looking up into author records in order to understand what is the potential family name(s) Vs. first name(s) (when not known in advance)
- [ ] `normalize_unicode`: e.g. conflating spaces, apostrophes, dashes (see #1219)

More?

This is related to #1099.

**Comment by bing13** [comment]
nice idea.

**Comment by aw-bib** [comment]
We solved such issues in Invenio 1.x by performing searches in the authorities relevant and returning the proper values by output format definition. In case of authors e.g. thus you do not need to know the name components for this search.

BTW: for name normalization we could contribute the piece of python join2 uses in the importers. This issue is actually quite tricky IRL as you have stuff like "Walther von der Vogelweide for the Atlas Collaboration" effectively ending up in two authors "von der Vogelweide, Walther". (Some 200 lines of testcases...)

**Comment by kaplun** [comment]
Sure why not? If there is some reusable part that can be adapated...

**Comment by aw-bib** [comment]
Are you interested in the "splitter" as well? Handling something like `Doe, Joe ; Smith, John` vs. `Joe Doe, John Smith`.

Usually, we have something like

``` python
for inputname in SplitNameList(namelist):
     store(NormalizeName(inputname))
```

I need to flesh it out from `libHandleNames`. What would be a suitable way to give you access?

**Comment by kaplun** [comment]
Well, ideally either you have a GPLed repo on Github or you can make a library out of it and uploading to pypi?

I don't understand what exactlty the splitter does.

**Comment by aw-bib** [comment]
GPL is ok github is sort of ok (its a closed repo). Them main problem is that you'd like to have one or at maximum two functions of the whole lib which is a bit bound to our authority usage. So making this a lib is a bit too much, IMHO. The whole `libHandleNames` implements some author to authority guessing, affiliation extraction from authorities and so on, this is not suitable for inSPIRE.

The splitter takes a list of names as string, either spearated by `;` or `,` splits it apart to individuals. Think of copy&paste of an authors list from a given PDF.

**Comment by kaplun** [comment]
I think most of these are dealt within `inspire-schemas` package, but I am not fully sure. @michamos? In particular I think there is no real normalization for author names, (e.g. to clean up white spaces) or journals...

**Comment by michamos** [comment]
This is the current status:
- [ ]  journal title normalization is being added to the workflows in #2938
- [x] id normalization is handled in the `LiteratureBuilder` by using `idutils`
- [x] author name normalization is handled by `inspire-utils` these days and called in the `LiteratureBuilder`
- [ ] unicode normalization is not systematically implemented

So I think it's OK to close this.
