### ISSUE TITLE
Further development of author profiles

### ISSUE THREAD

**Issue by jacenkow** [inspirehep/inspire-next#1105]
Opening an issue to track `TODO`s for profile pages.

Missing data:
- [x] co-authors
- [x] H-index

To do:
- [x] hookup citations count from `HEP` publications
- [x] hookup impact graphs for each publication
- [x] remove profile picture as well as keywords while website is run on mobile devices

**Comment by eamonnmag** [comment]
See https://github.com/inspirehep/inspire-next/pull/1151/commits/e91bf0ec3eeb1752f916dcb5123c3bb3108a7ce7 for h-index and i10 index code.

**Comment by kaplun** [comment]
@eamonnmag the commit SHA is no longer valid.

**Comment by eamonnmag** [comment]
https://github.com/inspirehep/inspire-next/pull/1151/commits/37e7f948aa6510bbb7b92693855b38862fb36e87

**Comment by kaplun** [comment]
It just needs then to be feed (in a performant way) with proper citation data.

**Comment by jacquerie** [comment]
h-index is now here: https://github.com/inspirehep/inspire-next/blob/3a40fbfb3ad21b769022136067b755e295ca1e76/inspirehep/utils/stats.py
