### ISSUE TITLE
demo records don't have recids in references

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1127]
With the latest demo records, such as `http://localhost:5000/api/literature/712925`, no recids are present in references:

```
"references": [
{
"journal_pubnote": [
"Phys.Lett.,B199,286"
]
},
{
"journal_pubnote": [
"Phys.Rev.,D37,2668"
]
},
{
"journal_pubnote": [
"Phys.Lett.,B305,402"
]
},
{
"journal_pubnote": [
"Phys.Rev.Lett.,72,812"
]
},
{
"journal_pubnote": [
"Phys.Lett.,B371,157"
],
"report_number": [
"hep-ex/9601001"
]
},
{
"journal_pubnote": [
"Z.Phys.,C34,163"
]
},
{
"journal_pubnote": [
"Phys.Lett.,B268,145"
]
},
{
"journal_pubnote": [
"Phys.Lett.,B292,210"
]
},
```

They used to be there in the past (exported by `xme` format in production), and used to resolve the references in detailed records.

@kaplun  ?

**Comment by kaplun** [comment]
The XME format well contain the recids, however, the referred records in your example are not in the demo record. 

If you want to have a look to a record having citation see:
https://github.com/inspirehep/inspire-next/blob/master/inspirehep/demosite/data/demo-records-links.txt#L2

E.g. 11883

**Comment by jmartinm** [comment]
I see, so for a record that does have references that can be resolved, the JSON looks like:

```
"references": [
{
"journal_pubnote": [
"Phys.Lett.,12,132"
],
"record": {
"$ref": "http://localhost:5000/api/literature/40440"
}
},
```

As discussed with @kaplun IRL, a separate issue is that the recid should be present as well. Will create a separate issue for this.

**Comment by kaplun** [comment]
cc: @mihaibivol

**Comment by mihaibivol** [comment]
The unit tests assert this behavior: https://github.com/inspirehep/inspire-next/blob/master/tests/unit/records/test_records_receivers.py#L28

Does the API load things from ES or from the database?

**Comment by kaplun** [comment]
Yep. So seems DB is used instead of ES?

**Comment by jmartinm** [comment]
Ah right, for detailed pages we are still loading the records from DB. Finishing [this issue](https://github.com/inspirehep/inspire-next/issues/1038) should solve it.

**Comment by jmartinm** [comment]
Related https://github.com/inspirehep/inspire-next/issues/1038#issuecomment-220973004
