### ISSUE TITLE
DESY Keywords

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1137]
As part of the mapping of MARCXML to JSON, we have to define `dojson` rules and the final `JSONSchema` representing all the information previously encoded in MARCXML.
- What is the meaning of DESY keywords? 
- `595_D $a`: https://github.com/inspirehep/inspire-next/blob/master/inspirehep/dojson/current_marcxml_usage/hep.txt#L4689 What is the meaning of these letters? How should this be mapped in JSON? Is this field repeatable?
- `595_D $a`: https://github.com/inspirehep/inspire-next/blob/master/inspirehep/dojson/current_marcxml_usage/hep.txt#L4740 What are these dates?
- `595_D $s`: https://github.com/inspirehep/inspire-next/blob/master/inspirehep/dojson/current_marcxml_usage/hep.txt#L4755 What are these codes?
- `595__ $b`: https://github.com/inspirehep/inspire-next/blob/master/inspirehep/dojson/current_marcxml_usage/hep.txt#L4801 Are these always scan barcodes from CERN?
- `595__ $s`: https://github.com/inspirehep/inspire-next/blob/master/inspirehep/dojson/current_marcxml_usage/hep.txt#L4929 What is this?

For reference the TWiki states:

```
[...]
595 a   internal note   hidden-note
    b   internal number old numbers from CDS, barcodes etc. (CM-)P00******
    c   internal cern field CDS tag for harvesting  "CDS"
    h   internal HAL field  tag for export  'y"/"n"
595_D   d   desy_timestamp   
    s   desy_status keyword assignment status of record: XDRN, 'abs'/'full'/'fullabs', 'printed', 'final', 'noprint'
    a   desy_expert letter of external expert
[...]
```

**Comment by kaplun** [comment]
@annetteholtkamp @ksachs @fschwenn (@bittirousku)

**Comment by annetteholtkamp** [comment]
These are internal DESY bookkeeping tags.
Some (all?) will become superfluous as soon as all journal workflow steps are integrated in the HP.
For Kirsten and Florian to say where to store the existing info.

- Annette

On May 23, 2016, at 4:38 AM, Samuele Kaplun <notifications@github.com<mailto:notifications@github.com>> wrote:


As part of the mapping of MARCXML to JSON, we have to define dojson rules and the final JSONSchema representing all the information previously encoded in MARCXML.

  *   What is the meaning of DESY keywords?
  *   595_D $a: https://github.com/inspirehep/inspire-next/blob/master/inspirehep/dojson/current_marcxml_usage/hep.txt#L4689 What is the meaning of these letters? How should this be mapped in JSON? Is this field repeatable?
  *   595_D $a: https://github.com/inspirehep/inspire-next/blob/master/inspirehep/dojson/current_marcxml_usage/hep.txt#L4740 What are these dates?
  *   595_D $s: https://github.com/inspirehep/inspire-next/blob/master/inspirehep/dojson/current_marcxml_usage/hep.txt#L4755 What are these codes?
  *   595__ $b: https://github.com/inspirehep/inspire-next/blob/master/inspirehep/dojson/current_marcxml_usage/hep.txt#L4801 Are these always scan barcodes from CERN?
  *   595__ $s: https://github.com/inspirehep/inspire-next/blob/master/inspirehep/dojson/current_marcxml_usage/hep.txt#L4929 What is this?

For reference the TWiki states:

[...]
595 a   internal note   hidden-note
    b   internal number old numbers from CDS, barcodes etc. (CM-)P00******
    c   internal cern field CDS tag for harvesting  "CDS"
    h   internal HAL field  tag for export  'y"/"n"
595_D   d   desy_timestamp
    s   desy_status keyword assignment status of record: XDRN, 'abs'/'full'/'fullabs', 'printed', 'final', 'noprint'
    a   desy_expert letter of external expert
[...]

**Comment by fschwenn** [comment]
These are not all internal DESY bookkeeping tags.
595_D is 'owned' by DESY. Anything in 595__ from DESY is irrelevant and can be deleted, but from my impression most things in 595__ are from elsewhere.
None of these 595_D will become superfluous as soon as all journal workflow steps are integrated in the HP. They concern the bookkeeping of assigning keywords by external experts.

**Comment by kaplun** [comment]
Thanks @fschwenn. Can you then help us mapping these to JSON? How would they fit in our current https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/records/jsonschemas/records/hep.json

**Comment by fschwenn** [comment]
Would be something like this:

"bookkeeping_keywording": {
    "uniqueItems": true,
    "items": {
        "type": "object",
        "properties": {
            "expert": {
                "type": "string"
            },
            "date": {
                 "type": "date"
            },
            "status": {
                  "enum": [
                      "full", 
                      "abs", 
                      "fullabs", 
                      "printed", 
                      "final", 
                      "noprint"
                   ],
                   "type": "string",
            }
        }
    },
    "type": "array",
    "description": "Keeps track of status of keywording done by external experts.",
    "title": "Keywording Bookkeeping"
 }

**Comment by kaplun** [comment]
Is expert representing a person? An actual user? Would we be able at some point to assume such expert has a profile in INSPIRE and we can link to it?

**Comment by fschwenn** [comment]
'expert' contains a letter representing a real researcher (user) who does the keywording (in the old days all papers were printed, we wrote the letters by hand on it, sorted them, and sent them to the expert). As all this is just temporary stuff, the relation letter->real person (at the moment) is not persistent. Whether we want to change this and instead have the INSPIRE-ID in that field, I do not know. 

-- 
Florian Schwennsen 
Deutsches Elektronen-Synchrotron DESY 
Building 01 Room O1.446 
phone: +49-40-8998-6190

**Comment by kaplun** [comment]
OK, so let's say for the time being we do not do further interpretation on these values and copy as from legacy using the schema you suggest. Thanks!

**Comment by kaplun** [comment]
@bittirousku can you take care of amending hep.json/dojson accordingly?

**Comment by bittirousku** [comment]
@kaplun Ok!

**Comment by jacquerie** [comment]
I _accidentally_ fixed this as part of https://github.com/inspirehep/inspire-next/pull/1918 (I wasn't even aware of this issue...)
