### ISSUE TITLE
Support for multiple native names

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1154]
We need to support more than one native name in Authors:
- [ ] Check Dojson
- [ ] Check schema
- [ ] Check mapping
- [ ] Check format

**Comment by aw-bib** [comment]
The usual use cases are name changes due to marriages/divorces etc.

Sounds like going for aliases in author authorities that get expanded in case.

**Comment by kaplun** [comment]
`native_names` is an `array` in the schema now.
https://github.com/inspirehep/inspire-schemas/blob/master/inspire_schemas/records/authors.yml#L151
