### ISSUE TITLE
workflows: migration from Labs to v3

### ISSUE THREAD

**Issue by jalavik** [inspirehep/inspire-next#1171]
Implement migration steps (possibly using `invenio-migrator`) to migrate current workflow objects on Labs (version 2) to version 3: 

invenio-workflows DB migration of model
- [x] _task_counter -> callback_pos
- [x] version -> status

extra_data fields:
- [x] arxiv_guessing to new key & data model
- [x] classifier results to new key

data fields:
- [x] pre-generated arXiv URLs in urls
- [x] potentially recreate metadata with dojson

files in fft before upload:
- [x] compatibility layer with FFT for existing objects, new objects will use files API

**Comment by kaplun** [comment]
See #1226

**Comment by kaplun** [comment]
@david-caro @jmartinm what is the status of this? Do you actually understand what they are the above missing points?

**Comment by jalavik** [comment]
@kaplun Just to quickly clear up:

The point "pre-generated arXiv URLs in urls" is not a blocker per se as it was an idea @eamonnmag had that the full URLs to arXiv was in the metadata avoiding client side code doing generation of arXiv URL from the identifier.

The FFT part is related to the fact that the older workflow objects in the `labs` Holding Pen have fft style structures, while newer objects use the `files` structure.

**Comment by kaplun** [comment]
@jalavik thanks for the input. Currently though the FFTs have still to be produced to be batchuploaded. Is this already taken care of?

**Comment by kaplun** [comment]
(BTW: Greetings to you!! Nice to read you)

**Comment by jalavik** [comment]
@kaplun Thanks the same :)

So FFT style structures can still be generated from the new files structure before a robotupload, but I do not think this is done at the moment..
