### ISSUE TITLE
profiles: missing email / gravatar bug

### ISSUE THREAD

**Issue by jacenkow** [inspirehep/inspire-next#1178]
If an author does not have an e-mail address, rendering of an author profile will fail due to this line
```html
<img class="profile-image img-circle" src="{{ record['positions'][0]['email'] ...>
```

**Comment by jacenkow** [comment]
CC: @jmartinm

**Comment by jacquerie** [comment]
I'd say "hold your horses" on this one, since an overhaul of emails is coming in the schemas.

**Comment by jmartinm** [comment]
Yep, that was a very quick thing for the AB presentation. See commit log message https://github.com/inspirehep/inspire-next/commit/d52028a079ca1d12a8bb3c1770f38080d8b575ee ;)

Once schemas are clean we need a utility function to get the preferred email address from an author record.

**Comment by jacquerie** [comment]
#1170 has landed, so this can proceed.

**Comment by jacenkow** [comment]
@jacquerie thanks for coming back!

**Comment by jacquerie** [comment]
A very quick fix: `record['positions'][0].get('email', 'gravatar@inspirehep.net') | gravatar`, and we register `gravatar@inspirehep.net` to Gravatar.
