### ISSUE TITLE
See citations involving only Published papers

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1183]
At the moment, we have a breakdown of citations for a given search:

![screen shot 2016-06-07 at 1 18 19 pm](https://cloud.githubusercontent.com/assets/580727/15855876/5da962e8-2cb2-11e6-84e4-6f57b5c4ac3c.png)

The column with `Published only` represents papers that are Published only but the citation counts include papers that are not Published.

The user requests a view were only Published papers are involved.

**Comment by jacquerie** [comment]
Blocked by #1215 for now.

**Comment by eamonnmag** [comment]
We need to add this to the authors page. It was missing from my initial
mockups. Maybe with the time line view.

**Comment by kaplun** [comment]
Actually this is simply implemented in #1304
