### ISSUE TITLE
Unify dropdowns look & feel

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1185]
We currently have a few different types of dropdowns across the site that don't all go with the overall look&feel and can appear differently across browsers. Even though there does not seem to be a standard way of doing this http://stackoverflow.com/a/15508240/890185 we can try using Bootstrap styling or https://select2.github.io/

![screen shot 2016-06-07 at 1 53 10 pm](https://cloud.githubusercontent.com/assets/580727/15856667/3799b7e2-2cb7-11e6-8053-851bfca340c5.png)

![screen shot 2016-06-07 at 1 53 55 pm](https://cloud.githubusercontent.com/assets/580727/15857636/ab82e4d0-2cbc-11e6-8c20-494c9280cbb2.png)

![screen shot 2016-06-07 at 1 54 13 pm](https://cloud.githubusercontent.com/assets/580727/15856687/537352b6-2cb7-11e6-9754-227dd51b0854.png)

**Comment by StellaCh** [comment]
this is now fixed
