### ISSUE TITLE
jsonschema: harmonize document_type Vs. collection

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1215]
Currently the `collection` field is just a porting of MARC `980`. E.g.:
```json 
{"collections": [
    {"primary": "CORE"},
    {"primary": "Book"},
    {"primary": "HEP"},
    {"primary": "Citeable"}
]}
```

On the other hand the concept of `document_type` is managed by the enhancer `facet_inspire_doc_type`. E.g.:
```json
{"facet_inspire_doc_type": ["book"]}
```

This is suboptimal.
* [ ] `Citeable` should become a flag and be added at indexing time based on other values
* [ ] `CORE` should be declared as a flag and be available in all schemas
* [ ] `HEP` is actually redundant since it represents the fact that this is a record from Literature
* [ ] `facet_inspire_doc_type` should become `document_type` and be populated by dojson, rather than enhanced before indexing.

**Comment by kaplun** [comment]
I think we should bump priority of this one, since category is really scattered around the code base in a wrong way.

**Comment by jacquerie** [comment]
This needs a spec. The thing I refactored in https://github.com/inspirehep/inspire-next/blob/25cba484c652d21c112628c4967e684c02d6fcfd/inspirehep/modules/records/receivers.py#L120-L210 is a 1 to 1 correspondence with the code that was there before, but makes no sense to me.

You need to define precisely:
- What should we do with `collections`
- What are the allowable `document_types`
- How are the `980__a` values mapped to those allowable values
- What is the algorithm that sets `Citeable`

**Comment by kaplun** [comment]
> What should we do with collections

Should disappear.
> What are the allowable document_types

Exactly the keys that  you have defined in the two tables in the docstring `populate_inspire_document_type()`.

> How are the 980__a values mapped to those allowable values

Those that are document types are mapped to document types (possibly with the same value as in 980). Those that are flags, such as `citeable` and `core` should be mapped to a corresponding flag. (I think we have it for core already). `deleted` is also mapped to a deleted field.

> What is the algorithm that sets `Citeable`:
Mmh. I guess it's more the question of what is not citeable. I see by default anything that comes from arXiv is citeable. @annetteholtkamp can you help here?

**Comment by jmartinm** [comment]
Now that https://github.com/inspirehep/inspire-next/pull/1589 is merged, and once we get rid of the `collections` field, note that we will still have a `_collections` field managed by `invenio-collections`.

This field gets populated based on a query matching the record (see [config](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/config.py#L150)) so that config will have to be amended for the queries to match the new `document_type` field.

**Comment by jmartinm** [comment]
Collection fields are:

```
   1100059 HEP 
    832449 Citeable 
    698265 CORE 
    584001 Published 
    401801 arXiv 
    312449 ConferencePaper 
     57480 Arxiv 
     51674  
     26942 Thesis 
     27168 Review 
     10148 Lectures 
      5637 NOTE 
      7727 Proceedings 
      7507 noncore 
      4643 THESIS 
      3488 Introductory 
      4003 Withdrawn 
      3982 Hep 
      3344 Book 
       172 D0-PRELIMINARY-NOTE 
      2069 BOOK 
      1239 NONCORE 
      1240 PROCEEDINGS 
      1115 citeable 
       891 BookChapter 
       452 Conference 
        33 Core 
        11 REPORT 
         5 Preprint 
         6 published 
         3 core 
         3 Note 
         2 Noncore 
         2 Report 
         1 PUBLISHED 
         1 thesis 
         1 book 
         1 proceedings 
         1 NonCore 
         1 Conferencepaper 
         1 Accelerators 
         1 Proceddings 
```

Our schema says possible document types are:

```
[
"Published",
 "arXiv",
 "ActivityReport",
 "ConferencePaper",
 "Thesis",
 "Review",
 "Lectures",
 "Note",
 "Proceedings",
 "Introductory",
 "Book",
 "BookChapter",
 "Report"
  ],
```

And our current document type facet has the following mapping (from `980__a` value to facet value):

```
        'published': 'peer reviewed',
        'thesis': 'thesis',
        'book': 'book',
        'bookchapter': 'book chapter',
        'proceedings': 'proceedings',
        'conferencepaper': 'conference paper',
        'note': 'note',
        'report': 'report',
        'activityreport': 'activity report',
        'lectures': 'lectures',
        'review': 'review',

'preprint' if no journal info
```

So for this issue to proceed we would need:

* [ ] For each value in `980__a` what document type from our schema to assign.
* [ ] Should the document type in the schema be human readable `ActivityReport` vs `Activity Report` for example.
* [ ] Complete the `enum` in our jsonschema to acomodate document types such as the hidden collections: `Hal Hidden`, notes from different experiments and so on.
* [ ] Do we still need the receiver to convert the document types into a more 'user facing' facet, with values such as `Preprint` or `Peer Reviewed` which are not mentioned as document types in the schema.

**Comment by kaplun** [comment]
@jmartinm Thanks. I'd suggest @annetteholtkamp et al. can help us removing all the outliers from 980__a

**Comment by kaplun** [comment]
```
1100059 HEP -> Literature Schema
    832449 Citeable -> citeable flag
    698265 CORE -> 'core' flag: True
    584001 Published -> published flag
    401801 arXiv -> ignore (redundant)
    312449 ConferencePaper -> 'conference paper'
     57480 Arxiv ->  ignore (redundant)
     51674  -> ignore (W00t?)
     26942 Thesis -> 'thesis'
     27168 Review -> 'review'
     10148 Lectures -> 'lectures'
      5637 NOTE -> 'note'
      7727 Proceedings -> 'proceedings'
      7507 noncore -> 'core' flag: False
      4643 THESIS -> 'thesis'
      3488 Introductory -> 'introductory'
      4003 Withdrawn -> 'withdrawn' flag
      3982 Hep -> Literature Schema
      3344 Book -> 'book'
       172 D0-PRELIMINARY-NOTE 
       891 BookChapter -> 'book chapter'
       452 Conference -> Wot? In HEP?
        11 REPORT -> 'report'
         5 Preprint -> ignore redundant
         6 published -> ignore redundant
```

**Comment by annetteholtkamp** [comment]
> On 05 Oct 2016, at 12:39, Samuele Kaplun <notifications@github.com> wrote:
> 
> 1100059 HEP -> Literature Schema
>     832449 Citeable -> citeable flag
>     698265 CORE -> 'core' flag: True
>     584001 Published -> published flag
>     401801 arXiv -> ignore (redundant)
why is that redundant?
>     312449 ConferencePaper -> 'conference paper'
>      57480 Arxiv ->  ignore (redundant)
>      51674  -> ignore (W00t?)

what is this?
>      26942 Thesis -> 'thesis'
>      27168 Review -> 'review'
>      10148 Lectures -> 'lectures'
>       5637 NOTE -> 'note'
>       7727 Proceedings -> 'proceedings'
>       7507 noncore -> 'core' flag: False

Is there only true and false, or also undefined ?
>       4643 THESIS -> 'thesis'
>       3488 Introductory -> 'introductory'
>       4003 Withdrawn -> 'withdrawn' flag
>       3982 Hep -> Literature Schema
>       3344 Book -> 'book'
>        172 D0-PRELIMINARY-NOTE 
We should ask Heath whether this tag is still necessary if a record is in HEP
>        891 BookChapter -> 'book chapter'
>        452 Conference -> Wot? In HEP?

Yes, we never managed to clean them all up. Most of them are probably conf papers - but needs to be checked.
>         11 REPORT -> 'report'
>          5 Preprint -> ignore redundan
>          6 published -> ignore redundant
- Annette

**Comment by kaplun** [comment]
>     401801 arXiv -> ignore (redundant)
why is that redundant?

We don't need to say `arXiv`. We already know from the arXiv ID.

>      51674  -> ignore (W00t?)
what is this?

A collection with empty value :smile: 

>       7507 noncore -> 'core' flag: False
Is there only true and false, or also undefined ?

Yes, all flags have also undefined values.

**Comment by kaplun** [comment]
Issue moved to [inspirehep/inspire-schemas #31](https://github.com/inspirehep/inspire-schemas/issues/31) via [**ZenHub**](https://www.zenhub.com/)
