### ISSUE TITLE
HEP schema: add qualifying information for DOIs

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1221]
On the MarcXML data model we have:

![screen shot 2016-06-16 at 10 53 28 am](https://cloud.githubusercontent.com/assets/580727/16110957/bcee40a2-33b0-11e6-8525-be004665692e.png)

The last subfield indicates if the DOI is an erratum, addendum and so on. We don't seem to be using such a field either in the schema or dojson rules. It should be added.

**Comment by kaplun** [comment]
I think we have it for the ISBN though

**Comment by jacquerie** [comment]
This was added to the schema in https://github.com/inspirehep/inspire-schemas/commit/d37cf3f71e5d2fc74cef7b9411cd73ab206d8323 and added to DoJSON in 496506476.
