### ISSUE TITLE
schemas: series and series_number is not enough

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-next#1228]
Having just `series` and `series_number` [as uncorrelated fields](https://github.com/inspirehep/inspire-next/blob/8978a67b4202e461a14bf404013e9ec05761ef5f/inspirehep/modules/records/jsonschemas/records/conferences.json#L70-L77) in the Conferences schemas is not enough: some conferences (~300) belong to more than one series, so it's not clear to which series is `series_number` referring. It should be something like this:

``` JSON
{
    "series": {
        "type": "array",
        "items": {
            "type": "object",
            "properties": {
                "name": {"type": "string"},
                "number": {"type": "string"}
            }
        }
    }
}
```

Note also the fact that `series_number` should be a string, not an integer, incorporating a suggestion by @jalavik.

**Comment by tomaszgy** [comment]
Just found today conferences with `recid=965456` (see [here](https://inspirehep.net/record/965456/export/xm)). It belongs to the two series (its field `411__a` is doubled) and after applying doJSON, the `series` field of the record looks like this:
` "series": [
                  [
                     "Moriond EW",
                     "Rencontres de Moriond"
                  ]
               ]`

That is, it's a list of lists instead of list of strings (as for current JSON Schema) or list of `ConferenceSeries elements` (as proposed above by @jacquerie).

**Comment by kaplun** [comment]
Mmh: @tomaszgy example looks like yet an other workaround to the Invenio 1 limitations. (e.g. in this case two synonyms for the same conference).

**Comment by tomaszgy** [comment]
@kaplun: Is it possible that one conference is part of two different conference series? Does it happen in reality?

**Comment by kaplun** [comment]
Question to be redirected to @inspirehep/inspire-content

**Comment by jacquerie** [comment]
We actually already determined that yes, this does happen: https://inspirehep.net/record/1425611 is part of the "Symposium on Physics" and the "NRHEP Network Meeting" series.

**Comment by jacquerie** [comment]
Another interesting case is made of http://inspirehep.net/record/1404073 and http://inspirehep.net/record/1404074: they are different tracks in the same conference, expressed as two different `411` records, one shared for the conference, one for the specific track.

In fact, @kaplun, it would be very helpful if you could pass us all the examples from https://github.com/inspirehep/inspire-next/blob/351cd75deed84a75edccc15df1efed80f556ec4b/inspirehep/dojson/current_marcxml_usage/conferences-repeatable.txt#L4.

**Comment by kaplun** [comment]
There it is:

411   -> (299) http://inspirehep.net/record/963662, http://inspirehep.net/record/963769, http://inspirehep.net/record/963792, http://inspirehep.net/record/963892, http://inspirehep.net/record/963914, http://inspirehep.net/record/963983, http://inspirehep.net/record/964014, http://inspirehep.net/record/964081, http://inspirehep.net/record/964119, http://inspirehep.net/record/964177, http://inspirehep.net/record/964233, http://inspirehep.net/record/964240, http://inspirehep.net/record/964262, http://inspirehep.net/record/964271, http://inspirehep.net/record/964299, http://inspirehep.net/record/964385, http://inspirehep.net/record/964418, http://inspirehep.net/record/964419, http://inspirehep.net/record/964442, http://inspirehep.net/record/964448, http://inspirehep.net/record/964561, http://inspirehep.net/record/964642, http://inspirehep.net/record/964720, http://inspirehep.net/record/964721, http://inspirehep.net/record/964767, http://inspirehep.net/record/964975, http://inspirehep.net/record/964985, http://inspirehep.net/record/964994, http://inspirehep.net/record/965019, http://inspirehep.net/record/965036, http://inspirehep.net/record/965045, http://inspirehep.net/record/965053, http://inspirehep.net/record/965245, http://inspirehep.net/record/965273, http://inspirehep.net/record/965332, http://inspirehep.net/record/965348, http://inspirehep.net/record/965389, http://inspirehep.net/record/965416, http://inspirehep.net/record/965433, http://inspirehep.net/record/965462, http://inspirehep.net/record/965463, http://inspirehep.net/record/965593, http://inspirehep.net/record/965646, http://inspirehep.net/record/965680, http://inspirehep.net/record/965714, http://inspirehep.net/record/965715, http://inspirehep.net/record/965738, http://inspirehep.net/record/965821, http://inspirehep.net/record/965825, http://inspirehep.net/record/965830, http://inspirehep.net/record/965844, http://inspirehep.net/record/965939, http://inspirehep.net/record/965976, http://inspirehep.net/record/965980, http://inspirehep.net/record/966018, http://inspirehep.net/record/966177, http://inspirehep.net/record/966196, http://inspirehep.net/record/966209, http://inspirehep.net/record/966217, http://inspirehep.net/record/966446, http://inspirehep.net/record/966504, http://inspirehep.net/record/966531, http://inspirehep.net/record/966626, http://inspirehep.net/record/966711, http://inspirehep.net/record/966815, http://inspirehep.net/record/966840, http://inspirehep.net/record/966890, http://inspirehep.net/record/966911, http://inspirehep.net/record/967006, http://inspirehep.net/record/967047, http://inspirehep.net/record/967050, http://inspirehep.net/record/967051, http://inspirehep.net/record/967175, http://inspirehep.net/record/967186, http://inspirehep.net/record/967328, http://inspirehep.net/record/967331, http://inspirehep.net/record/967351, http://inspirehep.net/record/967356, http://inspirehep.net/record/967408, http://inspirehep.net/record/967421, http://inspirehep.net/record/967568, http://inspirehep.net/record/967577, http://inspirehep.net/record/967639, http://inspirehep.net/record/967664, http://inspirehep.net/record/967754, http://inspirehep.net/record/967770, http://inspirehep.net/record/967792, http://inspirehep.net/record/967807, http://inspirehep.net/record/967809, http://inspirehep.net/record/967813, http://inspirehep.net/record/967839, http://inspirehep.net/record/967841, http://inspirehep.net/record/967872, http://inspirehep.net/record/968059, http://inspirehep.net/record/968136, http://inspirehep.net/record/968195, http://inspirehep.net/record/968227, http://inspirehep.net/record/968228, http://inspirehep.net/record/968433, http://inspirehep.net/record/968462, http://inspirehep.net/record/968565, http://inspirehep.net/record/968634, http://inspirehep.net/record/968725, http://inspirehep.net/record/968727, http://inspirehep.net/record/968788, http://inspirehep.net/record/968837, http://inspirehep.net/record/968908, http://inspirehep.net/record/968924, http://inspirehep.net/record/968999, http://inspirehep.net/record/969179, http://inspirehep.net/record/969196, http://inspirehep.net/record/969198, http://inspirehep.net/record/969250, http://inspirehep.net/record/969350, http://inspirehep.net/record/969354, http://inspirehep.net/record/969567, http://inspirehep.net/record/969587, http://inspirehep.net/record/969687, http://inspirehep.net/record/969863, http://inspirehep.net/record/969879, http://inspirehep.net/record/969890, http://inspirehep.net/record/970056, http://inspirehep.net/record/970057, http://inspirehep.net/record/970087, http://inspirehep.net/record/970090, http://inspirehep.net/record/970091, http://inspirehep.net/record/970093, http://inspirehep.net/record/970154, http://inspirehep.net/record/970368, http://inspirehep.net/record/970401, http://inspirehep.net/record/970462, http://inspirehep.net/record/970481, http://inspirehep.net/record/970505, http://inspirehep.net/record/970674, http://inspirehep.net/record/970758, http://inspirehep.net/record/970840, http://inspirehep.net/record/970856, http://inspirehep.net/record/970901, http://inspirehep.net/record/971235, http://inspirehep.net/record/971490, http://inspirehep.net/record/971492, http://inspirehep.net/record/971730, http://inspirehep.net/record/971788, http://inspirehep.net/record/971801, http://inspirehep.net/record/971879, http://inspirehep.net/record/972002, http://inspirehep.net/record/972009, http://inspirehep.net/record/972134, http://inspirehep.net/record/972145, http://inspirehep.net/record/972167, http://inspirehep.net/record/972263, http://inspirehep.net/record/972283, http://inspirehep.net/record/972315, http://inspirehep.net/record/972508, http://inspirehep.net/record/972550, http://inspirehep.net/record/972596, http://inspirehep.net/record/972629, http://inspirehep.net/record/972630, http://inspirehep.net/record/972720, http://inspirehep.net/record/972960, http://inspirehep.net/record/973072, http://inspirehep.net/record/973357, http://inspirehep.net/record/973374, http://inspirehep.net/record/973375, http://inspirehep.net/record/973478, http://inspirehep.net/record/973496, http://inspirehep.net/record/973510, http://inspirehep.net/record/973836, http://inspirehep.net/record/973974, http://inspirehep.net/record/973979, http://inspirehep.net/record/973980, http://inspirehep.net/record/973987, http://inspirehep.net/record/973997, http://inspirehep.net/record/974073, http://inspirehep.net/record/974100, http://inspirehep.net/record/974113, http://inspirehep.net/record/974213, http://inspirehep.net/record/974391, http://inspirehep.net/record/974440, http://inspirehep.net/record/974555, http://inspirehep.net/record/974639, http://inspirehep.net/record/974773, http://inspirehep.net/record/974830, http://inspirehep.net/record/974856, http://inspirehep.net/record/974857, http://inspirehep.net/record/974859, http://inspirehep.net/record/974903, http://inspirehep.net/record/975008, http://inspirehep.net/record/975019, http://inspirehep.net/record/975236, http://inspirehep.net/record/975530, http://inspirehep.net/record/975531, http://inspirehep.net/record/975566, http://inspirehep.net/record/975569, http://inspirehep.net/record/975670, http://inspirehep.net/record/975827, http://inspirehep.net/record/975841, http://inspirehep.net/record/976098, http://inspirehep.net/record/976339, http://inspirehep.net/record/976462, http://inspirehep.net/record/976489, http://inspirehep.net/record/976490, http://inspirehep.net/record/976928, http://inspirehep.net/record/977070, http://inspirehep.net/record/977115, http://inspirehep.net/record/977200, http://inspirehep.net/record/977364, http://inspirehep.net/record/977418, http://inspirehep.net/record/977422, http://inspirehep.net/record/977444, http://inspirehep.net/record/977520, http://inspirehep.net/record/977538, http://inspirehep.net/record/977569, http://inspirehep.net/record/977598, http://inspirehep.net/record/977640, http://inspirehep.net/record/977844, http://inspirehep.net/record/978123, http://inspirehep.net/record/978526, http://inspirehep.net/record/978574, http://inspirehep.net/record/978606, http://inspirehep.net/record/978615, http://inspirehep.net/record/978636, http://inspirehep.net/record/978693, http://inspirehep.net/record/978880, http://inspirehep.net/record/978882, http://inspirehep.net/record/978931, http://inspirehep.net/record/979119, http://inspirehep.net/record/979121, http://inspirehep.net/record/979404, http://inspirehep.net/record/979566, http://inspirehep.net/record/979887, http://inspirehep.net/record/980147, http://inspirehep.net/record/980229, http://inspirehep.net/record/980360, http://inspirehep.net/record/980361, http://inspirehep.net/record/980543, http://inspirehep.net/record/980544, http://inspirehep.net/record/980564, http://inspirehep.net/record/980698, http://inspirehep.net/record/980762, http://inspirehep.net/record/980787, http://inspirehep.net/record/980788, http://inspirehep.net/record/980798, http://inspirehep.net/record/980929, http://inspirehep.net/record/980935, http://inspirehep.net/record/981306, http://inspirehep.net/record/981307, http://inspirehep.net/record/981315, http://inspirehep.net/record/981316, http://inspirehep.net/record/981443, http://inspirehep.net/record/981617, http://inspirehep.net/record/981651, http://inspirehep.net/record/981746, http://inspirehep.net/record/1083232, http://inspirehep.net/record/1083783, http://inspirehep.net/record/1085467, http://inspirehep.net/record/1086511, http://inspirehep.net/record/1086621, http://inspirehep.net/record/1088735, http://inspirehep.net/record/1095077, http://inspirehep.net/record/1111069, http://inspirehep.net/record/1114216, http://inspirehep.net/record/1114226, http://inspirehep.net/record/1117067, http://inspirehep.net/record/1117765, http://inspirehep.net/record/1119933, http://inspirehep.net/record/1121335, http://inspirehep.net/record/1194432, http://inspirehep.net/record/1203198, http://inspirehep.net/record/1203199, http://inspirehep.net/record/1218346, http://inspirehep.net/record/1218347, http://inspirehep.net/record/1222759, http://inspirehep.net/record/1223906, http://inspirehep.net/record/1269098, http://inspirehep.net/record/1269099, http://inspirehep.net/record/1280000, http://inspirehep.net/record/1280001, http://inspirehep.net/record/1298456, http://inspirehep.net/record/1300053, http://inspirehep.net/record/1310150, http://inspirehep.net/record/1331208, http://inspirehep.net/record/1388546, http://inspirehep.net/record/1389784, http://inspirehep.net/record/1393359, http://inspirehep.net/record/1396385, http://inspirehep.net/record/1396387, http://inspirehep.net/record/1396388, http://inspirehep.net/record/1396389, http://inspirehep.net/record/1396390, http://inspirehep.net/record/1396392, http://inspirehep.net/record/1396395, http://inspirehep.net/record/1398489, http://inspirehep.net/record/1400716, http://inspirehep.net/record/1404073, http://inspirehep.net/record/1404074, http://inspirehep.net/record/1425611, http://inspirehep.net/record/1479203, http://inspirehep.net/record/1479204
411  a -> (8) http://inspirehep.net/record/965456, http://inspirehep.net/record/965980, http://inspirehep.net/record/966018, http://inspirehep.net/record/966890, http://inspirehep.net/record/969863, http://inspirehep.net/record/969879, http://inspirehep.net/record/973987, http://inspirehep.net/record/979566

**Comment by jacquerie** [comment]
Fixed in a series of PRs, the last one of which is https://github.com/inspirehep/inspire-next/pull/1563.
