### ISSUE TITLE
Searching for pubnotes

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1235]
When searching for pubnotes as in: `find j "Phys.Rev.Lett.,105*"` what should ideally happen is that there is a simple field in HEP, created on the fly upon indexing, called e.g. `publication_info.pubnote` which is the concatenation of the appropriate publication_info information.

**Comment by kaplun** [comment]
Given the snippet:
```json
"publication_info": [{
    "journal_title": "J.Foo.",
    "journal_volume": "3",
    "year": 1983,
    "journal_issue": "2",
    "page_start": "123",
    "page_end": "456",
    "artid": "120023",
}]
```

We should create at index time, possibly via Groovy (alternative with lang-python plugin) a new field:
```json
"publication_info.pubnotes": ["J.Foo.,3,123", "J.Foo.,2,3,123", "J.Foo.,3,123-456", "J.Foo.,2,3,123"]
```

**Comment by kaplun** [comment]
@inspirehep/inspire-dir, what other valid pubnote exists?

**Comment by eamonnmag** [comment]
?? Why would you use groovy for this? Do it Python directly and just update the dictionary.

**Comment by kaplun** [comment]
Was thinking that we might off-load a bit of these enhancements to ES itself, using default Groovy scripting of ES. But indeed it doesn't matter much, as long as the above expansion are always peformed.

**Comment by eamonnmag** [comment]
Indeed. It's just adding an extra level of complexity and indirection with no benefit.

**Comment by annetteholtkamp** [comment]
There’s also
cnum, page (range)/article id
773__w+c
Here a lookup has to be done to extract some info from the proceedings record - or if that does not exist, from the conference record.

We were thinking of also using
report number, (page range)/article id
conference acronym, page (range)/article id

The report number can currently appear in 773__r, the conf acronym in 773__q. 

Examples are contributions in a cern yellow report or contributions to JACoW conference proceedings.

- Annette

**Comment by ksachs** [comment]
inspire recid (773__0)
ISBN (773__z)
+ page (range)/article id (773__c)
esp. for book chapters.
Also used if there are several proceedings records for a conference.

**Comment by StellaCh** [comment]
addressed by https://github.com/inspirehep/inspire-query-parser/

**Comment by kaplun** [comment]
Is it though? In general when trying for expanding a search there is both a part where given the query you expand it to match potentially multiple ways it might have been indexed, and viceversa, given an indexed string you also index it in an expanded way so that it can be queried in alternative ways.

There are pros and cons to indexing vs. searching time expansion. 

Looking at: https://www.elastic.co/guide/en/elasticsearch/guide/current/synonyms-expand-or-contract.html#synonyms-expansion seems indeed that expanding at query time might be best for this use-case.
