### ISSUE TITLE
RFC: Better Docker Image Management

### ISSUE THREAD

**Issue by mihaibivol** [inspirehep/inspire-next#1238]
As we discussed on Jun 22 Standup we might want to also have a Python3 Base.
The current workflow is based on manually building images and tags. My suggestion is to:
* [x] Create Separate `inspirehep/dockerfiles` repo
* Create automatic builds for:
  * [x] inspirehep/python-base:python2
  * [x] ~~inspirehep/python-base:python3~~ Not compatible at dependency leverl
  * [x] inspirehep/elasticsearch with correct config

* [x] Push for successful builds

**Comment by mihaibivol** [comment]
cc @kaplun @jmartinm @jalavik @jacquerie

**Comment by jalavik** [comment]
For the repo part, there is already one we can reuse here https://github.com/inspirehep/inspire-docker

There I think we could hook in travis to auto build and push to dockerhub for every change in master branch (or used tagged approach).

**Comment by mihaibivol** [comment]
Can we deprecate everything in the `inspire-docker` repo and start with something new?

**Comment by jmartinm** [comment]
This sounds good to me. @jalavik or @kaplun can confirm that `inspire-docker` repo does not contain anything we want to keep.

**Comment by kaplun** [comment]
It is anyway all related to Invenio 2 and based on old techniques...

**Comment by jalavik** [comment]
@mihaibivol Yeah its all deprecated stuff. Please go ahead 👍

**Comment by mihaibivol** [comment]
@jacquerie since @jalavik has a farewell, can you put some secure credentials here? https://github.com/inspirehep/inspire-docker using these steps
* `gem install travis`
* https://docs.travis-ci.com/user/encryption-keys/#Usage

**Comment by jacquerie** [comment]
Uh, sorry to block you on this, but I can only do this after lunch.

**Comment by mihaibivol** [comment]
It's not blocking anything. You can even do it on Monday. We still have to
figure out how to trigger the build from the `inspire-next` repo.
