### ISSUE TITLE
Institutions DoJSON - related institutes missing

### ISSUE THREAD

**Issue by tomaszgy** [inspirehep/inspire-next#1239]
Current DoJSON for Institutes doesn't use field `510` which contains information about related institution's `recid` (subfield `0`), `name` (`a`) and type of relation (`w`) (see all the fields explained [here](https://twiki.cern.ch/twiki/bin/view/Inspire/DevelopmentRecordMarkupInstitutions)).

Twiki documents four possible types of relation: `parent` (value `t`), `predecessor` (`a`), successor (`b`) and `otherwise related` (`r`).

Field `related_institutes` is already defined in [JSON Schema for Institutions](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/records/jsonschemas/records/institutions.json#L151) and seems to be good with two  exceptions:
 - it contains subfield `curated_relation` which seems to not have its equivalent in MarcXML
 - subfield `relation_type`, being an enum, should probably contain also value `otherwise_related`.

Last thing to be discussed: is it possible to get rid of the `successor` value in records XMLs? We could instead add (pred_recid, `predecessor`) pair inside successor's XML where `pred_recid` is its predecessor's recid. That needs though to edit legacy's XMLs.

@jacquerie @kaplun

**Comment by jacquerie** [comment]
Ok, will deal with this after #1200, to ensure that the current rules are bug-free.

**Comment by kaplun** [comment]
@tomaszgy links should actually be considered curated any time there's a link based on institution ID which actually matches an existing record. (actually such links have always been added by hand, so you we can always consider them curated).

Regarding just having predecessor, I think it's a good idea. What we can do though on legacy is to always populate predecessor when only the successor is available on the other record. Then in dojson we can simply ignore successor relations.
