### ISSUE TITLE
author search for BAI

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1242]
As a follow up of https://github.com/inspirehep/inspire-next/pull/1222 I have seen that search for a given BAI currently returns no results. There is a related [x-failed test](https://github.com/inspirehep/inspire-next/blob/master/tests/unit/search/test_search_query.py#L645).

An exact query like author:"Ellis" produces the following ES query:

```
{
"bool": {
    "must": [
             {
                 "match": {
                     "authors.name_variations": "Ellis"
                 }
             }
         ],
         "should": [
             {
                 "match": {
                     "authors.full_name": "Ellis"
                 }
             }
         ]
     }
 }
```

I guess we need to add in the `must` query that either there is an exact match in `"authors.name_variations"` or there is an exact match in the [inspire_bai](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/records/mappings/records/hep.json#L319) field.

**Comment by jacquerie** [comment]
:+1:

A lot of tests were xfailed because we were missing the BAIs in the schemas. Now that we have them we can proceed.
