### ISSUE TITLE
Bad redirect for ORCID login?

### ISSUE THREAD

**Issue by jalavik** [inspirehep/inspire-next#1249]
Logged in through ORCID on QA after trying to access https://qa.inspirehep.net/holdingpen being logged out. So the URL for the login button is https://qa.inspirehep.net/login/?next=%2Fholdingpen%2F

After login on ORCID, I got directed to this URL:

https://qa.inspirehep.net/qa.inspirehep.net

which produces a 404. Happens every time.

**Comment by jmartinm** [comment]
I think that is fixed in this pending PR https://github.com/inspirehep/inspire-next/pull/1093

**Comment by jmartinm** [comment]
@Panos512 can you confirm https://github.com/inspirehep/inspire-next/pull/1093 fixes it and we can close this?

**Comment by Panos512** [comment]
Yeah this is fixed! 💃
