### ISSUE TITLE
Simplifying titles

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1257]
Titles are not used for searching (i.e. nobody searches for an exact title). What they are useful for is to convey concepts that might be searched for. 

For this reason it is proposed to:
* [x] kill old titles (they are used only 6 times!!! and 1 out of 6 is a DOI instead of a title)
* [x] kill title variations (which contains only slight variation, e.g.:
  * a LaTeX formula expressed in unicode
  * an acronym
  * and -> & and other useless substitutions
* [ ] LaTeX to unicode can be automatized
* [ ] Acronyms can be computed directly by stripping stop words and considering upper-case words (anyway they will be there in the abstract and can be boosted, i.e. receive more weight when searched for it).
* [ ] we could provide a synonym table to expand known acronym and symbols.

**Comment by kaplun** [comment]
cc: @inspirehep/inspire-dir

**Comment by ksachs** [comment]
I'm not sure what you are up to here.
We need a title 'history', i.e. different versions from arXiv, journal, what have you.
A synonym might have different meaning in math, astro or hep. going only with a table you will create false positives or miss some variants. we might decide another field is not worth the effort but we should discuss it.

**Comment by kaplun** [comment]
> I'm not sure what you are up to here.
> We need a title 'history', i.e. different versions from arXiv, journal, what have you.

@ksachs, why do you need a title history? Since we don't display them, I assume it's only for searching. Now:
* real users do not search really for titles. However they might search a la Google. In that case, in the modern world (so not with old Invenio exact-only search-engine), the search engine is able to search in approximate way, using synonyms etc. and displaying at the top documents that are more likely been searched by the user.
* Note that: we still plan to store both arXiv and publisher version explicitly. However not to store all the past versions from arXiv, or all the past versions from a publisher

> A synonym might have different meaning in math, astro or hep. going only with a table you will create false positives or miss some variants.

* Re synonyms, I am not proposing to go only with a table, but to additionally expand with synonyms: we have a modern search engine now and we can boost exact matches, and also allow for less boosted synonym matches. The final goal when using phrase fields such as title, abstract, fulltext, is to present on top the record the user was searching for, not to match all and only the records the user might have been looking (for that we would still use the normal fields such as category, subject, experiments, identifiers, etc.), i.e. the false positive will be there no matter what, but relegated to the bottom of the search engine.

> we might decide another field is not worth the effort but we should discuss it.

That's the very purpose of this ticket :+1: 
Note also the statistical usage: `old title` have been used only 6 times, so we can really kill it. And `title_variations` look more as a work around to the limits of Invenio and traditional search engines, that we can now solve with more robust methodology, simplifying cataloguer work (and also the maintenance of all the algorithms that deal with these fields).

**Comment by ksachs** [comment]
You would not explicitly search for old title, but it is included in the title index. A search for any (old) version of the title should yield the record. And I find it difficult if I can't trace why a record is included in the search result if the word/content is not in the record or can be derived from the record (stemming, synonym table).

**Comment by kaplun** [comment]
Yes, but the truth from usage statistics is that noone searches for the full title (and it basically never worked due to the punctuation issues, LaTeX formulas and so on).

Regarding why a record matched some results, ES can give you back this feedback. Note that the same would be true if we were matching records by title variation/old title (since we don't display them).

We should user test it, and see what confuses the least users: (i.e. being presented with many explanation from the search engine Vs. simply being presented with good results). Again note that all this discussion is specific to title which is a naturally fuzzy field where noone would perform an exact search, but rather give for granted some smart behavior by the search engine being used.

**Comment by fschwenn** [comment]
Please not, that titles can change dramatically from the first arXiv-version to the published one. Some researches invent especially catchy titles to draw attention to their arXiv-submissions and then change to reasonable and sound titlse for the published version. 

Florian 

-- 
Florian Schwennsen 
Deutsches Elektronen-Synchrotron DESY 
Building 01 Room O1.446 
phone: +49-40-8998-6190

**Comment by kaplun** [comment]
@fschwenn to be clear: the proposal is to keep the last arXiv title and last published title. 
The cons of keeping the whole history of titles is that it would complicate merging of records. @mihaibivol

**Comment by kaplun** [comment]
(note again that so far only 6 records have historical title).

**Comment by fschwenn** [comment]
Usually the arXiv-version is updated to the journal version when it is published such that for those cases the _last_ arXiv title would not be very useful while the old one(s) are "lost" in your model. 

-- 
Florian Schwennsen 
Deutsches Elektronen-Synchrotron DESY 
Building 01 Room O1.446 
phone: +49-40-8998-6190

**Comment by kaplun** [comment]
#1465 merges old title and title variations in title itself. The other expansion are left for a synonym table.
