### ISSUE TITLE
Killing book edition field (250__a)

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1258]
This field is used only 12 times https://inspirehep.net/search?ln=en&p=250__a%3A**&of=hb&action_search=Search&sf=earliestdate&so=d and is not even displayed.

Can we simply kill it, since it doesn't even convey much value to our end users. (it would make sense in a library which holds items).

**Comment by kaplun** [comment]
cc: @inspirehep/inspire-dir

**Comment by aw-bib** [comment]
> it doesn't even convey much value to our end users. (it would make sense in a library which holds items

This might potentially be true if you can rule out these strange books that state something like "will not be discussed here as it was already addressed in the former edition". (Ie. when really relevant for citations to give the _proper_ edition.)

IOW I would see "value to the user" _also_ from the point of proper citation.

**Comment by kaplun** [comment]
Yep, but what about capturing this information? In INSPIRE we have would have a single entry no matter the edition, so what would mean having a field with a given edition?

Regarding references, I believe we are not able to capture so far editions (does any publisher actually give us an edition information?)

**Comment by aw-bib** [comment]
> a single entry no matter the edition

@annetteholtkamp comment seems relevant: "But do we have clear guidelines when to update an existing record with a new edition and when to create a separate record?"

> does any publisher actually give us an edition information?

At least crossref has `edition_number` as element for `book_metadata`, `book_set_metadata`, `book_series_metadata`.

**Comment by kaplun** [comment]
Interestingly enough there are 11K records in INSPIRE with at least a citation mentioning the word "edition". Refextract is not able to recognize them but at this point I think it should at least from a completeness point of view.

**Comment by jacquerie** [comment]
I think that `editions` are here to stay, even if they are underused at the moment: https://github.com/inspirehep/inspire-schemas/commit/be54482ed6544a8e4d4399861f13b8b27c6c435e.

cc: @michamos for confirmation, reopen if I'm wrong
