### ISSUE TITLE
Thesis supervisor to be merged into authors

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1259]
By integrating [Casrai CRediT](http://dictionary.casrai.org/Contributor_Roles) into the author role field, we can actually conflate the thesis supervisor into the author field (by specifying the `supervision` role).

In this way the `thesis_supervisor` field (i.e. 701) can be simplified.

**Comment by kaplun** [comment]
cc: @inspirehep/inspire-dir

**Comment by kaplun** [comment]
To be noted that at search time, since authors are now a nested field, it will be possible to alias `supervisor:foo` to `author:foo and role:supervision`.

**Comment by annetteholtkamp** [comment]
But does a normal author search then also give the supervisors?

- Annette

**Comment by kaplun** [comment]
We can tune it for excluding it.
Today on the other hand an author search is matching also "editors". Would we want that?

**Comment by annetteholtkamp** [comment]
I think yes. Nobody ever complained about that.

- Annette

**Comment by annetteholtkamp** [comment]
+1

**Comment by jacquerie** [comment]
Won't be done in #1458, but this hints that the `authors` field might be called `people`...

**Comment by aw-bib** [comment]
I could imagine that you may want to search for `name if role is X` exclusively as well. (E.g. all papers A is author, all papers A is editor etc.)

We have this request from time to time when people use join² system to generate their [CV pages on the web.](http://www.fz-juelich.de/iek/iek-3/EN/UeberUns/Ansprechpartner/Management/Stolten%20JSP.html?nn=557422) This author e.g. also was editor for a conference with some 500 contributions where he is listed as editor. I think the same reasoning is equally valid for exports to BibTeX or whatever to generate those lists off line.

Calling the author field `people` instead as noted in some comment seems clever and nearer the mark. (It is the idea behind librarians speak [Main Entry - Personal name](http://www.loc.gov/marc/bibliographic/bd100.html) and [Added Entry - Personal name](http://www.loc.gov/marc/bibliographic/bd700.html))
