### ISSUE TITLE
Cleaning up thesis field

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1260]
`thesis` should not be repeatable: only the `thesis.university` field should be. (additionally the `thesis.record` field should be aligned with the `thesis.university`). And probably `thesis.university` should be called `thesis.institution`.

**Comment by mihaibivol** [comment]
@kaplun Other than `dojson` and some views (and bibtex export) do we need to change this elsewhere?

**Comment by kaplun** [comment]
Maybe in hepcrawl, since we are also harvesting theses.
