### ISSUE TITLE
multiple 773__ subfields

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1261]
TBD

**Comment by mihaibivol** [comment]
:(

**Comment by jacquerie** [comment]
There seems to be no bug here...

**Comment by kaplun** [comment]
Reverse enginereeing what I had in my mind (by looking at the referred ticket from Mihai) seems to be related to multiple CNUMs in the same MARCXML tags, thus indering the possibility to disentangle which other subfield is related to which conference.
