### ISSUE TITLE
dojson: double longitude for some institutions

### ISSUE THREAD

**Issue by tomaszgy** [inspirehep/inspire-next#1271]
Trying to load production data for Institutions I discovered that 102 Institutions have two values of the field `034__d` which describes the `longitude` of institution's location (see statistics [here](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/dojson/current_marcxml_usage/institutions-repeatable.txt#L38)). That makes doJSON crash [here](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/dojson/institutions/fields/bd1xx.py#L42) as `value[c]` returns a tuple instead of a string.

Usually both values for `d` are different which means that one of them is a longitude and the other a latitude. What shall we do with that? Reject both values? Try to guess which one is which?

@kaplun @jacquerie

**Comment by tomaszgy** [comment]
The quick fix: append `TypeError` [here](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/dojson/institutions/fields/bd1xx.py#L43). What do you think?

**Comment by kaplun** [comment]
Quick fix is to ignore them. We have to reprocess them anyway using Google API or similar. See: [ticket I can no longer find, where I was discussing this with @eamonnmag ]

**Comment by kaplun** [comment]
Found it: https://github.com/inspirehep/inspire/issues/170

**Comment by jacquerie** [comment]
Nope, I don't think this should be solved by DoJSON: it would require too much logic. This has to be solved on legacy data. I don't like the idea of a workaround such as the one in #1272: better have a validation error that shows that we have a problem, rather than silently ignoring it.

**Comment by jacquerie** [comment]
See: https://github.com/inspirehep/inspire-next/pull/1200#issuecomment-227852306 and https://github.com/inspirehep/inspire-next/pull/1200#issuecomment-227983528.

**Comment by jacquerie** [comment]
So, since this is already known and tracked elsewhere I am closing this and #1272.
