### ISSUE TITLE
legacy: missing link between Experiment and Institution

### ISSUE THREAD

**Issue by tomaszgy** [inspirehep/inspire-next#1274]
All records from Experiments are missing connection by `recid` to their `affiliation` (Institutions). Field `119__u` contains [sometimes](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/dojson/current_marcxml_usage/experiments.txt#L439) institution's name. Not always though, there are cases where it contains strings not being a name of any institution (e.g. `Astro`).

Would be great, if we had that fixed so we could connect Experiments and Institutions.

@kaplun

**Comment by kaplun** [comment]
Issue moved to [inspirehep/inspire #185](https://github.com/inspirehep/inspire/issues/185) via [**ZenHub**](https://www.zenhub.com/)
