### ISSUE TITLE
legacy: missing link between Jobs and Experiments

### ISSUE THREAD

**Issue by tomaszgy** [inspirehep/inspire-next#1280]
None of the records from _Jobs_ collection is connected by recid with an Experiment. Field `693__e` contains only Experiment's name.

As in https://github.com/inspirehep/inspire-next/issues/1274, would be great to have those connections.

@kaplun

**Comment by kaplun** [comment]
Issue moved to [inspirehep/inspire #186](https://github.com/inspirehep/inspire/issues/186) via [**ZenHub**](https://www.zenhub.com/)
