### ISSUE TITLE
legacy: missing link from Hepnames to PhdAdvisors

### ISSUE THREAD

**Issue by tomaszgy** [inspirehep/inspire-next#1283]
It seems like the link between a person from HepNames collection and his/hers supervisor is lost. At least, there is no connection by `recid`, only by INSPIRE ID e.g. `INSPIRE-00188911`.

Would be more convenient if we had `recids`.

Thanks a lot in advance, @kaplun, for fixing it :smile:

**Comment by kaplun** [comment]
I am implementing it at the moment, and this is the occasion to also do autoclaim for all those HEPNames for which we have an INSPIRE ID. Yay!

**Comment by kaplun** [comment]
Issue moved to [inspirehep/inspire #184](https://github.com/inspirehep/inspire/issues/184) via [**ZenHub**](https://www.zenhub.com/)
