### ISSUE TITLE
Set up record and file permissions

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1288]
Related to https://github.com/inspirehep/inspire-next/issues/1285

For record and file permission, keep an eye at this example:

https://github.com/CERNDocumentServer/cds/pull/160/files

**Comment by jmartinm** [comment]
Not a blocker for Invenio 3 deployment?

**Comment by kaplun** [comment]
I think it is because, users might still visit our records on labs (since we synchronize them for autocompletion)

**Comment by jmartinm** [comment]
Closed by https://github.com/inspirehep/inspire-next/pull/1589 for record permissions.

Once we add files to labs we can add the permission for them.
