### ISSUE TITLE
Pin down clean-css version

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-next#1296]
Investigating with @eamonnmag and @jmartinm, we found out that the newer clean-css (3.4.18) breaks the assets build step, so the version of clean-css should be pinned down (last known working version being 3.4.9).

Probably remove from puppet installation and move to the build step if possible.

**Comment by jmartinm** [comment]
Another option (that we should do anyways) is to correct the [problematic file](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/theme/static/scss/holding-pen/holding-pen.scss#L2) as importing CSS from SASS file [does not really work](https://github.com/sass/sass/issues/556).

Instead we can include that css file in the bundle file https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/workflows/bundles.py
