### ISSUE TITLE
Suggestion for HAL Hidden papers should be automatically rejected

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1297]
Say that a user suggests a paper that is in the HAL Hidden collection:
https://inspirehep.net/collection/HAL%20Hidden

Then:
- if the user is a French cataloguer we should say that the paper already exists
- else: if should thank for the suggestion but state that it had already been considered as pertinent...

**Comment by jmartinm** [comment]
So for non-cataloger users, a message like this?

<img width="1010" alt="screen shot 2016-07-07 at 1 36 28 pm" src="https://cloud.githubusercontent.com/assets/580727/16652014/ed0f8578-4447-11e6-9c13-9f029a5a1572.png">

**Comment by jmartinm** [comment]
Updated it to be closer to the standard message we send on rejection:

<img width="992" alt="screen shot 2016-07-07 at 1 49 54 pm" src="https://cloud.githubusercontent.com/assets/580727/16652281/b7136eec-4449-11e6-951f-c71ce32e05fb.png">

**Comment by jmartinm** [comment]
And for a cataloger, the standard message that points to the record:

<img width="1003" alt="screen shot 2016-07-07 at 1 52 15 pm" src="https://cloud.githubusercontent.com/assets/580727/16652326/070b4906-444a-11e6-85bd-812b3d3ca199.png">

**Comment by jmartinm** [comment]
Merged https://github.com/inspirehep/inspire-next/commit/3af86c2e45f128dac6b010c069fb26d532956599 and deployed.

**Comment by jmartinm** [comment]
* [ ] Port code to `master` code
