### ISSUE TITLE
Support hidden pubnote

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1331]
On legacy we are about to:
[...]
introduce hidden pubnote 7731_  without the R in pages and include that in the journal index (currently 773__%) and journal_page (773__c) logical field

currently less than 600 records affected according to Kirsten

I find only 62
https://inspirehep.net/search?p=773__c%3A%2F^r[0-9]%2B%24%2F&ot=773&rg=250

[...]

**Comment by StellaCh** [comment]
@michamos can we close this?

**Comment by jacquerie** [comment]
@michamos added this in https://github.com/inspirehep/inspire-schemas/pull/137.
