### ISSUE TITLE
Support new fields of Journal records

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1332]
See: https://twiki.cern.ch/twiki/bin/view/Inspire/DevelopmentRecordMarkupJournals

In particular the new fields describing the journal coverage.

See also https://app.asana.com/0/inbox/3720556472136/154009663633468/154737970387348

**Comment by StellaCh** [comment]
@michamos can we close this?

**Comment by michamos** [comment]
yes, we have `_harvesting_info` for journal coverage.
