### ISSUE TITLE
references.items.properties.url should be plural

### ISSUE THREAD

**Issue by harunurhan** [inspirehep/inspire-next#1345]
`references.items.properties.url` in the schema should `references.items.properties.urls` instead.  Because it is an array, also it is `urls` in records.

I wonder how this didn't break any tests.

**Comment by kaplun** [comment]
Ah these URL. @mihaibivol I guess this is amended already in your #1279

**Comment by eamonnmag** [comment]
If urls is not a required property and if additional properties are allowed
(true by default) then validation won't break.

**Comment by harunurhan** [comment]
@eamonnmag isn't schema supposed to cover all possible fields? and additionals aren't allowed.

**Comment by jacquerie** [comment]
> Isn't schema supposed to cover all possible fields? and additionals aren't allowed.

Nope, not at all. In fact, this is why the JSON Schema specification itself can be arbitrarily extended.

**Comment by eamonnmag** [comment]
It doesn't need to be. Additional properties can be allowed to give more
flexibility. The schema should just validate that what you expect to have
should be there, and in the right format.

**Comment by harunurhan** [comment]
Thanks!, Good to know. So `json-schema` is flexible but a little bit dangerous too. Also this might change my logic because currently I expect every field/sub-field to be in the schema.

**Comment by kaplun** [comment]
In a given object we can anyway enforce the allowed properties, and I believe we should do it all across the schemas. Otherwise we risks cataloguers to add again undesired properties that are not expected by the rest of the code.

We can simply add: {"additionalProperties": false}  anywhere in the schema.

**Comment by eamonnmag** [comment]
In reality,  we control the schema so it's OK. With additional properties
set to false you can have it fail when a property that doesn't exist in the
schema is found. So should be OK.

**Comment by mihaibivol** [comment]
@harunurhan now urls are like plural. You can check the new references schema from the current master.
