### ISSUE TITLE
RFC: isbns and dois in Literature schema

### ISSUE THREAD

**Issue by mihaibivol** [inspirehep/inspire-next#1349]
Currently we have these arrays inside the schema:
- `dois`
- `isbns`
- `publication_info`

`publication_info` also has an `isbn` field. I think it might be better to move everything that is publication related within `publication_info`. If we have only an ISBN then the publication info will contain only the ISBN information.

**Comment by kaplun** [comment]
The only issue I have is that ISBNs in publication info mean that the given document is a chapter inside a the referred book. Instead when the ISBN is in its own field it means that this record is about the book itself. At that point we should also have the imprint information (i.e. place, editor and year).

At the same time we have the concept of `being part of` which currently doesn't seem to be part of the `hep.json` schema. There is however a MARC tag for that: 78708 i.e. related record.

**Comment by kaplun** [comment]
@annetteholtkamp what is the actual way we relate a book chapter to its book?

**Comment by annetteholtkamp** [comment]
773__0 contains the recid of the book. Usually the 773 field for a book chapter contains just
773__0 and 773__c (page range).
But it may also be 773__i (for ISBN) and 773__c.

One could also imagine using the DOI of the book to refer to it. In principle it would be great if many identifiers are allowed to save cataloguers the work of looking up the recid.

We also have links via report number. E.g..
773__r may refer to a CERN yellow report

- Annette

On Jul 20, 2016, at 9:55 AM, Samuele Kaplun <notifications@github.com<mailto:notifications@github.com>> wrote:


@annetteholtkamp<https://github.com/annetteholtkamp> what is the actual way we relate a book chapter to its book?

**Comment by david-caro** [comment]
@kaplun if you are not working on this, move back to ready and unassign :+1:

**Comment by kaplun** [comment]
You are going to work on it?

**Comment by david-caro** [comment]
Are you asking or assigning? ;), but in any case, move to ready then, if you want me to work on it assign it to me  too.

**Comment by kaplun** [comment]
You self assign-it :P

**Comment by jacquerie** [comment]
This looks like a content decision. I think that @michamos should look at it and decide.

**Comment by michamos** [comment]
I am not sure I understand the issue. In `publication_info`, `parent_isbn`, `parent_record` and `parent_record_number` are defined. Maybe we also need `parent_doi` which is not currently defined? 

@annetteholtkamp ?

**Comment by annetteholtkamp** [comment]
That's a nice idea. The issue probably never came up before. But more and more books have a DOI, e.g. Springer books and proceedings. So it would be very useful if we can refer to a parent via its DOI.

- Annette


On May 11, 2017, at 4:52 PM, Micha Moskovic <notifications@github.com<mailto:notifications@github.com>> wrote:


I am not sure I understand the issue. In publication_info, parent_isbn, parent_record and parent_record_number are defined. Maybe we also need parent_doi which is not currently defined?

@annetteholtkamp<https://github.com/annetteholtkamp> ?

**Comment by jacquerie** [comment]
This issue was moved to inspirehep/inspire-schemas#210
