### ISSUE TITLE
schema utilities

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1355]
- [ ] We need a function that given a JSON parses from the schema URL the document type
- [ ] We need a function that given document type returns the Schema URL to be put in the schema field.
- [ ] We should refactor to use above functions.

**Comment by jacquerie** [comment]
This should be just a lookup in the following table:

| Schema URL | Document type |
| --------------- | ------------------ |
| /schema/records/hep.json | HEP |
| /schema/records/authors.json | Author |
| /schema/records/conferences.json | Conference |
| /schema/records/jobs.json | Job |
| /schema/records/institutions.json | Institution |
| /schema/records/experiments.json | Experiment |
| /schema/records/journals.json | Journal |

...which begs the following questions:

1. Why are all schema names plural (except HEP), when they define a single object?
2. Isn't HEP somewhat confusing as a document type, since it tells nothing about the contents?
3. We are never going to use HEPNames ever again, right?

**Comment by jmartinm** [comment]
>  We need a function that given a JSON parses from the schema URL the document type

Note that there is a similar function already. https://github.com/inveniosoftware/invenio-indexer/blob/master/invenio_indexer/api.py#L46-L59

> We need a function that given document type returns the Schema URL to be put in the schema field.

I guess we will make use of `url_for` like here - https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/literaturesuggest/tasks.py#L60-L62

> We should refactor to use above functions.

What places need to be refactored?

**Comment by jmartinm** [comment]
@jacquerie 

> Why are all schema names plural (except HEP), when they define a single object?

I think it would be nice to rename them to singular form.

Also, shall we use a version number for both schemas and ES mappings following Invenio standard? See [here](https://github.com/inveniosoftware/invenio-openaire/tree/master/invenio_openaire/jsonschemas/grants) or [here](https://github.com/inveniosoftware/invenio-marc21/tree/master/invenio_marc21/mappings/marc21/bibliographic).

> Isn't HEP somewhat confusing as a document type, since it tells nothing about the contents?

We can rename to Literature to match the collections (the name we use for display) as we do with the other ones.

> We are never going to use HEPNames ever again, right?

Nope, it was kept somehow for the migrator to understand the legacy `HepNames` collection I think but as soon as possible it can be killed.

**Comment by kaplun** [comment]
> Note that there is a similar function already. https://github.com/inveniosoftware/invenio-indexer/blob/master/invenio_indexer/api.py#L46-L59

Good. At that time I couldn't find it. Plus it's a private function `_record_to_index`, so should then be renamed and put into some utils, so that it's easily findable.

> What places need to be refactored?

Eh... I have no answer. But is this topic superseded by what you explained me IRL about the class-based implementation?

**Comment by kaplun** [comment]
@tomaszgy is looking for the same question: given a JSON what is going to its collection (whatever that means nowadays?) or index? or type? aaaaaghhh

@jmartinm @jacquerie @mihaibivol

**Comment by kaplun** [comment]
We found `InspireRecordIdProvider.schema_to_pid_type()`: I guess this is what we were looking for?

**Comment by jacquerie** [comment]
As far I can see, this is no longer a problem. Comments that pointed to this issue were simply addressed by a couple lines like https://github.com/inspirehep/inspire-next/blob/26d42863b7f86af22bd7a62efe7b05905740dea7/inspirehep/modules/records/receivers.py#L63-L64, and for the other conversions you will want to use one of https://github.com/inspirehep/inspire-next/blob/26d42863b7f86af22bd7a62efe7b05905740dea7/inspirehep/modules/pidstore/utils.py#L41-L70 or a lookup in https://github.com/inspirehep/inspire-next/blob/26d42863b7f86af22bd7a62efe7b05905740dea7/inspirehep/config.py#L298-L306.
