### ISSUE TITLE
pidstore: grab recid from production

### ISSUE THREAD

**Issue by jacenkow** [inspirehep/inspire-next#1356]
Create a HTTP wrapper that gets next `pid` from the production.

CC: @kaplun 😉

**Comment by kaplun** [comment]
Uh. I remember we discusssed about this in the past. We haven't put it on github?

**Comment by jacquerie** [comment]
I disagree. Why should we introduce a dependency on legacy? We should be able to drop legacy at a moment's notice.

**Comment by kaplun** [comment]
Because legacy is master for the first part of the future. So whenever we create a record on labs that we want to push to legacy, and we need, for whatever reason, to know what recid this record has, we need to reserve it for the first period on legacy.

**Comment by jacenkow** [comment]
Closed by #1502.
