### ISSUE TITLE
schemas: format keyword does nothing

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-next#1363]
Oh, this is going to be fun.

```
In [1]: from jsonschema import validate

In [2]: schema = {
   ...:     'format': 'uri',
   ...:     'type': 'string',
   ...: }

In [3]: validate('  ', schema)

In [4]: validate(42, schema)
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
<ipython-input-6-1b316f1498c4> in <module>()
----> 1 validate(42, schema)

/Users/jacquerie/Code/jsonschema/jsonschema/validators.py in validate(instance, schema, cls, *args, **kwargs)
    476         cls = validator_for(schema)
    477     cls.check_schema(schema)
--> 478     cls(schema, *args, **kwargs).validate(instance)

/Users/jacquerie/Code/jsonschema/jsonschema/validators.py in validate(self, *args, **kwargs)
    121         def validate(self, *args, **kwargs):
    122             for error in self.iter_errors(*args, **kwargs):
--> 123                 raise error
    124
    125         def is_type(self, instance, type):

ValidationError: 42 is not of type 'string'

Failed validating 'type' in schema:
    {'format': 'uri', 'type': 'string'}

On instance:
    42
```

In fact this is documented by the implementation of JSONSchema we use: https://github.com/Julian/jsonschema/blob/37a7bb96cacb7db6e589bdb054e49e62c4367a7e/jsonschema/_format.py#L13-L15

One could define `FormatChecker`s that implement these format checks, but then our schemas are not portable, not even between Python and JavaScript. So we should replace all them with `pattern`s, which do work in JSONSchema and are standard JavaScript regular expressions.

**Comment by kaplun** [comment]
No format enforced means we can actually enforce all formats :dancer: What if we actually do that? In this way we can e.g. enforce a `date` format to actually validate if the date is correct. Or an ISBN format that checks the checksum, same thing for ORCID. The number of these convention we need to implement for INSPIRE is not large, and would make validation great again. 

For @harunurhan's record-editor we could then have the client code to provide a mapping between formats and validation functions...

**Comment by jacquerie** [comment]
Oh, I forgot to add that `invenio-records` does not currently support `FormatChecker`s being passed to validators: https://github.com/inveniosoftware/invenio-records/blob/aab3b024d0078ccd36334e1d2faae02d078c8882/invenio_records/ext.py#L49-L57.

**Comment by kaplun** [comment]
We can propose an extension then. Would you mind opening an Issue in the repo? I can very see it can be implemented in a non disruptive way that could be easily get integrated.

**Comment by harunurhan** [comment]
@kaplun 

I think we should always have `pattern` where constraint can be described as `regexp`, because having `format` means that we should maintain the code that produces always same results in two places, in two different languages, so it is better to have as few as possible.

However, if it can not be described as `regexp` like `isbn`'s checksum thingy then we should use `format` since we have no other option 😄

**Comment by jacquerie** [comment]
> Would you mind opening an Issue in the repo?

https://github.com/inveniosoftware/invenio-records/issues/142

**Comment by jacquerie** [comment]
Solution coming in https://github.com/inveniosoftware/invenio-records/pull/144

**Comment by jacquerie** [comment]
https://github.com/inveniosoftware/invenio-records/pull/144 has been merged, so now the ball is on us to write a `FormatChecker` for our use case (and maybe try to get a release for `invenio-records`.

**Comment by jacquerie** [comment]
Formats are validated thanks to work from @michamos in `inspire-schemas`.
