### ISSUE TITLE
RFC Authors' profiles look.

### ISSUE THREAD

**Issue by MSusik** [inspirehep/inspire-next#138]
Hello!

Lately I've beeen working on moving the authors front-end to pu. I tried to keep the look with the current box order. Unfortunately it seems that that we don't have enough space to do that. Here is a screenshot from 1920x1080 monitor from demosite:

![wronglook](https://cloud.githubusercontent.com/assets/6649290/4935440/c44ed178-65ac-11e4-9f24-2d3f9ec56cce.png)

The boxes that in my opinion look wrong:
+ Personal details - rows don't fit.
+ Publications - this box should be wider so that most of the rows don't break in half
+ Papers - I wanted to use Bootstrap table to make it more readable. One column has been cut-off
+ Publication-graph - This is the smallest problem, we can create smaller icons.

<sub><sup>I don't want to discuss here any issues regarding compability with Invenio. This RFC aims to gather requirements for Inspire next author's page (and that's why it is here) and look for a solution for Inspire only. I need to know what will be needed by Inspire before I start writing the demosite version.
The solution implemented by me will work well for Invenio framework.</sub></sup>

### Proposal

Redesign. I know that it took a lot of time to develop current look, but we need to go forward.

@glouppe @jmartinm @kaplun

**Comment by PXke** [comment]
Hello, just an insight from outside. If you decide to implement badges, it would be cool to have the possibility to disable it. 

A bit like phabricator has its phun mode and pro. Not saying that badges is unprofessional but it can be perceived like that. 


It would be cool to have a panel like piwik. Where every simple table can be turned into a plot. 
It allows to summarize data when sometimes we have to many. 

Cheers, and have fun !

**Comment by kaplun** [comment]
This has been superseded as like as #218
