### ISSUE TITLE
tests: untrusted content of type pickle while migrating

### ISSUE THREAD

**Issue by jacenkow** [inspirehep/inspire-next#1396]
## Problem
If your first test case runs for more than 10 minutes, it will be automatically terminated by `Travis` due to inactivity.

One of the reasons for that might be a crash in `Celery` while migrating demo records.

## Check
Obviously the first thing to do is to run tests locally on your machine (always do that before submitting a PR 😉 ). Do that using `python setup.py test --addopts="..."` command while having `honcho` running in your terminal.

## Output
In the same terminal, where you are running `honcho` you should see a crash from `Celery` worker.
You might see something like
```
ContentDisallowed: Refusing to deserialize untrusted content of type pickle
(application/x-python-serialize)
```

## Why
According to @jacquerie and @mihaibivol, seems like Celery is changing the way of serialization while doing tests related to `Celery` tasks.

## How to fix it
Try to move your imports into the tests definitions.
For example, from a code looking like that
```python
from foo import bar

def test_use_case(app):
    assert bar() == 1
```

do that

```python
def test_use_case(app):
    from foo import bar

    assert bar() == 1
```

🎱

**Comment by jacquerie** [comment]
To clarify: only **tasks** imports have to be local. General imports don't and shouldn't be local.
