### ISSUE TITLE
RFC API: /authors endpoint

### ISSUE THREAD

**Issue by jacenkow** [inspirehep/inspire-next#1416]
As @jacquerie  requested, the API endpoint for `/authors` should be changed to meet the following requirements:

* `/authors/<pidpath(authors):pid_value>`
    Should return the whole metadata for a given `pid` value.
    I believe there is no need to change.

    See [Darien Robert Wood](http://localhost:5000/api/authors/983220) as an example.

* `/authors/<pidpath(authors):pid_value>/affiliations`
    Should return a list of affiliations for a given `pid` value.

    However, do we really need this, since it is exactly the same process as calling
    `/authors/<pidpath(authors):pid_value>` and accessing `['positions']` key?

* `/authors/<pidpath(authors):pid_value>/citations`
    Should return a list of citations for a given `pid` value.

    For example,
    ```python
    {
        "date": "2016-08-09",
        "reference": {
            "record": {
                "$ref": "http://localhost:5000/api/literature/1356276"
            }
        },
        "citation": {
            "record": {
                "$ref": "http://localhost:5000/api/literature/1406194"
            }
        }
    }
    ```

* `/authors/<pidpath(authors):pid_value>/coauthors`
    Should return a list of co-authors for a given `pid` value.

    For example,
    ```python
    {
        "date": "2015-03-26",
        "record": {
            "$ref": "http://localhost:5000/api/literature/1356276"
        },
        "author": {
            "record": {
                "$ref": "http://localhost:5000/api/authors/990458"
            }
        }
    }
    ```

    However, I believe it would be more useful to group co-authors, by keys representing
    `pid` values like in the following example,

    ```python
    {
        "990458": {
            "name": "Sanchez-Hernandez, Alberto",
            "publications": [
                {
                    "$ref": "http://localhost:5000/api/literature/1356276"
                },
                ...
            ],
            "record": {
                "$ref": "http://localhost:5000/api/authors/990458"
            },
            "shared_publications_count": 550,
        }
    }
    ```

* `/authors/<pidpath(authors):pid_value>/publications`
    Should return a list of publications for a given `pid` value.

    For example,
    ```python
    {
        "date": "2015-03-26",
        "title": "Combined Measurement of the Higgs Boson Mass in pp Collisions at √s=7 and 8 TeV with the ATLAS and CMS Experiments",
        "journal": {
            "title": "Phys.Rev.Lett.",
            "record": {
                "$ref": "http://localhost:5000/api/journals/1214495"
            }
        },
        "record": {
            "$ref": "http://localhost:5000/api/literature/1356276"
        }
    }
    ```

* `/authors/<pidpath(authors):pid_value>/stats`
    Should return different metrics for a given `pid` value.

    For example,
    ```python
    {
        "hindex": 137,
        "publications": 1139,
        ...
    }
    ```

I am not quite sure about `/authors/` endpoint (with no `pid`). Seems like for this moment we return not processed Elasticsearch result with well known to everyone `['hits']['hits']`. Is it something that we want? Should we just return `pid`s of available author profiles to access?

CC: @kaplun @jmartinm

**Comment by jacquerie** [comment]
> * `/authors/<pidpath(authors):pid_value>`
>     Should return the whole metadata for a given `pid` value.
>     I believe there is no need to change.
> 
>     See [Darien Robert Wood](http://localhost:5000/api/authors/983220) as an example.

:+1:

> * `/authors/<pidpath(authors):pid_value>/affiliations`
>     Should return a list of affiliations for a given `pid` value.
> 
>     However, do we really need this, since it is exactly the same process as calling
>     `/authors/<pidpath(authors):pid_value>` and accessing `['positions']` key?

Yeah, I don't like this either. Something more interesting would be disaggregating the bibliometric data per affiliation, so that one can compare authors' output to colleagues... But we can discard this in the first iteration of the API.

> * `/authors/<pidpath(authors):pid_value>/citations`
>     Should return a list of citations for a given `pid` value.
> 
>     For example,
>     ```python
>     {
>         "date": "2016-08-09",
>         "reference": {
>             "record": {
>                 "$ref": "http://localhost:5000/api/literature/1356276"
>             }
>         },
>         "citation": {
>             "record": {
>                 "$ref": "http://localhost:5000/api/literature/1406194"
>             }
>         }
>     }
>     ```

👍 , except I don't like the words "reference" and "citation"... "cited" and "citing"? I don't know.

> * `/authors/<pidpath(authors):pid_value>/coauthors`
>     Should return a list of co-authors for a given `pid` value.
> 
>     For example,
>     ```python
>     {
>         "date": "2015-03-26",
>         "record": {
>             "$ref": "http://localhost:5000/api/literature/1356276"
>         },
>         "author": {
>             "record": {
>                 "$ref": "http://localhost:5000/api/authors/990458"
>             }
>         }
>     }
>     ```
> 
>     However, I believe it would be more useful to group co-authors, by keys representing
>     `pid` values like in the following example,
> 
>     ```python
>     {
>         "990458": {
>             "name": "Sanchez-Hernandez, Alberto",
>            "publications": [
>                 {
>                     "$ref": "http://localhost:5000/api/literature/1356276"
>                 },
>                 ...
>             ],
>             "record": {
>                 "$ref": "http://localhost:5000/api/authors/990458"
>             },
>             "shared_publications_count": 550,
>         }
>     }
>     ```

I like your alternate proposal, but I don't like the idea of returning an object with keys the PIDs: just return a list of objects like you described. The PIDs are redundant information anyway.

> * `/authors/<pidpath(authors):pid_value>/publications`
>     Should return a list of publications for a given `pid` value.
> 
>     For example,
>     ```python
>     {
>         "date": "2015-03-26",
>         "title": "Combined Measurement of the Higgs Boson Mass in pp Collisions at √s=7 and 8 TeV with the ATLAS and CMS Experiments",
>         "journal": {
>             "title": "Phys.Rev.Lett.",
>             "record": {
>                 "$ref": "http://localhost:5000/api/journals/1214495"
>             }
>         },
>         "record": {
>             "$ref": "http://localhost:5000/api/literature/1356276"
>         }
>     }
>     ```

Here I don't like the limited subset of data that you return per publication. Keywords could be interesting, the fact that this is a collaboration paper could be interesting (people use crazy query strings to query for an author but avoid all collaboration papers)...

> * `/authors/<pidpath(authors):pid_value>/stats`
>     Should return different metrics for a given `pid` value.
> 
>     For example,
>     ```python
>     {
>         "hindex": 137,
>         "publications": 1139,
>         ...
>     }
>     ```

Here we definitely need experts' input on a concise set of bibliometric data to implement. @inspirehep/inspire-content 

> I am not quite sure about `/authors/` endpoint (with no `pid`). Seems like for this moment we return > not processed Elasticsearch result with well known to everyone `['hits']['hits']`. Is it something that > we want? Should we just return `pid`s of available author profiles to access?

IMO we should return brief serialization of authors, like: https://api.github.com/users. You can discard this in the first API iteration.

**Comment by kaplun** [comment]
Mmh. I believe most of these proposals are suitable to whatever subset of papers, of which those identified by `/authors/<pidpath(authors):pid_value>` are only a subset. 

Wouldn't be better to have these endpoints to answer for any type of query.

I am not sure I am enough clear. Maybe more on IRL.

**Comment by jacenkow** [comment]
Following my meeting with @jacquerie and @kaplun, these are the expecting endpoints.

* `/authors/<pidpath(authors):pid_value>/coauthors`

  ```python
  {
      "_id": "990458",
      "coauthored": [
          #left for the second iteration.
      ],
      "count": 1234,
      "name": "Sanchez-Hernandez, Alberto",
      "record": {
          "$ref": "http://localhost:5000/api/authors/990458"
      }
}

**Comment by kaplun** [comment]
cc: @jmartinm @eamonnmag

**Comment by kaplun** [comment]
> Here I don't like the limited subset of data that you return per publication. Keywords could be interesting, 

@jacquerie I am not sure keywords need to be presented through this API directly because they can not easily be aggregated in this format (and that's the main reason to expose them, otherwise they are more needed to do faceting and search result boosting)...

**Comment by jacenkow** [comment]
#1463 🍠
