### ISSUE TITLE
Redirection to homepage

### ISSUE THREAD

**Issue by Panos512** [inspirehep/inspire-next#1433]
We should have a fast way to redirect to our homepage. 

Something like would do the trick:
```python
redirect('home')
```

Since that's an operation we do quite often (on errors, on logo clicking etc) it would be very useful.

**Comment by jmartinm** [comment]
@Panos512 I think this is a concrete problem you are having?

Because according to the docs (http://flask.pocoo.org/docs/0.10/api/#flask.redirect) I think `redirect('/')` should work. Or `redirect(url_for('inspirehep_theme.index'))`

**Comment by Panos512** [comment]
Ow, yeah, if it's that way then it's concrete and we can close this. @jacquerie can also have a quick look (in case I misunderstood what we were discussing this morning).

**Comment by jmartinm** [comment]
I just did a quick test and `return redirect('/')` works for me.
