### ISSUE TITLE
API: how to expose functionality of your module

### ISSUE THREAD

**Issue by jacenkow** [inspirehep/inspire-next#1454]
## Getting your module to the next level.
Every module has its purpose, logic and a set of requirements to accomplish. However, most of the time you cannot proceed with the work without writing helper methods (these ones, which look like `_foo(bar)`) or any other functions that are meant to be used only within the module.

The question you might ask yourself is how to write, name or what is the way of exposing the functions that other components can use or what is the only proper way of accessing your module.

## API.
Obviously you can name all the internal methods with `_` at the beginning (as mentioned before) and even you should, but still leaving the main methods somewhere in your module might be problematic for other developers to apply in the proper way as you designed to.

The answer for the following problem might be a file called [`api.py`](https://invenio.readthedocs.io/en/latest/architecture/module-anatomy-structure.html). Not going into the definition of [API](https://en.wikipedia.org/wiki/Application_programming_interface) as well as why you should write one, let's just say that the code will be better and writing code, which reminds building blocks allows for better code maintenance and reuse in future.

So to conclude, if you wish to expose certain functionality to other users, put the appropriate method into `api.py`.

## API vs RESTful API.
Most of the time when we refer to `API`, what we mean is `RESTful API`. In terms of **Inspire** we would like to distinguish methods that are exposed across the whole system (`internal API`) and to UI (in the sense of `Angular.js` applications on the frontend side) and external developers, who can access resources using `/api` endpoint (`external API` accessible via `HTTP`).

If you think that some of your logic can be useful for other developers go for it, create a `RESTful` endpoint for your module.

## Ok, but how?
Now the fun part comes in. Currently `Invenio` does not support custom APIs. What is being offered at the moment (this `how-to` was written on the 19th August 2016, so by the time you are reading this text, it might be outdated) are API wrappers for all records within collections. What I mean by this is simply showing all data that we have or a single record (check [authors](http://localhost:5000/api/authors/) and [author profile](http://localhost:5000/api/authors/983220)).

However, what is possible with the current API are custom `serializers`. So special type of functions responsible for translating source object into another type of an object. You can ask the API to return your data not only in `JSON` but in `bibtex` format for example.

## Wait, what?!
Yeah, this is a *hacky* way of expanding the API, however it provides you functionality for grabbing a record, so you don't have to implement `pid` resolves or anything, which leads to finding an appropriate record while `/api/authors/<pidpath(authors):pid_value>/custom_endpoint` is being called.

## How? `config.py`
Let's start with the configuration file. Go to `inspirehep/config.py` and grep for `RECORDS_REST_ENDPOINTS` key. This is the configuration of `invenio-records-rest` and our start point. Let's say you want to expand the API for `authors` collection. What we want to do is create a new endpoint, which will provide publications for a given author. The endpoint for this type of action would be [`/api/authors/<pidpath(authors):pid_value>/publications`](https://github.com/inspirehep/inspire-next/issues/1416).

Now add to `RECORDS_REST_ENDPOINTS` something like that
```python
FILE: inspirehep/config.py

authors_publications=dict(
    pid_type='authors',
    pid_minter='inspire_recid_minter',
    pid_fetcher='inspire_recid_fetcher',
    search_class='inspirehep.modules.search:AuthorsSearch',
    record_serializers={
        'application/json': ('inspirehep.modules.authors.serializers'
                             ':publications_v1_response'),
    },
    search_serializers={
        'application/json': ('invenio_records_rest.serializers'
                             ':json_v1_search'),
    },
    list_route='/authors/',
    item_route='/authors/<pidpath(authors):pid_value>/publications/',
    default_media_type='application/json',
    max_result_window=10000,
    search_factory_imp=('inspirehep.modules.search.query'
                        ':inspire_search_factory'),
)
```

This is the minimum configuration for a new API endpoint. Even you are not interested in providing a list of all publications available (which is not our case, since we have `literature` for that), you must provide that. To explain, what each key is doing take a look [here](https://pythonhosted.org/invenio-records-rest/api.html#invenio_records_rest.config.RECORDS_REST_ENDPOINTS). To highlight the most important keys, `item_route` and `record_serializers` are responsible for handling single records, while `list_route` and `search_serializers` for whole collections (more less).

## How? Serializers.
So as you have noticed we have two `serializers`. Now we are going to focus on a custom `record_serializer`. Go to your module (in our example we will use `authors` module) and create a new folder called `serializers`. Inside the new folder we are going to create a new file called `publications.py`.

Inside we create a new class with record `serializer`, something like that

```python
FILE: inspirehep/modules/authors/serializers/publications.py

from __future__ import absolute_import, division, print_function

import json


class AuthorAPIPublications(object):

    def serialize(self, pid, record, links_factory=None):
        """Get author's name.
        :param pid: Persistent identifier instance.
        :param record: Record instance.
        :param links_factory: Factory function for the link generation,
                              which are added to the response.
        """
        out = record['name']['value']

        return json.dumps(out)
```

Obviously the endpoint doesn't return the list of publications for a given author, but instead is accessing the record (author, who is being called, like Darien Robert Wood from our [example](http://localhost:5000/api/authors/983220)) and finally returning his name.

In case you are interested in developing a search `serializer`, inside the same class add another method called `serialize_search`

```python
FILE: inspirehep/modules/authors/serializers/publications.py

def serialize_search(self, pid_fetcher, search_result, links=None,
                     item_links_factory=None):
    """Serialize a search result.
    :param pid_fetcher: Persistent identifier fetcher.
    :param search_result: Elasticsearch search result.
    :param links: Dictionary of links to add to response.
    """
    records = []
    for hit in search_result['hits']['hits']:
        records.append(json.dumps(hit['name']['value']))

    return "\n".join(records)
```

## How? `__init__.py`
The last part of our little API journey is to create `__init__.py` inside `serializers` folder.

In the config file we point the record `serializer` to use 
```python
FILE: inspirehep/config.py

record_serializers={
    'application/json': ('inspirehep.modules.authors.serializers'
                         ':publications_v1_response'),
},
```

In order to hook up our new `serializer` to the path we point in the configuration file, create `__init__.py`, which looks more less like that

```python
FILE: inspirehep/modules/authors/serializers/__init__.py

from __future__ import absolute_import, division, print_function

from inspirehep.modules.authors.serializers.publications import AuthorAPIPublications
from inspirehep.modules.records.serializers.response import (
    record_responsify_nocache,
)

publications_v1 = AuthorAPIPublications()
publications_v1_response = record_responsify_nocache(coauthors_v1,
                                                  'application/json')
```

Voilà! Now after restarting `honcho` you should be able to access author's name using `/api/authors/<pidpath(authors):pid_value>/publications/` path.

If you were cool enough to create a search `serializer`, then `__init__.py` should look like that

```python
FILE: inspirehep/modules/authors/serializers/__init__.py

from __future__ import absolute_import, division, print_function

from invenio_records_rest.serializers.response import search_responsify

from inspirehep.modules.authors.serializers.publications import AuthorAPIPublications

publications_v1 = AuthorAPIPublications()
publications_v1_search = search_responsify(coauthors_v1,
                                           'application/json')
```

with appropriate change in the configuration file of Inspire

```python
FILE: inspirehep/config.py

search_serializers={
    'application/json': ('inspirehep.modules.authors.serializers'
                         ':publications_v1_search'),
},
```

## But.
As I said before this the *hacky* way of expanding API and `serializers` are not meant to have logic, which goes beyond translating one object to another.  We use them, because they provide ready record for us to work with.

If the module you are working on doesn't have anything to do with single records, let's say `/api/stats/` I would recommend to use `Flask` blueprints and hook them up into the `Flask` application responsible for `/api` endpoints (check `inspirehep/factory.py` for the reference).

But using blueprints is a topic for another `how-to`.
Happy hacking!

**Comment by kaplun** [comment]
@jacenkow thanks for these bits!

I would also point to the official module architecture we are following: http://invenio.readthedocs.io/en/latest/architecture/module-anatomy.html

**Comment by lnielsen** [comment]
FYI The documentation in https://invenio.readthedocs.io/en/latest/architecture/module-anatomy-structure.html has not yet been updated to Invenio 3.0 - e.g. we don't use ``restful.py`` anymore, but simple add them in ``views.py`` (or create a ``views`` package if sufficiently large and complex) - basically treating them as normal flask blueprints.

As discussed on gitter with @kaplun we use webargs for parameter parsing, marshmallow for serialisation and Flask MethodView or Invenio-REST's ContentNegotiatedMethodView for splitting requests into their type (GET/POST/PUT etc).

**Comment by jacenkow** [comment]
@lnielsen really kind of you to comment this issue 😄  thank you for taking your time.
We have just started expanding our API to serve more use cases and still I don't have a clear view how to do it, so really I appreciate the comment 👍
