### ISSUE TITLE
PDG

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1479]
210 RPP should be considered as a document type.

**Comment by kaplun** [comment]
See also: #1215

**Comment by StellaCh** [comment]
Can you please give more details on what should be done for this and what's the use case? @kaplun

**Comment by kaplun** [comment]
Issue moved to [inspirehep/inspire-schemas #286](https://github.com/inspirehep/inspire-schemas/issues/286) via [**ZenHub**](https://www.zenhub.com/)
