### ISSUE TITLE
RFC Reference matching algorithm

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1486]
Let's assume we have workflow "reference matching":
- [ ] if not raw reference:
  - [ ] run refextract
  - [ ] store refextract ref as raw ref of type refextract
- [ ] for every reference
  - [ ] translate reference into mini-record
  - [ ] try to match mini-record with existing one
  - [ ] if sure match
    - [ ] record the match
  - [ ] elif ambiguous match and CORE:
  - [ ] request cataloguer to check
  - [ ] else:
    - [ ] create stub-record
    - [ ] record the match

**Comment by annetteholtkamp** [comment]
What do we define as minimal metadata necessary for creating a stub record?

- Annette

**Comment by kaplun** [comment]
I'd say: 
* arXiv ID (because we can fetch the matadata on the fly from arXiv
* DOI (same reason from Crossref)
* ISBN (because we can fetch the book on the fly)
* journal, volume/issue, (year), pages (because it allows to unambiguously match it)
* reportnumber + title + author

**Comment by StellaCh** [comment]
@jacquerie shall we close this?

**Comment by jacquerie** [comment]
> @jacquerie shall we close this?

We shall.
