### ISSUE TITLE
Disentangling complex 773s

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1507]
Dear @inspirehep/inspire-content 

Migration of record https://inspirehep.net/record/820763/ into Labs is currently failing because we are not able to interpret the complex 773 field:
```xml
<datafield tag="773" ind1=" " ind2=" ">
<subfield code="p">IAU Symp.</subfield>
<subfield code="w">C08-06-09</subfield>
<subfield code="v">354</subfield>
<subfield code="y">2008</subfield>
<subfield code="v">254</subfield>
<subfield code="y">2009</subfield>
<subfield code="c">45</subfield>
</datafield>
```

Any hint on what we should do in this case?

Similar case for https://inspirehep.net/record/748272:
```xml
<datafield tag="773" ind1=" " ind2=" ">
<subfield code="p">IAU Symp.</subfield>
<subfield code="w">C86-10-20.2</subfield>
<subfield code="v">128</subfield>
<subfield code="y">2007</subfield>
<subfield code="w">C06-08-21.8</subfield>
<subfield code="x">
Black Holes from Stars to Galaxies - Across the Range of Masses. V. Karas and G. Matt. Eds. Proc. of IAU Symp. 238, 21-25 August, 2006 in Prague, Czech Republic (Cambridge, UK: Cambridge University Press, 2007), pp.173-180
</subfield>
<subfield code="v">238</subfield>
<subfield code="c">173-180</subfield>
</datafield>
```

For devs this correspond to : https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/601683/

**Comment by david-caro** [comment]
@kaplun see https://app.asana.com/0/2345936208876/173487614851515

**Comment by kaplun** [comment]
Yep this is also connected and another facet of this problem. (here the `$v` are kind of valid, but who knows which `$v` goes with which?) :)

**Comment by david-caro** [comment]
Hmm, I see the issue..., here we should have had multiple 773 datafields instead of merging two into the same datafield right?

**Comment by kaplun** [comment]
Yup! Maybe I should give a list to cataloguers for all those that have meshed up 773s to disentangle.

**Comment by kaplun** [comment]
Until then what we can do is to consider only the first subfield of each `code`.
