### ISSUE TITLE
migrator: mark records as deleted

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1523]
When migrating records from production, records that have `980:DELETED` should be marked as deleted in the new system.

This does not seem to be the case atm:

http://inspire-nightly.cern.ch/search?page=1&size=25&cc=literature&q=980:deleted

Note that `invenio-records` provides a `delete` method in the API - https://github.com/inveniosoftware/invenio-records/blob/master/invenio_records/api.py#L276 so we can use that to `soft-delete` the record.
# Extra

When the record is deleted, accessing the record URL should do a redirection if the field `new_recid` is present to the new record id (as it is the case in production).

**Comment by kaplun** [comment]
For the redirection this could done via the pidstore.

**Comment by jmartinm** [comment]
Done https://github.com/inspirehep/inspire-next/issues/1541
