### ISSUE TITLE
Author new form issues

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1532]
The author creation form can be found in: http://inspire-nightly.cern.ch/submit/author/create

Current issues:

* [x] Autocompletion for Institution not working. [See file](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/forms/static/js/forms/affiliations_typeahead.js)
* [x] Autocompletion for Experiment not working. [See file](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/forms/static/js/forms/experiments_typeahead.js)
* [x] Autocompletion for Advisors not working. [See file](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/forms/static/js/forms/authors_typeahead.js)

Correct behaviour can be seen in http://labs.inspirehep.net/author/new

**Comment by jacquerie** [comment]
Closed in https://github.com/inspirehep/inspire-next/pull/1602.
