### ISSUE TITLE
HAL: fixmes

### ISSUE THREAD

**Issue by liamkirsh** [inspirehep/inspire-next#1584]
- [ ] Check the for_hal flag in the record to determine if it should be submitted
- [ ] Build a mapping between our categorization and the [HAL domains specified](https://api-preprod.archives-ouvertes.fr/ref/domain/?fl=*&wt=xml) (detailed in #1590)
- [ ] Add conference city, country, and country code fields
- [ ] Complete the helper function that specifies the [file source](https://api-preprod.archives-ouvertes.fr/ref/metadataList/?q=metaName_s:fileSource&fl=*&wt=xml) in the XML

**Comment by annetteholtkamp** [comment]
Is there a for_hal flag already defined? The suggestion I've talked about with Mathieu is 595__c:HAL - analogous to the 595__c:CDS flag we're already using for CDS export.

- Annette


On Sep 20, 2016, at 5:17 PM, Liam Kirsh <notifications@github.com<mailto:notifications@github.com>> wrote:


  *    Check the for_hal flag in the record to determine if it should be submitted
  *    Build a mapping between our categorization and the HAL domains specified<https://api-preprod.archives-ouvertes.fr/ref/domain/?fl=*&wt=xml>
  *    Add conference city, country, and country code fields
  *    Complete the helper function that specifies the file source<https://api-preprod.archives-ouvertes.fr/ref/metadataList/?q=metaName_s:fileSource&fl=*&wt=xml> in the XML

**Comment by jacquerie** [comment]
> Is there a `for_hal` flag already defined?

Not yet. But it's an easy fix (although currently blocked by #1610).

**Comment by jacquerie** [comment]
> Is there a for_hal flag already defined?

Updating my earlier answer, we now have it: https://github.com/inspirehep/inspire-schemas/blob/2a4d55e1f1c82cfa3c63f8ee0dffe76e757217ce/inspire_schemas/records/hep.yml#L44-L65
