### ISSUE TITLE
RFC move schemas to their own module

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-next#1586]
Moving all the schemas to their own module allows to reuse them directly from other projects, and it also opens the door to reuse there all the utility functions around them without having to depend on the whole inspire-next project.

A first step is just to move the schemas themselves, then bit by bit start building/moving there the tools around it (validators and such).

**Comment by jacquerie** [comment]
Since this is an RFC, my comment is: yes, please. : )

**Comment by kaplun** [comment]
Do you have a repo where you are doing this? There is https://github.com/inspirehep/inspire-schemas

**Comment by david-caro** [comment]
Yes, I just created that one, I've just created too the project on pypi to upload it there.

**Comment by jacquerie** [comment]
Done in #1610.
