### ISSUE TITLE
Exclude deleted records from search results

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1587]
After https://github.com/inspirehep/inspire-next/pull/1541 is integrated we need to make sure that deleted records do not show up in search results.

This can be done by adding a `default_filter` to the search classes (https://github.com/inspirehep/inspire-next/blob/af161b903582f1356ca8d8b4bcef20d0a0a134e1/inspirehep/modules/search/api.py#L34) that will exclude records with `deleted:True`.

Example of how to use `default_filter` [here](https://github.com/inveniosoftware/invenio-search/blob/master/invenio_search/api.py#L63)

**Comment by kaplun** [comment]
Actually just found we can simply use: `COLLECTIONS_DELETED_RECORDS` from `invenio-collections`. https://github.com/inspirehep/inspire-next/pull/1589#issuecomment-249136142

**Comment by jmartinm** [comment]
The solution mentioned here will add to all our queries: `and not deleted:True` so deleted records would not be shown.

With `COLLECTIONS_DELETED_RECORDS` what happens is once a record is deleted it will not have any content in `_collections` field (but they will still be shown in search results)

**Comment by kaplun** [comment]
We understood IRL. :)

**Comment by jmartinm** [comment]
Closed by https://github.com/inspirehep/inspire-next/pull/1589
