### ISSUE TITLE
Supporting merging records

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1609]
In legacy when a record A is merged into a record B, A is tagged as deleted (`980__c` is set to `DELETED`) the recid of B is copied into `970__d` and when a user visit record A she is redirected to record B.

We need to implement the same behavior on master, and migrate existing merged information. I.e.:
- [x] We need to add to all schemas (when missing) a new field:

```
"new_record": {
            "$ref": "elements/json_reference.json",
            "description": "Master record that replaces this record",
            "title": "New record"
        },
```
- [x] We need to add rules for dojson that copy `970__d` into the proper URL in the above field. (e.g. http://localhost:5000/literature/1234)
- [x] We need to capture upon record insertion/update (i.e. with a receiver) when need to amend all the PIDs pointing to record A and make them redirect to record B.
- [x] BONUS POINT: schedule a task that look for all the records that were pointing to A and update them to point to B. Yay! (Actually see #484)

**Comment by jacquerie** [comment]
> * [ ] We need to add to all schemas a new field:
> ```json
>         "merged_into_record": {
>             "$ref": "elements/json_reference.json"
>         },
> ```

Note that in some cases the schema already contains something like this, like [here](https://github.com/inspirehep/inspire-next/blob/1ebd2de957ab668315ad85e5f6d5ab03a800a06e/inspirehep/modules/records/jsonschemas/records/hep.json#L561-L565), so you should be careful of not duplicating this information in two fields.

Note also that this is "blocked" by https://github.com/inspirehep/inspire-schemas/pull/1. "Blocked" in the sense that this may proceed, but after that PR is merged the schema modifications will have to be split there before merging.

**Comment by kaplun** [comment]
See:
https://gist.github.com/kaplun/fe17d07b6ece96d137b60fcdae45b6fc

for an example of the original MARCXML.

**Comment by kaplun** [comment]
> Note that in some cases the schema already contains something like this, like here, so you should be careful of not duplicating this information in two fields.

Right! That has to disappear. That field does not make sense because you don't want to have the merged record to point back to the deleted ones. It's a legacy information of legacy. Really really legacy :dancer:

**Comment by kaplun** [comment]
I was actually thinking that `deleted_records`  (i.e. `981`) should not be needed. But indeed we need it as long as legacy exist. Otherwise we risk to throw away info.

**Comment by jacquerie** [comment]
Done in #1790.
