### ISSUE TITLE
Re-harvesting one-shot records from arXiv

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1627]
Currently we are harvesting from arXiv several collections, for which we are thus also receiving updates. However some records are integrated out of the regular harvest.

We need to foreseen a background task that goes through out-of-main-harvesting records and poll arXiv in order to check for updates.

**Comment by StellaCh** [comment]
I think this is addressed @david-caro @michamos , but feel free to reopen it if that's not the case

**Comment by kaplun** [comment]
Indeed, once we harvest all OAI sets of arXiv as foreseen this is no longer necessary.
