### ISSUE TITLE
migration: missing validation errors

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-next#1641]
For the past week or so https://sentry.cern.ch/ has not received validation errors from workers. It appears that the error was introduced in https://github.com/inspirehep/inspire-next/commit/79057cea55fa69c5444bc3f65820fd54621beac3 (reverting that commit fixes the issue), so this has to be related to configuration initialisation.

You'll probably need our `SENTRY_DSN` to diagnose this. If you want to work on this, ask me for it.

**Comment by jacquerie** [comment]
...validation errors are back. I don't know why.

**Comment by jacquerie** [comment]
Oh, I know why. Tonight's migration was VERY slow because I didn't use the workers, but ran all tasks in the `web` container, which doesn't suffer from the above configuration issue. Bug still stands.

**Comment by jmartinm** [comment]
Checking locally, my observations are:

* Sentry receives errors when running outside Celery.

* Sentry receives errors when running inside Celery on a small test task.

* Sentry does NOT receive updates when having errors inside dojson rules during migration.

**Comment by kaplun** [comment]
Currently blocked upstream in inveniosoftware/flask-celeryext#26
