### ISSUE TITLE
assets: truncation at random (?) point

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-next#1642]
http://inspire-nightly.cern.ch/ currently looks pretty bad:

<img width="1246" alt="assets-bug" src="https://cloud.githubusercontent.com/assets/381280/19308390/935ccd22-907f-11e6-996e-d3630df7a283.png">

This is due to the infamous truncation bug we've been intermittently seeing on our development machines. It _could_ be related to this other truncation bug: https://github.com/miracle2k/webassets/issues/468. The only issue with this theory is that the file currently served is 51288 bytes, but this could be the effect of the `clean_css` filter run afterwards.

- [x] Remove the `clean_css` filter and confirm that the truncation happens at 65536 bytes.
- [ ] Work around the issue by pinning the known functioning version of `node-sass` when installing.

**Comment by jacquerie** [comment]
>  this could be the effect of the clean_css filter run afterwards

This is actually the case: the file currently served is exactly 65536 bytes.

**Comment by zzacharo** [comment]
@jacquerie If this is the same problem that i dealt with when i installed inspirehep, i just ran npm install node-sass@3.4.2.

**Comment by jmartinm** [comment]
@zzacharo for the moment it would be enough if you can update the documentation to specify the `node-sass` version needed.

**Comment by jacquerie** [comment]
> it would be enough if you can update the documentation to specify the `node-sass` version needed.

Sadly not :(

The fact is, `docker-compose -f docker-compose.deps.yml run --rm assets` will install things inside of the web container, which will fetch its own version of `node-sass` (currently 3.10.1). If we try to add `node-sass@3.4.2` to the `css` bundle in `inspirehep/modules/theme/bundles.py` then we get an `ELIFECYCLE` error: https://github.com/sass/node-sass/issues/1687#issuecomment-243103844

**Comment by jacquerie** [comment]
This is also blocking #1607.
