### ISSUE TITLE
docs: document the pin on node-sass

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-next#1644]
Follow up to https://github.com/inspirehep/inspire-next/issues/1642. Docs need to be updated to inform new developers that they must install `node-sass@3.8.0`.

- [x] Find all places in which we say to install `node-sass`
- [ ] Amend them with `node-sass@3.8.0`

**Comment by zzacharo** [comment]
@jacquerie I created a pull request for #1642  regarding the docs update.

**Comment by jacquerie** [comment]
```
$   ag --nobreak node-sass --files-with-matches
inspirehep/config.py
INSTALL.rst
```
so yeah, there's only one point in the docs where we talk about `node-sass`
