### ISSUE TITLE
Reissuing (smaller) demo records

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1648]
@tomaszgy reports that additional links understood in inspirehep/inspire-next#1451 are not represented yet in the Demo records, and should hence be added. Possibly with new records.

(e.g. institution 902624 links to 910724 as its parent but the latter is not present in data)

**Comment by tomaszgy** [comment]
Would be great to have in Demo records also [this record](http://inspirehep.net/record/910724) to test relation `CHILD_OF` in Neo4j migrator.

Institution [with recid no 902624](http://inspirehep.net/record/902624) links to [the one with recid 910724](http://inspirehep.net/record/910724) as its `parent` but the latter is not present inside Demo records.

**Comment by jacquerie** [comment]
I'd rather see less records in the demo records, selected in a better way, so that our test suites are faster.

**Comment by kaplun** [comment]
We can have both at the same time...

**Comment by tomaszgy** [comment]
Let me just write down here three more records that I used for integration tests in https://github.com/inspirehep/inspire-next/pull/1569 (left for now with x-fails):

* experiments no. [1346343](http://inspirehep.net/record/1346343) and [1332130](http://inspirehep.net/record/1332130)
* author no. [993266](http://inspirehep.net/record/993266)

If you decide to find some better examples, please update my tests.

**Comment by StellaCh** [comment]
Is this still relevant @jacquerie ?

**Comment by jacquerie** [comment]
> Is this still relevant @jacquerie ?

Nope, this happened in https://github.com/inspirehep/inspire-next/pull/1747.
