### ISSUE TITLE
JSON Store

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1666]
In order to support the needs of the three-ways merging of JSON-Merger we need to implement a JSON-store.

Such store would need to store the last JSON version of a record as it came from a given source. E.g. one entry for the JSON from arXiv, one for the JSON from e.g. Elsevier. The stored JSON is the one right before it's being merged into the record.

Such store could be implemented as:

object_uuid, data, source, version/timestamp.

API could be:

``` python
def store_json(object_uuid, json_data, source):
    pass

def get_last_json(object_uuid, source):
    pass

def garbage_collect():
    remove any previous version of a given source
```

**Comment by kaplun** [comment]
@david-caro this is what we discussed today at the round-the-table.

**Comment by jacquerie** [comment]
This happened in https://github.com/inspirehep/inspire-next/pull/3005.
