### ISSUE TITLE
Authors submission form: when there, the literature tab is highlited and not authors

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-next#1692]

**Comment by jacquerie** [comment]
Looks like it is fixed now:

<img width="1276" alt="fix-issue-1692" src="https://cloud.githubusercontent.com/assets/381280/23838315/b8873e98-0794-11e7-91f1-c6545af1b6f0.png">

I don't know what fixed it ¯\\\_(ツ)_/¯

**Comment by jmartinm** [comment]
What fixed it might have been the moment we changed URL to /authors/new since the rule for the color involves checking the URL.
