### ISSUE TITLE
Bug in handling coordinates for Institutions

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1700]
See attached screenshot
![georgia](https://cloud.githubusercontent.com/assets/119349/19927806/adca5dfa-a0fb-11e6-807c-be90183e7adb.png)

Something wrong about what Georgia + Tibilisi means.

To be investigated if the coordinate are plain wrong Vs. they are ignored in the provided visualization

**Comment by kaplun** [comment]
cc: @jacquerie @jmartinm

**Comment by jacquerie** [comment]
Coordinates are in the wrong Georgia: http://inspire-nightly.cern.ch/api/institutions/1480957. Yet another reason why we should have used just the city, and not more complex untested logic, in https://github.com/inspirehep/inspire/pull/210.

**Comment by jacquerie** [comment]
Compare: https://inspirehep.net/record/edit/?ln=en#state=edit&recid=1480957&recrev=20160812222409, https://inspirehep.net/record/edit/?ln=en#state=edit&recid=1480957&recrev=20160829112050, and https://inspirehep.net/record/edit/?ln=en#state=edit&recid=1480957&recrev=20160908013316.

So this is not a bug in the application, this is wrong data in legacy.

**Comment by kaplun** [comment]
OK So we can simply drop the wrong coordinate and let our brand-new checker rule to add the correct ones.
