### ISSUE TITLE
Authorlist: cannot parse affiliations when empty lines

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspire-next#1702]
The new authorlist tool to convert lists of affiliations into MARC fails when empty lines are present.

Slightly changing the second example into
```
F. Lastname1, F.M. Otherlastname1,2

1 CERN
2 Otheraffiliation
```
gives the error message
```
Sorry! Seems there is a problem somewhere. Please see error message: ('Cannot parse affiliation ', u'')
```

**Comment by jacquerie** [comment]
@michamos, this is fixed on `master`, and will be fixed on QA the next time we deploy the code. How urgent is that?

**Comment by michamos** [comment]
Not urgent as far as I am concerned, just found this bug when playing with it a bit
