### ISSUE TITLE
Reference recognition improvements in Grobid

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1704]
As of today, latest Grobid codebase seems to have greatly improved WRT past test but can still improve on certain aspects:
* Seems not to recognize DOI in references (albeit it has the concept of DOI)
* Does not recognize arXiv in references
* Does not recognize report-numbers in references
* Does not recognize URLs in references

What it already does great:
* Does do recognize very well names and titles and publication notes

@michamos proposes to force-training Grobid by feeding it with automatically created PDF from our real BibTeX, using several BibTeX styles customized to output in the `.bbl` the actual tags that are required to produce the correct TEI, expected by Grobid.

For reference:
* Info on how to train Grobid: https://grobid.readthedocs.io/en/latest/Training-the-models-of-Grobid/
* Grobid TEI documentation: https://raw.githubusercontent.com/kermitt2/grobid/master/grobid-home/schemas/doc/Grobid_doc.html (ahem to be rendered as HTML)

* [ ] Have @michamos to have local running instance of Grobid
* [ ] BibTeX to TEI generator
* [ ] Training of Grobid
* [ ] Deployment of newly trained Grobid

**Comment by kaplun** [comment]
(Adding this in inspire-next because we don't have yet a neutral place for this type of projects).

**Comment by lfoppiano** [comment]
Hi @kaplun, I'm trying to answer your questions on [GROBID reference generation](https://github.com/kermitt2/grobid/issues/147). 

Could you provide an example for each cases you've described above? 

Thanks
Luca

**Comment by michamos** [comment]
Hi @lfoppiano, you could have a look at [arXiv:1503.07589](http://arxiv.org/pdf/1503.07589) which has a nice mix of unrecognized metadata. DOIs and arXiv numbers all over the place, and report numbers in `[25]`,`[27]`,`[29]`, and [arXiv:1611.09584](https://arxiv.org/pdf/1611.09584.pdf) which has arXiv numbers and a few URLs.

**Comment by StellaCh** [comment]
@michamos what's the update on this one?

**Comment by michamos** [comment]
after @iorala's training, reference extraction has progressed a lot. We should still deploy the new GROBID version and integrate it into Inspire, but that's a different story, so closing this issue.
