### ISSUE TITLE
Click on search results gives JSON view

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1711]
I assume after the introduction of https://github.com/inspirehep/inspire-next/commit/f6c29308cad90ac3c70cab52f0db7c466246fb06 this is happening.

When clicking on any search result, instead of the detailed view, the JSON view is being displayed.

**Comment by jacquerie** [comment]
Looks like a problem with your setup: http://inspire-nightly.cern.ch/literature/1405870 appears to work from here.

**Comment by jmartinm** [comment]
See https://github.com/inspirehep/inspire-next/pull/1713
