### ISSUE TITLE
Holding Crap

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1721]
The day that Labs becomes master for certain collections, we need to ensure that MARC fields that are not mapped via `dojson` are not discarded.

One idea that came out in the INSPIRE week is to have a `crap` field of the form:
```json
{
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "tag": {
                "type": "string"
            },
            "subfields": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "string"
                        },
                        "value": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}
```

Upon converting a record from MARCXML via dojson, all the fields and subfields not considered during the translation would be appended into such bag, so that catalogers could then access those when curating a record.

**Comment by jacquerie** [comment]
Err... ok, but:

1. This field is not for searching, and will NEVER be included in the mappings. If you need data from here, you have to convert it in a proper key
2. Remember that the structure of the records is part of the public API, so `crap` is not the best name... Maybe `scrap`?

**Comment by kaplun** [comment]
eheh, It's not for searching. actually we anyway need the concept of hidden fields (e.g. we could have an easy convention that all fields prefixed with an `_` are not exposed via API unless to authorized users, so this `crap` field could be one of those...) I also like `scrap` :+1:  The name I used is not important, but at least it's an easy to remember project, in this way.

**Comment by kaplun** [comment]
To discover what hasn't be consumed we could use the trick detailed here: http://stackoverflow.com/questions/10758095/python-dictionary-with-memory-of-keys-that-were-accessed

**Comment by StellaCh** [comment]
@jacquerie @michamos I close this but feel free to reopen it if needed
