### ISSUE TITLE
Rejected records

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1724]
When a literature record is rejected we need to store the minimal amount of metadata that allows it to be matched in the future (see other issues related to record matching) so that should an update come again the workflow can immediately decide whether to reject it.
* [ ] implement metadata stripper to just keep matching related information (i.e. publication information and title and say first author)
* [ ] implement collection for rejected record
* [ ] implement storing of rejected records
* [ ] implement matching step against rejected records and automatic rejection.
* [ ] in case of safe match, the new record would simply replace the matched one.

**Comment by kaplun** [comment]
@inspirehep/inspire-content are there situations when it is decided that a record should finally get into?

**Comment by kaplun** [comment]
We actually mused during the INSPIRE week that it would actually cool to preserve what we harvest and then being able to quickly restore it. So probably the easiest is to just store the whole record including PDF and then have a promoting action that would simply move the record into a public one and run all the usual reference extraction and guessing etc.

**Comment by StellaCh** [comment]
How is this handled currently @michamos ?

**Comment by michamos** [comment]
this is currently implemented it by matching against the holding pen. @ammirate to what extent is this implemented?

**Comment by ammirate** [comment]
This is implemented in the PR #2932 and should be ready to be put in place.

**Comment by StellaCh** [comment]
Thanks @ammirate . I assigned it to you for the time being, feel free to close it when the PR is merged
