### ISSUE TITLE
Collaboration guesser

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1725]
Given an incoming paper for which the authorlist is known we need an algorithm to guess the corresponding collaboration.

For this an easy technique could be to just index in ES for every collaboration and every year the list of surnames, initials of every incoming record.

When a record come it is searched for the correct collaboration, by simple `tf-idf` ranking. A threshold is needed to decide if the given collaboration does match.

The collaboration guessing step should then be added in the appropriate workflow.

**Comment by annetteholtkamp** [comment]
Do we really need a collaboration guesser? We already have an experiment guesser. A collaboration name we add only if it is explicitly mentioned on a paper, not by looking at the author list. If it's not included in the metadata we get I assume this is a job for Grobid to extract it from the pdf.

- Annette

On Nov 8, 2016, at 6:41 PM, Samuele Kaplun <notifications@github.com<mailto:notifications@github.com>> wrote:


Given an incoming paper for which the authorlist is known we need an algorithm to guess the corresponding collaboration.

For this an easy technique could be to just index in ES for every collaboration and every year the list of surnames, initials of every incoming record.

When a record come it is searched for the correct collaboration, by simple tf-idf ranking. A threshold is needed to decide if the given collaboration does match.

**Comment by kaplun** [comment]
Isn't it just reliable for when you have a record from arXiv? How do you know that this a record from CMS and ATLAS? It's quite easy to spot if we keep track of the authorlist of CMS and ATLAS.

**Comment by salmele** [comment]
How many of those papers/year are there and how difficult is instead for a human to eyeball them and say, yes, that's a given collaboration?

**Comment by kaplun** [comment]
Mmh, don't we want to automatize as much as possible the easy tasks anyway? This is something where the machine could very well be reliable (it's rare that 500 people works at the same time in 2 collaborations), so to me, even if it's easy for the cataloger, it's one less task to do that can be delegated to machines.

@annetteholtkamp the experiment guesser is a bit less reliable because is based on neural network over the title/abstract. Collaboration is very reliable because it's based on a large structured information.

Whether we should add the collaboration iff it appears in the paper, and about the difference between collaboration and experiment, these are indeed good questions, that we might pose to our community. I am not sure it is clear to our user about (the benefit of) this distinction.

**Comment by annetteholtkamp** [comment]
For papers of the whole collaboration we normally get this information already from arXiv, either from the arXiv metadata or from the author xml file. 
We often don’t get the collaboration name for conference papers (for the … collaboration) - which grobid should give us.
So I really don’t see the need to automatise this further.

- Annette

**Comment by StellaCh** [comment]
Closing this ticket since there're no pressing user requests for this feature but will make a note for it on future improvements
