### ISSUE TITLE
Authorizations 101

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1726]
We shall well define the types of authorization and roles that should be available in INSPIRE:

I would identify the following roles:
* *Admin*: i.e. those that should tune the overall service, that do typical operations such as deployment of updates, tuning of workflows etc.
* *Curator*: i.e. those that can edit the whole content of INSPIRE, accessing any workflow, editing any record, attaching any file
* *Project X curator*: i.e. those with a project-specific role, e.g. curators of only Institutions, or only Experiments, or only French records...
* *Authenticated user*: i.e. any casual user who is authenticated and for thus we can track their operations
* *Project X user*: i.e. any authenticated user that is authorized to a specific (hidden) collection, e.g. D0 notes.
* *Guest user*: i.e. any other user, who can typically access only public information

I would identify the following actions:
* *Administrating INSPIRE*: i.e. any fine tuning that the Invenio platform offers from the web interface
* *Accessing workflow Y*: i.e. being able to access halted workflows with tag Y and take decisions.
* *Record editor*: i.e. being able to edit any record
* *Record editor project X*: i.e. being able to edit record within the specific collection X
* *Bulk modification project X*: i.e. being able to bulk modify the specific collection X

**Comment by kaplun** [comment]
@jmartinm, @zzacharo WDYT? Can this model be taken into account while implementing authorizations?

**Comment by zzacharo** [comment]
@kaplun @jmartinm I don't know if we can customize the invenio-acoounts ActionRoles or ActionNeeds, probably we can do this.

**Comment by annetteholtkamp** [comment]
Where do bulk actions that can affect many records fit in? Like the current multiedit, or running bibcheck jobs. We should foresee a curator role for people who can access all collections but are not allowed to do bulk actions.

- Annette


On Nov 9, 2016, at 11:05 AM, Samuele Kaplun <notifications@github.com<mailto:notifications@github.com>> wrote:


We shall well define the types of authorization and roles that should be available in INSPIRE:

I would identify the following roles:

  *   Admin: i.e. those that should tune the overall service, that do typical operations such as deployment of updates, tuning of workflows etc.
  *   Curator: i.e. those that can edit the whole content of INSPIRE, accessing any workflow, editing any record, attaching any file
  *   Project X curator: i.e. those with a project-specific role, e.g. curators of only Institutions, or only Experiments, or only French records...
  *   Authenticated user: i.e. any casual user who is authenticated and for thus we can track their operations
  *   Project X user: i.e. any authenticated user that is authorized to a specific (hidden) collection, e.g. D0 notes.
  *   Guest user: i.e. any other user, who can typically access only public information

I would identify the following actions:

  *   Administrating INSPIRE: i.e. any fine tuning that the Invenio platform offers from the web interface
  *   Accessing workflow Y: i.e. being able to access halted workflows with tag Y and take decisions.
  *   Record editor: i.e. being able to edit any record
  *   Record editor project X: i.e. being able to edit record within the specific collection X

**Comment by StellaCh** [comment]
What's the current state @jmartinm ?

**Comment by jmartinm** [comment]
We have the permissions we need for editor, multieditor set up at the moment.

Currently there is a role cataloger that has assigned permissions to use the tools but, when needed, a new role can be created, like `cataloger-restricted` and not assign `multieditor` to it.
