### ISSUE TITLE
Login through ORCID redirects to /account/settings/linkedaccounts/

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1737]
At the moment on qa.inspirehep.net after logging in through ORCID, a redirect is done to /account/settings/linkedaccounts/ which gives a blank page.

**Comment by kaplun** [comment]
Ideally, where should it redirect to? The current page?

**Comment by jmartinm** [comment]
Yes, the current page would be best. Or the index page otherwise.

In many places in `invenio-oauthclient` it is hardcoded that the redirect is to the linked accounts page, for example, https://github.com/inveniosoftware/invenio-oauthclient/blob/master/invenio_oauthclient/contrib/orcid.py#L195.

To make sure we cover all cases might be best to add a handler for that page on our overlay that redirects to the front page (or reads the `referer` and redirects back to the original page, although I think the referer will be the login page so that's not what we want)
