### ISSUE TITLE
Local account login fails after account migration

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1755]
After migrating accounts on QA. Trying to login with an existing local account gives the following error (https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/614596/)

```python
flask_security/utils.py ? in verify_and_update_password
 
    verified, new_password = _pwd_context.verify_and_update(password, user.password)
passlib/context.py ? in verify_and_update
 
        record = self._get_or_identify_record(hash, scheme, category)
passlib/context.py ? in _get_or_identify_record
 
            return self._identify_record(hash, category)
passlib/context.py ? in identify_record
 
            raise ValueError("hash could not be identified")
```

**Comment by david-caro** [comment]
I was able to login with orcid, did not check the logs though.

--
David Caro <david.caro@cern.ch>

CERN - RCS-SIS
inSPIRE-HEP High Energy Physics information system
http://inspirehep.net

On Nov 17, 2016 14:25, Javier Martin Montull <notifications@github.com> wrote:

After migrating accounts on QA. Trying to login with an existing local account gives the following error (https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/614596/)

flask_security/utils.py ? in verify_and_update_password

    verified, new_password = _pwd_context.verify_and_update(password, user.password)
passlib/context.py ? in verify_and_update

        record = self._get_or_identify_record(hash, scheme, category)
passlib/context.py ? in _get_or_identify_record

            return self._identify_record(hash, category)
passlib/context.py ? in identify_record

            raise ValueError("hash could not be identified")

**Comment by jmartinm** [comment]
This error happened with `?local=1` using an existing cataloger account.

**Comment by kaplun** [comment]
Sounds like we are not correctly porting the right hash/salting method from legacy... Are there any toggles to play with?
