### ISSUE TITLE
workflows: ids of the new workflows start from 1

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-next#1782]
It might be that the migration of the old records did not work properly.

**Comment by kaplun** [comment]
http://stackoverflow.com/questions/787722/postgresql-autoincrement

**Comment by jmartinm** [comment]
And http://stackoverflow.com/a/244265/890185

**Comment by jmartinm** [comment]
I can confirm that running:

```
SELECT setval('workflows_object_id_seq', (SELECT MAX(id) FROM workflows_object));
```

fixes the problem, will add to the deployment instructions.
