### ISSUE TITLE
primarc support in search

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1791]
Upon searching, it should be possible to search for all the records that have a given arXiv category as first category.
(in SPIRES this was PRIMARC token).

**Comment by StellaCh** [comment]
Based on the usage stats (https://drive.google.com/file/d/0B8eFcMY6pLB1aF84OUE2UHBnSVU/view), this keyword is used in 0.07% of the cases, so I'm closing the issue for now and will reopen it depending on the strategy we decide to follow for the parser
