### ISSUE TITLE
OR query returns all results

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1792]
Doing the following query:

`control_number:1497201 OR control_number:1498589`

The query parser converts it to:

`Bool(should=[MultiMatch(fields=['control_number'], query=u'1497201'), MultiMatch(fields=['control_number'], query=u'1498589')])`

which in turn returns all results (23 in the demo site)

Expected
=======

It should only return the two records with those `control_number` values.

**Comment by jmartinm** [comment]
Actually the full query generated is:

```
{
    "query": {
        "bool": {
            "filter": [
                {
                    "match": {
                        "_collections": "literature"
                    }
                }
            ],
            "should": [
                {
                    "multi_match": {
                        "query": "1497201",
                        "fields": [
                            "control_number"
                        ]
                    }
                },
                {
                    "multi_match": {
                        "query": "1498589",
                        "fields": [
                            "control_number"
                        ]
                    }
                }
            ]
        }
    }
}
```

so the problem is that the filter makes all documents match. Removing the filter clause returns the expected 2 results.

**Comment by jmartinm** [comment]
Adding `"minimum_should_match" : 1` to the bool gives the correct result.

I wonder if that is what we want for all cases?

In which case [this line](https://github.com/inveniosoftware/invenio-search/blob/master/invenio_search/api.py#L79) needs to be modified from:

```
self.query = Bool(filter=default_filter)
```

to:

```
self.query = Bool(filter=default_filter, minimum_should_match=1)
```

**Comment by jacquerie** [comment]
Let's keep everything in one place. Continued in https://github.com/inspirehep/inspire-next/issues/2829.
