### ISSUE TITLE
generate_valid_keywords not being called

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1793]
The init code in `search` module (https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/search/ext.py):

```python
config.setdefault(
            'SEARCH_ALLOWED_KEYWORDS',
            LocalProxy(generate_valid_keywords)
        )
```

does not seem to be working and `generate_valid_keywords` is never called.

The place where it should be called is [here](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/search/parser.py#L267)

but even if I access the key right after the `setdefault`:

```python
config['SEARCH_ALLOWED_KEYWORDS']
```

the function is not called.

**Comment by StellaCh** [comment]
is this still relevant @jmartinm or can it be closed?

**Comment by jacquerie** [comment]
It refers to a parser architecture that is no longer there. Same goes for https://github.com/inspirehep/inspire-next/issues/1794.
