### ISSUE TITLE
generate_valid_keywords gathers too many keywords

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1794]
Even if https://github.com/inspirehep/inspire-next/issues/1793 was working, the current implementation of `generate_valid_keywords` gathers keywords from all registered schemas and mappings.

For example, these are our mappings:

```
['records-data', 'records-hep', 'records-experiments', 'records-journals', 'records-files-records-files-v1.0.0', 'records-authors', 'holdingpen-authors', 'records-jobs', 'records-institutions', 'records-conferences', 'holdingpen-hep']
```

Any module that registers via entry points an schema or mapping will make our allowed keywords change.

I am not sure what are the consequences of having too many keywords registered but this does not seem correct.

**Comment by jacquerie** [comment]
Do we need that magic, in fact? What about an explicit whitelist in our configuration?

**Comment by kaplun** [comment]
The ideal *ting* would to have one white list per document type. In other words t his could be done at initialization time of LiteratureRecord and co.

**Comment by jacquerie** [comment]
This refers to a parser architecture that is no longer there.
