### ISSUE TITLE
workflows: When an article is marked as 'already-ingested' there's nothing shown on the holdingpen ui

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-next#1799]
When an article submission is tagged as 'already-ingested' the workflow is created, and it shows on the holding pen, but it has no indication towards why it's not actually going on, it just shows as 'workflow completed' with no other info or actions available.

**Comment by david-caro** [comment]
For example when something was previously rejected.

**Comment by StellaCh** [comment]
@david-caro is this resolved in the new holding pen?

**Comment by david-caro** [comment]
Nop

**Comment by ammirate** [comment]
This is not going to happen anymore since the revisited logic in #2932 makes submissions always going through the workflow, never marking them as ``already-ingested``.
