### ISSUE TITLE
global: use a static code analysis tool

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-next#1834]
As discussed with @jmartinm, in order to have better reviews we need a better baseline for code quality (otherwise we waste lots of time commenting on obvious stuff like indentation, imports...).

The solution to this is a static code analysis tool. I like [prospector](https://github.com/landscapeio/prospector), which is a wrapper over several tools, except that critical PRs have been sitting unmerged for months (like https://github.com/landscapeio/prospector/pull/193).

Another one is [flake8](https://gitlab.com/pycqa/flake8), which wraps less tools but looks better maintained overall. It still catches lots of stuff:
```
% flake8 --count --ignore=E501

[...]

892
```

IMO we should implement `flake8` now and add later `pylint`, `pyroma`, `vulture`... (the rest of the stuff in `prospector`)

**Comment by jacquerie** [comment]
Some more options: https://github.com/mre/awesome-static-analysis#python

**Comment by kaplun** [comment]
@spirosdelviniotis, after you have finished with the merging PRs, this could be an interesting horizontal task. I.e. to go through all the warnings generated by flake8, and help improving the code base, thus making INSPIRE code base overall more robust.

Some gotchas are extremely easy, but some other are more interesting and allow to further improve Python skills.

**Comment by jacquerie** [comment]
I think we agreed to do this.
