### ISSUE TITLE
global: simplify years in licenses

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-next#1837]
As discussed with @jmartinm, in order to have better reviews we should avoid having to check licenses manually. One issue with them are the years, a requirement of the GPL( https://www.gnu.org/licenses/gpl-howto.en.html):

> The copyright notice should include the year in which you finished preparing the release (so if you finished it in 1998 but didn't post it until 1999, use 1998). You should add the proper year for each release; for example, “Copyright 1998, 1999 Terry Jones” if some versions were finished in 1998 and some were finished in 1999.

Since we (sadly) haven't released yet, I think that using only 2016 everywhere and updating to 2017 in bulk the next year is a perfectly acceptable interpretation of the above.

Related to #1836

**Comment by kaplun** [comment]
Doesn't make much sense for an ever modified online service which doesn't evolve in terms of releases... Mmh... Unless we also move the overlay to the versioning tool of @david-caro :)
