### ISSUE TITLE
author forms: move status key to top level when generating author document

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1862]
At the moment, author forms put the status key inside of `name`:

```
"name": {
"preferred_name": "Angela Wood",
"status": "retired",
"value": "Kay Mueller, Wynter Richard"
}
```

And the [authors schema](https://github.com/inspirehep/inspire-schemas/blob/master/inspire_schemas/records/authors.json#L265) has it on top level. Change should be made to align with schema.

**Comment by StellaCh** [comment]
is this fixed @jmartinm ?

**Comment by jmartinm** [comment]
Yes
