### ISSUE TITLE
Language field from form should be always 2 characters

### ISSUE THREAD

**Issue by rikirenz** [inspirehep/inspire-next#1915]
As you can see from the schema (https://github.com/inspirehep/inspire-schemas/blob/master/inspire_schemas/records/hep.json#L500), the language should be always of 2 characters. 
But now in `literature suggest` if we select:

- Language -> Other

- And we put a specific language that is not in the form list.

![screenshot from 2017-02-13 14-33-58](https://cloud.githubusercontent.com/assets/4679712/22885446/ce0636f8-f1f9-11e6-9889-198f33d969ec.png)

- Server side we are going to receive:

```
{
    language: 'oth',
    other_language 'japanese'
}
```

But we do not have a way to normalize the language in according to the standard ISO 639-1 (https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes). Actually we are doing some normalization for the fixed languages but not in a "good" way:

```
        languages = [('en', 'en'),
                     ('rus', 'ru'),
                     ('ger', 'de'),
                     ('fre', 'fr'),
                     ('ita', 'it'),
                     ('spa', 'es'),
                     ('chi', 'zh'),
                     ('por', 'pt'),
                     ('oth', 'ot')]

        if language == 'oth' and other_language:
            return other_language

        return unicode(dict(languages).get(language))

```

We can implement several solutions. I think it is necessary to discuss which is the best solution in according to:

- User Experience

- JSONSchema changes needed

**Comment by michamos** [comment]
> We can implement several solutions. I think it is necessary to discuss which is the best solution in according to:
> 
>     User Experience
> 
>     JSONSchema changes needed

`UI`-wise, the easiest for the user would probably be a single autocomplete for the language that in the end sends an `ISO 639-1` 2-letter code. This code is what the schema expects.
(cc @inspirehep/inspire-ux)

**Comment by jmartinm** [comment]
I will look into it and propose a solution with a single input.
