### ISSUE TITLE
Wrong earliest-date

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1916]
https://qa.inspirehep.net/literature/1400940 has an earliest date that has been set in 2030!

**Comment by jacquerie** [comment]
Ah, that's a funny one. This happens because the `preprint_date` is not a ISO-8601 date: `30-04-2015` instead of `2015-04-30`.

**Comment by kaplun** [comment]
Mmh, but still shouldn't it then use the `creation_date`? which is earlier?

**Comment by jacquerie** [comment]
I removed `creation_modification_date` from DoJSON because it's not in the schema: https://github.com/inspirehep/inspire-next/commit/c62a1d9d1108a94e9ade3d9887e3763efafb24ea.

**Comment by kaplun** [comment]
We really should find a way to treat meta-meta-data like these. But so we are currently ignoring legacy creation/modification dates...

**Comment by jacquerie** [comment]
IMO we shouldn't obsess over this distinction between data and metadata: a record in our system represents our knowledge about a certain piece of scientific content. Our knowledge includes stuff only we might care about (like how we got this record, or when we got it), but this does not warrant different treatment: it can just be part of the schema.

**Comment by kaplun** [comment]
Yes, as long as we ensure that the cataloger cannot touch this information, and it's rather set automatically (e.g. such as the modification date and the current `acquisition_source`.

**Comment by jacquerie** [comment]
> Mmh, but still shouldn't it then use the creation_date? which is earlier?

Now we have a rule to do that: https://github.com/inspirehep/inspire-next/blob/49a4197747193054894273b51732efd78dd4a25b/inspirehep/dojson/common/rules.py#L338-L349 (and this date is used in the `earliest_date` receiver), so this particular bug won't appear anymore.

The issue should still remain open, because we haven't fixed the missing ISO8601 normalization.

**Comment by StellaCh** [comment]
@jacquerie is the ISO8601 normalization fixed?

**Comment by jacquerie** [comment]
> @jacquerie is the ISO8601 normalization fixed?

Yes, thanks to several PRs by @michamos in `inspire-dojson`, `inspire-schemas`, and `inspire-utils`.
