### ISSUE TITLE
Propagate legacy_creation_date back into PostgreSQL

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1922]
https://github.com/inspirehep/inspire-schemas/pull/92 introduces a field to host the creation_date from legacy (which is exported in the XME format).

We could have a migration script that reads this field and correctly populate the corresponding database column.

**Comment by michamos** [comment]
Currently, this is put into the record JSON in `legacy_creation_date`, but the migrator should put this into the `created` field of the `InspireRecord` object instead. @iulianav : @jacquerie thinks this might be something for you.
