### ISSUE TITLE
author form/schema mismatch

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspire-next#1926]
These are the keys that are generated by the author form, and whether they match the schema:

* [x] `acquisition_source`
* [x] `acquisition_source->source`
* [x] `acquisition_source->email`
* [x] `acquisition_source->date`
* [x] `acquisition_source->method`
* [x] `acquisition_source->submission_number`

Also `acquisition_souce->orcid` and `acquisition_source->internal_uid` exist in the schema and should be populated by the form.

* [x] `advisors`
* [x] `advisors->name`
* [ ] `advisors->_degree_type`: does not exist any more, should be `advisors->degree_type`.

* [ ] `collections`
* [ ] `collections->primary`

We killed collections for authors.

* [x] `experiments`
* [x] `experiments->current`
* [x] `experiments->name`
* [x] `experiments->start_year`
* [x] `experiments->end_year`

* [x] `name`
* [x] `name->value`
* [ ] `name->status`: `status` exists but is top-level, not under `name`.

* [x] `name->preferred_name`
* [x] `native_name`

* [x] `urls`
* [x] `urls->value`
* [x] `urls->description`

* [x] `ids`
* [x] `ids->value`
* [x] `ids->type`

* [x] `positions`
* [x] `positions->emails`
* [x] `positions->old_emails`
* [x] `positions->institution->name`
* [x] `positions->current`
* [x] `positions->start_date`
* [x] `positions->end_date`
* [x] `positions->_rank`

* [ ] `public_email`: after discussion with @jmartinm, it seems not to be used any more.

* [x] `inspire_categories`
* [x] `inspire_categories->term`
* [x] `inspire_categories->source`

* [ ] `_private_note`: this is now a `_private_notes` sourced_value array.

**Comment by jmartinm** [comment]
What is the equivalent of `collections` so that `980` field will be correctly populated?

**Comment by michamos** [comment]
For authors, there are two collections on legacy: `hepnames` and `useful`. `hepnames` is implicit now (if using the author schema, then doJSON should write back `hepnames`, and 980:useful corresponds to `stub = false`. @jacquerie don't know if implemented yet.

**Comment by jacquerie** [comment]
> I don't know whether @jacquerie implemented this yet.

Yup, I did.

**Comment by jmartinm** [comment]
Done in https://github.com/inspirehep/inspire-next/pull/1918
