### ISSUE TITLE
literaturesuggest: separate import phase from manual filling

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1931]
At the moment the user can, for example, input a DOI and click **Import**. Then once the form is pre populated they can fill the arXiv ID but not click **Import** again. This is not very useful since the purpose of the first part is to import data so we would get an arXiv ID without arXiv categories, arXiv abstract and so on.

One option is to make the clear separation in the UI where you first import data and once it is imported, the import box disappears. Or after importing, the values in the import box get cleared to indicate that the box is just used for Import.

**Comment by StellaCh** [comment]
fixed
