### ISSUE TITLE
literaturesuggest: autocomplete institution risk of submitting form

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1932]
If when autocompleting an institution I press the right arrow so that the field gets autocompleted and then press Enter, the form gets submitted. That should not happen.

![autocomplete](https://cloud.githubusercontent.com/assets/580727/23308426/674e2fd2-faab-11e6-8072-51ac31fa1376.gif)

**Comment by StellaCh** [comment]
fixed
