### ISSUE TITLE
schema: HEP 210__a  title variations: RPP

### ISSUE THREAD

**Issue by annetteholtkamp** [inspirehep/inspire-next#1940]
The 210 field mostly contains synonyms, expansions of acronyms etc - which can probably be ignored in the future. But it also contains the acronym RPP which is used for the citesummary option to exclude the RPP. These records we need to tag somehow.

**Comment by kaplun** [comment]
Issue moved to [inspirehep/inspire-schemas #121](https://github.com/inspirehep/inspire-schemas/issues/121) via [**ZenHub**](https://www.zenhub.com/)
