### ISSUE TITLE
Automatically extract user inputted references to the record

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1942]
When a user copy/pastes references in the Literature Submission form, https://github.com/inspirehep/refextract should run on them and convert them into references in the JSON document.

* [ ] Integrate `refextract` into article workflow.
* [ ] Make sure data model supports fields for references
* [ ] Add integration tests where form has references and at the end of the workflow the appropriate MarcXML is created.

**Comment by jacquerie** [comment]
Done by @iulianav in https://github.com/inspirehep/inspire-next/pull/2854.
