### ISSUE TITLE
litterature submission: there's an author without name created when suggesting the record arXiv:1605.08535

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-next#1948]
It's shown in the record detail, after submitting it, might be an artifact of author extraction (in that case might be ok?)

**Comment by jmartinm** [comment]
I don't see any problem. Can you add screenshot?

**Comment by chris-asl** [comment]
I cannot replicate it also.  
Here's the submission popup:
  
![arxiv-imported](https://cloud.githubusercontent.com/assets/2846837/23716198/9d808fea-042f-11e7-80a1-fb78998a74b1.png)  

and [here (arXiv)](https://arxiv.org/abs/1605.08535) we see the same four authors.

**Comment by david-caro** [comment]
ht
![screenshot from 2017-03-09 13-23-44](https://cloud.githubusercontent.com/assets/587148/23750101/aeddf344-04cb-11e7-9c48-427caefdcf18.png)

**Comment by david-caro** [comment]
Sorry, I should have specified better."in the references section, there's an author without name..."

**Comment by jacquerie** [comment]
That reference in the paper itself is `[1] Lucene. https://lucene.apache.org/.`, so there's nothing better we can do there...
