### ISSUE TITLE
After accepting a record, you are still allowed to save, and that breaks the workflow

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-next#1952]
It breaks the workflow by keeping it on 'halted' state and not showing the action buttons anymore.

**Comment by rikirenz** [comment]
Some additional info:

- When we accept the record is still possible edit it. For instance we can add suggested keywords:
![screenshot from 2017-03-10 17-09-39](https://cloud.githubusercontent.com/assets/4679712/23803086/b2ec32da-05b5-11e7-8a31-1241158c4def.png)

- After, that a keyword is added, the `Save Changes` button appears. if we clicked the save button and we go back to the holdingpen list the record is still halted and the buttons are missing.

![screenshot from 2017-03-10 17-11-24](https://cloud.githubusercontent.com/assets/4679712/23803578/4951d42c-05b7-11e7-9818-38d773d8aad5.png)

@

**Comment by kaplun** [comment]
See #1953
