### ISSUE TITLE
holdingpen: you are allowed to change a record that's on the 'initial' state

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-next#1955]

**Comment by rikirenz** [comment]
This issue has been fixed (not in a classical way). For this reason I am going to close it  :clapper: .

**Comment by jacquerie** [comment]
> This issue has been fixed (not in a classical way).

Well, now I'm scared...

**Comment by david-caro** [comment]
not sure what he meant with that :), but this was fixed deploying the latest code, same as the editor (probably there was something wrong with the first deploy we did).

**Comment by rikirenz** [comment]
Sorry guys. I will be more precise next time.
