### ISSUE TITLE
author update: convert custom arxiv categories to schema enum ones

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1956]
HepNames contains categories for authors that resemble arXiv categories but they are not.

For example, there are values like ACC-PHYS <https://inspirehep.net/search?ln=en&cc=HepNames&p=65017%3AACC-PHYS&action_search=Search&sf=exactfirstauthor&so=a>
but we don't have those in the schema https://github.com/inspirehep/inspire-schemas/blob/master/inspire_schemas/records/elements/arxiv_categories.json so `dojson` filters them out and the update form is not correctly populated.

**Comment by jmartinm** [comment]
@jacquerie this can be 'fixed' at `dojson` level.

**Comment by rikirenz** [comment]
@jmartinm do you think we can close this issue?

**Comment by jacquerie** [comment]
No, this has still to be fixed at the DoJSON level. What I'm doing right now is too aggressive (https://github.com/inspirehep/inspire-next/blob/2784567a399948b3567d4298f841044be74ffbd5/inspirehep/dojson/hepnames/rules.py#L234-L240), discarding things that are not in the schema without attempting to convert them.

**Comment by jacquerie** [comment]
We're not going to need this, because curators are going to fix the bad data for us.
