### ISSUE TITLE
Links are not present in the Holdingpen

### ISSUE THREAD

**Issue by rikirenz** [inspirehep/inspire-next#1966]
Links are not visible in the `holdingpen`. 
If we insert in the `literaturesuggest` form a pdf link or a info link these are not shown in the holdinpen for that specific record.

**Insert Phase**
![links](https://cloud.githubusercontent.com/assets/4679712/23556204/1105b5f6-002c-11e7-809d-6b644e5dcf03.png)
**Halted Phase Record**
![links_holding_pen](https://cloud.githubusercontent.com/assets/4679712/23556207/12b42f2c-002c-11e7-9f45-6bd604a94064.png)

Note: If we try to get the record from the url: `https://qa.inspirehep.net/api/holdingpen/$record_id`
the urls are not present

**Comment by jmartinm** [comment]
I am confused... if that code is there might be for a reason? That was added precisely because we don't want arXiv urls to be added to the record, they get added automatically by the workflow when you use the import functionality
