### ISSUE TITLE
holdingpen ui: the 'can't save until state changes' button does not fit the container

### ISSUE THREAD

**Issue by rikirenz** [inspirehep/inspire-next#1967]
When we try to modify a record that is in the state `initial` a button with the label: `Can't save until state changes, try refreshing.` appears. The position of the button has to be adjust.

![button](https://cloud.githubusercontent.com/assets/4679712/23556470/0b306d5a-002d-11e7-913f-a4e557afe96a.png)

**Comment by rikirenz** [comment]
@jmartinm I do not think is a priority for this sprint. If yout hink is a priority plase add the `Invenio 3` milestone :)

**Comment by jmartinm** [comment]
Yeah, it does not seem very important :)
