### ISSUE TITLE
Not possible to add a Subject Areas for authors in the Holdingpen

### ISSUE THREAD

**Issue by rikirenz** [inspirehep/inspire-next#1968]
When we try to add a `Subject Areas` in a author record and we click on the `+ Add` button nothing happen.

![author](https://cloud.githubusercontent.com/assets/4679712/23557036/eb1fef8e-002e-11e7-8063-b3be9545312f.png)

**Comment by rikirenz** [comment]
@jmartinm What do you think about this issue?

**Comment by jmartinm** [comment]
The Add option is deleted in https://github.com/inspirehep/inspire-next/pull/1945.
