### ISSUE TITLE
Holding pen should show link to arXiv eprint

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspire-next#1972]
When submitting an arXiv paper, no arXiv url and pdf are added to the record.
However, the arXiv eprint number should be shown somewhere, and a link to the arXiv splash page/PDF.
This is what it looks like on the Inspire 2 holding pen:
![schermata del 2017-03-03 20-55-10](https://cloud.githubusercontent.com/assets/2895793/23566815/c81a2d04-0053-11e7-97c0-4a33816ceabc.png)

**Comment by kaplun** [comment]
@jmartinm can you take care of this?

**Comment by jmartinm** [comment]
Yep sure!
