### ISSUE TITLE
Add tests to formdata_to_model regarding citeable

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1980]
A quick fix was introduced in https://github.com/inspirehep/inspire-next/pull/1979 to adapt to latest `inspire-schemas`.

Proper tests need to be added to make sure that the form is adding the `citable` flag properly. Also the flag `refereed` needs to be checked.

**Comment by rikirenz** [comment]
**Citeable:**
If we submitted from literature suggest form an article we consider it `citeable` if it has all the following fields set properly:
- `year`
- `journal_title` 
- `journal_volume`

And at least one between:
- `page_start`
- `artid`

Here there is the code that is doing this consideration: https://github.com/inspirehep/inspire-schemas/blob/master/inspire_schemas/builders.py#L272&L300.

**Refereed:**
Now we do not populate the field refereed. Should be populated? if the answer is yes, let me know how we should populate that field.


@michamos let us know what we should do :speaking_head: with the `refereed` field

**Comment by jmartinm** [comment]
> Now we do not populate the field refereed. Should be populated? if the answer is yes, let me know how we should populate that field.

The equivalent before the big `inspire-schemas` merge was to add `collections:Published` (see https://github.com/inspirehep/inspire-next/commit/496506476a58c3daa5d1b0c6369fcaf5e9309115#diff-7855ab3082d8e025a3787d156d10988dL218). The equivalent now would be `refereed:True` @michamos can confirm.

> The tests should be easy but I think should be done in inspire_schema rather than in inspire_next
@jmartinm what do you think?

I personally liked the unit tests that were in `test_literaturesuggest_tasks.py` (like https://github.com/inspirehep/inspire-next/commit/496506476a58c3daa5d1b0c6369fcaf5e9309115#diff-7855ab3082d8e025a3787d156d10988dL197) and did not realise they got removed. You can discuss with @jacquerie

**Comment by jacquerie** [comment]
> I personally liked the unit tests that were in test_literaturesuggest_tasks.py (like 4965064#diff-7855ab3082d8e025a3787d156d10988dL197) and did not realise they got removed.

I took the decision to remove them in the interest of speed in #1918. That design was and still is better than the current one in `tests/integration/test_formdata_to_model.py`.

**Comment by rikirenz** [comment]
I will do it in the way that @jacquerie suggest that is the old one that we were using in the `test_literaturesuggest_tasks.py`. Anyway at that time we had logic inside the `formdata_to_model` that was supposed to be tested but now we have moved that logic in the builder. For this reason I think is not 100% useful write those tests for `formdata_to_model`. 

But please let me know why you ( @jmartinm @jacquerie ) like them or why you prefer those rather than the actual ones. Because probably you are right but I am not able to see your point.

**Comment by jacquerie** [comment]
> Anyway at that time we had logic inside the formdata_to_model that was supposed to be tested but now we have moved that logic in the builder.

That's the key part you are mistaken about: the builder is (almost) free of logic, and that logic is still in `formdata_to_model`. For example: https://github.com/inspirehep/inspire-next/blob/6aaa968061d351e856bbc25abd0a2c5f55c81ae4/inspirehep/modules/literaturesuggest/tasks.py#L204-L209 this is logic, and it can be unit tested.

**Comment by jmartinm** [comment]
Partially done in https://github.com/inspirehep/inspire-schemas/pull/118

What about `refereed`? Is formdata_to_model populating it? Does it need to?

**Comment by rikirenz** [comment]
@michamos told me that for know is not so easy fill that field. I do not know if @kaplun has a strategy to do it?

**Comment by kaplun** [comment]
Yeah that property really depends on the specific journal to which the record is associated, and even within a given journal it's not necessary all the volume/issues to be refereed (e.g. some journal publishes both conference proceedings and articles).
So we need a more deep discussion about this, but I believe that for the time being we can move on without this field being populated and then fill-it in asynchronously (e.g. in the workflow or with some deamon...)

**Comment by rikirenz** [comment]
Do you think we should open an issue for this?

_Now is better than never. Although never is often better than *right* now._

**Comment by jacquerie** [comment]
> What about refereed? Is formdata_to_model populating it?

No, so I think that this issue can be closed, since we already have one about implementing `refereed`: https://github.com/inspirehep/inspire-schemas/issues/117 (we don't even know the requirements yet).
