### ISSUE TITLE
Possible UI improvements on small screen resolutions

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-next#199]
* I'm currently testing INSPIRE on my Dell Inspiron 1010, which has a 1024x600 screen resolution. When I am on http://labs.inspirehep.net and I click on the "Send Feedback" link I get this:
![screenshot from 2015-02-05 10 00 45](https://cloud.githubusercontent.com/assets/381280/6057387/26637036-ad1e-11e4-9933-12d34aec622d.png)
and I can't dismiss the feedback window except by reloading the page. Several other resolutions suffer from similar problems: http://www.responsinator.com/?url=labs.inspirehep.net (sorry for all the ads).

* http://labs.inspirehep.net has a very tall header which stays fixed on scrolling, cluttering the view. A possible solution is to use [WickyNilliams/headroom.js](https://github.com/WickyNilliams/headroom.js) (demo [here](http://wicky.nillia.ms/headroom.js/)), which hides the header when scrolling.

(CC: @kaplun @jalavik)

**Comment by jalavik** [comment]
There is also the UI/UX question if we should have a sticky header at all. For example, when scrolling down search result, I am not sure if we should keep the header stickied.  @jmartinm

**Comment by jmartinm** [comment]
Thanks @jacquerie . The Send Feedback problem needs to be fixed indeed. I will create an issue.

And I take note of ``headroom.js``, it looks very nice. I personally like the sticky header but it might be good to experiment with reducing the size of it once you scroll down.

**Comment by jmartinm** [comment]
To be done:

- [ ] Fix Send Feedback modal to make it responsive so that it fits in all screens.

Feedback modal comes from https://github.com/inspirehep/feedback.js

**Comment by jmartinm** [comment]
And for future sticky header improvements, this is the task https://app.asana.com/0/8772567966361/26160507904709

**Comment by jacquerie** [comment]
I'm investigating three solutions for responsive modals:

* [jschr/bootstrap-modal](https://github.com/jschr/bootstrap-modal/): [demo](http://jschr.github.io/bootstrap-modal/)
* [VodkaBears/Remodal](https://github.com/VodkaBears/Remodal): [demo](http://vodkabears.github.io/remodal/)
* [drublic/css-modal](https://github.com/drublic/css-modal): [demo](http://drublic.github.io/css-modal/)

I'm leaning towards the last, which, since it's mostly CSS, should play nicer with the [current code](https://github.com/inspirehep/feedback.js/blob/master/examples/css/feedback.css#L51-85).

**Comment by jalavik** [comment]
@jacquerie Cool. Without looking deep into the examples one requirement would be that the styling should be kinda like how labs looks now with "custom bootstrap".

Another thing to consider is how modals will be presented in the rest of the site. At least for end-users, not necessarily admins, we would want the "same modals" being shown.

**Comment by jmartinm** [comment]
@jacquerie do you think we could adapt the feedback.js to use standard Bootstrap modal http://getbootstrap.com/javascript/#modals ?

As we already use Bootstrap in all pages, as @jalavik mentioned, would facilitate later on changing how our modals look like.

See for example https://labs.inspirehep.net/submit/literature/create for an example of the current use of modals.

**Comment by jacquerie** [comment]
Ok. Here's what the HTML generated from `feedback.js` looks like:

```html
<div class="feedback-glass" data-html2canvas-ignore="true" style="pointer-events: none;"></div>
<div class="feedback-modal" data-html2canvas-ignore="true">
  <div class="modal-header">
    <a class="feedback-close" href="#">x</a>
    <h3>Send Feedback</h3>
  </div>
  <div class="feedback-body">
    <div>
      <label>We welcome problem reports, feature ideas and general comments:</label><br>
      <textarea></textarea>
    </div>
  </div>
  <div class="modal-footer">
    <button class="btn btn-primary">Send</button>
  </div>
</div>
```

And here's instead the HTML generated by `bootstrap.js`:

```html
<div class="modal fade in" id="modalData" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false" style="display: block;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">The following fields were imported:</h4>
      </div>
      <div class="modal-body">
        [...]
      </div>
      <div class="modal-footer">
        <button type="button" id="rejectData" class="btn btn-danger" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancel</button>
        <button type="button" id="acceptData" class="btn btn-success" data-dismiss="modal"><span class="glyphicon glyphicon-ok"></span> Continue</button>
      </div>
    </div>
  </div>
</div>
```

Their structure is quite similar, but not exactly the same. That HTML is generated by `feedback.js` in a convoluted way here: https://github.com/inspirehep/feedback.js/blob/cc296527d4d1ba816c1f8ff04d31976f65e871b6/examples/js/feedback.js#L118-212, which, by the way, was already touched by @giokokos to add some (but not all) of the Bootstrap classes.

I can continue down this road, adding quite a lot of complexity to that already complex function, or I can attempt a rewrite partially inspired by [topless/bootstrap-feedback](https://github.com/topless/bootstrap-feedback) (which, unfortunately, uses CoffeScript).

Rewriting would probably take me the rest of the week, while I could quickly add complexity to that function incurring in some technical debt.

What do you think? (CC: @kaplun @jalavik @jmartinm)

**Comment by jalavik** [comment]
Hmm. I am thinking since we want to fix all the modals on the site and keep it bootstrap, that [bootstrap-modal](http://jschr.github.io/bootstrap-modal/) is the way to go?

**Comment by jmartinm** [comment]
> Hmm. I am thinking since we want to fix all the modals on the site and keep it bootstrap, that bootstrap-modal is the way to go?

There is the following note in the repo:

> Note: Since this plugin was created to solve a lot of the issues with BS2, it still uses the BS2 markup syntax. Currently I believe the default BS3 modal addresses some of the bigger issues and is not worth maintaining two versions of this plugin.

As we already use Bootstrap 3 probably not even worth relaying on another external library? A very simple JS plugin can be written that will create the feedback button in all pages and use the default Bootstrap modal for the user to input their feedback.

**Comment by jacquerie** [comment]
@jmartinm suggested a different approach: remove `feedback.js` and replace it with a smaller library within INSPIRE. I started working on this, and here's how I'm structuring this feature:

```bash
(inspire)~/.virtualenvs/inspire/src/inspire-next/inspire/base/static$ tree -I vendors
.
├── css
│   └──feedback
│       └── button.css
└── js
    ├── feedback
    │   ├── feedback.js
    │   └── templates
    │       ├── button.mustache
    │       └── modal.mustache
    ├── feedback_inspire.js (*)
    ├── inspire_base_init.js (*)
    └── settings.js (*)
```
(some output omitted) where a (*) denotes that I will modify that file. Of course, I will also modify the `bundles.py` in the parent folder.

`js/feedback/feedback.js` will export a constructor `Feedback` which will have an API similar to the current one. It will use the `js/feedback/templates/button.mustache` template to paint the button and it will style it with `css/feedback/button.css`. The modal will use the  `js/feedback/templates/modal.mustache` template and will fall back on the styles provided by Bootstrap; it could also use `css/feedback/modal.css` for overrides and future compatibility.

**Comment by jmartinm** [comment]
Thanks for the update @jacquerie 

The code should leave in ``inspire/base/static``, the ``vendors`` folder is reserved for 3rd party libraries that we install through ``$ bower install``

I am not sure we will need the css folder, if you use for the button a Bootstrap class like https://github.com/inspirehep/feedback.js/blob/master/examples/js/feedback.js#L158 then the global styling of INSPIRE is the one that dictates how those buttons would look like.

Such styles are applied, for example, here https://github.com/inspirehep/inspire-next/blob/master/inspire/base/static/less/base/variables.less

And to see how the styles on INSPIRE look like you can visit http://labs.inspirehep.net/style-guide

**Comment by jacquerie** [comment]
Whoops! It appears I didn't explain myself very well.

1. `tree -I vendors` excludes the `vendors` folder from `tree`'s output, so that it more or less looks like what I posted. In fact, the code resides in `inspire/base/static`.

2. `css/feedback/button.css` is used for styling the "Send Feedback" button, the one that stays fixed on the right while scrolling and activates the modal when pressed. In fact, it currently contains this portion of the old code: https://github.com/inspirehep/feedback.js/blob/master/examples/css/feedback.css#L108-L310. I will check Bootstrap to see if this code is redundant as well.

I will also check the style guide, since it's the first time I see that page...

**Comment by jmartinm** [comment]
Crystal clear now ;) thanks

**Comment by jacquerie** [comment]
Sorry for adding an empty ticket. I was checking which error is the current implementation printing when given an empty feedback form: the answer is none at all. I'm adding some validation for that, and this (configurable) message: `'Please don\'t leave an empty feedback.'`.

**Comment by jmartinm** [comment]
> Sorry for adding an empty ticket. I was checking which error is the current implementation printing when given an empty feedback form: the answer is none at all. I'm adding some validation for that, and this (configurable) message: Please don\'t leave an empty feedback..

Good catch. Once you have a final version you can put here a screenshot with the validation error and we can see what would be the most clear message.

At the moment it might look like it is possible to leave empty feedback with: `Please don't leave an empty feedback..` but we are just asking the user to please, don't do it ;)

**Comment by jacquerie** [comment]
This screenshot is both to confirm that the bug is gone with PR #207 and also to show the error message. I agree that it might be improved, and I'm open for suggestions.

![2015-02-12-132606_1024x600_scrot](https://cloud.githubusercontent.com/assets/381280/6167421/8f4088ee-b2bb-11e4-98aa-56fe1a91954e.png)

**Comment by jmartinm** [comment]
I would suggest using the [Bootstrap alert component](http://getbootstrap.com/components/#alerts)

```html
<div class="alert alert-danger" role="alert">
      <strong>Oh snap!</strong> Seems like you forgot to input your feedback?
</div>
```

**Comment by jacquerie** [comment]
Done, but not pushed: 
![2015-02-12-160519_1920x1200_scrot](https://cloud.githubusercontent.com/assets/381280/6169934/12c79e04-b2d1-11e4-8dd2-3f36b5e29585.png)

**Comment by jmartinm** [comment]
Fine with me.
