### ISSUE TITLE
Collapsing links when importing from arXiv

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1997]
When a user suggest some content from arXiv with the literature suggestion form, we really do not need the "Links" tab to be displayed because we already have a URL for the PDF (the arXiv one) and a URL for the abstract (the arXiv one).

So we could de-clutter the screen by collapsing that panel by default in case of import from arXiv.

**Comment by michamos** [comment]
how do you know that the user won't provide another link? it would be better if the boxes get displayed based on presence/absence of content, not some predetermined scenarios (that are not guaranteed to be respected).

**Comment by jmartinm** [comment]
This was already mostly done in the merged commit https://github.com/inspirehep/inspire-next/commit/4a689e44c2d32c3ec992686b8d5327ff73f8a477. It's just not deployed on QA.

As @michamos says, this is based on content, so if one uses only the arXiv import there will be no links and the panel will not be displayed.

Same for other panels like references or notes.

**Comment by kaplun** [comment]
@michamos I wasn't proposing to disable the panel (as I am understanding is implemented?) Just to collapse it. If it's on arXiv why bothering further the user?

**Comment by michamos** [comment]
oh, you mean the submission form. I thought you meant in the holding pen. Then it can be collapsed by default when it is an arXiv paper or also when a DOI is provided.

**Comment by jmartinm** [comment]
Ah yes, I also understood in the Holding Pen.

If it's about the form itself, once we have it up and running on Labs, and there is time, @StellaCh  could do a round of testing with some users to see if this one (or any other changes) are necessary.

**Comment by kaplun** [comment]
Yeah my idea was pre-usability: I was just thinking that we don't want to ask the user this information, since we have it already perfect from arXiv, because we risk that they will provide it to us in a way that just complicates (say link to the abstract but not the correct arXiv URL, or link to a PDF, but it's actually the tar.gz). It's just there asking them for information we don't want to have.
