### ISSUE TITLE
grunt: remove unused code

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-next#201]
@jalavik told me that this project no longer uses Grunt.js as a task manager. I might as well remove all traces of it: `Gruntfile.js`, `package.json`, and its documentation in `README.rst`.

(CC: @kaplun @jalavik @jmartinm)

**Comment by jmartinm** [comment]
The ``copy`` part can be removed. And all copy-related packages from ``package.json``.

On the other hand there are some helpers like ``jshint`` and ``jsbeautifier`` that can be useful so I guess we should keep them.

The README is also ok as it only refers to such helper functionalities.

**Comment by jacquerie** [comment]
Ok. One other thing: the `README` currently suggests to use `sudo` to install a package globally, which is widely considered a bad idea. May I add a solution like [this](https://jesse.sh/sudo-npm-install/#update-11-3-2014)?

**Comment by jmartinm** [comment]
> Ok. One other thing: the README currently suggests to use sudo to install a package globally, which is widely considered a bad idea. May I add a solution like this?

:+1:  sure, go ahead.

**Comment by jmartinm** [comment]
@jacquerie can you create a PR with proposed changes? Basically removing the ``copy`` tasks from Grunt and amending documentation.
