### ISSUE TITLE
literature suggestion: conference dropdown

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspire-next#2011]
When adding the conference information in the literature suggestion, the conference dropdown should be ordered by latest first (requested by Kirsten )
![conference](https://cloud.githubusercontent.com/assets/24955201/23796695/9490c2ec-059c-11e7-936b-a8c0057be1b9.png)

**Comment by jacquerie** [comment]
Just for curiosity, the order currently returned is not random as it seems: it's actually sorted by `control_number`. See:
* https://inspirehep.net/record/964142
* https://inspirehep.net/record/964905
* https://inspirehep.net/record/971586
* https://inspirehep.net/record/973634
* https://inspirehep.net/record/973997.
