### ISSUE TITLE
holding pen: ctrl-A

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspire-next#2012]
Is there a way to prevent CTRL-A from selecting all text in addition to all articles ? (request from Kirsten)

![screena](https://cloud.githubusercontent.com/assets/24955201/23797053/4cf3b712-059e-11e7-9ea7-8656ac516bac.PNG)

**Comment by jacquerie** [comment]
@ksachs, I can't reproduce this with Firefox@52.0 on MacOS. Mind sharing your version of Firefox/Ubuntu, so we can try to reproduce?

**Comment by jacquerie** [comment]
> I can't reproduce this with Firefox@52.0 on MacOS

...because, quite obviously, the shortcut on MacOS is Meta+A, not Ctrl+A.

**Comment by ksachs** [comment]
Ubuntu 14.04 LTS, Firefox 51.0.1

**Comment by chris-asl** [comment]
Can confirm too, Ubuntu 16.04 LTS, Firefox 52.0.
![holdingpen-ctrl-a](https://cloud.githubusercontent.com/assets/2846837/23849266/42fcd4ca-07db-11e7-9c2a-c2e91cf71768.png)
