### ISSUE TITLE
global: bump celery to version 4

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#2037]
As per the title.

http://docs.celeryproject.org/en/latest/faq.html#should-i-use-retry-or-acks-late
http://docs.celeryproject.org/en/latest/userguide/configuration.html?highlight=ack_late#task-reject-on-worker-lost

**Comment by lnielsen** [comment]
See https://github.com/inveniosoftware/flask-celeryext/issues/22 ;-)

**Comment by david-caro** [comment]
@kaplun if you are not working on this, can you move it to ready

**Comment by jacquerie** [comment]
This is done in https://github.com/inspirehep/inspire-next/pull/2138, which wasn't merged as we ignore the impact it would have on the production system.

**Comment by StellaCh** [comment]
Then, is it ok to close this @jacquerie ?

**Comment by jacquerie** [comment]
No, we still want to do this!
