### ISSUE TITLE
doJSON: export accelerator in 119__b for experiments

### ISSUE THREAD

**Issue by annetteholtkamp** [inspirehep/inspire-next#2038]
A new subfield b in 119 has been defined for the accelerator. This has to be exported into the field "accelerator" of the experiment schema.

**Comment by jacquerie** [comment]
Blocked by https://github.com/inspirehep/inspire-schemas/pull/136.

**Comment by jacquerie** [comment]
This issue was moved to inspirehep/inspire-dojson#12
