### ISSUE TITLE
Investigate/fix the experiment prediction for articles in holding pen

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-next#2054]
For now it's desactivated because the mapping is not prepared for it. But we should fix it

**Comment by jacquerie** [comment]
For this milestone it's enough to comment it out, as it happened already in #2065, because we don't even show this information anywhere. But of course, this should eventually be fixed.

**Comment by david-caro** [comment]
This is already fixed right?

**Comment by jacquerie** [comment]
Investigate, yes, fix is #2145, which I couldn't apply on `master`!

**Comment by david-caro** [comment]
ok, I'm on it 👍

**Comment by annetteholtkamp** [comment]
When will the predicted experiment be visible in the HP?

- Annette

On May 17, 2017, at 6:12 PM, Jacopo Notarstefano <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #2054<https://github.com/inspirehep/inspire-next/issues/2054> via #2342<https://github.com/inspirehep/inspire-next/pull/2342>.
