### ISSUE TITLE
After accepting a submission, the reason is wrong

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspire-next#2057]
It shows a show reason button:
![core_with_reason](https://cloud.githubusercontent.com/assets/2895793/24056831/778d0aee-0b45-11e7-83ca-1784c1e74854.png)

with the reject reason (which I hope is not sent out):
![core_reason_for_sejection](https://cloud.githubusercontent.com/assets/2895793/24056830/7628a0dc-0b45-11e7-9e22-7f88ffb6fa50.png)

**Comment by kaplun** [comment]
:scream:

**Comment by jmartinm** [comment]
It's just a bug in the display that displays the default reason. In reality the record is accepted just fine and no reason is sent.

Will be fixed on Monday.
