### ISSUE TITLE
editor: support dates

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-next#2086]
The editor shows an error message instead of showing the date itself:

![screenshot from 2017-03-21 20-19-34](https://cloud.githubusercontent.com/assets/587148/24166525/d3e28158-0e73-11e7-9f92-e7bb2872cd08.png)

**Comment by jmartinm** [comment]
Moved to https://github.com/inveniosoftware-contrib/ng2-json-editor/issues/224
