### ISSUE TITLE
editor: any drop-down or '+' button do not work on firefox

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-next#2087]
see the screenshot, the symbol for the dropdown is there, and I can edit the content, but clicking there does not show anything. Happens with all the right-side drop-downs (or whatrever they are called).

![screenshot from 2017-03-21 20-25-29](https://cloud.githubusercontent.com/assets/587148/24166718/8a896b92-0e74-11e7-8f01-8caf1ff2e8cf.png)

**Comment by david-caro** [comment]
Happens the same with any other drop-down, right or left, and the '+' buttons... I can't add new authors or anything.

**Comment by jmartinm** [comment]
Moved to https://github.com/inveniosoftware-contrib/ng2-json-editor/issues/225
