### ISSUE TITLE
editor: you can set wrong 'inspire role' on firefox

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-next#2088]
When entering the author info, if you put something not valid in the 'inspire role' field, it will allow you to save it and put there an empty value:

![screenshot from 2017-03-21 20-28-58](https://cloud.githubusercontent.com/assets/587148/24166869/0b443b40-0e75-11e7-9428-13d33fd84644.png)
![screenshot from 2017-03-21 20-28-34](https://cloud.githubusercontent.com/assets/587148/24166870/0cea6d3e-0e75-11e7-84cd-106e3747ebe3.png)

**Comment by jmartinm** [comment]
Moved to
