### ISSUE TITLE
author submission: you can enter invalid date ranges

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-next#2092]
For example when entering the experiment history:

![screenshot from 2017-03-21 21-22-22](https://cloud.githubusercontent.com/assets/587148/24169020/9362e858-0e7c-11e7-8db2-52b2a41f13f8.png)

**Comment by jacquerie** [comment]
This kind of constraint will probably require the custom validators of @zzacharo to be implemented.

**Comment by zzacharo** [comment]
It can be done quite easily I think. Or we can just force it through UI even. The date fields are being edited by editor?

**Comment by jmartinm** [comment]
What are the requirements here?

Invalid dates are:

* Start later than end date.

* Any date in the future?

* Dates before what year?

Once those requirements are clear I can create an issue on the forms to avoid it for users and also in the record-editor for @zzacharo's custom validators.
