### ISSUE TITLE
editor: when entering links, it shows duplicated link icon if it has 'https?//'

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-next#2093]
![screenshot from 2017-03-21 21-24-43](https://cloud.githubusercontent.com/assets/587148/24169122/e40ec22c-0e7c-11e7-957c-8ca46e547ca5.png)

**Comment by michamos** [comment]
the same small box also appears in the menu on the left.

**Comment by harunurhan** [comment]
small-box comes from another thing, maybe a global css for inspire-next, @jmartinm  might know

**Comment by jmartinm** [comment]
> small-box comes from another thing, maybe a global css for inspire-next, @jmartinm might know

Yes, there is a global css rule that for external links shows the external link icon. We need to find a clean solution to leave that on the site but don't do it inside of the editor. (probably by amending our global css rule)

**Comment by jmartinm** [comment]
This was already fixed in https://github.com/inspirehep/inspire-next/pull/2198
