### ISSUE TITLE
editor: when entering author subject areas, you can create duplicates

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-next#2094]
And those duplicates are then saved into the record:

![screenshot from 2017-03-21 21-29-40](https://cloud.githubusercontent.com/assets/587148/24169320/83760b22-0e7d-11e7-97a4-b7c5ddbe2d66.png)
![screenshot from 2017-03-21 21-29-26](https://cloud.githubusercontent.com/assets/587148/24169323/8511ce26-0e7d-11e7-9d25-9a79713feeb5.png)

**Comment by jmartinm** [comment]
Moved to https://github.com/inspirehep/record-editor/issues/122
