### ISSUE TITLE
holdingpen hep details: can't add any subject areas if there aren't any to harvested paper

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-next#2095]
There's no boxes to add any new subject areas.

![screenshot from 2017-03-21 21-52-00](https://cloud.githubusercontent.com/assets/587148/24170272/b225f09c-0e80-11e7-9495-b2f1c482ef19.png)

**Comment by michamos** [comment]
What should happen is this: 
- the arXiv paper has arXiv categories,
- these get automatically converted to the corresponding inspire categories,
-  the curator can override this automatic conversion (adding/removing inspire categories).

**Comment by michamos** [comment]
Almost sounds like a bdd-style test for @rikirenz 😀

**Comment by jmartinm** [comment]
In this case - example https://github.com/inspirehep/inspire-next/issues/2095 the first problem is that the record does not have `inspire_categories` so the arxiv categories did not get translated and added to the record. If that were the case the `Add` would be shown (CC @david-caro)

@michamos I am not sure if there will be the case where there are no `inspire_categories` and we want to add some, but can add the feature of adding for all non-author workflows.

**Comment by michamos** [comment]
Not sure I understand. arXiv harvests never have inspire categories when they come in. They always have arXiv categories, that should be mapped automatically to the corresponding inspire ones.

**Comment by michamos** [comment]
I don't know. For submissions, at some stage the translation arXiv->inspire categories happens: https://labs.inspirehep.net/holdingpen/601056. The same should be done for arXiv harvests.

**Comment by jmartinm** [comment]
> I don't know. For submissions, at some stage the translation arXiv->inspire categories happens: https://labs.inspirehep.net/holdingpen/601056. The same should be done for arXiv harvests.

In the case of the submissions this happens on the form. When you import from arXiv, the [following mapping](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/config.py#L1583) is checked in JavaScript and the dropdown with INSPIRE categories gets preselected for the user.

We can add a new task to the [article](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/workflows/workflows/article.py#L175) workflow to make sure the arxiv categories always get added as inspire_categories. (see https://github.com/inspirehep/inspire-next/issues/2106)

**Comment by rikirenz** [comment]
I have double checked this issue and it is solved. If you have questions or problem please let me know :champagne:
