### ISSUE TITLE
holdingpen: hide workflow actions buttons

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-next#2100]
currently restarting or resuming a workflow does not work, better hide the buttons to avoid errors.

**Comment by jmartinm** [comment]
Isn't there a connected issue where you were fixing the Restart?

**Comment by david-caro** [comment]
Yep, but it's not merged yet, this is an easy workaround in case that the other does not suffice. In the end, we should be able to restart the workflow from scratch, but that needs more investigating.

So I guess that action path is:
* Short term, merge #2111 or implement this
* Medium term, implement restart from the beginning (not just the current step)
* Long term, implement restarting from any point

I think that #2111 is better than just hiding the buttons, so we should decide, @kaplun @jacquerie wdyt?

**Comment by jacquerie** [comment]
I agree with your decision: merging #2111 was better than just hiding the buttons (this issue).
