### ISSUE TITLE
mobile version of website shows collections in hamburger menu

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspire-next#2101]
![hamburger_collections](https://cloud.githubusercontent.com/assets/2895793/24188848/2f16a620-0ee3-11e7-97c2-445b751a3280.png)

**Comment by jacquerie** [comment]
This might be causing the GoogleBot to discover our search pages and start breaking havoc on our unfinished search engine: https://sentry.cern.ch/inspire-sentry/inspire-labs/group/820421/.

**Comment by kaplun** [comment]
OT: which makes me remember we should add robots.txt on Labs to forbid everything for the time being.

**Comment by jmartinm** [comment]
@Glignos in the mobile version, the same check as it happens [here](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/theme/templates/inspirehep_theme/header.html#L205) should be done. So nothing should be shown if `config['INSPIRE_FULL_THEME'] = False`
