### ISSUE TITLE
workflows: 'en' language should generally not be written in the record

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspire-next#2103]
Currently, on the submission form, `en` is the default language, so
```json
"languages": ["en"]
```
gets written in the record. We don't want this, as the overwhelming majority of records are in English.
Instead, at some point in the submission/workflow, the following should happen:
if there is no `title_translations` or `languages` contains only `en`, remove languages.

**Comment by rikirenz** [comment]
IMHO we should do this in the submission phase and fix also this issue: #2000
