### ISSUE TITLE
holdingpen: deleting records from the list view redirects to unfiltered view

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspire-next#2108]
When in a filtered list view in the holdingpen, deleting several records (by checking the checkboxes and clicking on the delete button that appears) redirects to the full unfiltered list. Instead, it should preserve the active filters.

**Comment by jmartinm** [comment]
Changing https://github.com/inspirehep/inspirehep-search-js/blob/master/src/inspirehep-holdingpen-js/holdingpen/holdingpen.directives.js#L76 to 

```javascript
window.location.reload();
```

should be enough
