### ISSUE TITLE
holdingpen: sorting by core-guessing relevance is missing

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#2113]
@ksachs reports that it is no longer possible to sort by core guessing.

@ksachs can you detail, the exact specs of the sorting algorithm you were mentioning me?

**Comment by ksachs** [comment]
best records first, i.e.
CORE: descending (the larger the better)
NON-CORE: descending (the larger the better)
Reject: ascending (the smaller the better)
