### ISSUE TITLE
holdingpen: missing automatic-reject path

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#2115]
@ksachs reports:
> if there is no filtered core-keyword and the guesser-suggestion is reject, the record was rejected automatically.

**Comment by jmartinm** [comment]
Just to be clear, this means that records should be rejected automatically when no filtered core-keyword and the guesser-suggestion is rejected.

**Comment by kaplun** [comment]
I think so.

**Comment by kaplun** [comment]
@ksachs, please confirm.

**Comment by ksachs** [comment]
yes.
We might have to confirm that the keyword extraction works as expected.
But you can already turn the filter on

**Comment by kaplun** [comment]
But if keywords are not extracted properly, don't we risk to reject genuine records?

**Comment by ksachs** [comment]
we were loosing genuine records on previous labs due to unkown reasons. We will re-process via DESY channel anyhow. With all the garbage in the HP is not usable. -> reject noise NOW!

**Comment by kaplun** [comment]
@ksachs bugs are fixed ASAP (even during the night) so give us the necessary time.
Anyway, my concern is simply: once we solve the fact that we are harvesting unnecessary sets in #2114, we risk to have false-negative if we auto-reject. The algorithm has changed (hopefully improved, but you never know...)

**Comment by ksachs** [comment]
sorry 'NOW' was misleading.
I mean 'without unnecessary discussion'. Take all the time you need.
