### ISSUE TITLE
Update invenio-record-editor theme to be consistent with record-editor template

### ISSUE THREAD

**Issue by zzacharo** [inspirehep/inspire-next#2126]
Update javascript handler here https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/theme/templates/inspirehep_theme/invenio_record_editor/index.html#L49 because record-editor html has changed. Same here https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/theme/templates/inspirehep_theme/invenio_record_editor/index.html#L52 .

**Comment by StellaCh** [comment]
@zzacharo is this resolved?

**Comment by zzacharo** [comment]
@StellaCh yes you can close it. I think this is even outdated.
