### ISSUE TITLE
dojson: obsolete Orcid's

### ISSUE THREAD

**Issue by annetteholtkamp** [inspirehep/inspire-next#2129]
In rare cases an author may have 2 Orcid's. Although we'll try to get these cases solved on the Orccid side we should be prepared to deal with them. Currently they are put into 035__z. In the new schema Orcid's should be unique. A second Orcid should be automatically hidden.

**Comment by jacquerie** [comment]
Two interesting cases: https://inspirehep.net/record/1518989/export/xme and https://inspirehep.net/record/1005548/export/xme (both orderings appear in the data)

**Comment by jacquerie** [comment]
Another interesting case: https://inspirehep.net/record/1357501/export/xme (they also appear in the same field).

**Comment by jacquerie** [comment]
This issue was moved to inspirehep/inspire-dojson#11
