### ISSUE TITLE
literature submission: can't submit in case of double identical URL

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#2154]
The schema rightly forbids duplicate content. Currently there are a bunch of forms that failed to be submitted because the user has entered duplicate content (in particular duplicate URL).
https://sentry.cern.ch/inspire-sentry/inspire-labs/group/821007/

We shall either have a normalization step in the form builder (and record builder) that automatically strips away the duplicate fields.

**Comment by kaplun** [comment]
Should this be fixed at the record-builder level?

**Comment by michamos** [comment]
should be fixed by implementing #2066
