### ISSUE TITLE
literature submission: thesis date includes time / phd lower case

### ISSUE THREAD

**Issue by annetteholtkamp** [inspirehep/inspire-next#2161]
When a submitter inserts a complete date year/month/day a time gets added:
Thesis: phd UC, Santa Barbara (2016-09-01T00:00:00) 

And the degree appears in lower case: phd

**Comment by jmartinm** [comment]
Thanks. Yes, these are known issues that @Glignos is taking care of.

**Comment by jacquerie** [comment]
Done in https://github.com/inspirehep/inspire-schemas/pull/138, but this is annoyingly blocked by #2134 (to get the new builder we have to bump the schema to the latest version).

**Comment by jacquerie** [comment]
We actually realized that in order to fix the second issue we need to fix DoJSON: `phd` is what is written in the schema, but we want to produce back `PhD` in MARCXML.

**Comment by Glignos** [comment]
@jacquerie The correct capitalization should happen also when the key is retrieved from the schema.

**Comment by jacquerie** [comment]
This should be fixed. @annetteholtkamp, can you confirm?

**Comment by michamos** [comment]
The PhD capitalization is fixed, not the timestamp one https://inspirehep.net/record/edit/?ln=en#state=edit&recid=1598894&recrev=20170511113857

**Comment by jacquerie** [comment]
Whoops, right, because inspirehep/inspire-schemas#138 in the end landed in schema>31. We could backport it to `31.2.0` to close this quicker...

**Comment by jacquerie** [comment]
We now have a schema that contains the changes in https://github.com/inspirehep/inspire-schemas/pull/124, so this should be fixed after a deploy.

**Comment by jmartinm** [comment]
Fixed and deployed
