### ISSUE TITLE
literature submission: wrong doc type conference paper

### ISSUE THREAD

**Issue by annetteholtkamp** [inspirehep/inspire-next#2176]
Conference papers appear with 980 "conference paper", not ConferencePaper

**Comment by jmartinm** [comment]
@rikirenz can you have a look and fix this? Problem might be in `formdata_to_model` or in the dojson conversion.

**Comment by jacquerie** [comment]
Problem is in DoJSON: https://github.com/inspirehep/inspire-next/blob/0dd585ef207128a75b8a35a1eda68b05b8d23bbd/inspirehep/dojson/hep/rules/bd9xx.py#L172-L176

**Comment by jacquerie** [comment]
I'm going to steal this from @rikirenz because it's a quick fix for me.
