### ISSUE TITLE
arXiv harvest: which categories in holdingpen?

### ISSUE THREAD

**Issue by ksachs** [inspirehep/inspire-next#2187]
I finally discovered that ES can be forced to do an exact search using quotes.
I don't know if this is a metadata, search or harvesting problem.
Just to let you know ...

"nucl-*" gives reasonable results
https://labs.inspirehep.net/holdingpen/list/?page=1&size=10&q=metadata.arxiv_eprints.categories:%22nucl-*%22&status=HALTED

"math-ph*" even displays categories
https://labs.inspirehep.net/holdingpen/list/?page=1&size=10&q=metadata.arxiv_eprints.categories:%22math-ph*%22&source=hepcrawl&status=HALTED

"astro-ph*" is essentially empty
https://labs.inspirehep.net/holdingpen/list/?page=1&size=10&q=metadata.arxiv_eprints.categories:%22astro-ph*%22 

"physics*" is totally empty
https://labs.inspirehep.net/holdingpen/list/?page=1&size=10&q=metadata.arxiv_eprints.categories:%22physics*%22

**Comment by jacquerie** [comment]
I would lean towards "weird search behavior", because this subquery of `physics*` returns some results: https://labs.inspirehep.net/holdingpen/list/?page=1&size=10&q=metadata.arxiv_eprints.categories:%22physics.ins-det%22

**Comment by StellaCh** [comment]
We added the facet filtering for arxiv categories, so I'm closing the ticket, but feel free to reopen it if  it's not yet resolved.
