### ISSUE TITLE
Images not loading in help pages

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#2201]
In the Labs Help pages, the images are not loading:

https://labs.inspirehep.net/help/knowledge-base/article-and-conference-paper-suggestion/

https://labs.inspirehep.net/help/knowledge-base/thesis-suggestion/

**Comment by kaplun** [comment]
This issue is due to the /img/ that existed on the old LB.

**Comment by kaplun** [comment]
Fixed
