### ISSUE TITLE
workflows: rewrite arxiv_author_list task

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-next#2203]
`arxiv_author_list` is currently using an XML stylesheet to convert arXiv's XML to MARCXML, and then using DoJSON to convert this MARCXML to our current JSON data model: https://github.com/inspirehep/inspire-next/blob/22adbbb604cb17ae14a53dc198a1ec43d20e86dd/inspirehep/modules/workflows/tasks/arxiv.py#L179-L227

This is quite silly and convoluted, so we should rewrite it to convert directly from arXiv's XML to our JSON data model.

Note that fixing this will also fix https://github.com/inspirehep/inspire-next/issues/2195.

**Comment by Glignos** [comment]
So the solution I figured so far is,check first line of the file if (%auto-ignore) then remove it,then create a dict according to our schema and populate manually its fields in accordance with the fields that exist in the xml file. @jacquerie can you confirm that this is a good solution?

**Comment by jacquerie** [comment]
> then create a dict according to our schema and populate manually its fields in accordance with the fields that exist in the xml file

Can you expand on this? In a way, this is the core of this issue...

**Comment by jacquerie** [comment]
Truth to be told, because (for example) of the DESY spider, MARCXML is probably going to stay with us for a while (if not forever), so this silly implementation can stay...
