### ISSUE TITLE
populate correct metadata when merging records

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspire-next#2220]
When merging record A into record B, the `deleted` and `deleted_records` fields should be populated accordingly:
- write `deleted: true` into record A,
- write the link to record A in `deleted_records` in record B.

This is currently not implemented in [InspireRecord](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/records/api.py#L47).

**Comment by StellaCh** [comment]
@ammirate is this taken into consideration? If so, feel free to close the ticket

**Comment by ammirate** [comment]
Yes, this is done in #2904.
