### ISSUE TITLE
tests: investigate flakiness of test_submit_author

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-next#2222]
For example: https://travis-ci.org/inspirehep/inspire-next/jobs/221069173

**Comment by jacquerie** [comment]
@rikirenz I remember that we discussed this, but I don't remember what you told me about it... mind writing it down here?

**Comment by rikirenz** [comment]
I do not remember about this. I am going to investigate. it should be easy.

**Comment by jacquerie** [comment]
Not a `Type: Bug`, as this is not affecting users, just developers.

**Comment by kaplun** [comment]
Is it just a speed issue? I.e. we are too quick in loading the page and the record is not yet there in the right state?

**Comment by rikirenz** [comment]
Usually is always a time/speed issue with selenium: https://sqa.stackexchange.com/questions/14241/how-to-avoid-flakey-e2e-selenium-tests?answertab=votes#tab-top
 
From the moment that we are going to migrate all the tests in BDD. I do not think it makes a lot of sense try to figure out why that specific test is flakey. But if you think is important I will investigate.

**Comment by jacquerie** [comment]
Should have been fixed by #2502.
