### ISSUE TITLE
wrong files get attached to holding pen records

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspire-next#2238]
https://labs.inspirehep.net/holdingpen/619315 has an attached PDF, which is the PDF from a different record, namely https://labs.inspirehep.net/holdingpen/619303. Looks like the problem is on our side, as the submitters are different, and there is no PDF in the `formdata`.

**Comment by jacquerie** [comment]
That's interesting. I actually see different PDFs in the two records. I definitely remember seeing two equal PDFs on your screen, so what's going on? Maybe wrong caching from the Angular application?

**Comment by michamos** [comment]
Maybe it was fixed by @annetteholtkamp ?

**Comment by jmartinm** [comment]
Just managed to reproduce this locally. Will dig deeper to see what is the cause.

**Comment by jmartinm** [comment]
Problem seems to be in the workflows Python code btw, in the [submit view](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/literaturesuggest/views.py#L84) every time we create the Workflow object, it is reusing the previous extra_data. To reproduce:

```python
In [1]: from invenio_db import db

In [2]: from invenio_workflows import workflow_object_class

In [3]: workflow_object = workflow_object_class.create(
   ...:         data={},
   ...:         id_user=1,
   ...:         data_type="hep"
   ...:     )

In [4]: workflow_object.extra_data['foo'] = 'bar'

In [5]: workflow_object.save()
--------------------------------------------------------------------------------
DEBUG in api [/Users/jmartinm/.virtualenvs/inspirehep/src/invenio-workflows/invenio_workflows/api.py:133]:
Saved object: 3 at []
--------------------------------------------------------------------------------

In [6]: db.session.commit()

In [7]: workflow_object
Out[7]: <WorkflowObject(id = 3, id_workflow = None, status = ObjectStatus.INITIAL, id_parent = None, created = 2017-05-01 15:06:50.728624, )

In [9]: workflow_object.extra_data
Out[9]: {u'foo': u'bar'}

In [10]: workflow_object = workflow_object_class.create(
    ...:         data={},
    ...:         id_user=1,
    ...:         data_type="hep"
    ...:     )

In [11]: workflow_object.extra_data
Out[11]: {'foo': 'bar'}
```

**Comment by jmartinm** [comment]
Fixed in https://github.com/inveniosoftware-contrib/invenio-workflows/pull/40
