### ISSUE TITLE
removing URL from holding pen in editor also removes attached PDF

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspire-next#2240]
Holding pen records initially have a URL if they also have a PDF attached. When removing `urls` from the record editor, the attached PDF disappears too. This is not only a cosmetic problem: because there is no "attach PDF" checkbox any more, the PDF does not get sent to legacy.

@jacquerie mentions that this is due to a wrong test in https://github.com/inspirehep/inspire-next/blob/5c8b7d6687c1e8a4dcf801e23446cd27658d3ac7/inspirehep/modules/workflows/static/js/inspire_workflows_ui/templates/details_links.html.

**Comment by jmartinm** [comment]
Fixed in https://github.com/inveniosoftware-contrib/invenio-workflows/pull/40
