### ISSUE TITLE
demosite: use only one suite of demo records

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-next#2254]
Related to #1843: with one application fixture we only need one (small) suite of demo records. We currently have 6, some of which are not even used: https://github.com/inspirehep/inspire-next/tree/320adfedca6eb336e1029b897677006ab8602b06/inspirehep/demosite/data

**Comment by StellaCh** [comment]
What's the status of this @jacquerie ?

**Comment by jacquerie** [comment]
> What's the status of this @jacquerie ?

This has improved (we now have 4), but hasn't happened yet. Thing is, it probably doesn't deserve to be its own issue.
