### ISSUE TITLE
orcid: make the OAuth token last longer

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-next#2265]
Because it annoys me I have to type my password so frequently :P

**Comment by jacquerie** [comment]
Actually this has nothing to do with OAuth, but it's a core Flask setting: https://stackoverflow.com/a/11785722/374865.

**Comment by jmartinm** [comment]
I think we are just missing this config setting - https://github.com/inveniosoftware/invenio-oauthclient/blob/master/invenio_oauthclient/config.py#L85

**Comment by jmartinm** [comment]
Will test it now in QA.

**Comment by jmartinm** [comment]
It will not work if I don't fix https://github.com/inveniosoftware/invenio-oauthclient/issues/133 first...

**Comment by jacquerie** [comment]
Whoops! Well, we could meanwhile hack around it with the mechanism I suggested...
