### ISSUE TITLE
testing: continuous_migration locking should be tested

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#2285]
9e3128682ff9dc72360173b2d0c227b908201a48 introduces protection of `continuous_migration()` via redis-lock. This should be tested so that a naïve developer doesn't later remove this functionality.

**Comment by jacquerie** [comment]
This is **hard** to test automatically, yet it's easy to test manually. In a shell:
```
>>> for _ in range(1000):
...     continuous_migration.delay()
```
and you'll see in the logs several instances of the log message about the lock.

On the other hand testing this automatically requires to have an application with the `celery` configuration not in eager mode, then find a way to recreate the `celery` app with that configuration... maybe possible, but not really worth the effort.

I mean, the code under test is correct. I was wrong to insist it should be tested.

**Comment by kaplun** [comment]
But I am still working on it in #2286. Why do you close the issue then?

**Comment by kaplun** [comment]
(just realized putting the issue number in the subject and not the body is not properly linkining PRs.)

**Comment by jacquerie** [comment]
I was going to close that as well!

**Comment by kaplun** [comment]
After all the pain I am suffering... Aren't we close to the solution?

**Comment by jacquerie** [comment]
I don't think so.

**Comment by kaplun** [comment]
Plus I think setting to CELERY_ALWAYS_EAGER underlines a new bug.

**Comment by kaplun** [comment]
Check the outcome of the new push, and you'll see the ASCII/Unicode issue.

**Comment by jacquerie** [comment]
For the reasons in https://github.com/inspirehep/inspire-next/issues/2285#issuecomment-298639390 and https://github.com/inspirehep/inspire-next/pull/2286#discussion_r114346149 the benefit of this test is at least an order of magnitude less than the effort required to implement it.
