### ISSUE TITLE
Inspirehep JSON Merger

### ISSUE THREAD

**Issue by ammirate** [inspirehep/inspire-next#2294]
Introducing in Inspire a process and a set of rules to merge two records.

**Comment by ammirate** [comment]
Design Document at: 
https://docs.google.com/document/d/1DG2FXo0W9w1c05rnr7YTviWwzOvYk2KfeblXPWwxNZw/edit

Defined merging rules at :
https://docs.google.com/spreadsheets/d/1IKgKNgp0uStX07Uv7FECpkGX5J6xdZ57kErhS4Ra7BQ/edit#gid=0

**Comment by jacquerie** [comment]
Done in https://github.com/inspirehep/inspire-next/pull/3005.
