### ISSUE TITLE
Record not found 

### ISSUE THREAD

**Issue by rikirenz** [inspirehep/inspire-next#2316]
## Meta

**OS**:  
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename: xenial

**Browser**:  
Chrome 

**Browser Version**:  
Version 55.0.2883.87 (64-bit)

## Expected Behavior
When I select an item in the list at this url: https://labs.inspirehep.net/search?page=1&size=25&cc=literature 
![image](https://cloud.githubusercontent.com/assets/4679712/25805066/87976772-33fe-11e7-86ae-2c007f9e83fc.png)

I would expect to see the detail of that article

## Actual Behavior
When I select an item in the list at this url instead of see the detail of that article I receive this error page:

![image](https://cloud.githubusercontent.com/assets/4679712/25805092/a6b86eb2-33fe-11e7-962d-58b4cbedb9b3.png)

This happened for the following records:
- 923769 (https://labs.inspirehep.net/literature/923769)
- 1394639 (https://labs.inspirehep.net/literature/1394639)

and also for others

**Comment by jacquerie** [comment]
We don't support record access on Labs.

**Comment by david-caro** [comment]
Shouldn't it be there anyhow?

**Comment by kaplun** [comment]
Yeah. If a record is in the search result the detail view should be there. At least I wouldn't expect a 404, rather a 500 for some unexpected error.

But this might actually be an issue of ES and DB being out of sync for whatever reason...
