### ISSUE TITLE
Inspirehep JSON Merger: merging rules arXiv to arXiv

### ISSUE THREAD

**Issue by ammirate** [inspirehep/inspire-next#2320]
Define and test merging rules in according to the current HEP schema, for the use case arXiv update on arXiv head.

Rules can be found in the FIRST spreadsheet at:
https://docs.google.com/spreadsheets/d/1IKgKNgp0uStX07Uv7FECpkGX5J6xdZ57kErhS4Ra7BQ/edit#gid=0

**Comment by kaplun** [comment]
Implemented in inspirehep/inspire-json-merger#4
