### ISSUE TITLE
Inspire JSON Merger: root retrieval

### ISSUE THREAD

**Issue by ammirate** [inspirehep/inspire-next#2322]
The ROOT file, needed to merge two records, has to be stored in the workflow and be retrievable for the merging operation.

A Design Document can be found at:
https://docs.google.com/document/d/1BDG14AsY5FEtGXX10uR6U8CNTJnZuLXldgm6K4uOrCM/edit

**Comment by kaplun** [comment]
Why you closed this issue?

**Comment by jacquerie** [comment]
Done in https://github.com/inspirehep/inspire-next/pull/3005.
