### ISSUE TITLE
holdingpen display and sorting

### ISSUE THREAD

**Issue by ksachs** [inspirehep/inspire-next#2326]
Instead of
Filtered keywords include:
I would prefer
NN filtered core keywords (where NN is the length of "classifier_results": "complete_output": "Filtered Core keywords")

Can we get that line in color?
Orange if there is 0-1 filtered core keywords, Green if there are 2 or more filtered core keywords (similar to the relevance_prediction).

Followed by the list of all core keywords

Also sorting by relevance would be great:
CORE sortBy(scores[CORE]) > Non-CORE sortBy(scores[Non-CORE]) > Rejected sortBy(-scores[Rejected])
i.e.

      "scores": {
        "CORE": 1.2643910713210214,
        "Non-CORE": 0.29765000802701275,
        "Rejected": -0.2976990909545355
      }

      "scores": {
        "CORE": 0.7643910713210214,
        "Non-CORE": 0.29765000802701275,
        "Rejected": -0.2976990909545355
      }

      "scores": {
        "CORE": -1.2643910713210214,
        "Non-CORE": 0.29765000802701275,
        "Rejected": -0.2976990909545355
      }

      "scores": {
        "CORE": -1.2643910713210214,
        "Non-CORE": -0.29765000802701275,
        "Rejected": 0.2976990909545355
      }

      "scores": {
        "CORE": -1.2643910713210214,
        "Non-CORE": -0.29765000802701275,
        "Rejected": 1.2976990909545355
      }

**Comment by michamos** [comment]
@jmartinm these are Kirsten's requirements

**Comment by jmartinm** [comment]
I am almost done with this change, currently it looks like this on the search results:

<img width="386" alt="screen shot 2017-07-05 at 2 33 15 pm" src="https://user-images.githubusercontent.com/580727/27864437-def5109c-618e-11e7-9ffe-ed5451eba16c.png">

And in the detailed view I have not changed it:

<img width="410" alt="screen shot 2017-07-05 at 2 34 25 pm" src="https://user-images.githubusercontent.com/580727/27864466-00f3c81e-618f-11e7-915b-e488449a2379.png">

What do you think @ksachs ? Is it clear enough in the search results that both the filtered and non-filtered keywords are shown?

**Comment by ksachs** [comment]
Cool, I like it! Thanks a lot.
