### ISSUE TITLE
layout improvement in RT tickets

### ISSUE THREAD

**Issue by tsgit** [inspirehep/inspire-next#2335]
Hi,

I request minor layout improvement for RT tickets from literature suggestion. The current layout with no newline after the edit link breaks some old rt-parsing tools. In addition a newline after the edit link would improve ticket readability.

the templates

https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/literaturesuggest/templates/literaturesuggest/tickets/curation_core.html#L21

https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/authors/templates/authors/tickets/curation_needed.html#L21

create tickets like this:

https://inspirert.cern.ch/Ticket/Attachment/6305107/2032104/

New submission from liko@ualberta.ca

Curate record here: https://inspirehep.net/record/edit/#state=edit&recid=1596921.  Link to pdf: https://repository.asu.edu/attachments/143517/content/Chatterjee_asu_0010E_14546.pdf
Record url: http://inspirehep.net/record/1596921

Cheers
T.

**Comment by bing13** [comment]
:+1:
