### ISSUE TITLE
Crash in holding pen after deployment

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#2337]
After deploying of #2283 this error appered:
https://sentry.cern.ch/inspire-sentry/inspire-labs/group/822026/

**Comment by jacquerie** [comment]
This error also looks related: https://sentry.cern.ch/inspire-sentry/inspire-labs/group/822163/, and has nothing to do with `ARXIV_PDF_URL`.

**Comment by david-caro** [comment]
That one looks more like EOS imo...

**Comment by kaplun** [comment]
As far as I can see, we were never fetching really from arXiv explicitly in the workflow. Only refextract was, on his own and using the correct entrypoint.
Now that I have implemented real fetching from arXiv the correct prefix should be used. That nevertheless should be correct.

**Comment by jacquerie** [comment]
Still happening after #2338 / #2339 (no beer for @kaplun !)

**Comment by kaplun** [comment]
Ehehe. OK. Now I have another hypothesis for why it might happen: it could be due to the weird object passage in Invenio. What we currently do is to pass the request object around and posticipate the time when we basically we call `.read()`. Probably this is so late in the workflow (due to previous steps happening), that arXiv considers us dead and closes the connection.

**Comment by jacquerie** [comment]
I don't think the stacktrace supports this theory: the exception is happening when calling `download_file_to_workflow` in the workflow step `arxiv_fulltext_download`, the earliest possible step that is fetching the PDF from arXiv.

I think instead that this has to do with missing / invalid internal state if we are not calling the `files` property at least one time before using it. I have three arguments for this:

1. This is the closest thing that changed in the PR that triggered this error.
2. Restarting the workflow appears to fix the problem (my argument here is that the previous run of the step initialized the `files` property correctly, and now we don't see the failure anymore).
3. Just by looking at [the code](https://github.com/inveniosoftware-contrib/invenio-workflows-files/blob/22570da9aeb6b8029e2f88a3a5379d28a4f6b9ee/invenio_workflows_files/api.py#L76-L87), the `files` property looks inherently stateful...

**Comment by david-caro** [comment]
> I think instead that this has to do with missing / invalid internal state if we are not calling the files property at least one time before using it.

But it does not happen to all the arxiv crawls, if that were the case, it would happen to all of them, at any point in time.

ECONNRESET, that is, that the remote side sends a RST packet is something done explicitly and started by the remote side itself, like when the firewall closes a connection (just saying).

**Comment by david-caro** [comment]
Btw. every time that the error happens, there's a 'cascade' of workflows that get stuck in 'initial' status too.

**Comment by david-caro** [comment]
(just stating the correlation, not causality though)

**Comment by jacquerie** [comment]
> But it does not happen to all the arxiv crawls, if that were the case, it would happen to all of them, at any point in time.
> 
> ECONNRESET, that is, that the remote side sends a RST packet is something done explicitly and started by the remote side itself, like when the firewall closes a connection (just saying).

I can think of reasons why it doesn't fail all the time (essentially: race between the state initialization and the download), but yeah, you convinced me, it's probably an error that arXiv normally throws, and we should handle it.

BTW, [these other people](https://github.com/ContentMine/getpapers/issues/155) seem to have the same issue as us.

**Comment by kaplun** [comment]
OK: So I believe this problem has 2 clear solutions:
1. starting to download immediately after issuing the request.
2. retrying the download (with a small pause) after the ECONNRESET is captured.

BTW: looks like Python's `requests` allow to configure a retry workflow.
BTW2: we might be more gentle to arXiv by using instantiating a session (e.g. one per Celery worker). In this way we can keep a more stable connection to arXiv without issuing one new TCP connection per request.

**Comment by kaplun** [comment]
Can we just to the reading of the stream directly in our function rather than in invenio-records-rest?

**Comment by jacquerie** [comment]
> 1. starting to download immediately after issuing the request.

This is already happening, yesterday I was wrong in claiming I reproduced this error. We get RSTd by arXiv if we make too many requests, or if we wait too long after opening the connection. This exception is caused by the former, while yesterday I was producing the latter.

**Comment by jacquerie** [comment]
> Can we just do the reading of the stream directly in our function rather than in invenio-records-rest?

Nope. Follow the code down the rabbit hole (or read [@david-caro's explanation](https://github.com/inspirehep/inspire-next/blob/7c13374f6b38a20825bea081c1bfc29c03006a7e/inspirehep/modules/workflows/utils.py)) of what the innocent line `workflow.files[name] = req.raw` is actually doing.

**Comment by kaplun** [comment]
So we are always obliged to pass an open stream?

**Comment by jacquerie** [comment]
> BTW: looks like Python's `requests` allow to configure a retry workflow.

Sadly it doesn't apply here, because the exception happens _after_ we've made it to the server. `Retry` from `urllib3` would be more relevant, but that would need to be patched in `invenio-files-rest`, while the solution in #2349 only touches code in INSPIRE.

**Comment by jacquerie** [comment]
#2349 and #2357 did in fact fix this problem.
