### ISSUE TITLE
Holdingpen: table titles misaligned

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-next#2346]
The titles in the holdingpen list view are misaligned, really really bothering after I was made aware of it... xd

![screenshot from 2017-05-18 09-30-11](https://cloud.githubusercontent.com/assets/587148/26191107/cfec31dc-3bac-11e7-8365-39ada2f1f5d0.png)

**Comment by StellaCh** [comment]
this is fixed in the current holding pen
