### ISSUE TITLE
Bug in reporting ticket(?)

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#2348]
See Sentry entry: https://sentry.cern.ch/inspire-sentry/inspire-labs/group/822209/
Blocked record is: https://labs.inspirehep.net/holdingpen/639610

**Comment by kaplun** [comment]
Looks like the `obj['_extra_data']` was not having a `reason` key at the time @annetteholtkamp clicked. Now it contains an empty string:
https://labs.inspirehep.net/api/holdingpen/639610

The source code is doing `obj['_extra_data'].get('reason').strip()` which of course might crash

**Comment by jacquerie** [comment]
Yup, as I said this morning: https://github.com/inspirehep/inspire-next/pull/2313#issuecomment-302305699
