### ISSUE TITLE
workflows: json_api_request should be fault-tolerant

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-next#2355]
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs/group/822046

Unlike https://github.com/inspirehep/inspire-next/pull/2349, this can be implemented using `requests` only.

**Comment by chris-asl** [comment]
Could we do something like the suggestion [here](http://stackoverflow.com/a/35504626/774513)?  

Mount an `HTTPAdapter` using the `max_retries` parameter ([more](https://github.com/kennethreitz/requests/blob/master/requests/adapters.py#L80)) on the session object with a `url` pattern, which can be the `url` in the post method.

Regarding the `max_retries` parameter, we can have more control over how many retries or exponential backoff factor _per request_ by using the `Retry` object ([more](https://github.com/kennethreitz/requests/blob/bf1a2a4e399ec5e75c5e9aadae564f77ca99afff/requests/packages/urllib3/util/retry.py#L39)).

How does this approach look? @jacquerie @david-caro

**Comment by jacquerie** [comment]
Yes, this is the right solution.

**Comment by jacquerie** [comment]
Moreover we found out that Magpie is hosted in the Wigner data center, which explains why this problem is localized to this particular machine.

**Comment by chris-asl** [comment]
Actually the solution in the linked StackOverflow question doesn't fully fit our needs. 

It only provides a retry mechanism (optionally, with back-off) for when receiving certain HTTP error codes (e.g. 500).  

In the case of an exception, e.g. `ConnectionError`, as happened on [Sentry](https://sentry.cern.ch/inspire-sentry/inspire-labs/group/822046/), we need retry logic, i.e. _retrying on exception_ which isn't offered by `requests` ([source](https://stackoverflow.com/questions/16511337/correct-way-to-try-except-using-python-requests-module)).

@jacquerie Could this be a good fit for using [`backoff`](https://pypi.python.org/pypi/backoff/1.4.2)?  
(and a combination of the retry logic of requests for certain HTTP error codes)
