### ISSUE TITLE
setup: unpin Sphinx

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-next#2380]
Follow-up of https://github.com/inspirehep/inspire-next/pull/2278.

**Comment by jacquerie** [comment]
I have a feeling that 8022577164a3c359f905f96733bd8ab109d63950 fixed this issue, rather than fixing https://github.com/inspirehep/inspire-next/issues/2386.

**Comment by kaplun** [comment]
Almost. Our fix also contributed in fixing major warning: i.e. missing imports (which were indeed treated as errors and was actually causing the whole build to bail out).
