### ISSUE TITLE
PDF with compressed content-encoding are not decompressed

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#2408]
## Expected Behavior
If servers serve us with content-encoding: gzip, we should on the fly decode it.

## Current Behavior
This is currently not happening. So in: https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/workflows/utils.py#L177 we are serving gzipped data.

**Comment by kaplun** [comment]
This is related with many failed user submssion @annetteholtkamp is reporting (because we delivery to legacy a data file with the gzipped PDF rather than the actual PDF.

**Comment by jacquerie** [comment]
Looks like we were victim of this subtlety in the documentation: https://github.com/requests/requests/issues/2155#issuecomment-50885814. Luckily, https://github.com/requests/requests/issues/2155#issuecomment-287628933 should work for us.
