### ISSUE TITLE
Create RT API

### ISSUE THREAD

**Issue by harunurhan** [inspirehep/inspire-next#2418]
Utility for RT to be used across all modules (editor and holdingpen)

## Needed actions

- get all tickets by `RecordID`
- close a ticket `ticket_id`
- get RT users
- get Queue names
- create a ticket
- ~~update a ticket by `ticket_id`~~
- reply a ticket by `ticked_id`

**Comment by jacquerie** [comment]
Places in which part of this logic is currently scattered:

* https://github.com/inspirehep/inspire-next/blob/d4272c210dcca23ef08ac71dc05954e1f57d77ce/inspirehep/utils/tickets.py
* https://github.com/inspirehep/inspire-next/blob/d4272c210dcca23ef08ac71dc05954e1f57d77ce/inspirehep/modules/literaturesuggest/tasks.py#L185-L250
* https://github.com/inspirehep/inspire-next/blob/d4272c210dcca23ef08ac71dc05954e1f57d77ce/inspirehep/modules/authors/tasks.py#L116-L179

**Comment by harunurhan** [comment]
Apparently there is no need for `update` update is done only for `close` to change the status to `Resolved`

However there is a need for "reply a ticket by `ticked_id`".
