### ISSUE TITLE
xrootd: kill module

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-next#2453]
`xrootd` was added in https://github.com/inspirehep/inspire-next/pull/2437 to hold the XRootD extension. As observed in https://github.com/inspirehep/inspire-next/pull/2437#discussion_r122189274, though, this extension should rather live in https://github.com/inveniosoftware/invenio-xrootd.

- [x] Create a PR against `invenio-xrootd` to add the extension
- [x] Create a PR against `invenio-xrootd` to request a new release
- [ ] Bump `invenio-xrootd` here to use their extension instead of ours

**Comment by lnielsen** [comment]
Btw, make sure that you are on XRootDPyFS v0.1.5 or nasty things like http://blog.zenodo.org/2017/07/19/upload-storage-incident/ can happen.
