### ISSUE TITLE
HEP submission form: importing a record that already exists

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-next#2465]
Annette was able to import and submit two records using a doi that already exists in the database. I tried myself, and I was able to import it.

## Expected Behavior
It should not let you submit a record with a doi that already exists in the db.

## Current Behavior
It did allow to submit two records that already had the doi in the db, failing later in the robotupload step on legacy side.

## Steps to Reproduce (for bugs)
1. Go to hep submission form
2. Enter a doi number (for example '10.1016/j.optmat.2016.09.028')
3. Hit import

**Comment by david-caro** [comment]
I think that the issue is that the record is in a non-public collection...

**Comment by michamos** [comment]
the issue was fixed in #2441 but has not been deployed on labs yet.
