### ISSUE TITLE
change CFG_SITE_NAME

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#248]
Currently:

```python
CFG_SITE_NAME = u"HEP"
```

Which means that in certain parts like emails sent to the user, the title is `Account registration at HEP`

The reason behind that site name is that Invenio required the `CFG_SITE_NAME` to be the same as the main collection so that an empty search would work.

We need to double check if this is still a problem and solve it so that we can change the name.

**Comment by jmartinm** [comment]
One comment on this is that currently we don't have any HEP records, so it might not be a problem right now to change it. I am un unsure about side effects though.

**Comment by kaplun** [comment]
Would be good to move this into Invenio Github, as a feature request: i.e. to be able to set the site name independently from the root collection (I wonder indeed if this requirement still exist, after all the re-engineering of Jiri related to collections)

**Comment by jmartinm** [comment]
Solved by https://github.com/inveniosoftware/invenio/commit/f4bf802ef8e11c2a677db0afa2ffba93001da353
