### ISSUE TITLE
Continuous migration records are not properly created

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#2484]
It seems like the records created via continuous migration are not properly created. Currently on Labs (https://labs.inspirehep.net/search) there are ~900 records that arrived in that way but clicking  on them gives 404.

That indicates that the documents are in ElasticSearch but they are not in the database (and no pid is registered for them)

CC @kaplun

**Comment by kaplun** [comment]
I think this was a temporary inconsistency. Due to many tentative deployement.
