### ISSUE TITLE
Holding Pen: references template show authors

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#2490]
Since the output of refextract changed, the references table does not show correctly the authors.
![istantanea_2017-06-27_10-15-10](https://user-images.githubusercontent.com/119349/27577577-87e9f704-5b21-11e7-9aac-82c4d54522aa.png)

**Comment by kaplun** [comment]
The anonymous bug ninja @jmartinm fixed it yesterday night.

**Comment by michamos** [comment]
Is it supposed to be fixed in production? I still see broken templates.

**Comment by kaplun** [comment]
Right. I misread it.

**Comment by kaplun** [comment]
BTW. This remembers me of: https://youtu.be/yL_-1d9OSdk
