### ISSUE TITLE
holding pen: opening in editor should save

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspire-next#2493]
## Expected Behavior
If there are modifications to the HP record from the HP interface, clicking on `Open in Editor` should save the modifications.

## Current Behavior
Modifications are not saved.

## Steps to Reproduce (for bugs)

1. Open a record in the HP in `Halted` status
2. Do some modifications
3. Click on `Open in Editor`

**Comment by StellaCh** [comment]
Related to: https://github.com/inspirehep/inspire-next/issues/2877 
The system should force the user the save the changes
