### ISSUE TITLE
Email with email: prefix

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#2497]
@hoc3426 is adding `email:` in front of emails on legacy. We shall consider this in dojson script.

**Comment by jacquerie** [comment]
@michamos just told me that this is not happening on all emails, only a few fields... mind writing down which ones?

**Comment by kaplun** [comment]
@hoc3426 ?

**Comment by michamos** [comment]
`100/700__m`

**Comment by jacquerie** [comment]
This issue was moved to inspirehep/inspire-dojson#6
