### ISSUE TITLE
Sometimes test_submit_author doesn't pass

### ISSUE THREAD

**Issue by bavaria95** [inspirehep/inspire-next#2518]
## Expected Behavior
I expect test_submit_author to pass.

## Current Behavior
Realized that when running acceptance tests inside the kubernetes cluster, sometimes it got stuck sending request like:
`10.100.3.0 - - [06/Jul/2017:08:29:02 +0000] "GET /holdingpen/list/?workflow_name=Author&is-update=false&size=10&status=HALTED HTTP/1.1" 200 16775 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"`

It turned out that in this case author is created, but clean up happens before it's actually used:
`{"_index":"holdingpen-authors","_type":"authors","_id":"3","found":false}`
thus the test hangs indefinitely waiting for the record to be there.

**Comment by jacquerie** [comment]
Isn't this #2222 ?

**Comment by kaplun** [comment]
This should have been fixed by #2502. @bavaria95 please reopen in case of regression.

**Comment by david-caro** [comment]
It's not any of those, for some reason the cleanup was being executed while the test was running, it was something strange... only seen that when running on kubernetes though.
