### ISSUE TITLE
Wrong mime type leads to refextract fail

### ISSUE THREAD

**Issue by zzacharo** [inspirehep/inspire-next#2523]
## Current Behavior

`refextract` fails when tries to parse file content as it expects a pdf and gets mimetype HTML.
The problem is that here https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/workflows/tasks/arxiv.py#L75 the check for `pdf` passes but the content is `html` and so `refextract` fails when tries here https://github.com/inspirehep/refextract/blob/master/refextract/references/engine.py#L1395 with `magic` library to detect the content.

See sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs/group/824570/events/150921036/

**Comment by kaplun** [comment]
cc: @michamos
