### ISSUE TITLE
HoldingPen: are these arxiv articles harvested?

### ISSUE THREAD

**Issue by ksachs** [inspirehep/inspire-next#2528]
example of 4 records (from Jul 11) that got CORE keywords at DESY but are not in the holdingpen.
It is possible that bibclassify gives different output. That would be OK, the papers are garbage. But I would like to understand what happened.
Can someone check whether they were

- not harvested at all
- filtered somewhere (why)
- stuck or disapeared

physics 1707.02393    ;#  0: Sigma/b
https://labs.inspirehep.net/holdingpen/list/?page=1&size=10&q=1707.02393

physics 1707.02436    ;#  0: positive particle
https://labs.inspirehep.net/holdingpen/list/?page=1&size=10&q=1707.02436

physics 1707.02552    ;#  1: MICE
https://labs.inspirehep.net/holdingpen/list/?page=1&size=10&q=1707.02552

physics 1707.02604    ;#  2: KAMIOKANDE; KamLAND
https://labs.inspirehep.net/holdingpen/list/?page=1&size=10&q=1707.02604

**Comment by ksachs** [comment]
from the harvest of Wednesday (Jul 12)
7 out of 28 astro-ph articles have no trace in the holdinpen
[1707.03130, 1707.03155, 1707.03179, 1707.03180, 1707.03343, 1707.03345, 1707.03390]

**Comment by kaplun** [comment]
@ksachs thanks a lot. We keep on investigating. So far we still do not understand why they are missing.

**Comment by ksachs** [comment]
cond-mat 1707.09802 1707.09923 are  missing (2017-08-01)

**Comment by kaplun** [comment]
I believe the reason why we are missing articles is here: https://github.com/inveniosoftware/invenio-oaiharvester/issues/41

**Comment by kaplun** [comment]
@michamos and I have analyzed the situation. Looks like the bug had been introduced in Labs (was not been triggered on oldlabs), and has made on average to throw away more than half of each day harvesting (only 1001 records where harvested per day out of ~2.5K). 

The harvesting is harvesting these OAI sets in this order:
`cs math physics physics:astro-ph physics:cond-mat physics:math-ph physics:nlin physics:physics physics:quant-ph q-bio q-fin stat`

hence we suspect that the first 1001 records only (i.e. `cs`, `math` etc.) where harvested, while `stat` and `q-fin`, `q-bio` and `physics:quant-ph` etc. were lost (actually, after the first 999 records, one record every 1000 was still harvested).

We suspect this affected mostly these OAI sets
physics:nlin physics:physics physics:quant-ph q-bio q-fin stat

**Comment by ksachs** [comment]
2017-10-17: 1710.05350 and 1710.05845 are missing
astro-ph had an unusually high number of submissions today (151)

**Comment by kaplun** [comment]
Mmh... we really need to drop `invenio-oaiharvest`. Currently: grepping through the logs of hepcrawl:
```
root@inspire-prod-crawler1$ grep -or "oaiharvest_.*\.xml" * | uniq
290637fcb3a011e7ba0e02163e010a0e.log:oaiharvest_2017-10-18_a9k_z6.xml
6ef66e3ab07b11e7ba0e02163e010a0e.log:oaiharvest_2017-10-14_AHTpUT.xml
c2acc522b20d11e7ba0e02163e010a0e.log:oaiharvest_2017-10-16_gd9kam.xml
f9e6b862b2d611e7ba0e02163e010a0e.log:oaiharvest_2017-10-17_D9oi_T.xml
```

So these are the only files that have been read on input to extract records! However:
```
root@inspire-prod-crawler1$ ls -l oaiharvest_2017-10-1[789]*
-rw-r--r-- 1 inspire def-cg  459959 17 ott 03.03 oaiharvest_2017-10-17_D9oi_T.xml
-rw-r--r-- 1 inspire def-cg 2617097 17 ott 03.03 oaiharvest_2017-10-17_XYmNbZ.xml
-rw-r--r-- 1 inspire def-cg 2565375 17 ott 03.03 oaiharvest_2017-10-17_ybxKIt.xml
-rw-r--r-- 1 inspire def-cg 2245663 18 ott 03.03 oaiharvest_2017-10-18_a9k_z6.xml
-rw-r--r-- 1 inspire def-cg 2203194 18 ott 03.03 oaiharvest_2017-10-18_JCfpng.xml
-rw-r--r-- 1 inspire def-cg 1481651 18 ott 03.03 oaiharvest_2017-10-18_tdHRcz.xml
```

So many input files got ignored!!!

**Comment by michamos** [comment]
Seems `invenio-oaiharvest` is fine. Actually, `scrapy` receives all the files but is crashing on all but one:
```
2017-10-17 03:03:50 [twisted] CRITICAL: Unhandled Error Traceback (most recent call last):
  File "/opt/inspire/lib/python2.7/site-packages/scrapy/commands/crawl.py", line 58, in run
    self.crawler_process.start()
  File "/opt/inspire/lib/python2.7/site-packages/scrapy/crawler.py", line 285, in start
    reactor.run(installSignalHandlers=False)  # blocking call
  File "/opt/inspire/lib/python2.7/site-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/opt/inspire/lib/python2.7/site-packages/twisted/internet/base.py", line 1252, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/opt/inspire/lib/python2.7/site-packages/twisted/internet/base.py", line 878, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/opt/inspire/lib/python2.7/site-packages/scrapy/utils/reactor.py", line 41, in __call__
    return self._func(*self._a, **self._kw)
  File "/opt/inspire/lib/python2.7/site-packages/scrapy/core/engine.py", line 122, in _next_request
    if not self._next_request_from_scheduler(spider):
  File "/opt/inspire/lib/python2.7/site-packages/scrapy/core/engine.py", line 149, in _next_request_from_scheduler
    request = slot.scheduler.next_request()
  File "/opt/inspire/lib/python2.7/site-packages/scrapy/core/scheduler.py", line 71, in next_request
    request = self._dqpop()
  File "/opt/inspire/lib/python2.7/site-packages/scrapy/core/scheduler.py", line 106, in _dqpop
    d = self.dqs.pop()
  File "/opt/inspire/lib/python2.7/site-packages/queuelib/pqueue.py", line 46, in pop
    q.close()
  File "/opt/inspire/lib/python2.7/site-packages/queuelib/queue.py", line 175, in close
    os.remove(self.path)
exceptions.OSError: [Errno 2] No such file or directory: 'jobs/requests.queue/p0'
```
@jacquerie is suspecting EOS.

**Comment by kaplun** [comment]
As @david-caro and @ammirate and @jacquerie solved out on Gitter this was due to a misconfiguration of scrapy that was causing a race-condition on parallel crawls using the same workdir. This has been solved on production

**Comment by kaplun** [comment]
cc @StellaCh : this is the blocker bug I was mentioning at the meeting

**Comment by ksachs** [comment]
@fschwenn and I searched for missing arXiv articles of 2017. 
From those we accepted for INSPIRE there are 13 without a trace in the HP, 5 from November:

arXiv:1701.01022 , arXiv:1701.07062 , arXiv:1702.08285 , arXiv:1703.05573 , arXiv:1708.04550 , arXiv:1708.06728 , arXiv:1708.07361 , arXiv:1708.08897 , arXiv:1711.06094 , arXiv:1711.06044 , arXiv:1711.06547 , arXiv:1711.06674 , arXiv:1711.09009
