### ISSUE TITLE
Hidden collections

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspire-next#2539]

**Comment by jmartinm** [comment]
https://github.com/inspirehep/inspire-dojson/pull/36 will make collections defined as `special_collections` (https://github.com/inspirehep/inspire-dojson/blob/6e4b0949d85e145ce114d3f8631d6c12693731ad/inspire_dojson/hep/rules/bd9xx.py#L69-L87) not be shown to the user by default.

They will be visible through the URL like in legacy, for example, with `/search?cc=Hal%20Hidden`

**Comment by jacquerie** [comment]
https://github.com/inspirehep/inspire-dojson/pull/36 was superseded by https://github.com/inspirehep/inspire-dojson/pull/38, and I deployed INSPIRE after https://github.com/inspirehep/inspire-next/pull/2557.

Is there anything else to do here?

**Comment by StellaCh** [comment]
Is it ok to close this @jmartinm ?
