### ISSUE TITLE
Permissions implementation

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspire-next#2540]

**Comment by jmartinm** [comment]
The functionality to manage Restricted Collections works.

Things to be done are:

1) Make sure config for collections is correct in https://github.com/inspirehep/inspire-next/blob/master/inspirehep/config.py#L179

2) Create roles that should have access to the restricted collections

3) Assign to the roles the action `'view-restricted-collection'` with argument the name of the collection. This can be done from `/admin`

**Comment by StellaCh** [comment]
@jmartinm can we close this?

**Comment by jmartinm** [comment]
Once Labs becomes `master`, the only missing thing will be to add the user accounts that should have access to the restricted collections (or migrate them from legacy) and add a role for each collection that should be assigned to the users. So there is no development to be done, just migration of data from legacy.
