### ISSUE TITLE
Bootstrap theme issues

### ISSUE THREAD

**Issue by jalavik** [inspirehep/inspire-next#255]
I noticed some minor display issues in our style guide: https://labs.inspirehep.net/style-guide

- [ ] several panel contextual classes are mostly unreadable due to the white font color
- [ ] `label-success` green color is different than `btn-success` green color.

It would be nice to fix these as it affects the whole site. E.g. I noticed this in the Holding Pen.

**Comment by jmartinm** [comment]
Added related PR to fix it.
