### ISSUE TITLE
Changes in the merger

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspire-next#2561]
To investigate what needs to be changed in the merger concerning the files and plots

**Comment by jmartinm** [comment]
It would be good if these issues get more details about what needs to be done, etc. Would make it easy to distinguish all the issues we have.

**Comment by ammirate** [comment]
`inspire-json-merger` now is aware about these keys in the schema but there is no particular logic, since after the merging step in the workflow, such fields are going to be cleaned and rebuilt, as discussed IRL with @david-caro.
