### ISSUE TITLE
Holding Pen: auto-reject

### ISSUE THREAD

**Issue by ksachs** [inspirehep/inspire-next#2566]
## Expected Behavior

records with "Automatic Decision: Rejected" and 0 core keywords should be auto-rejected.

## Current Behavior

I think most of the time this works fine.
E.g. https://labs.inspirehep.net/holdingpen/686132

But now I found records waiting for decision where the score is negative, e.g.
https://labs.inspirehep.net/holdingpen/685260
Automatic Decision: Rejected -0.12
0 core keywords. 0 Filtered:

**Comment by jacquerie** [comment]
This seems to be the same issue as https://github.com/inspirehep/inspire-next/issues/2414. Can you confirm, @ksachs ?

**Comment by ksachs** [comment]
yes. You can close this issue.

**Comment by jacquerie** [comment]
Ok. I'm going to leave this open to remind me of the quick fix that we can do here: just remove the check on the `max_score`, since it's hard to interpret what it means anyway...
