### ISSUE TITLE
tests: test_arxiv_fulltext_download_logs_on_error is slow

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-next#2574]
## Expected Behavior
The entire unit test suite should run in ~30 seconds.

## Current Behavior
`test_arxiv_fulltext_download_logs_on_error` takes ~72 seconds to run.

## Steps to Reproduce (for bugs)
```
% py.test tests/unit/workflows/test_workflows_tasks_arxiv.py --durations=1

[...]

72.12s call     tests/unit/workflows/test_workflows_tasks_arxiv.py::test_arxiv_fulltext_download_logs_on_error
```

**Comment by jacquerie** [comment]
Bisected to https://github.com/inspirehep/inspire-next/commit/2419ca90df78ce14e413228df86b3c3d20d1b683.

**Comment by jacquerie** [comment]
> Bisected to https://github.com/inspirehep/inspire-next/commit/2419ca90df78ce14e413228df86b3c3d20d1b683.

In fact, one clearly sees what's wrong: we don't want to raise `DownloadError` for such an unrecoverable error, because then `backoff` will try again the download on a url that we know doesn't contain a PDF.

**Comment by zzacharo** [comment]
The thing is that we want to try again because sometimes when tries to download the pdf it is computed on the fly due to the arxiv thing that compiles the pdf only the first time is requested. So, in this case we missed some pdfs because we didn't wait enough.

**Comment by jacquerie** [comment]
> The thing is that we want to try again because sometimes when tries to download the pdf it is computed on the fly due to the arxiv thing that compiles the pdf only the first time is requested. So, in this case we missed some pdfs because we didn't wait enough.

Note how the tests are telling us that we're implementing exactly the opposite behavior. When the server always returns 500 we continue trying without success (https://github.com/inspirehep/inspire-next/blob/cc181af37e1ef8ae25db10b85c8d7c636b4ae224/tests/unit/workflows/test_workflows_tasks_arxiv.py#L119-L150), while when the PDF is being generated we try once, we log that we couldn't and we bail out (https://github.com/inspirehep/inspire-next/blob/cc181af37e1ef8ae25db10b85c8d7c636b4ae224/tests/unit/workflows/test_workflows_tasks_arxiv.py#L84-L116)...

**Comment by jacquerie** [comment]
> Note how the tests are telling us that we're implementing exactly the opposite behavior.

This description is actually quite incorrect... fixing the test should be enough here.
