### ISSUE TITLE
journal titles containing colons don't get normalized

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspire-next#2586]
## Expected Behavior
When a journal name contains a colon, the title should get normalized.

## Current Behavior
Colons (`:`) break autocomplete and normalization.

## Steps to Reproduce (for bugs)
1. Go to https://labs.inspirehep.net/literature/new
2. Skip and fill the form manually
3. Type `Nuclear Instruments and Methods in Physics Research Section A: Accelerators, Spectrometers, Detectors and Associated Equipment` in the journal title. See how autocomplete fails once the `:` is typed, and works again when removing it.

@chris-asl something to think about for you too probably.

**Comment by annetteholtkamp** [comment]
Whoops, that's not it. Closing.
