### ISSUE TITLE
submission: refextract doesn't run on references in textbox

### ISSUE THREAD

**Issue by annetteholtkamp** [inspirehep/inspire-next#2587]
## Expected Behavior
If a user copies/pastes a reference list in the text box refextract should run on these references, and the extracted references should be exported to legacy

## Current Behavior
Currently references in the text box are ignored.

## Context
Currently I have to copy/paste the references again in bibedit on legacy - a waste of time

**Comment by jacquerie** [comment]
@jmartinm made me realize that in order to do this we might need at least part of the merger, because we need to merge together the references extracted from the PDF and the ones parsed from the comments.

Or would it be okay to just override the PDF-extracted ones?

**Comment by annetteholtkamp** [comment]
I would use the references in the textbox only if no pdf is available. So nothing smart needed at the moment.

- Annette

On 10 Aug 2017, at 02:02, Jacopo Notarstefano <notifications@github.com<mailto:notifications@github.com>> wrote:


@jmartinm<https://github.com/jmartinm> made me realize that in order to do this we might need at least part of the merger, because we need to merge together the references extracted from the PDF and the ones parsed from the comments.

Or would it be okay to just override the PDF-extracted ones?

**Comment by jacquerie** [comment]
> I would use the references in the textbox only if no pdf is available. So nothing smart needed at the moment.

We can quickly implement this :+1:

**Comment by jacquerie** [comment]
Closed in https://github.com/inspirehep/inspire-next/pull/2854.
