### ISSUE TITLE
literature submission: author initials without dots

### ISSUE THREAD

**Issue by annetteholtkamp** [inspirehep/inspire-next#2604]
## Expected Behavior
When authors imported from CrossRef have initials with spaces behind them the space should be replaced by a dot.

## Current Behavior
Currently  the space is visible in the form but gets dropped on the way to legacy. So you get  Bruhwiler, DL instead of Bruhwiler, D.L.
Example: https://inspirehep.net/record/1614718

## Steps to Reproduce (for bugs)
Try to submit an article with initials-only authors from http://iopscience.iop.org/issue/1742-6596/180/1, e.g. 10.1088/1742-6596/180/1/012010

**Comment by jacquerie** [comment]
This is easier compared to https://github.com/inspirehep/inspire-next/issues/2591, so you might want to start from here.
