### ISSUE TITLE
holdingpen: enrichment: fully taken journals

### ISSUE THREAD

**Issue by fschwenn** [inspirehep/inspire-next#2643]
When journal articles end up in the holdingpen for selection - the holdingpen should know whether that journal is taken completely for INSPIRE and display it accordingly.

### knowing what to take completely
The information which journal is taken completely is stored in the JOURNALS database (583__a at the moment). The holdingpen should access these informations to know which journals are completely in INSPIRE.
There are also cases where certain parts of a journal are taken completely which is not yet stored in the JOURNALS database but only hard coded at DESY, e.g. for Phys.Rev.Lett.:
  re.search('^..(23|25|27|48|16|18|20)',articlid) are taken completely
The ideal case would be to store such cases also in the JOURNALS database but it is not clear to me, which form would be the most efficient.
### acting on it
We see basically two ways to proceed
- Harvest directly to INSPIRE, similar to arXiv completely harvested categories, e.g. gr-qc.
Additional CORE-tagging, assignment of field-codes, etc. can be done later, see #2657.
In this case unwanted stuff like editorials has to be deleted later.
- Indicate if a journal article belongs to such a journal. In principle it should not be possible to reject such an article, but since sometimes editorials and other rubbish is disguised as regular articles the possibility to reject such an article has to remain (button smaller or are-you-sure?-pop-up or ...).

## Current Behavior
None in the actual holdingpen. In the DESY-workflow, the decision to take an article is made by typing a letter. For fully taken journal the form is pre-filled.

## Context
It is essential that our users can rely on INSPIRE covering certain journals completely. Therefore we need to make sure that none of the articles of the core journals falls through the cracks

**Comment by ammirate** [comment]
Fixed by #2886.
