### ISSUE TITLE
holdingpen: enrichment: run bibclassify on abstract (if not fulltext available)

### ISSUE THREAD

**Issue by fschwenn** [inspirehep/inspire-next#2645]
If no fulltext is available, bibclassify should run on abstract+title+author keywords. It should indicated whether the core keywords are extracted from fulltext or from abstract.

## Expected Behavior
For arXiv papers we always have the fulltext but this not the case for all journal articles. In such cases bibclassify should run on abstract+title+author keywords instead. To know how to interpret the number of core keywords found, it should be indicated whether the core keywords are extracted from fulltext or from abstract.
One might even consider doing both (if possible) as core keywords found in the abstract are much more significant than core keywords found in the fulltext (especially the introduction often contains core keywords which are not really related to the real content of the paper).
These numbers should also be handed over to the function calculating the autmatic decision whether to take or reject a record.

## Current Behavior
At the moment bibclassify runs on the fulltext if present and on the title+abstract if not. No feedback is given about the presence of a fulltext and running on the author keywords is missing.

**Comment by kaplun** [comment]
Mmh... On Labs BibClassify runs on the abstract if the fulltext is not available:
https://github.com/inspirehep/inspire-next/blob/ac16592ee053b2f5409c350190b0209dee331ca3/inspirehep/modules/workflows/tasks/classifier.py#L81-L93

That's then represented as `fast_mode=true` in the `obj.extra_data`.

**Comment by kaplun** [comment]
Therefore I think this functionality was already implemented.

**Comment by annetteholtkamp** [comment]
We just did a test submission with abstract only and the invenio-classifier indeed ran.

**Comment by fschwenn** [comment]
Is the information that it ran on the abstract 'forwarded' and displayed?

**Comment by michamos** [comment]
yes, everything is displayed in the same way as for a fulltext keyword extraction. There is no visible difference at all. Do you need to know whether it ran on the fulltext or the abstract only?

**Comment by fschwenn** [comment]
Yes, I do. There are buzz words like 'gravitational radiation' which are very often mentioned somewhere in the introduction (i.e. in the fulltext) but not in the abstract where it is written what the paper is really about.

**Comment by fschwenn** [comment]
As I wrote in the issue, what I like to have is "bibclassify should run on abstract+title+author keywords" instead of "bibclassify should run on abstract only".

**Comment by michamos** [comment]
OK, reopening then.

**Comment by kaplun** [comment]
Yeah also in particular we are missing the "keyword" part.

**Comment by michamos** [comment]
Since #3175, keywords are extracted also from the author keywords. So only the display of where the keywords are extracted from is missing.

**Comment by StellaCh** [comment]
Fixed
