### ISSUE TITLE
dojson improvements

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#266]
The following dojson improvements are needed to reach a production status for INSPIRE.

* [x] Create a revert from the dojson to obtain a dictionary with marc keys. A sample dojson rule looks like:

```python
@hep.over('isbn', '^020..')
@utils.for_each_value
@utils.filter_values
def isbn(self, key, value):
    """Other Standard Identifier."""
    return {
        'isbn': value.get('a'),
        'medium': value.get('b')
    }
```

We then need the opposite that we will write in the same file close to the original:

```python
@unhep.over('020', 'isbn')
@utils.for_each_value
@utils.filter_values
def isbn(self, key, value):
    """Other Standard Identifier."""
    return {
        'a': value.get('isbn'),
        'b': value.get('medium')
    }
```

* [x] Write test cases that will go through all the fields (100% test coverage), from MARCXML will convert to `hep` then use `unhep` and make sure no information is lost. @ioannistsanaktsidis 

* [x] Make HEP dojson compliant with https://github.com/inspirehep/inspire-next/blob/master/inspire/dojson/hep/schemas/hep-0.0.1.json @ioannistsanaktsidis 

* [x] Fix https://github.com/inspirehep/inspire-next/issues/295

* [x] Complete Dojson model for Institutions

* [x] Complete Dojson model for Experiments

* [x] Complete Dojson model for Journals

* [x] Dojson model for Conferences

* [x] Dojson model for Jobs

* [x] Dojson model for Authors

**Comment by ioannistsanaktsidis** [comment]
Missing fields: preprint_info

**Comment by ioannistsanaktsidis** [comment]
Here we have quite good coverage. Just saw it in the tests:
```
inspire/dojson/hep/fields/bd01x09x.py                                                  99%   
inspire/dojson/hep/fields/bd1xx.py                                                         95% 
inspire/dojson/hep/fields/bd20x24x.py                                                   90%  
inspire/dojson/hep/fields/bd25x28x.py                                                   92%   
inspire/dojson/hep/fields/bd3xx.py                                                        100%
inspire/dojson/hep/fields/bd4xx.py                                                        100%
inspire/dojson/hep/fields/bd5xx.py                                                         97%  
inspire/dojson/hep/fields/bd6xx.py                                                        100%
inspire/dojson/hep/fields/bd70x75x.py                                                   88%   
inspire/dojson/hep/fields/bd76x78x.py                                                   100%
inspire/dojson/hep/fields/bd84188x.py                                                   87%   
inspire/dojson/hep/fields/bd90x99x.py                                                   100%
```
