### ISSUE TITLE
autor normalization: concatenated initials

### ISSUE THREAD

**Issue by annetteholtkamp** [inspirehep/inspire-next#2662]
## Expected Behavior
A name with concatenated capital initials like "Fitzakerley, DW" should be converted to
"Fitzakerley, D.W."
ex: https://inspirehep.net/record/1488707

This conversion should only happen, if the family name is not all caps since we may encounter Chinese names like "SHI, YU"

## Context
Currently, cataloguers have to change this manually which is painful for long author lists and may easily be overlooked. In the current system I believe this may generate  superfluous new author profiles.

**Comment by kaplun** [comment]
Is this happening in general (hence to be added to the workflow) or is only within certain sources (e.g. arXiv) (hence to be fixed in a crawler?)

**Comment by jacquerie** [comment]
This issue was moved to inspirehep/inspire-schemas#221
