### ISSUE TITLE
records: what is the intention behind match_valid_experiments?

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-next#2683]
[`match_valid_experiments`](https://github.com/inspirehep/inspire-next/blob/dfa9d1f1fe9bcf8c02a8ff3884bc9a6a468c33d7/inspirehep/modules/records/receivers.py#L109-L132) normalizes at indexing time the experiment names contained in Literature records.

This looks weird: if the system contains bad data we should fix that, rather than sweep the problem under the rug. I wonder what is the actual need behind it, so that we can build a solution that helps fixing the data.

CC: @michamos

**Comment by michamos** [comment]
@jmartinm maybe you remember why you wrote that thing in https://github.com/inspirehep/inspire-next/commit/f3d158d211733cf6a33c5860f94d0d108d3e867d? I agree that in principle, this should be done at ingestion time: the data in the records should be as clean as possible.

**Comment by jacquerie** [comment]
Fixed in https://github.com/inspirehep/inspire-next/pull/2766.
