### ISSUE TITLE
541__e is populated differently between hepcrawl and submissions

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#2687]
## Expected Behavior
I'd expect that the field `541__e` sent to legacy would contain the ID of the holding pen entry that I can add to: `http://labs.inspirehep.net/holdingpen/XXX` in order to access the entry.

E.g.

```xml
<datafield tag="541" ind1=" " ind2=" ">
<subfield code="a">orcid:0000-0002-9075-015X</subfield>
<subfield code="b">fischler@zippy.ph.utexas.edu</subfield>
<subfield code="c">submission</subfield>
<subfield code="d">2017-08-28T23:43:50.572572</subfield>
<subfield code="e">708757</subfield>
</datafield>
```

->  https://labs.inspirehep.net/holdingpen/708757

## Current Behavior
In the case of `hepcrawl` here's what is stored instead:

```xml
<datafield tag="541" ind1=" " ind2=" ">
<subfield code="a">arXiv</subfield>
<subfield code="c">hepcrawl</subfield>
<subfield code="e">ac5c1012821e11e7887e02163e010a0e</subfield>
<subfield code="d">2017-08-16T03:03:41.606022</subfield>
</datafield>
```

**Comment by jacquerie** [comment]
So `hepcrawl` is calling `add_acquisition_source` with some weird parameter (and that's a bug in `hepcrawl`), but it can't possibly know at that time the holdingpen entry id, so it must be added later by the worfklow (and that's the enhancement to do here).
