### ISSUE TITLE
Inspirehep JSON merger: GUI

### ISSUE THREAD

**Issue by ksachs** [inspirehep/inspire-next#2696]
## Expected Behavior
Conflicting information can arise when merging records. This has to be solved manually.
Information from both records has to be presented to a cataloger with the possibility to select the information from one or the other. The possibility to modify the resulting record manually is an advantage. At least one record is already in INSPIRE. The other record can be 

- an other INSPIRE record
- an incoming merge, e.g. journal version of the preprint
- update from the same source

## Current Behavior
Currently there are 2 tools: 
- BibMerge to merge 2 records in INSPIRE
- BibEdit with the possibility to merge a record from the (old) holdingpen to an INSPIRE record (see screenshot)

## Context
To merge incoming journal versions with the existing arxiv record,  DESY relies heavily on the merge GUI in BibEdit. This feature is essential.

## Screenshots (if appropriate):
![bibedit_merge](https://user-images.githubusercontent.com/7591594/29871021-8ab81768-8d8a-11e7-9a0c-912ae19f4c26.png)

**Comment by jacquerie** [comment]
The backend part was done in https://github.com/inspirehep/inspire-next/pull/3005, the frontend was done by @harunurhan in some PR of which I don't know the number, but now it would be a good idea to move from the `dev` branch to `master`...

**Comment by harunurhan** [comment]
We have UI, which is similar to this one in a way now and support is released with `ng2-json-editor` months ago, now it is available on the official release of `record-editor` when you edit a workflow object.
