### ISSUE TITLE
Search button bug

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspire-next#2698]
You can't search by clicking on the Search button (in orange below) but clicking Enter works

![ellis](https://user-images.githubusercontent.com/24955201/29923188-dcedadda-8e58-11e7-8477-270d98b7735f.PNG)

**Comment by StellaCh** [comment]
@Dinika @jmartinm what's blocking this from deploying it?

**Comment by Dinika** [comment]
PR [#41](https://github.com/inspirehep/inspirehep-search-js/pull/41) in inspirehep-search fixes this issue. It's merged but maybe, it isn't deployed yet.
