### ISSUE TITLE
Cite selected records

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspire-next#2699]
When you click on 'Cite all selected records' and have selected only 2 from the list, it returns citations for all documents in the list and not just of the 2 selected:

 ![cite](https://user-images.githubusercontent.com/24955201/29923287-471e2680-8e59-11e7-9033-1208ce3667e0.PNG)

**Comment by jacquerie** [comment]
CC @jmartinm: I'd wager that this is the same bug that was happening in the Holdingpen (https://github.com/inspirehep/inspire-next/issues/2579)

**Comment by jmartinm** [comment]
Actually the problem is with the search configuration. The frontend performs the request: `control_number:123 or control_number:567` and all records are being returned (instead of the expected 2). See https://github.com/inspirehep/inspire-next/issues/2829
