### ISSUE TITLE
Wrong citation numbers

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspire-next#2700]
In the document's detailed page, eg: https://labs.inspirehep.net/literature/882793 , the number of citations in References and Citations is always 0
![numb](https://user-images.githubusercontent.com/24955201/29923467-eeb8431c-8e59-11e7-8180-838720132643.PNG)

**Comment by jacquerie** [comment]
This is because `inspirehep migrator count_citations` was never run on Labs, so no citation counts were computed. If instead you visit Nightly, where that command was run, this works as it should: http://inspire-nightly.cern.ch/literature/882793.

**Comment by jacquerie** [comment]
(That is, this is not a frontend bug, so it doesn't belong to this milestone.)
