### ISSUE TITLE
support jsonschema handler

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#273]
inveniosoftware/invenio-jsonschemas#1 implements `jsonschema-registry`. Would be cool to:
* [x] have our overlay depending on it
* [x] make our JSONSchemas available to the registry and hence downloadable. (see inveniosoftware/invenio-jsonschemas#2)

**Comment by jmartinm** [comment]
Done here https://github.com/inspirehep/inspire-next/commit/28c83e20c63f002c3a0856a5e43b5560fd144b99
