### ISSUE TITLE
workflows: remove old harvesting code

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-next#2758]
There are some code leftovers that were used for harvesting before we had hepcrawl, specifically the receiver here:
    https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/workflows/receivers.py

And the related code it uses (`inspirehep.modules.converter.xslt`) that will probably not needed anymore either.

**Comment by david-caro** [comment]
@michamos This is what we just talked about :)

**Comment by jacquerie** [comment]
> And the related code it uses (inspirehep.modules.converter.xslt) that will probably not needed anymore either.

That guy is still used here: https://github.com/inspirehep/inspire-next/blob/bd599c78741fb88fbaaf8eb0ea1113731e7bcc54/inspirehep/modules/workflows/tasks/arxiv.py#L208-L216 (but the converter module shouldn't exist anyway).

**Comment by jacquerie** [comment]
So in fact everything that is left to do here is https://github.com/inspirehep/inspire-next/issues/2259.
