### ISSUE TITLE
Elasticsearch mapping for HEP records

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-next#276]
Currently the [Elasticsearch mapping](https://github.com/inveniosoftware/invenio/blob/002a46d048c0faeac32383b2a94658a9226ac297/invenio/ext/es.py) is taken from Invenio; we are still missing a mechanism to allow for its override at the overlay level, but (I think) this will eventually be solved upstream. 

In any case, here I'll note a few modifications that we are going to need:

- [x] DOIs should not be analyzed:
```JSON
"doi": {
    "type": "object",
        "properties": {
            "doi": {
                "type": "string",
                "index": "not_analyzed"
            }
    }
}
```

(This of course is strongly tied to the data models developed in #265)

**Comment by jmartinm** [comment]
Just fyi, I developed a WIP PR that will allow this sort of configuration, still pending review and merge:

https://github.com/inveniosoftware/invenio-search/pull/2

**Comment by kaplun** [comment]
Is this still uptodate? I think we need to create better a generic issue where to collect all search related issues.

**Comment by jmartinm** [comment]
Yes, we can close this one. The doi mapping is not yet correctly added in our `hep.json` though. Will create a PR.

**Comment by jmartinm** [comment]
This should address the point mentioned by @jacquerie https://github.com/inspirehep/inspire-next/pull/635

**Comment by jmartinm** [comment]
I tested it locally with success :)

**Comment by kaplun** [comment]
So you mean it's solved and we can close?

**Comment by kaplun** [comment]
You could have just said yes.

**Comment by kaplun** [comment]
:stuck_out_tongue:

**Comment by jmartinm** [comment]
No time to write :P
