### ISSUE TITLE
Holdingpen: KeyError

### ISSUE THREAD

**Issue by ksachs** [inspirehep/inspire-next#2768]
See [https://labs.inspirehep.net/api/holdingpen/715549]
seems as if something went wrong with the workflow. 

It has a extra_data._action._error_msg:
File \"/opt/inspire/lib/python2.7/site-packages/invenio_records_files/api.py\", line 164, in __getitem__    raise KeyError(key) KeyError: '1707.03461.tar.gz

However the record was not in state 'error' but 'Record ingestion complete.' 

I rejected the record in the holdingpen.
The status of the corresponding RT ticket [https://inspirert.cern.ch/Ticket/Display.html?id=745995]
does not change and there is no email to the requestor.

**Comment by StellaCh** [comment]
Has this been resolved @david-caro ?

**Comment by david-caro** [comment]
Nop, not really, not sure if it can be debugged now either :/

So far all that I can see is that it should have replied the ticket (and closed it) as it ran the actual tasks:
```
      {
        "doc": "Reply to a ticket for the submission.", 
        "name": "reply_ticket", 
        "nicename": "Reply to a ticket for the submission.", 
        "parameters": [], 
        "time": "2017-09-05 20:44:02.154784"
      }, 
      {
        "doc": "IF: args(<function is_submission at 0x4eb7ed8>, [<function close_ticket at 0x6627398>]); kwargs().", 
        "name": "IF", 
        "nicename": "IF", 
        "parameters": [], 
        "time": "2017-09-05 20:44:02.155087"
      }, 
      {
        "doc": "Close the ticket associated with this record found in given key.", 
        "name": "close_ticket", 
        "nicename": "Close the ticket associated with this record found in given key.", 
        "parameters": [], 
        "time": "2017-09-05 20:44:02.362531"
      }
```
So the problem might have been in the communication with RT or on RT itself. We did some changes to that code not long ago to improve it, so it has changed.

About the error message, most probably the workflow was 'resumed' or 'skipped' the step once it failed, as any part of the code that does set the `_error_msg` also sets the status to `ERROR`, but the `_error_msg` is not unset when restarted (helps debugging).

Most probably it was 'skipped' at this point:
```
      {
        "doc": "Extract authors from any author XML found in the arXiv archive.\n\n    :param obj: Workflow Object to process\n    :param eng: Workflow Engine processing the object\n    ", 
        "name": "arxiv_author_list", 
        "nicename": "Extract authors from any author XML found in the arXiv archive.", 
        "parameters": [], 
        "time": "2017-09-05 20:39:54.555404"
      }, 
      {
        "doc": "IF: args(<function is_submission at 0x6463ed8>, [<function submission_fulltext_download at 0x6466050>, <function refextract at 0x64661b8>]); kwargs().", 
        "name": "IF", 
        "nicename": "IF", 
        "parameters": [], 
        "time": "2017-09-05 20:43:52.964802"
      }, 
```

In the `arxiv_authors_list` task. But we don't have the audit log yet so there's no trace of who/how was that done :/

**Comment by david-caro** [comment]
But there are no new issues like this, so I think we can consider it solved. We are improving a lot and quickly the files handling on the workflows, so this kind of issues will become less and less frequent.
