### ISSUE TITLE
Holdingpen: UI for merger

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspire-next#2769]
On the separate holdingpen card that Antonio created for the merger, add the button 'Resolve Conflicts':
<img width="611" alt="screen shot 2017-09-20 at 10 08 29" src="https://user-images.githubusercontent.com/24955201/30633308-7cf9009e-9deb-11e7-8d9b-db1bd18aa71a.png">

Use the same fa-bolt class that is used for conflicts in the record editor

**Comment by michamos** [comment]
I would suggest something more explicit, like "Resolve conflicts".

**Comment by StellaCh** [comment]
Good point, agreed.

**Comment by StellaCh** [comment]
resolved in https://github.com/inspirehep/inspirehep-search-js/pull/43
