### ISSUE TITLE
Implementation of matching module for ingestion workflows

### ISSUE THREAD

**Issue by jalavik** [inspirehep/inspire-next#277]
We need a module or facility (for example, invenio-matcher via search engine extensions) that will provide an API to perform weighted, configurable searches on INSPIRE records to determine if the incoming record is already in INSPIRE or not.

See https://github.com/inveniosoftware/invenio/issues/2886 for more details.

This will probably be heavily dependant on #276 as well.

TODO: List INSPIRE specific use cases.

@fschwenn @jacquerie @kaplun

**Comment by kaplun** [comment]
(sorry @jstypka for the spam)

@jalavik you are currently working on porting this to Invenio3 right?

**Comment by jalavik** [comment]
@kaplun Yes, done here https://github.com/inspirehep/invenio-matcher/pull/11 Just need to address some minor comments and it is mergable.

**Comment by kaplun** [comment]
Great! I was doing a bit of ticket clean up :)

**Comment by david-caro** [comment]
Isn't this the same as #406?

**Comment by kaplun** [comment]
Nope: this is about the creation of the invenio-component, while #406 is about the usage of ditto invenio-component within the workflow.

**Comment by david-caro** [comment]
hmmm.... I can't add the :+1: to the message itself.

**Comment by kaplun** [comment]
The actual question is: can this module be used in order to implement the complex workflow that emerged during the inspire-week? https://docs.google.com/document/d/1zMCjUAPaa4ixK7dRhQN_m-W8uV9yqH9-I90LQtUR2ck/edit?usp=sharing

**Comment by kaplun** [comment]
> hmmm.... I can't add the ￼:+1: to the message itself.

Maybe it's your Javascript blocker? :dancer:

**Comment by david-caro** [comment]
haha! I will check :)

**Comment by david-caro** [comment]
No, it's not 😢

**Comment by StellaCh** [comment]
What's the status of this @jacquerie @david-caro ?

**Comment by david-caro** [comment]
This is already done I think, at least, as minimal starting point. This would be the matcher (both strict and fuzzy matching). I'll let @jacquerie reply with any info on he's side before closing.

**Comment by jacquerie** [comment]
This is https://github.com/inspirehep/inspire-matcher.
