### ISSUE TITLE
hal: export all INSPIRE categories

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-next#2774]
## Expected Behavior
Reported by @mathieugrives:
> I spotted an issue when 2 or more domains are present in a Inspire record : only the 1st one is exported to HAL [(example)](https://hal.archives-ouvertes.fr/hal-01584704) ; all domains should be sent

## Current Behavior
The code is (by design) converting only the first one: https://github.com/inspirehep/inspire-next/blob/7768a786d803900a3594d130ef45c504ec120362/inspirehep/modules/hal/utils.py#L284-L305

The fix is really easy.

**Comment by mathieugrives** [comment]
Thanks! Could you also quickly check if there could possibly be the same
problem with multiple collaborations or experiments. Don't have examples to
see if it is already working well, sorry.

Mathieu Grivès
CNRS - IN2P3

2017-09-21 10:31 GMT+02:00 Jacopo Notarstefano <notifications@github.com>:

**Comment by jacquerie** [comment]
> Could you also quickly check if there could possibly be the same
> problem with multiple collaborations or experiments.

No, we don't have the same problem there. Here's the code:
https://github.com/inspirehep/inspire-next/blob/7768a786d803900a3594d130ef45c504ec120362/inspirehep/modules/hal/utils.py#L94-L109

Note how it returns a list of all possible collaborations. The template will then take this list and create one `<org/>` entry per collaboration. So we are good there :+1:
