### ISSUE TITLE
workflows: process all author XML files

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspire-next#2800]
## Expected Behavior

Sometimes there are two XML author list files in an arXiv submission (e.g. https://inspirehep.net/record/1623908/ ). In that case, all authors should be processed by https://github.com/inspirehep/inspire-next/blob/c780ed7ad6f0ac10358f46b771a39cd0eda12d92/inspirehep/modules/workflows/tasks/arxiv.py#L175-L222 instead of only the authors from one of the lists.

## Current Behavior

Only the authors from one of the list are processed.

## Steps to Reproduce (for bugs)

1. run the task on the given arXiv record
2. see that ~half the authors are missing.

**Comment by michamos** [comment]
BTW, it's quite dangerous to update the current record with the one from the authorlist, as that might overwrite other fields that are set by default, better to replace `authors` only.

**Comment by david-caro** [comment]
This is very similar to a fix I'm doing for QA, I'm fixing this too in the same PR
