### ISSUE TITLE
api: endpoint to run json-merger on 2 records

### ISSUE THREAD

**Issue by harunurhan** [inspirehep/inspire-next#2813]
We have a requirement in the editor that we need an api endpoint to run `json-merger` on 2 records.

Ref: https://github.com/inspirehep/record-editor/issues/227

**Comment by harunurhan** [comment]
So we seem to need an endpoint that will takes 2 record ids and returns a workflow object id.

The workflow object here will be created from merging 2 records and it will have also conflicts inside.

**Comment by jacquerie** [comment]
Done in https://github.com/inspirehep/inspire-next/pull/3005.
