### ISSUE TITLE
Use MathJax CDN

### ISSUE THREAD

**Issue by jalavik** [inspirehep/inspire-next#283]
We should use the MathJax CDN to avoid moving around 40k static files.

Include on page:
```html
<script src="//cdnjs.cloudflare.com/ajax/libs/mathjax/2.5.3/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
```

On document load:
```javascript
MathJax.Hub.Config({
    tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}
});
MathJax.Hub.Queue(["Typeset", MathJax.Hub]);
```

**Comment by kaplun** [comment]
Isnt't this part of Invenio out of the box?

**Comment by jalavik** [comment]
MathJax? I guess it is, but we can override the static files to not include it in the bundles.

**Comment by jmartinm** [comment]
So far I have removed it from our dependencies so we don't load it anymore a38db73e79d24c0f4fd029e5299c6aa1469c03e5

Now it just needs to be added in the appropriate templates to load from CDN.
