### ISSUE TITLE
Eprint category in upper case bug

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspire-next#2848]
## Current Behavior
The query "find eprint HEP-LAT/0201006" doesn't return any results. However, when the field is unfocused, the search becomes lower case "find eprint hep-lat/0201006" and when we try to search again with lowercase, it works. The query should return the same results when the eprint category is uppercase.

**Comment by jacquerie** [comment]
Right, we need to do https://github.com/inspirehep/inspire-next/pull/2845/commits/45b32334fefd7205afa9b521830dcc33b99f7fed as well for `arxiv_eprints.value.raw`, because the normalization has to happen at search time too.
