### ISSUE TITLE
Literature records: exclude 'references' field from '_all' field

### ISSUE THREAD

**Issue by iulianav** [inspirehep/inspire-next#2857]
## Expected Behavior

When searching for an author's name in the Literature collection, only records whose authors match should be returned and the referenced authors matches should be ignored.

## Current Behavior

When searching for an author's name in the Literature collection, records that reference that author are returned too.

## Steps to Reproduce (for bugs)

1. Click https://labs.inspirehep.net/search?page=1&size=25&q=ellis,%20john
2. Notice the large number of (irelevant) results

## Context

The 'references' field must be excluded from the '_all' field in the case of Literature collection records because  many matches occur in the references when searching for an author's name, and not int the actual authors.

## Screenshots (if appropriate):
![references](https://user-images.githubusercontent.com/20461142/31447902-66741232-aea3-11e7-8358-7ba27525f6dc.png)

**Comment by iulianav** [comment]
@jacquerie am I right ?

**Comment by jacquerie** [comment]
Done in https://github.com/inspirehep/inspire-next/pull/2856.
