### ISSUE TITLE
workflows: normalize journal title

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspire-next#2862]
## Expected Behavior

The `publication_info.journal_title` should be normalized by the workflow to match the `short_title` of the journal. The fields that should be considered for this are the same as for `refextract`: https://github.com/inspirehep/inspire-next/blob/67ff20df8c6ed9abb6a7d59a6a7c536d2610a925/inspirehep/modules/refextract/tasks.py#L56-L74. Also the `journal_record` field could then be populated based on the record ref of the matched journal record.

## Current Behavior

A partial implementation exists in https://github.com/inspirehep/inspire-next/blob/67ff20df8c6ed9abb6a7d59a6a7c536d2610a925/inspirehep/utils/normalizers.py#L30-L44, but uses ES whereas refextract uses the DB directly. @jacquerie wanted to use the latter, he can comment on the reasons. However it is used in `literaturesuggest` only: https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/literaturesuggest/normalizers.py#L117. It should be moved to the workfows so that it runs also for hepcrawl harvests.

## Context

This is needed if we want to obtain the correct journal titles for the hepcrawl harvests.

**Comment by iulianav** [comment]
@michamos does the `journal_record` field exist at the moment?

**Comment by ammirate** [comment]
Closed by #2938.
