### ISSUE TITLE
pub info for books in journal field

### ISSUE THREAD

**Issue by annetteholtkamp** [inspirehep/inspire-next#2864]
## Expected Behavior
The publication info for books should appear in the 260 field

## Current Behavior
Lots of older books have their pub info in 773__x, usually in the form
773__x:Cambridge, Uk: Univ. Pr. ( 1985) 376p
Sometimes series info appears in parentheses at the end, e.g.
Berlin, Germany: Suhrkamp (2012) 481 p, (Suhrkamp Taschenbuch Wissenschaft 2033)

## Steps to Reproduce (for bugs)
tc b and not 260__b:** and 773__x:** and not 773__p:**
https://inspirehep.net/search?wl=0&ln=en&p=tc+b+and+not+260__b%3A**+and+773__x%3A**+and+not+773__p%3A**&of=hb&action_search=Search&sf=earliestdate&so=d&rm=&rg=250&sc=0

## Context
Results e.g. in wrong bibtex entries.
It should be checked whether the info in 773__x is already present in 260, 300 and 490

**Comment by michamos** [comment]
This issue was moved to inspirehep/inspire-dojson#120
