### ISSUE TITLE
submission form: journal autocomplete - show more than 5

### ISSUE THREAD

**Issue by annetteholtkamp** [inspirehep/inspire-next#2866]
## Expected Behavior
The journal autocomplete should show more than 5 candidates.

## Current Behavior
Currently only 5 suggestions are shown. E.g. trying Philosophical Magazine shows 5 entries of the form Phil.Mag.Ser.x but Phil.Mag. is not shown - and cannot be made to appear by typing a lengthier string.

## Context
One has to consult the journal db to find the correct form.

**Comment by jacquerie** [comment]
I tested manually on a local dump of the Journals database that @iulianav's PR fixes this issue, in particular that typing "Philosophical Magazine" will show "Phil.Mag.". It will be deployed soon!
