### ISSUE TITLE
Submissions don't attach files

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#2873]
Looks like submission are not properly attaching files. E.g. see: https://labs.inspirehep.net/api/holdingpen/755762 where `_files` is empty, while `documents` sports the non-existing `/api/files/77a26236-e863-4915-9e95-a3d1419163bf/fulltext.pdf` URL.

**Comment by kaplun** [comment]
cc: @zzacharo @michamos @ammirate

**Comment by kaplun** [comment]
This is super-urgent because it affects very visible user submission workflow that currently are piling up in the legacy queue and need to be fixed one by one by hand...

**Comment by michamos** [comment]
closed by #2875.
