### ISSUE TITLE
handle the journal split in extract_journal_info

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspire-next#2936]
## Expected Behavior

The `extract_journal_info` workflow step https://github.com/inspirehep/inspire-next/blob/9d9ecfe0dee3ddbacb2e478b7ae197cb010e9dc1/inspirehep/modules/workflows/tasks/refextract.py#L46-L90 correctly puts the volume letter in the `journal_title`.
## Current Behavior

It still uses the old scheme where the journal letter is put in the `volume`.

**Comment by jacquerie** [comment]
Started working on this in https://github.com/jacquerie/inspire-next/tree/fix-extract_journal_info, I will probably finish it on the train (if I don't fall asleep...)
