### ISSUE TITLE
dojson: wrong DOI mapping

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#295]
In the DOI rule https://github.com/inspirehep/inspire-next/blob/master/inspire/dojson/hep/fields/bd01x09x.py#L55 we are adding as a `doi` key any value that comes in the field `024`.

```python
@hep.over('doi', '^024[1032478_][10_]')
@utils.for_each_value
@utils.filter_values
def doi(self, key, value):
    """Other Standard Identifier."""
    return {
        'doi': value.get('a')
    }
```

Problem is that 024 field is reused for other identifiers that are not DOIs.

To solve this we should only add in the `doi` key values that contain `$$2DOI`

```python
@hep.over('doi', '^024[1032478_][10_]')
@utils.for_each_value
@utils.filter_values
def doi(self, key, value):
    """Other Standard Identifier."""
    if value.get("2").lower() == "doi":
        return {
            'doi': value.get('a')
        }
```

Then we will have to add in their appropriate keys the rest of the identifiers found in `024`.

**Comment by jmartinm** [comment]
ping @ioannistsanaktsidis can you have a look?

**Comment by ioannistsanaktsidis** [comment]
Yes of course, I will take care tomorrow morning ;-)
Στις 8 Οκτ 2015 11:32 π.μ., ο χρήστης "Javier Martin Montull" <
notifications@github.com> έγραψε:

**Comment by ioannistsanaktsidis** [comment]
@jmartinm  this one is fixed, so I guess we can close it. ;)
