### ISSUE TITLE
inexistent author page does not return 404 status

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#2977]
@michamos commented on [Fri Dec 16 2016](https://github.com/inspirehep/inspire/issues/249)

e.g. https://inspirehep.net/author/O.W.Kenobi.1 redirects to https://inspirehep.net/author/search?q=O.W.Kenobi.1 instead of having a 404 status.

I noticed this because a link from wikipedia to INSPIRE was broken, and wikipedia has bots monitoring broken links, which this "feature" prevents.

---

@tsgit commented on [Fri Dec 16 2016](https://github.com/inspirehep/inspire/issues/249#issuecomment-267648899)

I'd say wontfix

---

@jacquerie commented on [Sat Dec 17 2016](https://github.com/inspirehep/inspire/issues/249#issuecomment-267792091)

I like this. Can you open this on `inspire-next`, please?

---

@tsgit commented on [Tue Dec 20 2016](https://github.com/inspirehep/inspire/issues/249#issuecomment-268115916)

from a user perspective, do you rather see a `404` or a search results page with potentially useful info -- or at least an entry point for further searching ? I think the current behavior is user friendly, maybe not robot friendly. for some links Inspire distinguishes based on `User-Agent` whether to return a bad `HTTP Status` or a page

---

@michamos commented on [Tue Dec 20 2016](https://github.com/inspirehep/inspire/issues/249#issuecomment-268181994)

We could have both, like  [Github does](https://github.com/inspirehep/nonexistent), a 404 status with a search bar on the error page.

**Comment by jacquerie** [comment]
We now do, thanks to @eamonnmag's work.
```shell
$ http --headers https://labs.inspirehep.net/authors/does-not-exist

HTTP/1.1 404 NOT FOUND
Content-Encoding: gzip
Content-Type: text/html; charset=utf-8
Date: Wed, 22 Nov 2017 15:52:41 GMT
Server: nginx/1.12.2
Set-Cookie: session=b4e38829f3e01da8_5a159d49.nM9K7QXRdn5GoJrxYAMLC9DJwqk; Domain=.labs.inspirehep.net; Expires=Sat, 23-Dec-2017 15:52:41 GMT; HttpOnly; Path=/
Transfer-Encoding: chunked
Vary: Accept-Encoding
```
