### ISSUE TITLE
Cloning of reference/citation

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#298]
We should keep synchronized the citation tables between old production and labs in order to be able to search based on citation/reference.

That means, when sending records to elasticsearch for indexing we should be smart and enhance them using the citation table

**Comment by jmartinm** [comment]
Is there a preference on going for this idea or on porting existing refextract/bibrank and running it locally on Labs ?

**Comment by kaplun** [comment]
Refextract maybe. BibRank on labs nope, that is not feasible, I think. I was talking today with @nharraud and we found several ways in which to have elasticsearch digest citations and let us build again the citedby/refersto functionality.

**Comment by kaplun** [comment]
This is superseeded by #621
