### ISSUE TITLE
Deploying a beard server

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#300]
A new server (similar to elasticsearch deployment) needs to be deployed to serve the beard REST interface (see: https://github.com/inspirehep/beard-server)

**Comment by kaplun** [comment]
@jalavik as soon as we can we should start playing with this part of the beast :smile:

**Comment by jalavik** [comment]
@kaplun So we need one single node to serve beard requests? How powerful?

**Comment by kaplun** [comment]
Yep beard is not going to profit (yet?) from a multinode architecture, as far as I understand (@MSusik, @glouppe?).

In fact we already have all that is needed (the inspire-heavy nodes), 32GB of ram. We need just to puppetize them accordingly.

**Comment by glouppe** [comment]
Yes, no need to add complexity with multiple machines. Just provision a single machine with plenty of RAM and cores.

**Comment by jalavik** [comment]
`inspire-heavy` is a hep2.8 flavour with RAM 15GB, 8 VCPU. What about the inspire-ml-* nodes, are they appropriate candidates for this?

**Comment by kaplun** [comment]
Yep I was referring to them :-) (sorry for misunderstanding...) They are leaving in the INSPIRE Heavy openstack space.

**Comment by glouppe** [comment]
Yes, the `inspire-ml-*` are good enough for disambiguating everything without too many problems.

**Comment by jacenkow** [comment]
@kaplun can we close this issue?

**Comment by kaplun** [comment]
Well, are the machines correctly puppetized in terms of firewall, in particular? In particular we need to open celery and http ports

**Comment by jacenkow** [comment]
Oh yeah, still to do a back-up of `/home`. Regarding ports `Celery`, `HTTP` and maybe `Flower`? For this moment I am using on `inspire-ml-01` `RabbitMQ` as well.

**Comment by jacenkow** [comment]
@kaplun seems we can close this one.

**Comment by kaplun** [comment]
:+1:
