### ISSUE TITLE
Missing information in a paper

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspire-next#3053]
https://labs.inspirehep.net/literature/1299183 

## Screenshots (if appropriate):
![frontend bug](https://user-images.githubusercontent.com/24955201/33932055-3325134c-dff2-11e7-9723-12bb5e8e85fa.PNG)

1. Hide 'View in' if there are no links
2. How do we see the authors of the paper? There's no link to show all authors in the page

**Comment by jacquerie** [comment]
@Dinika should have already fixed 1. in https://github.com/inspirehep/inspire-next/pull/3026.

**Comment by Dinika** [comment]
Yep. 1. was indeed fixed in #3026 
and #3057 fixes 2.
