### ISSUE TITLE
Port author addition/update forms

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#308]
Connected to https://github.com/inspirehep/inspire-next/issues/266. Once we get the author model converted to `dojson` we need to port the author forms to use it.

Mainly the change has to happen in the [conversion from the form fields to the expected author model](https://github.com/inspirehep/inspire-next/blob/master/inspire/modules/authors/tasks.py#L64) (so that the right MarcXML is produced on the output).

Also, all autocomplete fields have to be double checked to be working with ElasticSearch.

**Comment by kaplun** [comment]
Shoudln't this go into enabling authors milestone?

**Comment by jmartinm** [comment]
Nope, this is just to replicate the functionality we have at the moment in labs.inspirehep.net with the author update/addition form.

We are not able to deploy the elasticsearch branch if this is not working.

**Comment by jmartinm** [comment]
Done https://github.com/inspirehep/inspire-next/commit/889436bc1b222512fa4559498ff3897941bdf61e
