### ISSUE TITLE
holdingpen: no title - no link to detailed view

### ISSUE THREAD

**Issue by ksachs** [inspirehep/inspire-next#3111]
https://labs.inspirehep.net/holdingpen/855695
is a record without title

## Expected Behavior
There should be a way to get to the detailed view from the holdingpen list
https://labs.inspirehep.net/holdingpen/list/?page=1&size=10&source=submitter&workflow_name=HEP&status=HALTED

## Current Behavior
The title is the only link (afaik), so there is no link for this record to the detailed page

## Context
Some information is not available in the list, e.g. type of publication / journal / arXiv
So I need the detailed view.

## Screenshots (if appropriate):
![holdingpen_notitle](https://user-images.githubusercontent.com/7591594/34940650-a15c16b8-f9f0-11e7-83d1-442996caa362.png)

**Comment by david-caro** [comment]
Duplicated of https://github.com/inspirehep/inspire-next/issues/3109
