### ISSUE TITLE
workflows: deleted inspire categories shouldn't reappear in updates

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspire-next#3124]
## Expected Behavior

Inspire categories should not be changed by automatic updates when harvesting the arXiv update.
A category derived automatically from an arXiv category and manually deleted shouldn't reappear .
A category manually added shouldn't be deleted. 

## Current Behavior

All arXiv categories in the update are converted to inspire categories, so previously deleted categories reappear. There is no way to prevent this.

**Comment by michamos** [comment]
@ksachs I hope this is a faithful translation of the issue you raised by email. If not please edit it or reply with a correction.

The problem is actually worse than you mention: currently, updates to arXiv preprints that fall in the 30 day window after the first version was created are sent to legacy as `correct`, so potentially overwriting curator work. This is a terrible bug that was caused by increasing the window for accepting arXiv harvests from 5 days to 30 days (see https://github.com/inspirehep/inspire-next/issues/2524#issuecomment-339677349 ). @ammirate interrupted his work to fix this before tomorrow's harvest, and we will try to find all affected records and revert them if curator work has been overwritten.

Once the merger is integrated (#2760), we will be able to handle updates correctly.

**Comment by ksachs** [comment]
what about stopping updates from labs completely until the merger is in place?

I assume legacy can handle the basic updates.
The rest was ignored the last years, so it doesn't matter if we ignore it a few weeks/month longer.

**Comment by ksachs** [comment]
I guess those updates could also wipe out information from journal harvest.

**Comment by michamos** [comment]
> what about stopping updates from labs completely until the merger is in place?

that's exactly what @ammirate is implementing.

> I guess those updates could also wipe out information from journal harvest.

wipe out no, the updates were done in `correct` mode, so they would overwrite MARC fields, but not erase existing MARC fields that were not in the arXiv metadata. This could happen on top of a journal harvest only if

1.the journal harvest occurred within the 30 day window after initial arXiv submission, and
2. there was an arXiv update after the journal harvest, still in the 30 day window.

Authors usually submit to the journals at the same time as to arXiv ar after and it takes more than a month for the article to go through the whole editorial process, so while definitely possible, it has probably not happened very often.

**Comment by michamos** [comment]
This should be fixed by #3126.
