### ISSUE TITLE
update record-editor ("Edit") links

### ISSUE THREAD

**Issue by harunurhan** [inspirehep/inspire-next#3132]
When merging [multi-editor](https://github.com/inspirehep/ng2-multi-record-editor) into [record-editor](https://github.com/inspirehep/record-editor), client side routing needed be changed. So now links to edit a single record `/editor/record/<record_type>/<record_id>` instead of `/editor/<record_type>/<record_id>`.

**Comment by michamos** [comment]
what about the holdingpen?

**Comment by harunurhan** [comment]
@michamos that one did not change.
