### ISSUE TITLE
holdingpen: physics.data-an rejected 

### ISSUE THREAD

**Issue by ksachs** [inspirehep/inspire-next#3187]
## Expected Behavior
primary category physics.data-an should be taken completely

## Current Behavior
e-Print: arXiv:1802.03636 [physics.data-an]  is not in INSPIRE

https://labs.inspirehep.net/api/holdingpen/893922
has
already-in-holding-pen | false
approved | false
auto-approved | true

I don't understand why the record didn't make it to INSPIRE

**Comment by david-caro** [comment]
@michamos can you confirm that the behavior in the proposed PR is correct?

**Comment by fschwenn** [comment]
same holds for cross-lists to hep*categories:
1802.04492
https://labs.inspirehep.net/holdingpen/896007
