### ISSUE TITLE
holdingpen: arxiv raw affiliations in wrong field

### ISSUE THREAD

**Issue by ksachs** [inspirehep/inspire-next#3193]
## Expected Behavior
sometimes there is affiliation information in the metadata coming from arXiv.
This should be written to 100/700__v
Only standardized institutions shall be written to 100/700__u.

## Current Behavior
Raw affiliations are written to 100/700__u

## Example 
[arXiv feed](http://export.arxiv.org/oai2?verb=GetRecord&identifier=oai:arXiv.org:1801.10471&metadataPrefix=arXiv) contains

    <author>
       <keyname>Telnov</keyname>
       <forenames>V. I.</forenames>
       <affiliation>Institute of Nuclear Physics and Novosibirsk State Univ., Novosibirsk, Russia</affiliation>
    </author>

-> holdingpen

        "authors": [
          {
            "affiliations": [
              {
                "value": "Institute of Nuclear Physics and Novosibirsk State Univ., Novosibirsk, Russia"
              }
            ], 
            "full_name": "Telnov, V.I."
          }
        ],

-> INSPIRE

    001651521 100__ $$aTelnov, V.I.$$uInstitute of Nuclear Physics and Novosibirsk State Univ., Novosibirsk, Russia

## Optional automatic translation (to be decided):
If the affiliation coming  from arXiv is a value in 110__u of an INST record we can write it in both 100/700 $$v and $$u. Example: 
https://inspirehep.net/record/1654921?ln=en

**Comment by michamos** [comment]
This is due to https://github.com/inspirehep/hepcrawl/issues/185

**Comment by jacquerie** [comment]
This will be fixed in the next deploy to production.
