### ISSUE TITLE
do not create RT tickets for arXiv updates

### ISSUE THREAD

**Issue by fschwenn** [inspirehep/inspire-next#3197]
The RT-ticket-generation for arXiv harvesting is still buggy.

## Expected Behavior
If a new CORE record is generated, a HEP curation ticket in RT should be created. If an updated version is available at arXiv not curation ticket should be generated.

## Current Behavior
Today a number of HEP curation ticket where generated in RT for already existing INSPIRE records, e.g. 

800247 | arXiv:1712.10180
800249 | arXiv:1709.00190
800250 | arXiv:1712.03526
800251 | arXiv:1711.01935

**Comment by michamos** [comment]
Indeed, tickets should not be created for record updates. A bigger problem though is that CORE records should not be updated from labs for the time being, as they might overwrite curated metadata.

**Comment by david-caro** [comment]
They are not, the update gets 'dropped' at the end of the workflow.

**Comment by fschwenn** [comment]
just for information: I removed ~600 RT-tickets  of that kind.

**Comment by fschwenn** [comment]
just for information: I removed another ~450 RT-tickets of that kind.

**Comment by fschwenn** [comment]
just for information: I removed another ~670 RT-tickets of that kind.

**Comment by michamos** [comment]
@fschwenn sorry for the work you have to do, the bug has been fixed by @drjova last week, but we are experiencing problems with deployment to labs, so the bug is still visible. Hopefully there will be a deploy soon.

**Comment by david-caro** [comment]
This is already deployed in production :), please reopen if you see it happening again (after right now I mean).
