### ISSUE TITLE
Set up HTTPS

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#326]
At the moment, when the user has to recover password or login, this is being done in plain text HTTP. This needs to be changed to be done with HTTPS.

**Comment by jmartinm** [comment]
Is this for inspire labs? To me it works always with https.

If we are going to start using github more actively, to have it under control we should be quite elaborate in title, body and start using labels?

**Comment by kaplun** [comment]
Eih eih are you trying to bossing me? :-P 
This is *clearly* an automatic ticket opened by my Zap from the Asana one. I think it corresponds to the message related to the help ticket...

Better if I stop this synchronization since it seems to copy comments out of context (even when the corresponding issue is closed on Asana)

**Comment by kaplun** [comment]
P.s.: https://app.asana.com/0/8772567966361/46688393970763

**Comment by jmartinm** [comment]
ah hehe, did not think about the Zap sync :P

Would be nice if it said somewhere in the description or comment (Synchronized from Asana or something like that)
