### ISSUE TITLE
prodsync working

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#327]
Depends on dojson models from https://github.com/inspirehep/inspire-next/issues/266

Production sync has to be working for records in all collections. This means reviewing that harvesting is still possible and making sure the dojson model is in place in order to get the appropriate JSON from the production MarcXML.

**Comment by jmartinm** [comment]
This was completed with a new workflow for harvesting. @jalavik can you add a pointer to the code that deals with this and we see if we can mark it as complete?

**Comment by jalavik** [comment]
Sure. The workflow is here https://github.com/inspirehep/inspire-next/blob/master/inspire/modules/workflows/workflows/oaiharvest_production_sync.py

And it is used by `inveniomanage oaiharvester` (either as periodical or one-shot command) to feed records from the OAI-PMH source to this workflow.
