### ISSUE TITLE
CitationAnalysis: unresolved arXiv citation

### ISSUE THREAD

**Issue by ksachs** [inspirehep/inspire-next#3272]
1245018,-350.0 cited by 365 records (ie. loosing all but 15). Why?

On legacy a typical citation looks like:
01262111 999C5 $$01245018$$hC. Adams et al.$$m[LBNE Collaboration]$$o6$$rarXiv:1307.7335 [hep-ex]

On the pdf the reference can be scarce
C. Adams et al. (LBNE) (2013), 1307.7335.

**Comment by ksachs** [comment]
obsolete

**Comment by jacquerie** [comment]
Sorry, didn't see this issue before.

The reason is that that record did not migrate successfully on Salman's machine. So only the curated citations are attributed to it, while all citations that require a search didn't match, because the target wasn't there.
