### ISSUE TITLE
CitationAnalysis: Phys.Rev.B

### ISSUE THREAD

**Issue by ksachs** [inspirehep/inspire-next#3323]
Why are these references not matched on labs?
I think there is a problem with Phys.Rev.B.
2 examples with other journal

    recid:27730    (Published, Citeable)
    Chiral Spin States and Superconductivity
    Wen, X.G. et.al
    10.1103/PhysRevB.39.11413
    NSF-ITP-88-179
    Phys.Rev. B39 11413-11423 (1989)
    Citations difference:236  legacy:274  labs:38
      999C5 $$027730$$sPhys.Rev.B39,11413

-

    recid:294554    (Published, Citeable)
    Chiral Luttinger Liquid and the Edge Excitations in the Fractional Quantum Hall States
    Wen, X.G.
    10.1103/PhysRevB.41.12838
    IASSNS-HEP-90-14
    Phys.Rev. B41 12838-12844 (1990)
    Citations difference:186  legacy:213  labs:29
      999C5 $$0294554$$sPhys.Rev.B41,12838

-

    recid:371076    (Published, Citeable)
    Density-matrix algorithms for quantum renormalization groups
    White, Steven R.
    10.1103/PhysRevB.48.10345
    Phys.Rev. B48 10345-10356 (1993)
    Citations difference:171  legacy:224  labs:53
      999C5 $$0371076$$sPhys.Rev.B48,10345

-

    recid:352046    (Published, Citeable)
    Transmission through barriers and resonant tunneling in an interacting one-dimensional electron gas
    Kane, C.L. et.al
    10.1103/PhysRevB.46.15233
    Phys.Rev. B46 15233-15262 (1992)
    Citations difference:164  legacy:182  labs:18
      999C5 $$0352046$$sPhys.Rev.B46,15233

-

    recid:370818    (Published, Citeable)
    Skyrmions and the crossover from the integer to fractional quantum Hall effect at small Zeeman energies
    Sondhi, S.L. et.al
    10.1103/PhysRevB.47.16419
    Phys.Rev. B47 16419-16426 (1993)
    Citations difference:134  legacy:148  labs:16
      999C5 $$0370818$$sPhys.Rev.B47,16419

-

    recid:294192    (Published, Citeable)
    Large-n limit of the Hubbard-Heisenberg model
    Marston, J.Brad et.al
    10.1103/PhysRevB.39.11538
    Phys.Rev. B39 11538-11558 (1989)
    Citations difference:110  legacy:121  labs:11
      999C5 $$0294192$$sPhys.Rev.B39,11538

-

    recid:391838    (Published, Citeable)
    Low-energy properties of fermions with singular interactions
    Altshuler, B.L. et.al
    10.1103/PhysRevB.50.14048
    Phys.Rev. B50 14048-14064 (1994)
    Citations difference:90  legacy:106  labs:16
      999C5 $$0391838$$sPhys.Rev.B50,14048

-

    recid:465674    (Published, Citeable)
    BCS to Bose crossover: Broken-symmetry state
    Engelbrecht, Jan R. et.al
    10.1103/PhysRevB.55.15153
    Phys.Rev. B55 15153-15156 (1997)
    Citations difference:87  legacy:97  labs:10
      999C5 $$0465674$$sPhys.Rev.B55,15153

-

    recid:813038    (Published, arXiv, Citeable, Fermilab)
    SEGUE: A Spectroscopic Survey of 240,000 stars with g=14-20
    SDSS-II SEGUE
    Yanny, Brian et.al
    10.1088/0004-6256/137/5/4377
    FERMILAB-PUB-09-103-A-CD, arXiv:0902.1781
    Astron.J. 137 4377-4399 (2009)
    Citations difference:194  legacy:224  labs:30
      999C5 $$0813038$$sAstron.J.137,4377

-

    recid:1654690    (Citeable)
    Instantons on ALE spaces, quiver varieties, and Kac-Moody algebras
    Nakajima, Hiraku
    10.1215/S0012-7094-94-07613-8
    Duke Math.J. 76 365-416 (1994)
    Citations difference:90  legacy:100  labs:10
      999C5 $$01654690$$sDuke Math.J.76,365

**Comment by salmanmaq** [comment]
Interesting catches. I didn't inspect all of these records, but the few I did, the issue seems to be due to the ambiguity between page_start and artid. Most of the records had page_start, while for references, it got parsed as the artid. However, coincidentally, this was fixed in a recent code update, so I'll close the issue.
