### ISSUE TITLE
HoldingPen: Workflow: adding subjects

### ISSUE THREAD

**Issue by ksachs** [inspirehep/inspire-next#3474]
Need input slot in detailed view, input via single letter;
final solution: on brief listing too.
Subject guesser would be nice; at DESY subject guessing via authors is in place.

Might be a bug when the list of subjects is empty.

**Comment by Dinika** [comment]
Fixed in [PR 87](https://github.com/inspirehep/inspirehep-search-js/pull/87) [PR 88](https://github.com/inspirehep/inspirehep-search-js/pull/87)

**Comment by Dinika** [comment]
Fixed in [PR 87](https://github.com/inspirehep/inspirehep-search-js/pull/87) and [PR 88](https://github.com/inspirehep/inspirehep-search-js/pull/87)

**Comment by Dinika** [comment]
Fixed in [PR 87](https://github.com/inspirehep/inspirehep-search-js/pull/87) [PR 88](https://github.com/inspirehep/inspirehep-search-js/pull/87)
