### ISSUE TITLE
HoldingPen: Workflow: halt for adding subjects

### ISSUE THREAD

**Issue by ksachs** [inspirehep/inspire-next#3475]
records without subjects should stay halted

**Comment by ksachs** [comment]
To make this more precise and more background.

First we decide which records will be rejected, usually from the list view. 
Based on the same information and in principle at the same time as rejecting articles we decide whether an article should be CORE or not and what is the subject. All these decisions are based on the content.

In the end every article in INSPIRE should have a subject.
To ensure this I see 2 possibilities:

- prevent upload to INSPIRE of articles without subject 
- catch articles without subjects in INSPIRE and put (a copy) back in the holdingpen

For the first possibility it might be enough to have the reject button of the bulk-action at the top of the list view active + display of the enrichment (core guesser, keywords, references, ...).
Accept would only be possible from the detailed view after the subject is added.
This might be a similar logic than preventing reject from the list view for author submissions.

The second possibility might be useful for other use-cases. E.g.
arXiv articles that are auto-accepted but are not automatically CORE (e.g. nucl-th) have to show in the holdingpen at some time to add the CORE tag if relevant, see #2657.
Currently this is done locally at DESY. Temporarily it would also be possible to add subjects via a scipt running locally at DESY.

**Comment by StellaCh** [comment]
This has been resolved by always showing the reject button (first possibility described below)
