### ISSUE TITLE
HoldingPen: merge conflicts for report numbers

### ISSUE THREAD

**Issue by ksachs** [inspirehep/inspire-next#3529]
Example: arXiv:1807.00620

https://labs.inspirehep.net/holdingpen/1110908 (harvested 2018-07-04)
is halted to resolve conflicts from report numbers.

The original harvest from 2018-07-03 has
https://labs.inspirehep.net/api/holdingpen/1108662

      "report_numbers": [
        {"source": "arXiv", "value": "MAD-TH-17-08"}, 
        {"source": "arXiv", "value": "IFT-UAM/CSIC-18-69"}
      ], 

INSPIRE has 

     001680493 037__ $$9arXiv:reportnumber$$aMAD-TH-17-08
     001680493 037__ $$9arXiv:reportnumber$$aIFT-UAM/CSIC-18-69
     001680493 037__ $$aMAD-TH-17-08
     001680493 037__ $$aIFT-UAM-CSIC-18-69

The halted record has only one report number and 6 conflicts
https://labs.inspirehep.net/api/holdingpen/1110908

      "report_numbers": [
         {"source": "arXiv", "value": "IFT-UAM/CSIC-18-69"}
      ], 

Something is wrong here.

I don't know how the original metadata of todays harvest looks like, but arXiv still has 2 report numbers. So the metadata from today (V2) should be identical to the harvest on labs yesterday (V1).

I would have assumed there is first a diff between V1 and V2.
If there is none, there is no need for merging.
If there are differences, there is a merge attempt only for those differences. 
But maybe the problem is somewhere else.

Depending on how many updates (same source, same ID) are halted due to merge-conflicts, we might need to distinguish between updates and merges (different sources (or different IDs)). 
Real merges have higher priority.

Btw: *if conflicts are not resolved will information that can be merged automatically be pushed to INSPIRE?*

## Another point with this record:
Can someone have a look at the resolved references:
the first record has 33/65 core, 34/65 matched
the second (incl. the merge from legacy I guess) has 44/65 core, 45/65 matched

## And a side-remark:
To check the metadata comming from arXiv I did a harvest as user-request on my local docker version (which might not behave like labs).
The received metadata did not include the report-numbers at all. 
*Can someone make sure report-numbers from arXiv are included in user-submissions?*

**Comment by StellaCh** [comment]
@michamos this looks similar to the bug we had with the other lists, what do you think?


> Can someone make sure report-numbers from arXiv are included in user-submissions?

yes, added it in our backlog
