### ISSUE TITLE
test_workflows is slow

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#364]
:smile: @jalavik is there anything we can do? Is currently the bottleneck on Travis...

**Comment by jalavik** [comment]
It's true that it is a bit slow right now. I guess In particular it's the part doing a full ingestion workflow. These tests are even expected to fail at the moment on Travis due to some funky SQLAlchemy session exception. So overall, they need some extra work indeed.

**Comment by jmartinm** [comment]
This is fine now?

**Comment by jacquerie** [comment]
Still slow on my machine. We could add a `pytest.skipif` decorator that detects if we are not running on Travis for this test and a few others (like the one in `test_views` that checks every record).
