### ISSUE TITLE
Missing stuff in brief results

### ISSUE THREAD

**Issue by ioannistsanaktsidis** [inspirehep/inspire-next#381]
- [x] journals: Missing doc_string from url and Publisher. 
- [x] jobs: Creation date missing.
- [x] experiments: Missing HEP articles and collaboration link. 
- [x] institutions: Missing affiliation line (e.g 860 Papers from KIPAC, Menlo Park)
- [x] conferences: Contributions link missing.
- [ ] authors: Author profile link missing.

**Comment by ioannistsanaktsidis** [comment]
@kaplun Is creation date of the job now added to the metadata?

**Comment by jmartinm** [comment]
We will tackle the author part once we start using the new profiles.
