### ISSUE TITLE
Explore most suitable font for titles and content

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#391]
In the first iteration of the labs search results we are using as a font:

```html
<link href='https://fonts.googleapis.com/css?family=Lato:300,400' rel='stylesheet' type='text/css'>
```

![screen shot 2015-10-01 at 3 07 58 pm](https://cloud.githubusercontent.com/assets/580727/10221377/4d68fffc-684e-11e5-8c0e-0d107cf85e03.png)

We need a comparison with other fonts and sites to make sure we go for the most crisp and readable font in different monitors.

For example:

| Site        | h1, h2, ... font           | Content font  |
| ------------- |:-------------:| -----:|
| http://elifesciences.org/elife/search      | Avenir LT W01 85 Heavy',sans-serif; | Helvetica |
| [aps journal](http://journals.aps.org/search/results?sort=relevance&clauses=%5B%7B%22operator%22:%22AND%22,%22field%22:%22all%22,%22value%22:%22atlas%22%7D%5D)     |  Proxima Nova     |   Helvetica Neue |

**Comment by eamonnmag** [comment]
+1 this is always tough. Google have some nice ones. The cleanest one I think is the one used by the elife lens. http://lens.elifesciences.org/10825/index.html?_ga=1.68657046.68384527.1443017183

**Comment by jmartinm** [comment]
Yes, that one is clean. It is http://www.fontsquirrel.com/fonts/source-sans-pro

I also like the one that APS uses for their titles in search results although it seems to be paying http://www.fontspring.com/fonts/mark-simonson-studio/proxima-nova-complete

**Comment by jmartinm** [comment]
Here is some comparison of fonts:

https://www.dropbox.com/sh/5cfvst4ou9g50ts/AACWj3FZo2UtasPCkkR8Yvora?dl=0

**Comment by eamonnmag** [comment]
Nice! I think i like either source or robot the best. Maybe some weights can change.
