### ISSUE TITLE
Add initial merging procedure of matched records in ingestion workflow

### ISSUE THREAD

**Issue by jalavik** [inspirehep/inspire-next#406]
- [ ] Add interface to enable super-users to approve/reject/fix when suggesting matches with uncertainty
- [ ] As a potential temporary measure, upload accepted matches to DESY merging workflow
- [ ] Based on given rules, upload a new revision for the current source to be merged with "master" record. (See more upcoming info about "mega merging workflow")

**Comment by david-caro** [comment]
@ammirate this is partially the fuzzy matching workflow you are implementing, and partially the merger.

@kaplun I'm not sure though what the 'desy merging workflow' means.

**Comment by kaplun** [comment]
> @kaplun I'm not sure though what the 'desy merging workflow' means.

IMHO It's not relevant anymore. Sounds like an old plan to have DESY performing the merging on their side, ad interim.

**Comment by ammirate** [comment]
@david-caro well, I would say this can be closed by #2760.
