### ISSUE TITLE
IN2P3 papers are pushed to HAL via SWORD protocol

### ISSUE THREAD

**Issue by jalavik** [inspirehep/inspire-next#407]
- [ ] ~~Setup special HAL collection mechanics on legacy prod~~
- [ ] Push IN2P3 papers to legacy prod special collection
- [ ] Add detection of potential papers in Labs ingestion workflow
- [x] Add conversion to TEI including author+affiliation IDs (@liamkirsh)
- [x] Add SWORD push to HAL (@liamkirsh)

**Comment by salmele** [comment]
First three parts (set-up collection, detect in ingestion, organize in collection) needed by start 2016, and IN2P3 will cooperate to prepare search queries to automatize this process (on metadata and full-text)

Last two parts might be needed only much later (possibly end 2016, TBC)

**Comment by kaplun** [comment]
Random notes from today meeting with HAL:

- Send ORCIDs
- Send Aurehal and OrgRef and GRID and ISNI 
- Send to HAL only when it's tagged as ready by the cataloguer
- Send everything from the institution DB into the TEI for every affiliation
- We could automatically send to HAL as soon there is an institution affiliated with Aurehal

**Comment by StellaCh** [comment]
@jacquerie can we close this?

**Comment by jacquerie** [comment]
> @jacquerie can we close this?

I would say so.
