### ISSUE TITLE
Data model: special field for `ForCDS`, `ForHAL` etc.

### ISSUE THREAD

**Issue by jalavik** [inspirehep/inspire-next#412]
For the HAL use case, we could have both a collection identifier (HAL) ala HEP today, but in addition we would need some way to indicate status. E.g. done/exported etc. 

Also, something like the ForCDS tag of today that marks a record for export to another system.

To cover the use cases of HAL catalogers removing certain wrongly tagged records or saying its done and ready for HEP or HAL etc.

@kaplun @annetteholtkamp

**Comment by jacquerie** [comment]
Done in https://github.com/inspirehep/inspire-schemas/commit/aee49d81d2e0c2d28db4835c376712939f5128f4.
