### ISSUE TITLE
Upgrade inspire-next to use CDS's pinned invenio-* versions

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#426]
To properly write regression tests involving creation/deletion of records one would need https://github.com/inveniosoftware/invenio-records/commit/02cfd62390c349b94abdae31493b15feec3916a2

But this brings in a chain reaction. Hopefully most of it has been already solved by @egabancho in: https://github.com/CERNDocumentServer/cds/blob/cdslabs/base-pinned.requirements.txt

So we just need to merge these and amend the overlay for Invenio-base.

**Comment by kaplun** [comment]
@jalavik what do you think?

**Comment by jalavik** [comment]
@kaplun That could work, but we'll need to sort out our own forks, see if we need to use the CDS forks or not, and test the whole thing without updating the `master` branches of any of our forks.

If it gets painful and regression tests is the only real benefit we get by upgrading, I would not consider this a blocker for enabling search, as we could wait until things have stabilised even more. And then just mock the records or update the test cases for #357 until then. 

Note that by upgrading Invenio, we soon after have to finish the externalisation of plotextractor as well as refextract, but I have a WIP for those and it has to be done anyway.

**Comment by jmartinm** [comment]
Done :smiley:
