### ISSUE TITLE
Data model: full support for references

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#430]
- [x]  references should be lists of lists (because there might be errata/ibid on the same reference)
- [x] What was once a pubnote in $s should be splitted up into journal title, volume, issue, start page

**Comment by kaplun** [comment]
cc: @jalavik, @annetteholtkamp

**Comment by annetteholtkamp** [comment]
We would also need an object for “reportnr, page” in case a report contains several contributions - see e.g. CERN Yellow Reports. 
And also “conf acronym, page/article id” e.g. for JACoW conferences.

- Annette

**Comment by kaplun** [comment]
Well, if we split up $s into its components then we would naturally have separate page and reportnumber supporting your above Yellow report use case. Regarding Conf acronym, do we have some today in 999C5?

**Comment by annetteholtkamp** [comment]
Not yet, but we’ve already some in 773. As soon as we’re exposing that in our bibliographic data we should be able to recognise the corresponding references as well.

- Annette

**Comment by aw-bib** [comment]
Just to ask: 
- a reference is (usually) pointing to an existing record
- basically, thus it has the very same structure as a record
- it even probably needs this complex structure to model all different pub types etc.

Thus, isn't _the link_(tm) enough probably drawing in some display and get expansions for indexing?

Ie for me references sound a bit like "just the same as the gigantic workflow, except it's children live in HEP space".

The exception are references that are not in inspire, ie. records that usually do not get a curation etc. Thus they will end up in some free form text anyway.

I wonder if such an approach would not simplify the model a lot.

**Comment by kaplun** [comment]
@aw-bib we have to store the whole reference (possibly already structured) because it we don't know if:
* this match any record at the time the record is ingested
* it will possibly match a future record still to arrive
* it is currently matching a record but this is a mistake and the reference structure is used to check this.

So the link is not enough.

But indeed it is a good point that the reference could basically be structured almost as whole record. That open up quite some reflection points...

In fact it all boils down to how much information we are able to match from publishers or guess from PDFs via refextract/Grobid.

**Comment by aw-bib** [comment]
I see your point, but wouldn't in this case storage of the raw string be enough?

If not, why not use the data extracted and  create a (stub) record and use this for  linking. Then you are sure you can map every needs. If the real record comes in later, just brush up the stub by usual merging. I think this simplifies the overall data structure.

So the question is it worth the efford to add a nested record structure, with all its complications.

**Comment by kaplun** [comment]
Coming back to this issue after discussion with @jalavik I think we can have the best of all worlds:
* [ ] hepcrawl/harvesting store references in either structured way (using the current jsonschema) or as raw strings (when nothing better is there.
* [ ] rawstring are transformed into structured references via `grobid` (YAY)
* [ ] fields are normalized (e.g. ISBN/ISSN/DOI/journal titles, etc. gets transformed into standard format)
* [ ] for every reference a STUB record is created with all the metadata in the reference
* [ ] through `invenio-matcher` we match the STUB record against existing records (either real or STUB)
* [ ] if no record matches the STUB record is added to the system (and tagged properly as stub)
* [ ] a link is recorded from the reference to the STUB record
* [ ] when indexing the current record care is taken in order to properly decorate the references pointing to STUB records, so that when presented, e.g. to cataloguer or user it is clear the referred record is stub
* [ ] when a new record arrives it is matched as usual against existing records (stub or not)
* [ ] if an incoming record matches a stub one, we can happily overwrite the stub one.

Bonus of this model:
* we have to maintain 1 way to match references
* we discover records that should get into INSPIRE easily (just look into HEP stub for the most cited record and promote it to real record)
* if a user reaches a stub record, well, dear user: help us enrich it, tell us if it's worth including into INSPIRE etc.

**Comment by kaplun** [comment]
@bittirousku can you take care of the above points:
> references should be lists of lists (because there might be errata/ibid on the same reference)
> What was once a pubnote in $s should be splitted up into journal title, volume, issue, start page

**Comment by bittirousku** [comment]
Sure, I can do that.

**Comment by eamonnmag** [comment]
List of dicts is always better. Otherwise one has to iterate over all items
and check properties to discover which reference should be displayed.

**Comment by kaplun** [comment]
Uh! @eamonnmag what are you referring to?

**Comment by eamonnmag** [comment]
> references should be lists of lists (because there might be errata/ibid on the same reference)
What was once a pubnote in $s should be splitted up into journal title, volume, issue, start page 

Unless I've misunderstood what you're storing in the references block and it's different from say, holdingpen, then if they are lists of lists you have this:
```
[
    [{'type': 'erratum', 'title': 'bla'},
    {'type': 'correct', 'title': 'blah'}]
]
```

Now to display the references, I will have to loop over the array and get the 'correct' type in this case. If instead we have this:
```
[
    {
        'correct': {'title': 'blah'},
        'erratum': {'title': 'bla'}
    }
]
```
I can just iterate over each reference and get 'correct'.

Obviously the keys are rubbish in this case. But something like this. This would be especially convenient when you have perhaps even more than two.

**Comment by jacquerie** [comment]
Currently `references` are still list of dicts, but each reference has a list of `raw_reference`s inside.

**Comment by mihaibivol** [comment]
The correct / erratum use-case should always happen when adding info between various versions and has to do with the way versioning is done. It will aways be `v0 = [{'title': 'bla'}]` `v1 = [{'titles': 'blah'}]` -- use magic --> correct = [{'title': 'bla'}] and you will only display that title. 

The problem with list of lists was with references that share the same number. @kaplun You had a pdf example. So far, refextract did a mess in legacy references. List of lists are generally bad for versioning and merging since you have to match a list of reference-like things denoting a single reference with another list of reference-like things. The goal is to always keep `correct` on top and previous versions of raw_reference only for curators to have fast access in fixing things.

**Comment by jacquerie** [comment]
Everything that had to be decided about this has already been decided in https://github.com/inspirehep/inspire-schemas/pull/130.
