### ISSUE TITLE
Page range/ Article ID - data model consistency

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#434]
I have found some inconsistencies between our dojson import and the HEP Schema that should be addressed:

* [x] `page_artid` is in dojson but not on schema. It is called `page_range` [in the schema](https://github.com/inspirehep/inspire-next/blob/master/inspire/dojson/hep/schemas/hep-0.0.1.json#L383) which I am not sure covers the full meaning of the field.
* [x] cnum in dojson is conference_paper_info in schema
* [x] collaboration is not array in dojson but it is in the schema.
* [x] url should be renamed to urls in schema and dojson

Tasks missing https://github.com/inspirehep/inspire-next/issues/434#issuecomment-152526331

**Comment by annetteholtkamp** [comment]
It still hasn't been decided whether we want to split article nr and page range. Would be useful in case we have both - e.g. for JACoW conferences.

- Annette


On Oct 21, 2015, at 11:21 AM, Javier Martin Montull <notifications@github.com<mailto:notifications@github.com>> wrote:


I have found some inconsistencies between our dojson import and the HEP Schema that should be addressed:

  *    page_artid is in dojson but not on schema. It is called page_range in the schema<https://github.com/inspirehep/inspire-next/blob/master/inspire/dojson/hep/schemas/hep-0.0.1.json#L383> which I am not sure covers the full meaning of the field.
  *    cnum in dojson is conference_paper_info in schema
  *    collaboration is not array in dojson but it is in the schema.
  *    url should be renamed to urls in schema and dojson

**Comment by jalavik** [comment]
Regarding, `page_range` I fixed it as part of #422 https://github.com/inspirehep/inspire-next/pull/422/files#diff-3db794b5dfd367ebcb5f09729f2490f5 

But yeah, I guess it make sense to split it rather?

**Comment by kaplun** [comment]
> ￼ collaboration is not array in dojson but it is in the schema.

Should indeed be an array. (e.g. paper from ATLAS and CMS).

**Comment by ioannistsanaktsidis** [comment]
@jmartinm @kaplun the collaboration problem I think is fixed. I have just checked and it is array in both now.

**Comment by kaplun** [comment]
IMHO this belongs to the `Enabling search` milestone

**Comment by jacquerie** [comment]
BTW, not an inconsistency but some undefined behavior: https://github.com/inspirehep/inspire-next/blob/3dab446ea8ff9776830954b098461a956fd93271/inspire/dojson/hep/schemas/hep-0.0.1.json#L753-L778 only allows us to define affiliations as opaque strings, but maybe we want to specify which kind of affiliation it is: is it a collaboration, an institute, a department...

**Comment by kaplun** [comment]
@jacquerie in the HEP field the affiliation within a HEP record is typically the Department + Institute to which each author is affiliated while writing a given paper. Within Inspire Institution database we have entries both for Institutes and for the specific departments, with links allowing to go from Department to Institute. So it should be enough to have the opaque string to match uniquely a given department, for the system to reliably add the institution.

Collaborations are instead considered as a special authorship for a paper.

E.g. the whole ATLAS "collaboration" signs a paper (hence all the single authors). (this was represented in MARC with the dedicated tag 710, separate from the 100/700) . Also the collaboration should unambiguously match an existing experiment in the Experiment collection.

Regarding the opaqueness of the string, this is true: sometimes (depending on the source) we have some structured information that we could leverage, sometimes just a simple string. The very purpose of it is at the end to be able to match a Institution entry, so a simple string could be enough. But, indeed, given the affiliation guessing tool on which @Lilykos is working on it might be indeed useful to preserve some structure... Maybe it could be defined as an object with undefined fields? @jalavik?

**Comment by jacquerie** [comment]
About the collaboration: sometimes I've seen people declare multiple affiliations, one of which is a collaboration, in a paper not published by the collaboration. It probably doesn't happen with ATLAS or CMS, since they have strict standards about the use of their name, but smaller collaborations might allow that.

I really wish I had an example to show you : )

**Comment by kaplun** [comment]
:scream:

**Comment by kaplun** [comment]
@annetteholtkamp only you can save us now!

**Comment by kaplun** [comment]
@annetteholtkamp says we can ignore collaborations when they are put in the affilation fields.

**Comment by annetteholtkamp** [comment]
What I mean by this: You can just leave it in the affiliation field and cataloguers can fix it. You don’t have to be smart and recognise it as a collaboration, to put it into the right field. 
Should it turn out that Grobid misinterprets phrases like “on behalf of collaboration xxx” then we’d need to do something.

- Annette

**Comment by kaplun** [comment]
> page_artid is in dojson but not on schema. It is called page_range in the schema which I am not sure covers the full meaning of the field.

In which way have you fixed it? @annetteholtkamp mentions we should be able to store separately page ranges and article IDs.

**Comment by jmartinm** [comment]
Nothing is changed so far AFAIK so there is only one field `page_artid` both in the schema and in dojson.

I agree that separation would be nice but are we able to do that? If we import all our existing records are we able to distinguish what is a page range and what an article id? or it will be worse as we try to guess in all our workflows what is what and we will end up filling the wrong fields?

**Comment by jacquerie** [comment]
Has this to happen at workflow time? Maybe you can just copy as if it were a page range and then decide  in a batch job that it is in fact an article id.

**Comment by kaplun** [comment]
> Has this to happen at workflow time? Maybe you can just copy as if it were a page range and then decide in a batch job that it is in fact an article id.

Yes, in fact @annetteholtkamp mentioned me there are some heuristics to decide if it's an article ID or the begin page. E.g.:
* if it has a dash it's a page range
* it it has 2 ore more letters it's an article ID
* it it is longer than 5 digits it's an article ID
* if it's from journal Foo it is...

We could in principle:
* [ ] put this heuristics in a common utils module
* [ ] amend the schema to have `article_id` and `page_range` field
* [ ] rename everywhere to use e.g. `page_range`.
* [ ] plug somewhere the call to the utility to amend this information to the correct place (unless it was not already done at workflow time).

**Comment by kaplun** [comment]
So this is not really a blocker for Enabling search milestone. It's going to be needed though by the time we enable all the citation machinery.
