### ISSUE TITLE
submission: thesis field reordering

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#438]
The order of the fields should be:

Degree type
Thesis Date (we leave only one date)
Institution
Supervisors

Would be good to mark in the interface Degree type and Thesis date as important to remind the user to fill them in.

Also make PhD default degree type.

**Comment by jmartinm** [comment]
@gartocern this can be a good warm up task too

**Comment by kaplun** [comment]
@jmartinm still needed?

**Comment by jmartinm** [comment]
Just double checked and this did not get done. It will be a bootcamp task for @koursaros93
