### ISSUE TITLE
Improve 0 results page

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#452]
This needs to be modified in the template `search.html`

When there are no results in a query, currently the following message is displayed:

```
Your search did not match any records. Please try again.

Try to modify the query.
```

In this case, we can:

1) On the server side we try to modify the query in a smart way to get matches and then communicate to the user the change performed.

2) We offer some search helpful tips and point to the search help.

Obviously 2) is easier so we should start by that.

**Comment by aw-bib** [comment]
Sometimes, the information: "there is nothing" is very helpful and in all those setups where one "modifies the query in a smart way to return something" this information is easily overlooked and can produce quite some confusion.

Thus, probably, some "did you mean" listing just queries that give results is probably an option to consider.

**Comment by jmartinm** [comment]
Good suggestion @aw-bib thanks

**Comment by nikpap** [comment]
In this case, I suggest it would be good to display the search bar once again. This way, the user can quickly do another search without having to go back to the previous page. Also, the query should be visible to the user; that is not currently the case.

**Comment by eamonnmag** [comment]
Yes, or just the same page with some text where the search results are saying "No results have been returned for this query".

**Comment by jmartinm** [comment]
Yes, the page should be the same one always when doing searches and the search bar always available.

Question here was more about improving the feedback given to the users in the part where the search results would be. For example, by giving a link to the search tips and/or showing variants of the search performed that would yield some results.

**Comment by eamonnmag** [comment]
Search tips yes. Variants could be done by storing previously executed query strings that were non-empty, then taking the distance between the strings.

**Comment by salmele** [comment]
@jmartinm I think we got comments in the usability review of the present system along these lines (showing search bar and about help/tips): can you check them. The 'did you mean' that @eamonnmag is sort of suggesting could come later, but can be explored.

**Comment by jmartinm** [comment]
@salmele Yes, they recommended 2) 

This issue comes actually after reviewing and extracting action points from the usability review that I collected here https://docs.google.com/document/d/1yQp7LIl_ZKJ8o-HccPYzmxI8RJ11eZ0hLnJHMe8lPTY/edit?usp=sharing

**Comment by jmartinm** [comment]
Actually at the moment, no message at all is being shown, so this needs to be fixed

![screen shot 2015-11-30 at 11 07 33 am](https://cloud.githubusercontent.com/assets/580727/11468829/a2a2ff6c-9752-11e5-8a07-4b5119a344bf.png)
