### ISSUE TITLE
Crash in Holdingpen for unicode error

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#456]
See: https://labs.inspirehep.net/admin/holdingpen/details/188544

**Comment by kaplun** [comment]
See: https://sentry.cern.ch/inspire-sentry/inspire-labs/group/6478/

**Comment by kaplun** [comment]
@jalavik, @jmartinm was this fixed on current master?

**Comment by jalavik** [comment]
Partially, at least it does not crash the site, but there is still an exception happening. (I have a local dump of it). I will look into what's causing the crash.

**Comment by jmartinm** [comment]
Fixed by https://github.com/inspirehep/inspire-next/pull/643
