### ISSUE TITLE
Export functionality improvements

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#459]
* [ ] Loading spinner is always displayed close to the Download button. The element can be hidden from the beginning with css `display:none` and then shown when needed.
* [ ] All the files exported are called `export_as`. Would be nice to have the name based on the export format. Like `latexus.tex`
* [ ] CV Format Latex and CV Format Text have `<br>` tags in them. Not sure that is intended when downloading?
* [ ] The dropdown is not well aligned

![screen shot 2015-11-04 at 5 06 32 pm](https://cloud.githubusercontent.com/assets/580727/10943809/614cedde-8316-11e5-86a1-bef0e2bd9aad.png)

* [ ] We might still find the case when people prefer to just see the output format as part of the results ( like [currently on INSPIRE](http://inspirehep.net/search?ln=en&ln=en&p=author%3A%27Ellis%27&of=hx&action_search=Search&sf=earliestdate&so=d&rm=&rg=25&sc=0) ). We should ask certain users in the next round of user testing what they think about this.

**Comment by ioannistsanaktsidis** [comment]
@jmartinm the PR for the improvements that you mentioned https://github.com/inspirehep/inspire-next/pull/461

**Comment by jmartinm** [comment]
DOne
