### ISSUE TITLE
Show plots in detailed view

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#464]
Detailed views of Literature should show the attached plots.

Currently the link to the plots can be found in the record:

```
 "urls.url": [
                  "http://inspirehep.net/record/1090018/files/figures_2LoopDiags.png",
                  "http://inspirehep.net/record/1090018/files/figures_3LoopDiags1of4.png",
                  "http://inspirehep.net/record/1090018/files/figures_3LoopDiags2of4.png",
                  "http://inspirehep.net/record/1090018/files/figures_3LoopDiags3of4.png",
                  "http://inspirehep.net/record/1090018/files/figures_3LoopDiags4of4.png",
                  "http://inspirehep.net/record/1090018/files/figures_CoupPlot2s2f.png",
                  "http://inspirehep.net/record/1090018/files/arXiv:1202.4757.pdf"
               ],
               "urls.description": [
                  "00000 Diagrams that contribute to $q$ at two-loop order.",
                  "00001 (3)",
                  "00002 (3)",
                  "00003 (3)",
                  "00004 Diagrams that contribute to $q$ at three-loop order.",
                  "00005 RG evolution of the couplings in the model with two real scalars and two Weyl fermions on a scale-invariant limit cycle as a function of RG time. Here $\\epsilon=0.01$."
               ]
```

So based on the filename it is possible to distinguish a plot because of the `png` extension.

The plots should be shown with thumbnails, the current selected one in big and the description close to it.

For the moment plots can be served directly from the INSPIRE link (so no need to be attached locally)

See also related issue https://github.com/inspirehep/inspire-next/issues/463

**Comment by jalavik** [comment]
A mentioned in #463, is it clear how we will "attach" the plots? Locally or just integrate images from inspirehep.net?

**Comment by jmartinm** [comment]
As mentioned in https://github.com/inspirehep/inspire-next/issues/463 for the moment I would just serve the images from inspirehep.net.

**Comment by nikpap** [comment]
@jmartinm  I've started working on this issue as well.
