### ISSUE TITLE
do not allow anonymous feedback

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#465]
At the moment the feedback form

<img width="627" alt="screen shot 2015-11-05 at 2 59 38 pm" src="https://cloud.githubusercontent.com/assets/580727/10970257/c7cc3382-83cd-11e5-80a4-b6182265c8ea.png">

Uses the email address from the user if he/she is logged in.

If the user is not logged in, a ticket is created in the RT system but no email appears.

Solution
======

If the user is not logged in and the feedback form is presented there should be an extra email field mandatory for feedback to be submitted.

**Comment by salmele** [comment]
It is very valuable to keep the threshold low for users to help with feedback, at least while we are in labs+prod phase. I agree that forcing (ORCID) login for this would be too much. I agree with the solution of asking extra e-mail field.

Concerning the verbiage, we should be careful about what we are asking for: it is ONLY for labs, and/or for bizarre things we see in that page. Not citations missing/other suggestions which should go another way.

**Comment by jacquerie** [comment]
I can take this. Proposal for copy: "INSPIRE Labs welcomes problem reports, feature ideas and general comments. For missing citations in the current INSPIRE please refer to [this page](https://inspirehep.net/info/hep/corrections_reference)".

**Comment by annetteholtkamp** [comment]
Add “and other corrections/suggestions” 

- Annette
