### ISSUE TITLE
Mega dropdown improvements

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#471]
Here we will collect improvements that need to be added to the Resources Dropdown.

* [x] Add an arrow down symbol that indicates the dropdown is going to open.

Like we do in the login

![screen shot 2015-11-06 at 1 45 00 pm](https://cloud.githubusercontent.com/assets/580727/10997357/cb923966-848c-11e5-9341-56d54a4f890a.png)

* [ ] Experiment with adding links close to the Logo on the left. That would allow the Resources dropdown to feel in place when opening.

* [x] Open by default the first element in the dropdown. That way the whole width will be covered with content. Like in Khan Academy

![screen shot 2015-11-06 at 4 47 46 pm](https://cloud.githubusercontent.com/assets/580727/11001178/3ca183b4-84a6-11e5-8f0b-c945dfe2d027.png)

**Comment by ioannistsanaktsidis** [comment]
@jmartinm this one is addressed by your latest changes right?

**Comment by jmartinm** [comment]
Yes, I will close this. I think its ok for the moment.
