### ISSUE TITLE
Sorting of search results

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#474]
Sorting of search results needs to be implemented. Possible values for the dropdown can be:

* Best Match
* Newest
* Oldest
* Most Cited
* Least Cited (?)

Some other option?

**Comment by jacquerie** [comment]
Do we have data about what do the users use currently?

**Comment by salmele** [comment]
Agree with @jacquerie : we should check logs about how often people do something different than the default today and what they do. Hopefully with the ascending/descending variations. And -possibly- offer the same default. 

Also, do checking the piwik/apache data for recurrent signs of user frustration in trying different queries to get to the order they really want does add information to the above.

Checking (1) collective memory; (2) feedback tickets and (3) usability report for additions to the drop down is a good idea as well.

**Comment by annetteholtkamp** [comment]
Has the "latest first" option vanished from your design? I think it's sometimes useful - but the naming is somewhat unfortunate.

- Annette


On 06 Nov 2015, at 18:03, Javier Martin Montull <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorting of search results needs to be implemented. Possible values for the dropdown can be:

  *   Best Match
  *   Newest
  *   Oldest
  *   Most Cited
  *   Least Cited (?)

Some other option?

**Comment by jacquerie** [comment]
> Has the "latest first" option vanished from your design? I think it's sometimes useful - but the naming is somewhat unfortunate.

Am I misunderstand, or this could be called "most recent"?

**Comment by annetteholtkamp** [comment]
"recently added"? These are the papers recently added to Inspire but they can be old. It has to be clear that this is not the date of the paper itself, but the date of ingestion.

- Annette

On Nov 7, 2015, at 1:19 PM, Jacopo Notarstefano <notifications@github.com<mailto:notifications@github.com>> wrote:


Has the "latest first" option vanished from your design? I think it's sometimes useful - but the naming is somewhat unfortunate.

Am I misunderstand, or this could be called "most recent"?

**Comment by salmele** [comment]
That's exactly what can be unnerving to users who do not understand that we can add things from the past (remote or close) somewhat haphazardly. Do we have indeed stats of how often someone sorts in such a way AND/OR uses F DADD as proxy for the interest of retrieving recently added papers?

**Comment by kaplun** [comment]
There is one additional point to add to the discussion: Invenio-based search used up until now in INSPIRE was by default always AND-ing all the searched terms, and then ranking by whatever criteria needed (in HEP nowadays this is latest papers on top, latest as in user, not as in librarians).

Elasticsearch on the other hand, by default, offers word similarity: i.e. all documents matched by at least one term are returned, however, the documents matching more terms are on top (it is more complex than that, but you get my point). That means that we can choose whether now switching to the elasticsearch mode, and return many more results, albeit having the first ones on top to be the most correct (as bit like in Google you don't expect one result, rather billions, but to have the good ones at the top). Additionally we can combine a decide to boost the result by taking into consideration both the freshness of the document (i.e. the current INSPIRE criteria) and the word similarity.

In fact the possibilities are even wider. 

I strongly believe in:
> Checking (1) collective memory; (2) feedback tickets and (3) usability report for additions to the drop down is a good idea as well.

I am confident we're going to produce very improved results.

**Comment by kaplun** [comment]
See also #609

**Comment by bing13** [comment]
I don't think piwik can tell us which sort option was selected, but I could be wrong.  The Visitor Log is a lovely way to scan what people are searching for, but it seems to only have the query itself. Systematically log diving for this info wouldn't be much fun.

We have had user tickets in the past on the recently added vs recently published question. "Recently added" sounds nice to my ears, it's still ambiguous but less so. One can imagine a tooltip near the sort option that provides explicit help.

"I am confident we're going to produce very improved results."   +1 !!

**Comment by jmartinm** [comment]
So for the moment we stay with `Best Match`, `Newest First` and `Most Cited`.

We will further enquiry users to see if more options are needed.
