### ISSUE TITLE
Invalidate cache of cited records after record update

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#479]
After a record is created/updated, a new receiver should be added to ~~invalidate the cache of~~ reindex all referred records that might be affected by this change:
* [ ] records that were cited by the modifed record and no longer are,
* [ ] records that are now cited by the modified record.

See also #478

**Comment by kaplun** [comment]
This would mean for the given record: fetch from elasticsearch the current `references.recid` list, check against the new one, and invalidate the cache for all the `recid`s that are not in the intersection.

**Comment by jmartinm** [comment]
Do we have a cache for the citations/references or this means that we reindex the affected records in ES with the updated `citations` fields ?

**Comment by kaplun** [comment]
This is assuming the citing records are calculated on the fly and the resulting numbers/links presumably cached in  redis.

**Comment by jmartinm** [comment]
Related to https://github.com/inspirehep/inspire-next/issues/515

**Comment by kaplun** [comment]
@tomaszgy is currently working on it in #691
