### ISSUE TITLE
Upon deletion of record checks for referring records

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#483]
We should raise a warning to the cataloguer if there is at least one link towards the record being deleted.

**Comment by jmartinm** [comment]
This should be moved to https://github.com/inspirehep/record-editor ?

**Comment by kaplun** [comment]
I am not sure. 

`record-editor` is a library to edit JSON. What it means to delete a record is not defined in Invenio AFAIK, so each installation will have it's convention (e.g. set a subfield to DELETED). So somehow I see the operation of deleting a record as an additional side widget, that INSPIRE will present in the same page.

**Comment by jmartinm** [comment]
> What it means to delete a record is not defined in Invenio AFAIK

There seems to be some convention in the API:
https://github.com/inveniosoftware/invenio-records/blob/master/invenio_records/api.py#L276

So it depends if we make `record-editor` a more plain JSON editor or a more integrated `invenio-record-editor` in which case it would make sense to use `invenio-records` API to for example delete a record (which would be useful for all installations)

**Comment by kaplun** [comment]
:+1: 
This is a good point. If this is also mapped in `invenio-record-rest`, and this one can be augmented to raise exception in case of linked ref, then indeed we can have `record-editor` to simply support a deletion end point and being able to accept e.g. `403` states for `Forbidden`.

In this way we could keep it agnostic to Invenio, but still support  this functionality.

**Comment by kaplun** [comment]
Issue moved to [inspirehep/record-editor #74](https://github.com/inspirehep/record-editor/issues/74) via [**ZenHub**](https://www.zenhub.com/)
