### ISSUE TITLE
Experiment completed 046__t -> 9999?

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#488]
Currently in Experiment record, if the experiment is still running the field `046__t` is set to 9999. However e.g. for https://inspirehep.net/record/1401119/export/hm no field `046__t` is set. Should we assume it is still running? What shall we do when converting to JSON? Enforce 9999?

cc: @annetteholtkamp, @jmartinm

**Comment by kaplun** [comment]
Meanwhile I proposed in #497 that in case no field is there nothing is printed.

**Comment by annetteholtkamp** [comment]
If this field is empty we just don't know. Better not to assume anything.
Btw, even the 9999 may be wrong. It's not so consistently updated. It's just a best effort.

- Annette


On Nov 10, 2015, at 11:16 AM, Samuele Kaplun <notifications@github.com<mailto:notifications@github.com>> wrote:


Currently in Experiment record, if the experiment is still running the field 046__t is set to 9999. However e.g. for https://inspirehep.net/record/1401119/export/hm no field 046__t is set. Should we assume it is still running? What shall we do when converting to JSON? Enforce 9999?

cc: @annetteholtkamp<https://github.com/annetteholtkamp>, @jmartinm<https://github.com/jmartinm>

**Comment by salmele** [comment]
Which is the process through which we check when any/each experiment is no longer "running"?
