### ISSUE TITLE
Resources dropdown error on Firefox

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#493]
When using Firefox, the following error is thrown which blocks the rest of the JavaScript on the pages to load:

```
 ReferenceError: activateSubmenu is not defined1 dropdown-menu.js:41:12
```

**Comment by ioannistsanaktsidis** [comment]
The activateSubmenu is coming from jQuery menu aim, so I guess the library is not yet loaded when referred or sth like this?
