### ISSUE TITLE
Create custom error pages (401, 403, 404, 500)

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#499]
Here is an example on how to register them:

https://github.com/inveniosoftware/invenio-theme/commit/1f6c4d33873ed50062e7ce27ba67035a25c9c067#diff-c4a18f011bbc6c827aab63168099ee71R69

**Comment by kaplun** [comment]
@eamonnmag as mentioned IRL would be great if you can make a PR with awesome error pages :-)

**Comment by eamonnmag** [comment]
Yup,  I will.
