### ISSUE TITLE
Add caching for brief record templates

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#515]
We are using `Flask-cache` for caching needs. In this link https://pythonhosted.org/Flask-Cache/#caching-jinja2-snippets it is explained how to cache jinja2 templates and how to invalidate the cache.

As some numbers displayed in search results (like the number of citations) will be calculated on the fly we need to add caching for brief results.

An API needs to be available as well that based on `record ids` as input will invalidate the cache for those templates.

**Comment by kaplun** [comment]
I am removing the milestone here, since this is not a blocker to Enabling search. The number of citation is no longer going to be computed on the fly, since it needs to be used for ranking any way.

**Comment by kaplun** [comment]
@jmartinm A bit OT: is there someone working on the rank by citation number?

**Comment by StellaCh** [comment]
@jmartinm @kaplun is this still an issue?

**Comment by jmartinm** [comment]
Not as it is described since we don't use jinja anymore in search results. Also the citation numbers are not calculated on the fly so we are good.

Only thing that is done on the fly and maybe should be cached is retrieving information from related records (like the conference title on a record published at a conference)
