### ISSUE TITLE
Select-all export problem

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#538]
When using facets to filter results and then selecting all search results there seems to still be a problem @ioannistsanaktsidis 

<img width="917" alt="screen shot 2015-11-20 at 6 07 48 pm" src="https://cloud.githubusercontent.com/assets/580727/11306390/c1f767a2-8fb1-11e5-85e6-6250069783d5.png">

**Comment by ioannistsanaktsidis** [comment]
@jmartinm I think by default the rg value should be 10, as we display 10 results per page. Or you think we should change the results per page to 25 by default?

**Comment by jmartinm** [comment]
The default search results are now fixed.

**Comment by annetteholtkamp** [comment]
The current default on prod is 25. Is there a reason not  to keep it?

- Annette

**Comment by jmartinm** [comment]
The default will still be kept in 25. There was just a bug in code that was setting it to 10 ;)
