### ISSUE TITLE
Detailed/Brief: Display information about conferences

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#541]
For Literature records that have conference information, the following info can be found in the JSON:

```json
"publication_info":[  
   {  
      "cnum":"C14-02-23.1",
      "conference_recid":1276884,
      "journal_issue":"6",
      "journal_recid":1214555,
      "journal_title":"Nuovo Cim.",
      "journal_volume":"C037",
      "page_artid":"101-109",
      "parent_recid":1357781,
      "year":2014
   }
]
```

Showing info in conference papers
==========================

Example 1
--------------

001292801 773__ $$c101-109$$n6$$pNuovo Cim.$$vC037$$wC14-02-23.1$$y2014

![screen shot 2016-01-15 at 3 15 55 pm](https://cloud.githubusercontent.com/assets/580727/12355144/fa6bb664-bb9a-11e5-9daf-b5d493434ca3.png)

As there is publication info and conference info, the text would be:

```Published in Nuovo Cim. C037 (2014) 6, 101-109 (Proceedings of 28th Rencontres de Physique de la Vallée d'Aoste)```

Where `Proceedings` will be a link pointing to record id `1357781` and `28th Rencontres de Physique de la Vallée d'Aoste` a link pointing to record id `1276884`

Example 2
--------------

001292801 773__ $$c101-109$$n6$$wC14-02-23.1

Same as before but no journal information. The text would be:

```Published in proceedings of 28th Rencontres de Physique de la Vallée d'Aoste, pages 101-109```

Example 3
--------------

001405098 773__ $$wC15-07-14  (as long as there is no Proceedings record)

Here there only available field will be `conference_recid`. In that case we just will have the text:

```Contribution to 4th European Particle Accelerator Conference (EPAC 94)```

Example 4
--------------

000395649 773__ $$c1-10$$wC94-06-27$$xIn *London 1994, Proceedings, EPAC 94, vol. 1* 165-169, and Juelich KFA - Juel-2965 (94/09,rec.Dec.) 1-10

If a record does not have information in `parent_recid` but contains the field `pubinfo_freetext` (old $$x in MARC) then we display the content of that field.

**Comment by annetteholtkamp** [comment]
We need to differentiate whether a contribution has been published in the proceedings. Then information should be taken from the proceedings record (CNUM + collection Proceedings). - "published in ..."  There are 2 options:
- The proceedings are published in a journal (or in a series we treat like a journal). Then the information is in the metadata of the paper.
- The proceedings are pbulished in a book. Then the paper record contains only the CNUM and the page range.

If there's only the CNUM and no further publication info then the display need to be different. Contribution to... or presented at...

Topic for content meeting on Monday.

- Annette


On 20 Nov 2015, at 18:27, Javier Martin Montull <notifications@github.com<mailto:notifications@github.com>> wrote:


Depends on #485<https://github.com/inspirehep/inspire-next/issues/485>

For Literature records that have conference information, the following info can be found in the json:

"publication_info": [
                  {
                     "cnum": "C13-12-02",
                     "recid": "",
                     "year": ""
                  }
               ]


Once the task above is completed the recid will be filled with the appropriate conference record.

Currently on inspirehep the conference information is simply the cnum

[screen shot 2015-11-20 at 6 22 55 pm]<https://cloud.githubusercontent.com/assets/580727/11306699/c570d146-8fb3-11e5-8d8a-b16badd00534.png>

From the metadata we currently have, what would be the information we can display? Like Presented at EuroPython 2015, do we know if it was presented there, part of the proceedings and so on. @annetteholtkamp<https://github.com/annetteholtkamp>

**Comment by ioannistsanaktsidis** [comment]
@jmartinm Could you assign it to me? Thnx!
