### ISSUE TITLE
Literature detailed: Author display improvements

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#542]
Based on the current implementation for inspirehep, author display has to be amended:

https://github.com/inspirehep/inspire/blob/master/bibformat/format_elements/bfe_INSPIRE_authors.py#L27

Important to note the logic about displaying corporate authors and collaborations.

**Comment by ioannistsanaktsidis** [comment]
@jmartinm this one is in the WIP PR for tha brief and detailed that I created. I have to check once more some stuff about corporate author and collaboration You can assign this issue to me.
