### ISSUE TITLE
Year filter and number of citations filter

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#543]
Apart from being able to filter by a given year

<img width="295" alt="screen shot 2015-11-20 at 6 42 27 pm" src="https://cloud.githubusercontent.com/assets/580727/11307130/88aba378-8fb6-11e5-9ddb-6659656673d0.png">

it can be useful to have an extra facet that allows for a range and displays the distribution. Similar to

<img width="310" alt="screen shot 2015-11-20 at 6 43 57 pm" src="https://cloud.githubusercontent.com/assets/580727/11307153/abcd46d6-8fb6-11e5-8104-66e8a6e9c6a5.png">

A similar filter can be implemented for the number of citations.

**Comment by salmele** [comment]
This seems really something to user test, both in the idea of the slider and what to put in...

**Comment by jmartinm** [comment]
As user testing results showed, the current year facet as is would not be of much use.

Instead a range would be desired. @eamonnmag and @ioannistsanaktsidis were looking into a D3 implementation.

**Comment by eamonnmag** [comment]
I will implement this for hepdata tomorrow. Plugging it in to inspire will be easy :)

**Comment by eamonnmag** [comment]
![hepdata-year-filter](https://cloud.githubusercontent.com/assets/282396/12841329/596219a0-cbeb-11e5-8fb0-44ed032168c6.gif)

https://jsfiddle.net/qckrvvtd/12/

**Comment by ioannistsanaktsidis** [comment]
:+1:

**Comment by bing13** [comment]
nice!

**Comment by kaplun** [comment]
@jmartinm @eamonnmag I believe we were close to have this integrated, right?

**Comment by jmartinm** [comment]
For the year filter there is https://github.com/inspirehep/inspire-next/pull/1256

That PR can be resumed and finished once I am back.

**Comment by jacquerie** [comment]
#1256 was merged.
