### ISSUE TITLE
Author update form: create preview in Holding Pen

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#561]
As we have dropped support for the legacy templates, there is currently no preview of how a HepNames record will look like in the Holding Pen when a user adds/updates an Author.

A new basic template needs to be added that resembles the current HepNames (see for example https://inspirehep.net/record/1222902).

The code for this legacy template can be found here: https://github.com/inspirehep/inspire/blob/master/bibformat/format_templates/Hepnames_HTML_detailed.bft

**Comment by jmartinm** [comment]
@ioannistsanaktsidis This is needed for deployment of the latest `master` branch. We can talk about it later.

**Comment by ioannistsanaktsidis** [comment]
@jmartinm for a start should I start creating the file and the functions  according to the bft?
