### ISSUE TITLE
Literature brief results

### ISSUE THREAD

**Issue by nikpap** [inspirehep/inspire-next#564]
An idea would be to increase the width of the left column in the brief results, by removing unused white space on the right side.

On top: suggested modification
On bottom: previous state - note the white space on the right side.

![capture d ecran 2015-11-26 a 14 36 10](https://cloud.githubusercontent.com/assets/2742143/11424188/4958dff8-944b-11e5-9c25-23012e8555ae.png)

**Comment by annetteholtkamp** [comment]
We should also take into consideration where to put all the external links, see e.g.


Examples of mirror partners arising from integrable systems<https://inspirehep.net/record/558665> (In English and French)
Partenaires miroirs provenant des systèmes intégrables
Tamás Hausel<https://inspirehep.net/author/profile/Hausel%2C%20Tam%C3%A1s?recid=558665&ln=en> (UC, Berkeley, Math. Dept.<https://inspirehep.net/search?cc=Institutions&p=institution:%22UC%2C%20Berkeley%2C%20Math.%20Dept.%22&ln=en>), Michael Thaddeus<https://inspirehep.net/author/profile/Thaddeus%2C%20Michael?recid=558665&ln=en> (Columbia U., Dept. Math.<https://inspirehep.net/search?cc=Institutions&p=institution:%22Columbia%20U.%2C%20Dept.%20Math.%22&ln=en>). Jun 18, 2001. 6 pp.
Published in Compt.Rend.Acad.Sci.Ser.I Math. 333 (2001) 4, 313-318
DOI: 10.1016/S0764-4442(01)02057-2<http://dx.doi.org/10.1016/S0764-4442(01)02057-2>
e-Print: math/0106140<http://arxiv.org/abs/math/0106140> | PDF<http://arxiv.org/pdf/math/0106140.pdf>

  *   References<https://inspirehep.net/record/558665/references> | BibTeX<https://inspirehep.net/record/558665/export/hx> | LaTeX(US)<https://inspirehep.net/record/558665/export/hlxu> | LaTeX(EU)<https://inspirehep.net/record/558665/export/hlxe> | Harvmac<https://inspirehep.net/record/558665/export/hlxh> | EndNote<https://inspirehep.net/record/558665/export/xe>
  *   CERN Document Server <http://cds.cern.ch/record/504671> ; AMS MathSciNet<http://www.ams.org/mathscinet-getitem?mr=1854771>; zbMATH<http://www.zentralblatt-math.org/zmath/en/search/?an=1009.14005>; ADS Abstract Service<http://www.adsabs.harvard.edu/abs/2001CRASM.333..313H>
  *


- Annette

On Nov 26, 2015, at 2:38 PM, Nick Papoutsis <notifications@github.com<mailto:notifications@github.com>> wrote:


An idea would be to increase the width of the left column in the brief results, by removing unused white space on the right side.

On top: suggested modification
On bottom: previous state - note the white space on the right side.

[capture d ecran 2015-11-26 a 14 36 10]<https://cloud.githubusercontent.com/assets/2742143/11424188/4958dff8-944b-11e5-9c25-23012e8555ae.png>

**Comment by salmele** [comment]
Would most of the external links be more in the purview of the full record?

**Comment by jmartinm** [comment]
> Would most of the external links be more in the purview of the full record?

For me they would belong inside the detailed view of a record. We have plenty of information already in the brief that allows to find the right record a user is searching for. Except if there was an intensively used link that would that by being in the brief format would save some time (I am not aware of any)

**Comment by salmele** [comment]
I fully agree (of course). Can we check the present logs, and strive for simplification? Also, present logs will give indication for the order of links in the detailed record (most clicked first)
