### ISSUE TITLE
Facets reset

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#573]
I think a quick way to reset facets (and hence start a new search session) is missing.

E.g. imagine I am deep into certain facets but then I'd like to start a new search anew. Currently I would need either to go to the homepage or to unclick the facets one by one.

**Comment by kaplun** [comment]
cc: @jmartinm @nikpap

**Comment by nikpap** [comment]
Hey Sam, I believe that if you write a new search term on the search bar, all of the facets are reset.

Do you believe that is sufficient or should we add a "Clear facets" button?

**Comment by jmartinm** [comment]
Yes, to me it would be nice to have something like in this flight website:

![](https://cloud.githubusercontent.com/assets/580727/10842243/9b93d888-7ef0-11e5-97c6-1f0882ba287e.png)

On the top of the search results. We can a similar message:

```
23 of 300 publications coincide with the filters you selected. [ Clear Filters ]
```

**Comment by jmartinm** [comment]
It was the last point of this https://github.com/inspirehep/inspire-next/issues/411 btw

**Comment by kaplun** [comment]
Ah @jmartinm sorry I wasn't aware of that.

**Comment by ioannistsanaktsidis** [comment]
The functionality looks good, we just need to see where it fits better.

**Comment by ioannistsanaktsidis** [comment]
@kaplun  you can assign this to me.
