### ISSUE TITLE
Support multiple continents in Jobs

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#575]
Record https://inspirehep.net/record/1375854/export/xme is failing because it specifies multiple continents:
```python
09:47:50 worker.1  | Traceback (most recent call last):
09:47:50 worker.1  |   File "/home/skaplun/.virtualenvs/labs/src/inspire-next/inspire/modules/migrator/tasks.py", line 174, in create_record
09:47:50 worker.1  |     json = jobs.do(record)
09:47:50 worker.1  |   File "/home/skaplun/.virtualenvs/labs/local/lib/python2.7/site-packages/dojson/overdo.py", line 73, in do
09:47:50 worker.1  |     output[name] = creator(output, key, value)
09:47:50 worker.1  |   File "/home/skaplun/.virtualenvs/labs/src/inspire-next/inspire/dojson/jobs/fields/bd1xx.py", line 114, in continent
09:47:50 worker.1  |     return value.get('a')
09:47:50 worker.1  | AttributeError: 'list' object has no attribute 'get'
```
* [ ] support for multiple continents in Jobs dojson
* [ ] support for multiple continents in Jobs jsonschema
* [ ] support for multiple continents in Jobs elasticsearch mapping
* [ ] support for multiple continents in Jobs format

cc: @jmartinm @ioannistsanaktsidis

**Comment by ioannistsanaktsidis** [comment]
You can assign this one to me. I will take care.

**Comment by kaplun** [comment]
Thanks :+1:

**Comment by ioannistsanaktsidis** [comment]
As I see now this record contains in the continent this:
```
[{'a': 'Europe / South America'}, {'a': 'South America'}, {'a': 'Europe'}]
```
I can make it support a list, but is it correct to have all these in the record ?

**Comment by kaplun** [comment]
I think the first element is probably due to some past limitation. I guess just having:
`[{'a': 'South America'}, {'a': 'Europe'}]` would be the correct model. What record ID is this?

cc: @annetteholtkamp, @hoc3426
