### ISSUE TITLE
Facet display improvements

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#577]
* [ ] In some cases, there are facets that get empty. They should be removed

![screen shot 2015-11-30 at 11 21 01 am](https://cloud.githubusercontent.com/assets/580727/11469107/6f20e184-9754-11e5-90d9-8b4270c2b2aa.png)

* [ ] As an extra would be nice to be able to collapse the facet content. Like

![screen shot 2015-11-30 at 11 23 21 am](https://cloud.githubusercontent.com/assets/580727/11469168/c7e95846-9754-11e5-96a6-a7effcd794ca.png)

That will allow adding some filters that are less commonly used and collapse them by default.

**Comment by ioannistsanaktsidis** [comment]
@jmartinm  by default the facets will be opened or closed?
