### ISSUE TITLE
Detailed record: make filtering work

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#579]
The filter for References and Citations on detailed pages should be made to work.

The user should be able to type any part of a reference/citation and only that will be shown.

![screen shot 2015-11-30 at 11 33 24 am](https://cloud.githubusercontent.com/assets/580727/11469372/28d528dc-9756-11e5-93a9-ae852ca878bb.png)

**Comment by nikpap** [comment]
Think this one is no longer relevant and can be closed.
