### ISSUE TITLE
Export of multiple record bugs/enhancements

### ISSUE THREAD

**Issue by nikpap** [inspirehep/inspire-next#589]
In the search results, exporting a record can currently be done from two places: 

1. Clicking on the cite button, inside the record block
2. Selecting the record and downloading the file from the top of the search results.

A different file with a different name is produced in each case:

1. Bibtex[record-id].bibtex, where record-id is the id of the record
2. bibtex.bib

Therefore, we need to: 

- [ ] Decide the name of the file: see comments.
- [ ] Stick to the same extension eg. bib
- [ ] Provide modal window when selecting multiple records to export.
- [ ] Change id so it's more than an number. This would imply doing some changes in the JavaScript selectors as well. https://github.com/inspirehep/inspire-next/blob/master/inspirehep/base/templates/format/record/Inspire_Default_HTML_brief.tpl#L33
- [ ] Disable `download` button when search has 0 results but "all" are selected, using the checkbox next to the "Export as".

**Comment by kaplun** [comment]
Yep, the `.bib` extension is the only correct one.

**Comment by aw-bib** [comment]
I would suggest for the file name something that signifies iNSPIRE (bibtex sounds a bit too generic to me) I'm not entirely sure if it might be clever to add a some datestamp or the like so that subsequent downloads don't accidentally overwrite each other.

**Comment by nikpap** [comment]
> I would suggest for the file name something that signifies iNSPIRE (bibtex sounds a bit too generic to me)

INSPIRE + record title ? 

> I'm not entirely sure if it might be clever to add a some datestamp or the like so that subsequent downloads don't accidentally overwrite each other.

That's already handled by the browser, so there's no need to worry about it.

**Comment by aw-bib** [comment]
What would be `record title` for several records? For a single record, the full title could be a bit long.

**Comment by salmele** [comment]
> record title 

or recid?

For several recid (which is a distinct case if users would build an entire bibliography from a given search) the concatenation could be very long. Is there a moment where we have to worry about some OS not liking the size of the filename, and maybe just revert to INSPIRE+bibtex+timestamp ?

An (very likely) use case of the above would be a citedby:X search, so to reconstruct the outgoing reference list of a paper on a subject, if an author wishes to write a paper on a very similar subject, and have a citable bibtex in one go.

**Comment by kaplun** [comment]
Note that the users interviewed so far stated they simply prefer copy&paste than download because they have anyway opened their editor on the side. Last user suggested we can simply let the user to choose the file name by giving an optional textfield.

**Comment by aw-bib** [comment]
`recid` sounds good to me, if it's not considered to technical. Bibtex-keys would also be an option but Windows does not like the `:`.

To keep the names short (I think it is also a usability issue, if I want to import that beast to something like JabRef) one could consider `<fromid>-<toid>` giving the smallest and largest number, knowing that it might not be a sequence.

As @kaplun points out it is only a suggestion anway, but it is IMHO a good thing if it is a usable suggestion.

@kaplun for the copy&paste: we got a bunch(!) of tickets entirely negating your observation. Not all of them were too nice. I think having both options is the way to go.

**Comment by kaplun** [comment]
> @kaplun for the copy&paste: we got a bunch(!) of tickets entirely negating your observation. Not all of them were too nice.

Do you mean RT tickets in INSPIRE? Can you point me to those?

**Comment by aw-bib** [comment]
We == join2. No tickets in rt.

**Comment by salmele** [comment]
As we are currently unsure on the overlap in information practices of the two user bases, we could just feed this back into our next round of user testing for INSPIRE. Good.

**Comment by bing13** [comment]
+1 for the user testing.  

In the past we have indeed occasionally gotten tickets for "please can we get rid of the cut-and-paste, no modern site makes us do that."   But searching in RT stinks. The only ticket I could find was this one (which also refers to API): https://rt.inspirehep.net/Ticket/Display.html?id=363293

**Comment by aw-bib** [comment]
Usually, requests to download instead of copy&paste stem from people using graphical tools for literature management like JabRef, EndNote, Citavi, Zotero etc. These people integrate external databases into their local work flows of literature management and often use their local databases also for easy full text access to stored files. Set up properly, clicking the download will feed the references directly to their databases without having to fiddle with the file as such. Additionally, most of these tools do not allow to copy&paste a number of references in an (for them) import format. Thus dropping back to copy&paste translates to copy&paste per reference per field, or creating the file for import from copy&paste.

A userbase that might easily gets missed, depending on how users for testing are selected, are the secretaries who have to compile publication lists for project or time based reports etc. In HEP this is often done from iNSPIRE, especially if you have to collect publications of guest scientists. These are often word processor based work flows, which usually have to include something like EndNote/Citavi or the like for formatting.

**Comment by kaplun** [comment]
Just to clarify: the download functionality is not going to disappear.

What appeared through user testing is simply that users would like to have a chance to still cut & paste, or in general see the the BibTeX content *before* clicking on the download button.

Then there was the minor open question on how to call the downloaded content, but this is really minor.

So related to BibTeX generation, do not worry: both download and cut & paste workflows are going to be availble.

**Comment by jmartinm** [comment]
This issue can be closed, functionality is implemented in http://qa.inspirehep.net
