### ISSUE TITLE
Remove breadcrums ?

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#592]
As they are right now, breadcrums do not provide much useful navigation that a user would like to use:

In searches
========
![screen shot 2015-12-01 at 1 16 45 pm](https://cloud.githubusercontent.com/assets/580727/11500484/c669db24-982d-11e5-9597-5b009055421d.png)

In detailed views
==========
![screen shot 2015-12-01 at 1 26 40 pm](https://cloud.githubusercontent.com/assets/580727/11500708/22afc802-982f-11e5-8824-feafb943b088.png)

In submission form
==========
![screen shot 2015-12-01 at 1 18 44 pm](https://cloud.githubusercontent.com/assets/580727/11500686/fac8b830-982e-11e5-81a0-97c7a84ad768.png)

So I would suggest to omit them.

In the detailed page, the breadcrum could become a `Back to search results` link

![screen shot 2015-12-01 at 1 36 24 pm](https://cloud.githubusercontent.com/assets/580727/11500910/8e5040ea-9830-11e5-8306-cd98f635e3ca.png)

What do you think? @nikpap

**Comment by nikpap** [comment]
I agree that it might be best to remove breadcrumbs; in their current state they don't add any useful information.

Regarding the `Back to search results` link, would that be a link to the previous page in the browser history? In case the user comes eg from Google's search results or from a direct external link, would be opt to completely remove the breadcrumbs?

**Comment by jmartinm** [comment]
>  Regarding the Back to search results link, would that be a link to the previous page in the browser history? In case the user comes eg from Google's search results or from a direct external link, would be opt to completely remove the breadcrumbs?

That's a good point. By checking the `referer` in the request, if it comes from our search pages we could even personalize it with the query they used.

`< Back to search results for author:Ellis`

And if they come from an external site then we don't show anything and they can use the search bar on top.

**Comment by salmele** [comment]
We could then see how often this is used and, if unconvincing, axe it off the options.
Or maybe even try our hand with A/B testing upon launch and decide almost immediately.

**Comment by jmartinm** [comment]
> Or maybe even try our hand with A/B testing upon launch and decide almost immediately.

Sounds good, this can be a simple example to get the A/B testing tools in place.

**Comment by nikpap** [comment]
Note that there are some 'hidden' breadcrumbs behind the search bar:

![capture d ecran 2015-12-02 a 17 16 12](https://cloud.githubusercontent.com/assets/2742143/11536396/954e1ed8-9918-11e5-89b0-02d99c579cd8.png)

**Comment by jmartinm** [comment]
Breadcrums have now been removed.
