### ISSUE TITLE
Design in brief results

### ISSUE THREAD

**Issue by ioannistsanaktsidis** [inspirehep/inspire-next#594]
<img width="364" alt="screen shot 2015-12-01 at 14 56 27" src="https://cloud.githubusercontent.com/assets/7301890/11502560/d0233f8a-983b-11e5-9e6f-c6f879f8f3cc.png">

I think we should align all the boxes to be in the same level for consistency.

**Comment by nikpap** [comment]
Indeed, has been noted in https://github.com/inspirehep/inspire-next/issues/591

**Comment by ioannistsanaktsidis** [comment]
cool then i am closing mine.

2015-12-01 15:01 GMT+01:00 Nick Papoutsis <notifications@github.com>:
