### ISSUE TITLE
Brief and detailed production check

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#597]
Brief and detailed formats still lack some basic information that is currently displayed on production.

This is more obvious in some of the records:

![screen shot 2015-12-01 at 5 20 17 pm](https://cloud.githubusercontent.com/assets/580727/11506419/c514fc96-984f-11e5-9809-e9b5ecb487da.png)

The current [brief](https://github.com/inspirehep/inspire/blob/master/bibformat/format_templates/Default_HTML_brief.bft) and [detailed](https://github.com/inspirehep/inspire/blob/master/bibformat/format_templates/Default_HTML_detailed.bft) formats need to be reviewed, and the missing information needs to be added (prior decision if the information is still relevant)

Also the following needs to be fixed:

* [ ] Avoid blind capitalization - titles are being capitalized which does not make sense in most cases (due to acronyms or other parts of the title meant to be in capital letters). Only if a title is all in capital letters (like some older records) we should capitalize the title.

In order to compare one can search any record in inspirehep.net to see how it is currently displayed.

@ioannistsanaktsidis can you have a look?

**Comment by ioannistsanaktsidis** [comment]
@jmartinm Fixed publication info, added year, fixed title problem, added report numbers. That's what I discovered. Anything else in mind?
