### ISSUE TITLE
Normalization of hepnames/authors

### ISSUE THREAD

**Issue by jacenkow** [inspirehep/inspire-next#604]
I was wondering if we can carry out a normalization of ```hepnames / authors``` in the same way as it was done with ```hep``` for Elasticsearch.

For example, an author of a ```hep``` record will have all the fields but with ```null``` value for a not complete dataset.

```json
"authors": [
    {
     "profile": "",
     "alternative_name": null,
     "affiliations": [
        {
           "value": "Duke U."
        }
     ],
     "inspire_id": null,
     "name_variations": [
        "Fortney L",
        "Fortney L R",
        "Fortney R",
        "Fortney, L",
        "Fortney, L R",
        "Fortney, R",
        "L Fortney",
        "L R Fortney",
        "R Fortney"
     ],
     "claimed": null,
     "role": null,
     "full_name": "Fortney, L.R.",
     "orcid": null,
     "recid": null,
     "signature_block": "FARTNYl",
     "email": null,
     "uuid": "349cf597-cfe0-4fd3-a8c8-359cfb8b941b"
    }
]
```

But currently the ```hepnames / authors``` index not only introduces an empty string (```''```) in case of a missing field, but does not include all the fields (in this example ```ids```, ```source``` and others are missing). 

```json
  "oai_pmh": [
           {
              "set": "INSPIRE:HepNames",
              "id": "oai:inspirehep.net:983934"
           }
        ],
        "date_and_time_of_latest_transaction": "20140307233110.0",
        "name": {
           "status": "",
           "preferred_name": "Joerg Weber",
           "value": "Weber, Joerg"
        },
        "_collections": [
           "HepNames"
        ],
        "control_number": "983934",
        "positions": [
           {
              "status": [
                 "Current",
                 "902624"
              ],
              "end_date": "",
              "start_date": "",
              "rank": "",
              "institution": {
                 "name": "Aachen, Tech. Hochsch."
              }
           }
        ],
        "spires_sysnos": [
           "HEPNAMES-22985"
        ],
        "breadcrumb_title": "Weber, Joerg",
        "creation_modification_date": [
           {
              "creation_date": "1996-02-08"
           },
           {
              "modification_date": "2009-06-07"
           }
        ],
        "collections": [
           {
              "primary": "HEPNAMES"
           }
        ],
        "facet_inspire_subjects": []
     }
  }
]
```

What do you think?
@kaplun @jalavik @jmartinm

**Comment by kaplun** [comment]
Personally I think we should not have `null`/empty values. This are unnecessarily bloating the data. Elasticsearch should allow us to search for non filled up values, correct?

**Comment by jmartinm** [comment]
Yes, the fact that there are `null` values for HEP was not done in purpose and it is more a consequence of our `dojson` conversion. In fact @kaplun was doing some changes so that all these `null` values would be removed.

So the conclusion would be that records will only contain the information available and not all keys.

**Comment by kaplun** [comment]
Yes, I have a PR with this change: #617 (still not passing Travis) which contains this filtering.
