### ISSUE TITLE
Searching for a record title doesn't show the record in the results.

### ISSUE THREAD

**Issue by nikpap** [inspirehep/inspire-next#606]
Copy-pasting and searching for a record title usually shows 0 results.

Some queries are succesful: https://qa.inspirehep.net/search?cc=HEP&p=Horizons+of+knowledge+in+cosmology&action_search=&rg=25 correctly displays the right record. 

While fail:
https://qa.inspirehep.net/search?cc=HEP&p=About+functional+methods+in+superspace&action_search=&rg=25 
should probably show https://qa.inspirehep.net/record/181838 in the search results, but instead displays 0 results.

Tested on QA.

**Comment by jmartinm** [comment]
I guess related to https://github.com/inspirehep/inspire-next/issues/609

**Comment by jmartinm** [comment]
Fixed now.
