### ISSUE TITLE
Searching 101

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#609]
* On current legacy Invenio a query of the form of `foo bar baz`, was searching for **all and only** the documents having *all* the 3 words anywhere.
* On current legacy Invenio a query of the form of `key:value key2:value2` is matching **all and only** the documents having `value` in `key` and `value2` in `key2`.
*  On Google and default elasticsearch a query for the form `foo bar baz` is matching **all** the documents that have **at least** one of the words (hence an Invenio `foo or bar or baz`), but is ranking them by how much the document matches the query(!), hence documents having all the 3 words will be ranked higher and so on.

We keep on talking about INSPIRE offering Google like search capability, but what we have by default a `strict boolean and`, which is perfect for filtering, but not for information retrieval. 

Proposal
------------
Shall we change our default to be the elasticsearch one, and fall back to the Invenio `default boolean and `as soon as one uses a *keyworded* search? Baisc boolean filtering is then offered anyway by facets.

Usage of quotes
----------------------
We could still use the Invenio convention: something quoted should not be *massaged*. So no stemming, no removal of plurals, no normalization of spaces (or maybe yes?).

**Comment by jmartinm** [comment]
+1 for Elasticsearch way when not using any specific syntax `foo bar baz`

The best practice is to have as many results as possible and ElasticSearch should do a good job in the ranking.

**Comment by annetteholtkamp** [comment]
If we go for this option we should make it transparent to the user whether all words have been found or not. Google shows you the unmatched words by striking through them. 
Or we should add a tick box: Match all terms (use ‘and' instead of ‘or')

- Annette

**Comment by aw-bib** [comment]
> The best practice is to have as many results as possible 

I may buy this for google. I'm pretty sure I do not (at least not in this generality) if I'm searching scientific literature.

Usually, the problem there is that you get to many results that you need to narrow down, and unlike google where basically any document that is _good enough_ serves in the scientific case you're searching _the_ relevant paper. And relevance in itself here gets very difficult. More keys that match (the google case) is usually way to simple.

In your language I usually had the worst of user experiences as soon as bibliographic databases just threw whatever sounds only half plausible by some algorithm at me.

In any case an option to have boolean search is mandatory.

**Comment by ksachs** [comment]
It has to be transparent what this thing is doing. I.e. keep it simple or at least tell the user what was done (and why) so they have a chance of understanding the query. I guess I have to see it before I understand your proposal.

**Comment by kaplun** [comment]
> I may buy this for google. I'm pretty sure I do not (at least not in this generality) if I'm searching scientific literature.

> Usually, the problem there is that you get to many results that you need to narrow down, and unlike google where basically any document that is good enough serves in the scientific case you're searching the relevant paper. And relevance in itself here gets very difficult. More keys that match (the google case) is usually way to simple.

Unfortunately this is not what we are experiencing day by day with user testing. All users interviewed so far said they are typing thing in INSPIRE ala Google, then don't find what they want (either deluge of unrelated results or no results at all), then they move to Google and there they find the exact paper they want in the first 3 results. This is because when they are looking for a paper, what they are searching for is some approximation of the title and/or author and in the current Invenio we fail because we don't apply sensible ranking nor we are graceful in the exactness of the query. By letting elasticsearch do by default what is designed to do best, we are going to have basically the Google behavior expected by users. 

A different case is when the user is searching for a specific ID, but then again we can rank high those papers that have the ID not just mentioned in references but really in the metadata.

Another common use case is where users are just copy & pasting a reference from a PDF into the search bar, and there we have the possibilities of being better than Google (as we are already today).

**Comment by aw-bib** [comment]
Probably, I only get those jobs to my desk where people can not find it in google right away (ie. the not entirely trivial things). As I treat them as very valid use cases, especially for a specialized database, at least have an option to get exact matches "for what I ask for". For me one selling point of invenio is that I can have a complex question.

**Comment by bing13** [comment]
I agree with the suggestion we leverage elasticsearch's strength as the default. Annette's suggestion that we flag when we return results that are missing terms would be extremely helpful, I think.

As mentioned, this would increase the importance of offering an obvious option for submitting an exact query.

**Comment by kaplun** [comment]
> Probably, I only get those jobs to my desk where people can not find it in google right away (ie. the not entirely trivial things). As I treat them as very valid use cases, especially for a specialized database, at least have an option to get exact matches "for what I ask for". For me one selling point of invenio is that I can have a complex question.

Yes, the complex queries will fully be supported. The main question here is more for the simple Google like ones, whether to go for default elasticsearch behavior. I think the overall consensus is summarized by @bing13 in the above comment.

**Comment by jmartinm** [comment]
As there seems to be agreement on this, I have created this task - https://github.com/inspirehep/inspire-next/issues/682 Please, check if it is complete and we can then close this RFC.
