### ISSUE TITLE
Using native elasticsearch autocompletion

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#611]
Elasticsearch supports a native datatype suitable for auto-completion  (whatever that means):
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-completion.html

Would be great to investigate it and, in case, take advantage of it in all our auto-completion usecases.

cc: @jmartinm

**Comment by jmartinm** [comment]
This is already being used in https://github.com/inspirehep/record-editor

**Comment by kaplun** [comment]
You mean we have proper mapper with the correct indexes?

**Comment by jmartinm** [comment]
For each index, `invenio-records-rest` allows some configuration of suggesters - https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/views.py#L688
