### ISSUE TITLE
Literature submission to check for real PDF

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#619]
Currently in the literature submission a check is missing (or broken) to check whether a specified URL of a PDF corresponds to actually a PDF (and not a splash page).

E.g. the system got tricket by the URL http://escholarship.org/uc/item/93t675vk.pdf (which redirects normal agents to a web page displaying the PDF in an iframe).

cc: @annetteholtkamp

**Comment by jmartinm** [comment]
The current Labs uses a legacy function for the check:

```python
def pdf_validator(form, field):
    """Validate that url points to PDF."""
    from invenio.legacy.bibdocfile.api import guess_format_from_url
    message = "Please, provide a direct link to a PDF document."

    if field.data and guess_format_from_url(field.data) != ".pdf":
        raise StopValidation(message)
```

And as that function disappeared, the new Labs (once deployed) will have:

```python
def pdf_validator(form, field):
    """Validate that url points to PDF."""
    import requests

    def get_content_type(url):
        session = requests.Session()
        try:
            response = session.head(
                url,
                allow_redirects=True
            )
        except:
            return
        return response.headers['content-type']

    message = "Please, provide an accessible direct link to a PDF document."

    if field.data and get_content_type(field.data) != 'application/pdf':
        raise StopValidation(message)
```

Might not be able to capture those special cases.

**Comment by kaplun** [comment]
The old implementation uses head as well as a first technique. This might explain why it is currently failing. So we after the upgrade we are probably going to offer the same service.

Might still good then to keep this ticket open, until we implement the full check of download and `magic` check.

**Comment by jalavik** [comment]
We should check and compare with some of the failing cases as I suspect the `requests` solution might perform better due to redirects etc. 

PS: Some legacy applications may report back `application/x-pdf` as content-type, so potentially we can use something like `'pdf' in content_type`.

**Comment by jalavik** [comment]
Another case I have seen in the MARCXML sent to production is that `FFT__a` lacks the protocol scheme (`http(s)://`) and it fails.

**Comment by kaplun** [comment]
Ideally the final solution is really to try to follow the URL on Labs, try to download the PDF and see if it is indeed a PDF, and if it not also corrupted.

See also a quick check based on PyPDF2 in inspirehep/invenio#300

**Comment by jmartinm** [comment]
Continued in https://github.com/inspirehep/inspire-next/issues/619

**Comment by kaplun** [comment]
Ahem... This is #619 :dancing_men: it's kind of recursive ahaha.

**Comment by jmartinm** [comment]
I meant https://github.com/inspirehep/inspire-next/issues/1057
