### ISSUE TITLE
Journal publication info in HEP brief results

### ISSUE THREAD

**Issue by nikpap** [inspirehep/inspire-next#637]
Streamline the display of journal in brief results: 
https://github.com/inspirehep/inspire-next/blob/master/inspirehep/base/templates/format/record/Inspire_Default_HTML_brief_macros.tpl#L31-L43 

with what is currently used in production: https://github.com/inspirehep/inspire/blob/master/bibformat/format_elements/bfe_INSPIRE_publi_info.py#L28

**Comment by jmartinm** [comment]
To be done together with https://github.com/inspirehep/inspire-next/issues/541
