### ISSUE TITLE
Collections top bar vertical space

### ISSUE THREAD

**Issue by nikpap** [inspirehep/inspire-next#639]
The bar that is displayed on top of each page (displaying collections) currently takes up too much vertical space, especially on mobile. Therefore, it is suggested that the bar is hidden on scroll down, to resurface only when the user scrolls upwards.

Another option would be to somehow merge the collections bar in the top bar. There's some free space in between the logo and the resources menu.

**Comment by bing13** [comment]
the bar with the INSPIRE Labs logo?

**Comment by nikpap** [comment]
I'm referring to the second bar displaying the collections, as seen in https://qa.inspirehep.net/literature. I've edited the original message to make it clearer.

**Comment by bing13** [comment]
Thanks. I agree it would be a good goal to conserve that vertical space.  I think it's a nice affordance  to have all of the collections listed out. It's also essential to explaining the information architecture, so I wouldn't recommend we hide that.  Not sure what the design options would be - perhaps just tightening up the vertical spacing within the two bars?

**Comment by nikpap** [comment]
I'm not suggesting to completely hide the collections bar. I'm referring to an implementation like the Guardian's : http://www.theguardian.com/international.

The categories (collections in our case) are initially shown, however they are hidden when the user scrolls down, to provide more space for the content. Once the user scrolls up, the collection will be once again shown. I believe that's a valid trade-off between showing the categories and conserving the much needed vertical space.

**Comment by jmartinm** [comment]
+1 for that thin bar when scrolling down that would include search.

I am not sure showing the collections is needed when scrolling up though. As we have seen in our user testing that all the users stay in `Literature`, except some rare cases, I think the user that really needs it can scroll to the top of the page and change Collection.

**Comment by jmartinm** [comment]
This has been resolved.
