### ISSUE TITLE
Modify facet behaviour to perform AND boolean operation for a given facet

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#649]
Currently, facets perform and OR query inside of a facet and AND query between facets.

As the numbers ElasticSearch returns correspond to the AND operation this is confusing, plus clicking on a second option inside of one facet brings more results instead of drilling down the results which causes user confusion.

![screen shot 2015-12-11 at 11 38 28 am](https://cloud.githubusercontent.com/assets/580727/11741820/b8d2f9a2-9ffb-11e5-98a7-4f5d25db2663.png)

The default boolean operator should be changed for AND in all cases.

**Comment by ioannistsanaktsidis** [comment]
@jmartinm  the PR for the issue.  https://github.com/inspirehep/invenio-search/pull/11

**Comment by kaplun** [comment]
Are we sure we don't want to adjust this facet by facets? E.g. document type should really be in OR

**Comment by kaplun** [comment]
The same for year
