### ISSUE TITLE
Safari keeps reloading the page

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#657]
The search results page reloads indefinitely in Safari.

**Comment by ioannistsanaktsidis** [comment]
@jmartinm  seems like we have this problem for a long time now. I am reverting commits and it is not fixed. You can assign it to me, I will take care.

**Comment by jmartinm** [comment]
Thanks, @jalavik was also going to take a look today, you can update him if you discover what is going on.

**Comment by ioannistsanaktsidis** [comment]
Cool! ;)

**Comment by jmartinm** [comment]
Fixed https://github.com/inspirehep/invenio-search/pull/13
