### ISSUE TITLE
find a search

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#661]
The following search `find a Mangano, m` seems to not be working properly.

On INSPIRE, one can see that the authors in the papers include the author one is looking for (Michelangelo Mangano and his variations):

http://inspirehep.net/search?ln=en&ln=en&p=find+a+Mangano%2C+m

Instead on the local machine, the search brings unrelated results:

![screen shot 2015-12-15 at 10 03 16 am](https://cloud.githubusercontent.com/assets/580727/11806408/1a48c8e6-a313-11e5-9f37-53b76aca2ed4.png)

**Comment by jmartinm** [comment]
Related work in progress - https://github.com/inspirehep/invenio-search/pull/14

@Panos512

**Comment by Panos512** [comment]
I think this is ready to be closed
