### ISSUE TITLE
Complex queries

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#676]
We should be able to support complex queries as in:
`(773__w:C14/06/16 or 773__w:C14-06-16 and 980__a:ConferencePaper) AND (refersto:journal:"Phys.Rev.ST Accel.Beams" or refersto:journal:"PRSTAB")`

-> http://inspirehep.net/search?ln=en&ln=en&p=%28773__w%3AC14%2F06%2F16+or+773__w%3AC14-06-16+and+980__a%3AConferencePaper%29+AND+%28refersto%3Ajournal%3A%22Phys.Rev.ST+Accel.Beams%22+or+refersto%3Ajournal%3A%22PRSTAB%22%29&of=hb&action_search=Search&sf=earliestdate&so=d&rm=&rg=25&sc=0&wl=0

and `year:2013 (citedby:773__w:C14/06/16 or citedby:773__w:C14-06-16) AND (journal:"Phys.Rev.ST Accel.Beams"  or journal:"PRSTAB")`

-> https://inspirehep.net/search?ln=en&ln=en&p=year%3A2013+%28citedby%3A773__w%3AC14%2F06%2F16+or+citedby%3A773__w%3AC14-06-16%29+AND+%28journal%3A%22Phys.Rev.ST+Accel.Beams%22++or+journal%3A%22PRSTAB%22%29&of=hb&action_search=Search&sf=earliestdate&so=d&rm=&rg=25&sc=0

**Comment by chris-asl** [comment]
This example provides queries on Marc codes, which we are not going to support on `inspire-next`. 
We support searching for the equivalent marc codes and in the future we are going to support both Journal searches but also `refersto` queries.

The search goals are going to tracked in a new search related milestone that @StellaCh is going to create.
