### ISSUE TITLE
Record links

### ISSUE THREAD

**Issue by nikpap** [inspirehep/inspire-next#677]
"View in" is only displayed if they're is at least one from ADS or SLAC. This needs to be amended to include make sure there's at least one link in general.

https://github.com/inspirehep/inspire-next/blob/master/inspirehep/base/templates/format/record/Inspire_HTML_detailed_macros.tpl#L226-L228

**Comment by jmartinm** [comment]
By the way, note this change on ADS linking https://github.com/inspirehep/inspire/pull/145/files It needs to be taken into account as the metadata that we receive for new records will have the ADS information in field `035` instead of the `url`.

**Comment by jmartinm** [comment]
Also the text `View in` is not being displayed (at least in some cases)

![screen shot 2016-02-09 at 4 44 55 pm](https://cloud.githubusercontent.com/assets/580727/12921244/903f5852-cf4c-11e5-9acb-342660ecedce.png)

That record in the example is https://inspirehep.net/record/710976 which has many outgoing links (but only the SLAC one is being shown)
