### ISSUE TITLE
Search bar and collections bar styling

### ISSUE THREAD

**Issue by nikpap** [inspirehep/inspire-next#679]
This is the proposed style in order to save a lot of vertical space.

![labs-results](https://cloud.githubusercontent.com/assets/2742143/12094273/fb14f986-b307-11e5-91e3-9f1b6e763462.jpg)
![labs-detailed](https://cloud.githubusercontent.com/assets/2742143/12094274/fb15339c-b307-11e5-8eb9-5c00c5ac0be8.jpg)

**Comment by jacquerie** [comment]
Can we preserve the colors, at least as a hint? Like, a colored bar at the bottom/top of each collection button, or just a corner.

**Comment by nikpap** [comment]
Yes. An idea would be to have the background color of each button reflect the color of the collection eg orange for literature.

**Comment by jmartinm** [comment]
Done.
