### ISSUE TITLE
Complete support for Spires and Invenio keywords

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#683]
* [ ] Spires syntax [translates to the following keywords](https://github.com/inspirehep/invenio-query-parser/blob/master/invenio_query_parser/contrib/spires/config.py#L26).

```python
In [3]: set(SPIRES_KEYWORDS.values())
Out[3]:
{'037__c',
 '046__a',
 '246__a',
 '595',
 '650__a',
 '695__a',
 '773__y',
 '970__a',
 'address',
 'affiliation',
 'anyfield',
 'arXiv',
 'author',
 'authorcount',
 'caption',
 'cataloguer',
 'cited',
 'citedby',
 'collaboration',
 'collection',
 'confnumber',
 'country',
 'datecreated',
 'datemodified',
 'doc_type',
 'doi',
 'earliest_date',
 'exactauthor',
 'experiment',
 'firstauthor',
 'fulltext',
 'journal',
 'journalpage',
 'keyword',
 'note',
 'postalcode',
 'rank',
 'rawref',
 'recid',
 'reference',
 'refersto',
 'region',
 'reportnumber',
 'subject',
 'texkey',
 'title',
 'year'}
```

Each of them needs to be configured either at [indexing time](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/base/searchext/mappings/hep.json) or at [query time (where several fields and boosts can be defined)](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/config.py#L300)

The following document https://docs.google.com/spreadsheets/d/1Mm5FWjQV4V5pp3pQkRZ3LHxNJTAGSD_122huIaJFN7s/edit?usp=sharing constains for the current INSPIRE the list of allowed keywords and the corresponding MARC tags. The equivalent for each MARC tag can be found in the [dojson configuration](https://github.com/inspirehep/inspire-next/tree/master/inspirehep/dojson/hep/fields).

**Comment by ioannistsanaktsidis** [comment]
After checking all the fields and making some searches I get the following results.
037__c:'astro-ph.CO' Labs:10 results, Legacy:10 results,
 '046__a': Missing field,
246__a:'Integrated Sachs Wolfe Effect and Rees Sciama Effect' Labs:1 result, Legacy:1 result,
 '595': not working,
 650__a:'Astrophysics' Labs:53 results, Legacy:0 results,
695__a:'anisotropy' Labs: 7 results, Legacy: 7 results,
 773__y: 1998 Labs:22 results, Legacy: 22 results,
 '970__a: Missing',
address:'CMS Collaboration' Labs:27 results, Legacy 27 results,
 affiliation:'KMI, Nagoya' Labs:3 results, Legacy 3 results,
affiliation:'CMS Collaboration' Labs:27 results, Legacy: 27 results,
anyfield:'Nishizawa:2014vga' Labs: Exception, Legacy: 1 result,
anyfield:'DA15-kp44g' Labs: Exception, Legacy: 1 result,
anyfield:'CERN-PH-EP-2015-208' Labs: Exception, Legacy: 1 result,
anyfield:'astro-ph.CO' Labs: Exception, Legacy: 15 results,
anyfield:'five-dimensional Anti-de Sitter space' Labs: Exception, Legacy: 1 result,
anyfield:'The integrated Sachs–Wolfe effect and the Rees–Sciama effect' Labs: Exception, Legacy: 1 result,
anyfield:'Integrated Sachs Wolfe Effect and Rees Sciama Effect' Labs: Exception, Legacy: 1 result,
 'arXiv',
 'author',
 'authorcount',
 'caption',
 'cataloguer',
 'cited',
 'citedby',
 'collaboration',
 'collection',
 'confnumber',
 'country',
 'datecreated',
 'datemodified',
 'doc_type',
 'doi',
 'earliest_date',
 'exactauthor',
 'experiment',
 'firstauthor',
 'fulltext',
 'journal',
 'journalpage',
 'keyword',
 'note',
 'postalcode',
 'rank',
 'rawref',
 'recid',
 'reference',
 'refersto',
 'region',
 'reportnumber',
 'subject',
 'texkey',
 'title',
 'year'

**Comment by ioannistsanaktsidis** [comment]
In the above comment I will comment the searches that I am testing and the results that I am getting from  labs and legacy. Ideally in the end we should have the same results. Cheers.

**Comment by ioannistsanaktsidis** [comment]
As discussed with @Panos512  for testing this correctly I should rebase invenio-search and invenio-parser? Is that right?
cc @jmartinm @kaplun

**Comment by kaplun** [comment]
@ioannistsanaktsidis you should take the OPS version from our inspirehep private repositories. So basically you would fork inspirehep/invenio-query-parser and inspirehep/invenio-search and `pip install -e .` in your local environment. This should allow you directly edit them.

**Comment by ioannistsanaktsidis** [comment]
@kaplun  thnx, although I do not need to edit them, just to check what results are returned ;)
