### ISSUE TITLE
Select automatically bibtex when clicking on Cite

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#688]
To speed up, the use case of getting, e.g the BibTex of a paper, it would be good if when clicking on `Cite` on a brief or detailed view the content would be automatically selected.

![screen shot 2016-01-07 at 10 26 42 am](https://cloud.githubusercontent.com/assets/580727/12166886/3caecee4-b529-11e5-95d5-89c9eb5198d3.png)

See, for example, how the cite button works in https://www.semanticscholar.org/paper/a30bb4ac51d18af3c4e72b5944742c3ade56eb10

* [ ] Add `Copy to clipboard` button using https://zenorocha.github.io/clipboard.js/

**Comment by bing13** [comment]
Nice. What about a "copy to clipboard" button?

**Comment by jmartinm** [comment]
Yes, that would be nice too. It was always a bit tricky to implement but I see this library might do the job https://zenorocha.github.io/clipboard.js/
