### ISSUE TITLE
Journal search

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#693]
It should be possible to search for: `journal:Phys.Rept.` as well as `journal:Phys journal:Rept` (generated automatically by SPIRES syntax `find j Phys Rept`. This does not work on legacy but would it be great if it worked on Labs.

See also: https://rt.inspirehep.net/Ticket/Display.html?id=323751

**Comment by StellaCh** [comment]
addressed by https://github.com/inspirehep/inspire-query-parser/
