### ISSUE TITLE
Document type multiple preprint

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#694]
Records get multiple times the preprint document type. See for example https://qa.inspirehep.net/record/146539/export/recjson (field `facet_inspire_doc_type`)

This is due to the following code https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/records/receivers.py#L66 where for each collection as a fallback the type `preprint` is being added.

**Comment by ioannistsanaktsidis** [comment]
@jmartinm  could you pls remind me the fallback? It was sth like if nothing exists and we have publication info  and  there is not page_artid in publication info we add 'preprint' right?

**Comment by annetteholtkamp** [comment]
If it’s neither:

published
thesis
book
bookchapter
proceedings
note

and it has no complete publication info in 773 (complete means it has a 773__c) then it’s a preprint.

- Annette

**Comment by ioannistsanaktsidis** [comment]
@annetteholtkamp  thank you !
