### ISSUE TITLE
Filter by year: elements with 0 matches

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#695]
A search like https://qa.inspirehep.net/search?post_filter=(doc_type%3A%22proceedings%22%20AND%20doc_type%3A%22review%22%20AND%20doc_type%3A%22preprint%22)

yields in the year filter some elements with 0 matches:

![screen shot 2016-01-11 at 11 10 15 am](https://cloud.githubusercontent.com/assets/580727/12230924/eca3a630-b853-11e5-82da-cd990e46d385.png)

**Comment by jmartinm** [comment]
By the way, with the help of @eamonnmag and to make that facet more useful we should move to an approach like the one here https://www.semanticscholar.org/search?q=%22Pedro%20M.%20Domingos%22 as our user testing suggests that selecting exact years is not a typical use case (better to have a range)

**Comment by ioannistsanaktsidis** [comment]
I guess it should be used d3, right @eamonnmag ? I would like to work on that, although I have almost no idea on d3 :P
