### ISSUE TITLE
Fix publi_info display in latex.

### ISSUE THREAD

**Issue by ioannistsanaktsidis** [inspirehep/inspire-next#697]
Currently due to some model changes we did, we caused a problem in publi_info.
<img width="869" alt="screen shot 2016-01-11 at 13 28 19" src="https://cloud.githubusercontent.com/assets/7301890/12233393/365d455c-b867-11e5-8839-d6ff89dcd4f2.png">

**Comment by ioannistsanaktsidis** [comment]
@jmartinm you can assign this to me.

**Comment by kaplun** [comment]
Would be great to add a test to ensure there are no longer regression on these less visible formats.

**Comment by ioannistsanaktsidis** [comment]
:+1:
