### ISSUE TITLE
Duplicate dois in model

### ISSUE THREAD

**Issue by ioannistsanaktsidis** [inspirehep/inspire-next#709]
We need to clean the dois field as there are still duplicate values in it.
```
[{u'value': u'10.1016/S0370-2693(98)01167-8'}, {u'value': u'10.1016/S0370-2693(98)01167-8'}]
```

**Comment by ioannistsanaktsidis** [comment]
@jmartinm you can assign this to me.

**Comment by jmartinm** [comment]
@kaplun as mentioned here https://github.com/inspirehep/inspire-next/issues/685#issue-125186762

Shall we on ingestion time make sure the doi does not have any prefix?

**Comment by kaplun** [comment]
Yep, actually we could use the `before_record_insert` and `before_record_update` signals for that, and in general for all these easy normalizations...

**Comment by jmartinm** [comment]
@ioannistsanaktsidis something was done with this?

**Comment by ioannistsanaktsidis** [comment]
Not with before_record_insert and update. The records still come with duplicate dois but  I am filtering in dojson so as they are displayed unique.
