### ISSUE TITLE
Indexing issues earliest_date

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#722]
On the latest data import from production, the following records could not be indexed due malformed `earliest_date`:

```
4723
42299
42313
42316
45160
45181
45282
45295
44636
44637
44644
44650
44652
44653
44666
44687
44706
44707
44708
44919
44920
44921
44993
48481
47893
340070
737285
1376107
```

Error is:

```
{u\'type\': u\'mapper_parsing_exception\', u\'reason\': u\'failed to parse [earliest_date]\', u\'caused_by\': {u\'reason\': u\'Invalid format: ""\', u\'type\': u\'illegal_argument_exception\'}
```

Here is where we set the field `earliest_date` - https://github.com/inspirehep/inspire-next/blob/5f98853705a19c103d2eff3d7613509cd00cb842/inspirehep/dojson/hep/receivers.py#L32

Might be that those records do not have a value in the field. That could be prevented if enhanced XML includes creation_date (see https://github.com/inspirehep/inspire-next/issues/721)

**Comment by annetteholtkamp** [comment]
I checked a few, and they all have a date field - most of them 773__y. Do you have any expectation on the range of years? The ones I looked up had all a year before 1900.

- Annette

**Comment by jmartinm** [comment]
Thanks @annetteholtkamp 

Indeed the problem (or one of them) seems to be:

```python
In [1]: from inspirehep.dojson.utils import create_valid_date

In [2]: create_valid_date(1862)
Out[2]: ''

In [3]: create_valid_date(1901)
Out[3]: '1901-01-01'
```

**Comment by jalavik** [comment]
Good ol' dates before 1900 issue. In Invenio date utils we fixed it a while back. Perhaps the utility can fall back to it, or use it somehow. https://github.com/inveniosoftware/invenio-utils/blob/master/invenio_utils/date.py

**Comment by jmartinm** [comment]
Thanks @jalavik just had a look and tried some of the utilities there but did not see any that by passing a year like the example above would return the correct year `1862-01-01` do you know which one should be used?

**Comment by jalavik** [comment]
I believe we can close this issue after the date fix?

**Comment by kaplun** [comment]
Yes, the earliest date algorithm should still be improved but this particular issue can be closed.
