### ISSUE TITLE
Bug in handling experiments

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#735]
See: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/9799/
```python
Stacktrace (le chiamate più recenti alla fine):

  File "inspirehep/modules/migrator/tasks.py", line 202, in migrate_chunk
    before_record_index.send(recid, json=json, index=index)
  File "blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "inspirehep/modules/records/receivers.py", line 94, in match_valid_experiments
    experiment = experiment.lower()
```
AttributeError Root Cause
'NoneType' object has no attribute 'lower'

**Comment by Panos512** [comment]
That's strange. If the `accelerator_experiments` field of a record is empty it shouldn't proceed - https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/records/receivers.py#L88
