### ISSUE TITLE
 Fix the citation number latex

### ISSUE THREAD

**Issue by ioannistsanaktsidis** [inspirehep/inspire-next#737]
Currently in the output formats (latex, cv latex) we are missing the citation number. 
e.g %245 citations counted in INSPIRE as of 21 Aug 2015

**Comment by ioannistsanaktsidis** [comment]
cc @jmartinm @kaplun you can assign this to me.

**Comment by ioannistsanaktsidis** [comment]
@kaplun  @jmartinm  I am looking the legacy code and I see that for the date we used.
from invenio.bibrank_tag_based_indexer import get_lastupdated
Is this the same as u'creation_modification_date field we have?

**Comment by ioannistsanaktsidis** [comment]
this is the function used in legacy
```
def get_lastupdated(rank_method_code):
    """Get the last time the rank method was updated"""
    res = run_sql("SELECT rnkMETHOD.last_updated FROM rnkMETHOD WHERE name=%s", (rank_method_code, ))
    if res:
        return res[0][0]
    else:
        raise Exception("Is this the first run? Please do a complete update.")
```

**Comment by kaplun** [comment]
Nope, not really. This is the last time the ranking algorithm responsible for computing citations has run. I think we can skip mentioning this date in Labs, since these numbers should be computed at runtime nowadays, and always be correct.

**Comment by ioannistsanaktsidis** [comment]
So we can just keep this:
```
%245 citations counted in INSPIRE
```
?

**Comment by jmartinm** [comment]
> So we can just keep this: 
%245 citations counted in INSPIRE
?

:+1:

**Comment by kaplun** [comment]
Uh Actually, before it's too late I think I understand what is the intention behind that date: the fact is that the number of citation is not a fixed thing and evolves as time passes. So the above comment is useful in the sense that is stating that the given number of citation is the number known at a given date.

So what we could do is still presenting the date, but just using *today* as the date.

**Comment by ioannistsanaktsidis** [comment]
@kaplun thnx :) It is not merged yet, so I will amend the commit. Cheers!
