### ISSUE TITLE
Errors in detailed records for qa.inspirehep.net

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#738]
After running a test against all records in qa.inspirehep.net to see which detailed records would cause an error, here is [a list with 27142 of them](https://www.dropbox.com/s/mkva4fu3a4jmk2j/failed-recids.txt?dl=0).

I have extracted the XML from production so that the records can get loaded locally and fixed.

https://www.dropbox.com/s/x5gn76k4myasrco/bad-xml.xml?dl=0

To load locally:

```bash
inveniomanage migrator populate -f ~/Desktop/bad-xml.xml
```

Probably there are just few errors being repeated multiple times.

**Comment by ioannistsanaktsidis** [comment]
After fixing some errors and trying to load again the bad-xml I am getting in some records this strange error:
```
17:38:10 worker.1    | InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1205, 'Lock wait timeout exceeded; try restarting transaction') [SQL: u'INSERT INTO bibrec (id, additional_info) VALUES (%s, %s)'] [parameters: (19146, None)]
```

cc @jmartinm @kaplun  any ideas?

**Comment by kaplun** [comment]
This could mean many things and depends a lot on what has happened before. Basically it means that a session has been rolledback but not closed... Where it is happening?

**Comment by ioannistsanaktsidis** [comment]
while I am trying to load the bad-xml file. First I get this
```
17:38:10 worker.1    | [2016-01-20 17:38:10,722: ERROR/Worker-3] inspirehep.modules.migrator.tasks.migrate_chunk[e3c8db3c-46d4-4ca8-a871-cf1bfaf59562]: ERROR with record None and json None
```
and then the one I sent before

**Comment by ioannistsanaktsidis** [comment]
Is it normal to happen sth like  this ? 
```
11:59:56 worker.1    | [2016-01-21 11:59:56,924: ERROR/Worker-6] inspirehep.modules.migrator.tasks.migrate_chunk[5375f0b3-8a0f-4845-b746-73436b720cfe]: ERROR with record None and json None
```
It happens when I load the records.
Also some records doesn't seem to have the collections field.
