### ISSUE TITLE
Collaboration.raw leftover in SEARCH_ELASTIC_KEYWORD_MAPPING

### ISSUE THREAD

**Issue by jalavik** [inspirehep/inspire-next#740]
d87a90dab0f4e168b496ebadc262b561c1fb5769 changed the collaboration spec and it is no longer any `raw` property. Shall this be reflected also in `SEARCH_ELASTIC_KEYWORD_MAPPING`? E.g. change to `collaboration.value`.

PS: hep-0.0.1.json schema needs to be updated as well.

cc @ioannistsanaktsidis @jmartinm

**Comment by ioannistsanaktsidis** [comment]
@jalavik  I guess we can keep only the [collaboration.value]. I am changing the SEARCH_ELASTIC_KEYWORD_MAPPING in this task https://github.com/inspirehep/inspire-next/pull/700/files so it will be removed when the PR is merged.

**Comment by jalavik** [comment]
@ioannistsanaktsidis Cool! Will the schema also be updated to reflect current data model as well?

**Comment by ioannistsanaktsidis** [comment]
Yes we should also update the hep-0.0.1.json. I can create a task for this and as soon all the related model tasks we have are merged, I can take care of updating the whole json. Cheers!

**Comment by jmartinm** [comment]
Looking at the kind of values that exist in the collaboration field https://github.com/inspirehep/inspire-next/blob/master/inspirehep/dojson/current_marcxml_usage/hep.txt#L6853 I think we should still keep an analyzed version and the raw version.

Keeping only the not-analyzed would make it quite difficult to find.

And `SEARCH_ELASTIC_KEYWORD_MAPPING` should contain:

```
"collaboration": ["collaboration", "collaboration.raw^2"]
```

**Comment by ioannistsanaktsidis** [comment]
:+1:

**Comment by ioannistsanaktsidis** [comment]
@jalavik I guess we can close this issue as long as are not making any changes in the end.
