### ISSUE TITLE
Update hep-0.0.1.json schema.

### ISSUE THREAD

**Issue by ioannistsanaktsidis** [inspirehep/inspire-next#741]
After all the related model tasks are merged we should update the hep-0.0.1.json so as to keep the schema up to date.

**Comment by ioannistsanaktsidis** [comment]
@jmartinm you can assign this to me,

**Comment by jmartinm** [comment]
Maybe you can add a pointer to the tasks that need to be merged?

**Comment by ioannistsanaktsidis** [comment]
The tasks that need to be merged first:
https://github.com/inspirehep/inspire-next/issues/683
https://github.com/inspirehep/inspire-next/issues/724
https://github.com/inspirehep/inspire-next/issues/721

**Comment by jmartinm** [comment]
@ioannistsanaktsidis all the tasks above are already closed/merged. Please, have a look at discrepancies with the schema and we can close this issue.

**Comment by ioannistsanaktsidis** [comment]
:+1:
