### ISSUE TITLE
authors: signature assignment IndexError on bad authors

### ISSUE THREAD

**Issue by jalavik** [inspirehep/inspire-next#746]
The `before_record_index` receiver `assign_signature_block` raises an exception if the author name passed to beard is malformed, e.g. ``{'author_name': u'., '}``.

The receiver should in this case catch this exception (or validate authorname beforehand) so that it does not cause the indexing to fail. Another issue is, what should then be assigned to ``signature_block`` value of the author? I'd presume nothing, but I dunno if some other assumptions are in place that it is filled for every indexed author.

@kaplun @jacenkow

**Comment by jalavik** [comment]
How to reproduce:

```python
from beard.clustering import block_phonetic
import numpy as np

name = {'author_name': u'., '}
signature_block = block_phonetic(
    np.array([name], dtype=np.object).reshape(-1, 1),
    threshold=0,
    phonetic_algorithm='nysiis'
)
```

**Comment by kaplun** [comment]
The signature block is there in order to be able to search very easily for similar signatures, and perform author disambiguation. For such invalid names, we can happily ignore exceptions.
