### ISSUE TITLE
Errors in brief records for qa.inspirehep.net

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#747]
After doing a full test on all the brief formats on qa.inspirehep.net the following errors appear:

Recid | Error
------------ | -------------
874680 | unhashable type: 'list'
1230870 | expected string or buffer
1238277 | unhashable type: 'list'
1317440 | expected string or buffer

The xml can be downloaded, for example, https://qa.inspirehep.net/record/874680/export/xm

Loaded locally:

```bash
$ inveniomanage migrator populate -f ~/Desktop/xm.xml
```

And then test the brief format:

```bash
$ inveniomanage shell
```

```python
from invenio_ext.es import es
from invenio_records.api import Record as RecordApi
from invenio_formatter.engine import format_record
format_record(RecordApi(es.get(index='hep', id=recid)['_source']), 'hb')```
```

**Comment by annetteholtkamp** [comment]
I fixed some wrong metadata in these 4 records on prod. Not sure it solves the problems below.

- Annette


On Jan 20, 2016, at 10:50 AM, Javier Martin Montull <notifications@github.com<mailto:notifications@github.com>> wrote:


After doing a full test on all the brief formats on qa.inspirehep.net<http://qa.inspirehep.net> the following errors appear:

Recid   Error
874680  unhashable type: 'list'
1230870 expected string or buffer
1238277 unhashable type: 'list'
1317440 expected string or buffer

The xml can be downloaded, for example, https://qa.inspirehep.net/record/874680/export/xm

Loaded locally:

$ inveniomanage migrator populate -f ~/Desktop/xm.xml

And then test the brief format:

$ inveniomanage shell

from invenio_ext.es import es
from invenio_records.api import Record as RecordApi
from invenio_formatter.engine import format_record
format_record(RecordApi(es.get(index='hep', id=recid)['_source']), 'hb')```

**Comment by ioannistsanaktsidis** [comment]
For the first 3 indeed the problem is fixed. I just tested them and they work good. As for the 4th, I can't access the record publicly. Can anyone send me the xml of 1317440 so as to test it?

**Comment by jmartinm** [comment]
That last record does not seem to exist https://inspirehep.net/record/1317440/xm (gives 404) so we can forget about it.

**Comment by ioannistsanaktsidis** [comment]
:+1:

**Comment by annetteholtkamp** [comment]
Not true. It’s in a restricted collection, so you can’t forget about it.

- Annette

**Comment by ioannistsanaktsidis** [comment]
Is it possible to send me the marcxml so as to check it?

**Comment by annetteholtkamp** [comment]
I can access the record only via bib edit. So I could send only the marc file, but not marcxml

- Annette
