### ISSUE TITLE
Hidden records are not hidden

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#766]
An innocent query such as: "upgrade tdr lhcb", brings is 8000 unrelated results:
https://qa.inspirehep.net/search?cc=hep&post_filter=experiment%3A%22CERN-LHC-LHCb%22&p=upgrade+tdr+lhcb&action_search=&sf=&so=&rg=25&post_filter=experiment%3A%22CERN-LHC-LHCb%22

And clicking on the LHCb facets is broken...

**Comment by annetteholtkamp** [comment]
This message is weird as well:
8377 of 0 results match the filters you selected.

- Annette

On 21 Jan 2016, at 22:32, Samuele Kaplun <notifications@github.com<mailto:notifications@github.com>> wrote:


An innocent query such as: "upgrade tdr lhcb", brings is 8000 unrelated results:
https://qa.inspirehep.net/search?cc=hep&post_filter=experiment%3A%22CERN-LHC-LHCb%22&p=upgrade+tdr+lhcb&action_search=&sf=&so=&rg=25&post_filter=experiment%3A%22CERN-LHC-LHCb%22

And clicking on the LHCb facets is broken...

**Comment by kaplun** [comment]
eheheh :dancer:

**Comment by jmartinm** [comment]
@kaplun This looks better now?

What is the current problem?

**Comment by kaplun** [comment]
So the facet is now correct (also the numbering).

The error stems from the fact that the hidden(?) D0 collaboration records, contain "upgrade" in one of the author, and this make them too much boosted. 

I guess this particular issue is going to be solved as soon as hidden records, are hidden for real :-)

**Comment by jmartinm** [comment]
Task to hide records is here https://github.com/inspirehep/inspire-next/issues/796
