### ISSUE TITLE
Elasticsearch: error when going over the 10.000 result

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#785]
As ElasticSearch sets a limit on how many results are ranked, if one visits the last page of search results, the following error happens:

```
TransportError(500, u'search_phase_execution_exception', u'Result window is too large, from + size must be less than or equal to: [10000] but was [1114950]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.')
```

There seems to not be a solution for this, either we don't allow to visit pages after a certain one or we change the `limit` parameter.

**Comment by kaplun** [comment]
IMHO the value of going to the last page is to implicitly reverse the order of the results to check the oldest paper (no one would really want to look for the least matching or the least cited).

So: shall we simply add 4th rank method which is "oldest first"?
