### ISSUE TITLE
Support for Hidden/restricted collections

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#796]
- [ ] Restrict hidden documents D0 CDF etc.
- [ ] Move hidden jobs (i.e. what to do when a record exist and should be moved to a different collection)

**Comment by kaplun** [comment]
See also #919

**Comment by jmartinm** [comment]
And see also https://github.com/inspirehep/inspire-next/pull/1116

**Comment by StellaCh** [comment]
Is this resolved @jmartinm ?
