### ISSUE TITLE
datatables error

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#805]
The following record https://qa.inspirehep.net/record/947006

![screen shot 2016-02-02 at 11 07 05 am](https://cloud.githubusercontent.com/assets/580727/12746064/1ec28316-c99d-11e5-9bd0-2e52d5dec926.png)

 gives a datatables error.

**Comment by jalavik** [comment]
It also happens in this record https://qa.inspirehep.net/record/1315715

BTW, it reminds me that the MathML is not being rendered.
