### ISSUE TITLE
Facet change resets sorting and number of results per page

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#810]
If a sorting is first applied like, Sort by: `Most Cited` and then a facet selected, the sorting is reseted to the original value.

Same happens with number of results per page.

**Comment by ioannistsanaktsidis** [comment]
This happens because when we click to a facet we the request is sth like this:
```
/search?cc=HEP&p=&post_filter=doc_type%3A%22preprint%22
```
while in the url these parameteres
```
sf=earliest_date&so=desc
```
 still appear. So when we are doing this:
```
<option value="newest"{{ ' selected' if request.args.get('sf') == 'earliest_date' and request.args.get('so') == 'desc'}}>Newest first</option>
```
it will function well as the sf and so are not in the request url.

**Comment by jmartinm** [comment]
Not applicable since we have now moved to AngularJS library.
