### ISSUE TITLE
dojson broken records

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#812]
Currently, the number of broken records is:

```
mysql> select count(*) from inspire_prod_records where successful=False;
+----------+
| count(*) |
+----------+
|    29637 |
+----------+
1 row in set (0.11 sec)
```

After https://github.com/inspirehep/inspire-next/pull/761 has been merged the number should be reduced.

I will now rerun all the records and keep track in this task of the new number of failures.

**Comment by jmartinm** [comment]
Definitely an improvement:

mysql> select count(*) from inspire_prod_records where successful=False;
+----------+
| count(*) |
+----------+
|      146 |
+----------+

Will extract the XML of the failed ones to see what was wrong.

**Comment by jmartinm** [comment]
Here are the records that are currently failing:

https://www.dropbox.com/s/zcgh2vu8hckkc0s/wrong-dojson.xml?dl=0

**Comment by jalavik** [comment]
Nice! I guess the 115 errors we got from Celery and migrate_chunk task are among these. E.g.

```
Task inspirehep.modules.migrator.tasks.migrate_chunk 
with id c9af7532-7c6b-46fc-bf9e-848c08e16362 raised exception:
'BulkIndexError(u\'1 document(s) failed to index

.\', [{u\'index\': {u\'status\': 400, u\'_type\': u\'record\', 
u\'_id\': u\'962940\', u\'_index\': u\'jobshidden_v2\', 
u\'error\': {u\'type\': u\'mapper_parsing_exception\',
 u\'reason\': u\'failed to parse [deadline_date]\', 
u\'caused_by\': {u\'reason\': u\'Invalid format: "2011-01" is malformed 
at "-01"\', u\'type\': u\'illegal_argument_exception\'}}}}])'

```

**Comment by jmartinm** [comment]
These are actually errors from the dojson conversion so they are never sent to ES.

We should create a separate issue with the errors related to indexing :)

**Comment by jalavik** [comment]
@jmartinm Aight cool. I will do that

**Comment by ioannistsanaktsidis** [comment]
I fixed most of the problems with the records concerning this xml file, although there are still some issues with the dois. I will first fix this issue https://github.com/inspirehep/inspire-next/issues/709 and after is merged I will finish this one.
