### ISSUE TITLE
Proofchecking queries

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#817]
- [ ] `journal:` field (to actually use refextract to build corresponding query)
- [ ] `refersto:` nested support
- [ ] `citedby:` basic support (this need to bypass ES, and simply load all the records from the corresponding recid)
- [ ] `citedby:` nested support
- [ ] `eprint:` should understand both `arxiv:1007.5048` and without the `arxiv` prefix
- [ ] `fulltext:` should work
- [x] `author:"b storaci"`, `author:"b. storaci"` should be the same (see also https://inspirehep.net/info/hep/search-tips?ln=en#author)
- [ ] `author:B.Storaci.1` should work (assuming BAIs are fetched from HepNames)
- [ ] `topcite:200+` should return all the record with more than 200 citations (@panos512)
- [ ] `find r atlas-conf-*`: search by reportnumber (@panos512)
- [ ] `find cc italy`: search by country (or country code)
- [ ] `find caption "Diagram for the fermion flow violating process"` caption 
- [ ] `find tc book`: type codes (@panos512) (#970)
- [ ] `find fc a`: field codes (@panos512) (#971)

For reference see: https://inspirehep.net/info/hep/search-tips

**Comment by kaplun** [comment]
cc: @jalavik, @jmartinm the above are documented searches on Legacy that do not work on QA. Many of them can not be addressed in the current milestone.

**Comment by Panos512** [comment]
'refersto' and 'citedby' can popup a message that they are unsupported (with the flash technique), until we fix them.

I will check if we can quickly fix some of the others and come back for more.

**Comment by StellaCh** [comment]
outdated
