### ISSUE TITLE
Search wildcards

### ISSUE THREAD

**Issue by Panos512** [inspirehep/inspire-next#831]
Currently on inspirehep.net we support wildcards. 
E.g. someone can query for `muon*` or `find r atlas-conf-*` . 

We can have this on labs but the problem is that a `*` character can also be used as the multiplication symbol. What we could do is have the users use a special character to "wrap" a `wildacrad query` (as `/` is used for a regex query e.g. `title:/^E.*s$/`).

**Comment by kaplun** [comment]
cc: @inspirehep/inspire-dir

**Comment by bing13** [comment]
As a wildcard, is * ever actually used anywhere but at the very end of the search string?  If not, that would allow a more graceful and user-friendly disambiguation.

**Comment by ksachs** [comment]
SPIRES had # as wildcard (just thinking out loud - not necessarily serious)
-> colou*rs, symmetr#

**Comment by jmartinm** [comment]
A search like `find r atlas-conf-*` is indeed quite nice and easy to explain (vs the verbose regular expression version)

Do you have some examples from production where the ambiguity between that symbol and the multiplication symbol is giving unexpected results?

**Comment by kaplun** [comment]
If I am not mistaken there are particles having `*` in their name. Correct? Actually I guess these are not searchable in today INSPIRE either.

**Comment by bing13** [comment]
If so, whoever named those particles should be punished.

**Comment by kaplun** [comment]
There's a PR for this right? Or it's even a duplicate right now?

**Comment by Panos512** [comment]
Yes, it's here https://github.com/inspirehep/inspire-next/pull/961 .

**Comment by hoc3426** [comment]
They're for excited states and I think people would be unlikely to search
on them. Yes, you could search them on SPIRES:
-> fin t n*
-Result: 287 DOCUMENTS
-> typ

10915630
Isospin decomposition of $\gamma N \to N^*$ transitions within a dynamical
coupled-channels model.

Fun story, when INSPIRE first arrived one of my physicist friends was very
pleased that the "outdated, 1960s era # had been replaced by * for
truncation".

H :-)
