### ISSUE TITLE
Display link back from detailed page to search results

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#846]
When accessing a detailed record page we should have a link back to the search results.

2 options are possible:

1) The page is accessed from a search page. Then the `request` referer should contain information about the query made that can then be displayed.

![screen shot 2016-02-08 at 4 23 15 pm](https://cloud.githubusercontent.com/assets/580727/12889701/69ed2c14-ce80-11e5-91ca-623242905167.png)

2) The page is accessed directly (without a search page referer) like from a Google page. Then we can display a different (more generic) message.

![screen shot 2016-02-08 at 4 26 32 pm](https://cloud.githubusercontent.com/assets/580727/12889767/c4539bb6-ce80-11e5-9ca0-5aab5ea51fd1.png)

**Comment by bing13** [comment]
Great.  Where would "Browse all literature" take the user?

**Comment by jmartinm** [comment]
> Great. Where would "Browse all literature" take the user?

The idea was to go to an empty search, like https://inspirehep.net/search so that all results are shown.

**Comment by jmartinm** [comment]
Done.
