### ISSUE TITLE
Capitalize titles when all uppercase

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#847]
When titles are all uppercase they should be capitalized (and **only** in that case)

Example

![screen shot 2016-02-08 at 4 41 11 pm](https://cloud.githubusercontent.com/assets/580727/12890159/c7609fb4-ce82-11e5-9487-5635e1f6808d.png)

There is already a filter but it is not being used at the moment. https://github.com/inspirehep/inspire-next/blob/master/inspirehep/ext/jinja_filters/record.py#L454

**Comment by jmartinm** [comment]
Looking closely at what happens in [current production](https://inspirehep.net/record/201328), if a title is all in capital letters in the metadata, like:

`RACETRACK: A COMPUTER CODE FOR THE SIMULATION OF NONLINEAR PARTICLE MOTION IN ACCELERATORS`

On display time, all words get capitalized:

`Racetrack: A Computer Code For The Simulation Of Nonlinear Particle Motion In Accelerators`

Do we still want that, or we capitalize the sentence?

`Racetrack: a computer code for the simulation of nonlinear particle motion in accelerators`

cc @inspirehep/inspire-dir

**Comment by kaplun** [comment]
Wild idea: what if we build a statistical dictionary based approach (based on the correct existing title) and automatically correct these titles? E.g. we could:
* consider all the non-capitalized titles in INSPIRE
* ignoring the first word of sentences, build a dictionary with every word (counting how many times these appear).
* We can then query the dictionary and take the case of the most common word that matched.
* If a word don't match we can simply decide to make it lower
* Of course if it's at the beginning of a sentence we respect the case.

This could be a nice quick project to correct in general the case of all the old records. On average it cannot be worse than the current all-capitalized titles.

**Comment by annetteholtkamp** [comment]
Great idea

- Annette


On 09 Feb 2016, at 10:23, Samuele Kaplun <notifications@github.com<mailto:notifications@github.com>> wrote:


Wild idea: what if we build a statistical dictionary based approach (based on the correct existing title) and automatically correct these titles? E.g. we could:

  *   consider all the non-capitalized titles in INSPIRE
  *   ignoring the first word of sentences, build a dictionary with every word (counting how many times these appear).
  *   We can then query the dictionary and take the case of the most common word that matched.
  *   If a word don't match we can simply decide to make it lower
  *   Of course if it's at the beginning of a sentence we respect the case.

This could be a nice quick project to correct in general the case of all the old records. On average it cannot be worse than the current all-capitalized titles.

**Comment by ksachs** [comment]
Bad examples:

Diffraction And Precise Qcd Measurements At Hera
[https://inspirehep.net/record/1422853?ln=en]

Soft Qcd At The Lhc
[https://inspirehep.net/record/1422855?ln=en]

I think it's the hole conference:
[https://inspirehep.net/search?ln=en&p=773__w%3AC12-03-10&ot=245&action_search=Search]

**Comment by ksachs** [comment]
Looking at the Moriond contribution titles, could we keep it simple?

    High Order Qcd Predictions Of The Higgs Boson Production Cross-Section At The Lhc

is almost unreadable. I think non-capitalized titles are better

    High order qcd predictions of the higgs boson production cross-section at the lhc

With a KB of (basic) acronyms and the names of collaborations from the EXP collection ->

    High order QCD predictions of the higgs boson production cross-section at the LHC
