### ISSUE TITLE
Proper validation of authors in the form

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#852]
Do not allow invalid format for authors.

The format should be `last name(s), first name(s)`

We are getting some bad formats such as `firstname lastname`

**Comment by StellaCh** [comment]
is this resolved @jmartinm ? If so, feel free to close the issue

**Comment by michamos** [comment]
This has been resolved but in a [different way](https://en.wikipedia.org/wiki/Robustness_principle): instead of shouting at users when they type the author name in the wrong format, we normalize it so that it conforms to our format.
