### ISSUE TITLE
Extract user references

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#854]
References should be extracted from:

a. from pdf if link given
OR
b. from textbox if references pasted

See related https://github.com/inspirehep/inspire-next/pull/206

**Comment by jmartinm** [comment]
This depends as well on the status of Grobid APIs

**Comment by StellaCh** [comment]
@jmartinm is this fixed?

**Comment by jacquerie** [comment]
Yes, by @iulianav in https://github.com/inspirehep/inspire-next/pull/2854.
