### ISSUE TITLE
Split publication note from arxiv after import

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#855]
After importing from arxiv sometimes we get something like **Nucl.Instrum.Meth. B325 (2014) 15-26**  that we are adding to the Journal name field. Instead this should be split into parts and added to the appropriate (Name, Volume, Year, ...)

See related https://github.com/inspirehep/inspire-next/pull/191

For this we can use the Grobid API.

**Comment by kaplun** [comment]
This could be small enough for a bootcamp, since it simply requires to plug a tool in the proper place.

**Comment by StellaCh** [comment]
Is this resolved @michamos @jacquerie ?

**Comment by michamos** [comment]
Hepcrawl is populating `pubinfo_freetext`, and refextract is called in the workflow to split it up into a proper `publication_info`.
