### ISSUE TITLE
Avoid google links

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#856]
We should refuse google links like
 https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=4&ved=0CC0QFjADahUKEwiRoOC9vqrHAhXIuhQKHckkAMw&url=http%3A%2F%2Fpos.sissa.it%2Farchive%2Fconferences%2F247%2F033%2FDIS2015_033.pdf&ei=4t_OVZGnJ8j1UsnJgOAM&usg=AFQjCNGr128Do2G1vJlxjYdEEFVkKPpmXA&sig2=FhluqPXzQqNQgQUrnIpiVw&bvm=bv.99804247,d.d24

In the Link to PDF validator and instead ask the user to supply a direct link.

**Comment by kaplun** [comment]
What about resolving it and see if it corresponds to a PDF? Security risks?

**Comment by StellaCh** [comment]
this is handled correctly in the current Labs
