### ISSUE TITLE
Smarter journal name recognition

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#857]
The Journal name in the submission form is currently being looked up in a Knowledge Base and if a match is found, our canonical name is used.

One example of improvement is "Phys. Scr.".  The kb knows the mapping PHYS SCR---Phys.Scripta

So by removing punctuation we should be able to find the correct match.

**Comment by kaplun** [comment]
BTW at the same time we should start using the Journal DB at its full.

**Comment by aw-bib** [comment]
If the submission form accepts a DOI for import I'd strongly encourage to consider using the ISSNs instead of/additionally to names (beware though that a "Journal" has many of them).

**Comment by jmartinm** [comment]
We now query the Journals DB and normalize the name based on the `title_variants`.
