### ISSUE TITLE
Formulas facet: wrong HTML id

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#862]
When clicking on the formulas facet in order to hide it, the wrong facet (the first one) gets hidden.

![screen shot 2016-02-09 at 1 17 59 pm](https://cloud.githubusercontent.com/assets/580727/12916023/8d8699b2-cf2f-11e5-92f6-958a7a05bc91.png)

**Comment by kaplun** [comment]
Nice!
