### ISSUE TITLE
mathoid: cannot find app.js

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#864]
On Mac OS, the current Procfile line:

`mathoid: nodejs node_modules/mathoid/server.js -c node_modules/mathoid/config.dev.yaml`

produces an error because of `app.js` not found.

One possible solution is to create a file `mathoid.config.yaml` in the root INSPIRE folder with this line inside:

```
module: ./node_modules/mathoid/app.js
```

And change `Procfile` to:

```
mathoid: node node_modules/mathoid/server.js -c mathoid.config.yaml
```

**Comment by jacquerie** [comment]
Maybe we should test on both `linux` and `osx`? https://docs.travis-ci.com/user/multi-os/

**Comment by jalavik** [comment]
@jacquerie Depends what the full goal is. We are developing in a different environment than what production runs. And developer A on MacOS is different than developer B on Debian. The obvious answer here is the Docker container setup, which we partly have in Travis, but running on a ubuntu based setup - different than the puppet based CentOS7/SLC6 based production/qa machines.

So a myriad of systems here.. ideally they should be all the same all the way. Question is, is everyone ready for a Docker based dev environment?

**Comment by kaplun** [comment]
@jmartinm indeed anyway the config.yaml file should be shipped with our repo. So I will prepare one with the above suggestion.

**Comment by jacquerie** [comment]
@jalavik I'd love to have a Docker-base environment — but I'm not running one, so it's a bit awkward for me to push for it : )

That said, we are constantly losing productivity because of the variety of environment we run/support and the variety of ways stuff breaks on each of them. It is something that must be considered, I think.

**Comment by jalavik** [comment]
The INSTALL.rst should also be updated with instructions for the new server:

```
cdvirtualenv src/inspire-next
npm install
```
