### ISSUE TITLE
Brief and detailed record: display full date or just year ?

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#865]
On Labs we are currently displaying only the year:

![screen shot 2016-02-09 at 3 14 42 pm](https://cloud.githubusercontent.com/assets/580727/12918557/089aa8fe-cf40-11e5-99bd-fe14e72399f4.png)

While on production we display a full date:

![screen shot 2016-02-09 at 3 14 28 pm](https://cloud.githubusercontent.com/assets/580727/12918503/d3c75942-cf3f-11e5-82bd-898b745664fe.png)

So, if available, we display a human-readable full date? cc @inspirehep/inspire-dir

**Comment by hoc3426** [comment]
I think the full date is nice.

**Comment by kaplun** [comment]
:+1: it's something user are going to be interested into (e.g. imagine for an important paper, to see when exactly it came out and what legacy it had).

**Comment by bing13** [comment]
:+1:
