### ISSUE TITLE
Remove leading numbers from plot captions

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#870]
All plot captions have a trailing number:

![screen shot 2016-02-09 at 5 27 41 pm](https://cloud.githubusercontent.com/assets/580727/12922618/82cf50ea-cf52-11e5-99c2-f2700497c1f4.png)

Does this have any meaning? Shall we remove it on display or at the source?

**Comment by jmartinm** [comment]
@jalavik we have talked about this in the past.

**Comment by jalavik** [comment]
@jmartinm It's a legacy label that simply numbers the plots in order of appearance in the TeX I believe. It has no real value beside that. I might even have been introduced with some reason related to BibDocFile, but I cannot recall.

**Comment by jmartinm** [comment]
Alright, so I will remove it from the display for the moment and we will see if we remove it at the source further along.

**Comment by jmartinm** [comment]
Done https://github.com/inspirehep/inspire-next/pull/874
