### ISSUE TITLE
mapping: repetition of curated_relation within authors

### ISSUE THREAD

**Issue by jacenkow** [inspirehep/inspire-next#875]
https://github.com/inspirehep/inspire-next/blob/master/inspirehep/base/jsonschemas/hep-0.0.1.json#L892

Currently the ```Elasticsearch``` mapping of ```hep``` collection contains ```curated_relation``` field as well as ```claimed```, which hold exactly the same information.

**Comment by jacenkow** [comment]
CC: @kaplun

**Comment by kaplun** [comment]
cc: @ioannistsanaktsidis @jmartinm

**Comment by ioannistsanaktsidis** [comment]
Claimed needs to be erased. You can assign it to me.
