### ISSUE TITLE
Make use of invenio-collections ?

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#919]
Previously we were making use of https://github.com/inveniosoftware/invenio-collections that was connecting to the `before_record_update` signal to always add a `_collections` field to a record.

This field was used, for example, to know if a certain user had permission to see a collection.

The status of `invenio-collections` needs to be evaluated and decided if we make use of it.

A concrete task to test is to make hidden collections not show in a general HEP search. With our current demo records 427 results are obtained but only 426 should be shown as one is part of the hidden collection `CDF Internal Notes`.

See [this test](https://github.com/inspirehep/inspire-next/commit/dcff4ded8184e64c1e1aed5398280694fa0f87eb#diff-1200a5bdb3e2ab7c11ec659179d2474aR54)

**Comment by kaplun** [comment]
Is there a reason not to use `invenio-collections`?

**Comment by jalavik** [comment]
@jmartinm Said to check if we can just get the permissions part from a permissions factory in `records-rest`
