### ISSUE TITLE
Make use of permissions

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#920]
An example of how we were using permissions to restrict a view:

https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/workflows/views/holdingpen_edit.py#L73

The new way of handling permissions needs to be checked (possibly using https://github.com/inveniosoftware/invenio-access) and see if our use cases are currently supported (implement them otherwise):
- [ ] Restrict access to a workflow view
- [ ] Restrict access to workflow API
- [ ] Restrict access to files API

@jalavik @kaplun any other use cases?

**Comment by kaplun** [comment]
Today not so many more.
As soon as we start building curation tools we will have to protect them accordingly (as in old `runbibedit`, `runfilemanager`, `runmultiedit`...

**Comment by jmartinm** [comment]
With https://github.com/inspirehep/inspire-next/pull/1817/files and https://github.com/inveniosoftware-contrib/invenio-workflows-ui/pull/17 we should have restrictions in place.

**Comment by jmartinm** [comment]
Done.

**Comment by kaplun** [comment]
Are we restricting the callback from legacy? If yes, how does it work?

**Comment by jmartinm** [comment]
Nope, that part has never been restricted.
