### ISSUE TITLE
Loading fixtures

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#921]
We currently have the following fixtures:

https://github.com/inspirehep/inspire-next/tree/master/inspirehep/base/mixer

We will have to port the `mixer` functionality to make them work again - https://github.com/inspirehep/invenio-ext/tree/master/invenio_ext/mixer

* [ ] Collections fixtures - depends if we use `invenio-collections`
* [ ] Knowledge fixtures - `invenio-knowledge` needs to be Invenio 3 ready
* [ ] Oaiharvest fixtures - @jalavik still applicable?

**Comment by kaplun** [comment]
For Knowledge, as discussed on gitter with @tiborsimko & Lars, it's probably worth considering if we can do without them and just choose between record-based KBs and simple config lists.

**Comment by jalavik** [comment]
The OAI harvest fixtures are not strictly needed (e.g. not worth the effort if this is the only thing using it).

**Comment by kaplun** [comment]
Also for collections we are going to probably just dump them in a simple script. So we can close this ticket. Yay
