### ISSUE TITLE
Suggestion form

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#924]
Current HEP suggestion form uses `invenio-deposit` which has been deprecated.

We need to port it to an approach similar to how the author update/addition form works.

Forms will be generated using the existing wtforms and with the [forms module](https://github.com/inspirehep/inspire-next/tree/invenio3/inspirehep/modules/forms) then a workflow can run on form submission.

As the content of the form will not be saved anymore in the database, we should keep the values in the user session so that reopening the form after accidentally navigating away still keeps the values.
- [x] Port wtforms Literature forms and all JS dependencies
- [x] Move all needed parts from legacy `invenio-deposit` to overlay
- [x] Port literature workflow
- [x] Check integration with holding pen
- [x] Port extensions to query arXiv and Crossref
- [ ] Save content of the form in the user session

**Comment by kaplun** [comment]
What about the deposition dashboard? Will it be possible to let the user see what she submitted in the past? (even things that haven't been approved as records)

**Comment by jalavik** [comment]
AFAIK, dashboard is not part of this yet. For the first iteration we may not need it - we can check how many accessed `https://labs.inspirehep.net/submit/literature` to check if it is already widely used. It would be nice to have though, and could be queried by getting all workflow objects for the current user id.

**Comment by kaplun** [comment]
Right! So should the need arise, we are going to have all the necessary number and references in the workflow models. Perfect.

**Comment by jalavik** [comment]
This is mostly done now I guess? Apart from the user session. Perhaps we make a new issue?

**Comment by jmartinm** [comment]
> This is mostly done now I guess? Apart from the user session. Perhaps we make a new issue?

Yes.
