### ISSUE TITLE
Port invenio-knowledge module

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#927]
We currently use `invenio_knowledge` in different components:

https://github.com/inspirehep/inspire-next/search?utf8=%E2%9C%93&q=invenio_knowledge

The module can be made Invenio 3 ready so that we can use it again.

**Comment by kaplun** [comment]
* [ ] Port `CODENS` KB to use the journal collection
* [ ] Port `DEPOSIT_INSPIRE_SUBJECTS_KB` to a file resource
* [ ] Port `DEPOSIT_INSPIRE_DEGREE_KB` to a file resource
* [ ] Port `DEPOSIT_INSPIRE_JOURNALS_KB` to the journal collection (this is going to be done also on Legacy!)

**Comment by kaplun** [comment]
cc: @ioannistsanaktsidis

**Comment by kaplun** [comment]
@jacenkow @ioannistsanaktsidis has someone worked on it?

**Comment by kaplun** [comment]
Actually: `DEPOSIT_INSPIRE_SUBJECTS_KB` and `DEPOSIT_INSPIRE_DEGREE_KB` is going to be moved by @tomaszgy into sub jsonschemas.

**Comment by ioannistsanaktsidis** [comment]
I started implementing some parts which I needed for Bibtex, latex , but in the end I realised that I didn't need them so I dropped it.

**Comment by kaplun** [comment]
@ioannistsanaktsidis `CODENS` where needed in BibTeX and LaTeX conversion. How are you doing at the moment then?

**Comment by ioannistsanaktsidis** [comment]
Here it is https://github.com/ioannistsanaktsidis/inspire-next/blob/invenio3-formatter-with-angular/inspirehep/utils/bibtex.py#L668-L675 . Stiil in an open PR through. I will need @jacquerie tests to confirm 100% it is working.

**Comment by kaplun** [comment]
OK I guess we can close this particular issue as we are anyway not porting KBs, rather reimplementing each time a particular solution.
