### ISSUE TITLE
Complete Elasticsearch mapping

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#928]
Our [data models](https://github.com/inspirehep/inspire-next/tree/invenio3/inspirehep/modules/records/jsonschemas/records) and [mappings](https://github.com/inspirehep/inspire-next/tree/invenio3/inspirehep/modules/records/mappings/records) need to be aligned.

There was a first attempt by @kaplun https://github.com/inspirehep/inspire-next/pull/745

It needs to be checked if we can use https://github.com/inveniosoftware/domapping to automatically generate the ES mapping out of our jsonschema.

**Comment by kaplun** [comment]
@jmartinm I indeed used `domapping` at that time to generate one of the inputs, I have also used what ES had derived implicitly from all our data. And then merged the 2 JSONs.

**Comment by jmartinm** [comment]
@jacquerie how are we doing with this? Changed milestone since this is currently blocking https://github.com/inspirehep/inspire-next/pull/1964 and https://github.com/inspirehep/inspire-next/pull/1978

**Comment by jacquerie** [comment]
Alignment happened in https://github.com/inspirehep/inspire-next/pull/2003.
