### ISSUE TITLE
Revise existing modules and port needed functionality

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#930]
```bash
modules/
├── __init__.py
├── access
├── audit
├── authors
├── citations
├── converter
├── deposit
├── formatter
├── forms
├── (harvester)
├── migrator
├── oaiharvester
├── predicter
├── (ranker)
├── records
├── refextract
├── styleguide
└── workflows
```

**Comment by kaplun** [comment]
Shall we move them outside of the overlay? Such as `predicter`, `audit`... 
`ranker` can be forgotten.

**Comment by jalavik** [comment]
`audit` is currently a model only, so probably no need to make a separate package yet. However `predicter` has some meat to it, but should be renamed as the name is not a correct english word. 

`harvester` can also be forgotten WRT v3 as `hepcrawl` will take care of it's duties.

**Comment by kaplun** [comment]
Yep sorry it wasn't clear from my message: only `ranker` was to be forgotten :wink:

**Comment by jalavik** [comment]
Anything missing here? Perhaps this issue is too generic at this point?

**Comment by jmartinm** [comment]
Yes, this issue is quite old. I don't think it is useful anymore.
