### ISSUE TITLE
Add support for retrieving list of search recids (former /search?of=id)

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#931]
The functionality to query the search API with `of=id` was being used in several places in order to retrieve a list of recids.

If needed, it needs to be implemented in the best possible way (using the `search/` view, calling `invenio-records-rest` or using the `pidstore` or...)

**Comment by kaplun** [comment]
Mmh. Ideally this is a central API and we should now take the occasion to standardize this following the Invenio patter of having `/api` route. I believe `invenio-records-rest` is indeed offering this functionality.

**Comment by kaplun** [comment]
@jmartinm I this is no longer needed, right?

**Comment by jmartinm** [comment]
I am not sure, it was first requested by @jacquerie or @ioannistsanaktsidis , do you remember if we still need it?

**Comment by jacquerie** [comment]
As long as the `/api` endpoint has this feature (do we need a proper `content-type`?)...

**Comment by ioannistsanaktsidis** [comment]
This one was needed so as to be able to export all search results(5000 was
the limit). If API provides it then we are ok.

**Comment by kaplun** [comment]
Mmh. Do we think there is going to be a real use case where someone is going to look more than 5000 results in one go? I guess since anyway we are moving away from really advertising recids, we can assume whomever will want query INSPIRE for more than 5000 records will use the provided /api that let you obtain all the results by issuing multiple requests.

**Comment by ioannistsanaktsidis** [comment]
Yes but what about if someone search for higgs for example and then want to
export all the higgs papers ?

**Comment by kaplun** [comment]
I guess in that case the purpose is more to do some statistics analysis or further data manipulation. So he/she probably going to write anyway a script that can query the API using the scroll interface.

Seems this is supported by invenio-records-rest: https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/views.py#L387

**Comment by jmartinm** [comment]
So the use case for @ioannistsanaktsidis that I remember was:

1) User searches for `higgs`
2) The first page contains 25 results. The user clicks on cite-all button and an option appears to 'Cite 5000 results'.
3) On the client side a call to /search?p=higgs&of=id was being done to retrieve all ids and a call to the server side was done to export all the `bibtex` for the formats.

Do we need this now?

A call to /api/ with `Accept:bibtex`  and the query `higgs` would give us the bibtex that we can display on the interface, non?

**Comment by jacquerie** [comment]
My (transient) use case: extending https://gist.github.com/jacquerie/a046e5b4aa5aec1de68a to become an acceptance test for our search, comparing results against legacy to see if some queries require further attention.

**Comment by jmartinm** [comment]
> My (transient) use case: extending https://gist.github.com/jacquerie/a046e5b4aa5aec1de68a to become an acceptance test for our search, comparing results against legacy to see if some queries require further attention.

Although a bit heavy, maybe you can do the query through the JSON API and the get `record[control_number]` from each result.

Problem might be the limitation to 10000 results, in which case maybe you need your own endpoint that uses [scroll](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html)

**Comment by jacquerie** [comment]
Partly addressed by https://github.com/inspirehep/inspire-next/pull/2876.

**Comment by StellaCh** [comment]
What is missing @jacquerie ?

**Comment by jacquerie** [comment]
> What is missing @jacquerie ?

Do we want to preserve the old API, and write redirector controllers that rewrite queries using the old API to use the new, or are we going to do a breaking change?

**Comment by jacquerie** [comment]
But we might want to decide that (in general, the issue of which legacy routes to continue handling) in another issue.
