### ISSUE TITLE
Separate endpoints for each document type

### ISSUE THREAD

**Issue by jacenkow** [inspirehep/inspire-next#937]
Since we just moved to ```Invenio3``` it is not too late to consider a major update. It's just a proposal and I want to open a discussion.

At the moment all the records, despite the type (```hep```, ```hepnames``` and so on) are accessible by the same endpoint, ie. ```record/:recid```. I was wondering if we can introduce separate endpoints, so the ```hep``` articles could be reached by ```articles/:recid```, ```hepnames``` by ```authors/:recid``` and so on. The first con and I believe the most important is the clarification where the users are, the second (at least for me) is more cleaner code instead of building lookup dictionaries and loading a 'correct piece of code' and I think there are many other arguments in favor. However it requires to rebuild some stuff, but since we just started it is still worth of considering.

Obviously the ```record``` endpoint must be preserved, since we want users to still be able to access the content, but after reaching a specific document via ```record/:recid``` a redirection to a proper path would occur.

CC: @kaplun, @jmartinm, @jalavik, @jacquerie

**Comment by kaplun** [comment]
@jacenkow have you seen discussion in Gitter:
lnielsen feb 27 00:31
It’s already taken care of  https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/views.py#L212-L226

lnielsen feb 27 00:36
http://pythonhosted.org/invenio-records-ui/usage.html#redirection

**Comment by kaplun** [comment]
* [ ] Defines desired endpoints (I guess we still want to have `/literature/123` and `/record/123` to use the same IDs
* [ ] Check implementation of `pidstore`/`invenio-records-ui/rest` as suggested by @lnielsen for how to implement this via configuration.
* [ ] Amend `JSONSchema`/`dojson` to generate `jsonref`in order to represent relations.

**Comment by kaplun** [comment]
Let's say that the first 2 are kind of a blocker for 3. After having defined official new URLs for objects in INSPIRE it will be then time to expose these URLs in the correct way using $ref and whatnot, rather than the current usage of plain `recid` integers.

**Comment by kaplun** [comment]
BTW Just moved Point 3 to #958 as a bootcamp for @mihaibivol
