### ISSUE TITLE
Porting reference to use JSONref

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#958]
* [ ] Amend all JSONSchemas to have 
```json
"record": {
    "$ref": "http://.../jsonschema/correct-schema.json"
}
```

* [ ] Amend correspondingly the ES mappings
* [ ] Amend dojson to produce:
```json
"record": {
    "$ref": "http://.../type/123"
}
``` 

(instead of `"recid": 123`).
* [ ] Test it :-) 
  * [ ] unit test for dojson
  * [ ] integration test that you can search via the new field
  * [ ] unit test for receiver
* [ ] Generate `recid` on the fly upon indexing using a receiver.

**Comment by mihaibivol** [comment]
Regarding the first point, `$ref` can be just `reffered-schema.json` and will resolve to another schema under the same path.

> $ref can also be a relative or absolute URI, so if you prefer to include your definitions in separate files, > you can also do that. For example:

> ```json
> { "$ref": "definitions.json#/address" }
> ```
> would load the address schema from another file residing alongside this one.. 

Thing is that the validator will validate referred resources at index time before the actual resource is available at a given url. This causes the validator to fail.

**Comment by mihaibivol** [comment]
From the next comment, prepending an additional task:

* [ ] In order to reduce boilerplate in other schema definitions add `json_reference.json` schema as defined above to be served.

**Comment by kaplun** [comment]
:+1:

**Comment by mihaibivol** [comment]
Implementation here for easily moving around the two. #967
