### ISSUE TITLE
Avoid reaching API rate-limit

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#960]
When doing requests from the brief search results, the REST API returns

<img width="279" alt="screen shot 2016-03-03 at 2 32 39 pm" src="https://cloud.githubusercontent.com/assets/580727/13495810/120a22b0-e14d-11e5-9b65-e82bc9acb40b.png">

We need to be careful not to get banned ourselves :)

The configuration of https://github.com/inveniosoftware/invenio-rest needs to be checked to have no limit from within INSPIRE.

**Comment by kaplun** [comment]
Do we risk this? Seems like the limit is well far to be reached from the above screenshot.

**Comment by jmartinm** [comment]
The reset in the screenshot would happen at ` 3:25:57 PM` so 2 hours to make 5000 requests.

Are the requests counted by user, or all the requests that we make to the /search API from our application count for this limit?

**Comment by kaplun** [comment]
Maybe @lnielsen can help by guiding us? :)

**Comment by jmartinm** [comment]
I assume this is not an issue, @lnielsen do you have any insight? Nothing to worry about?

**Comment by jacquerie** [comment]
This is just an issue of adding the right decorator to the routes we want to make sure are always available: https://flask-limiter.readthedocs.io/en/stable/#decorators.

**Comment by lnielsen** [comment]
Right now it's a global limit for the entire REST API which I believe is per remote address. See https://github.com/inveniosoftware/invenio-rest/pull/13 for per-user rate limiting.

**Comment by jmartinm** [comment]
`Flask-limiter` was removed from `invenio-rest` so we are currently not using it.

It is now the installation responsibility to add it - see https://github.com/inveniosoftware/invenio-app/commit/1c3c87c416f0416b7dd98ddf08e8b05db0a8385c
