### ISSUE TITLE
find fc

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#971]
https://inspirehep.net/info/hep/search-tips#fc

Basically one has to simply create an enhancer looking at the subject field and implement the mapping to the single letter.

`find fc astrophysics` and `find fc a` should lead to same results.

**Comment by StellaCh** [comment]
With only 0.07% of the user searches on field-code https://drive.google.com/file/d/0B8eFcMY6pLB1aF84OUE2UHBnSVU/view , this implementation is not a priority

**Comment by StellaCh** [comment]
The stats didn't come from piwik, so they also took cataloguer searches into account

**Comment by StellaCh** [comment]
closing this for now and will reopen it if needed following the user requests
