### ISSUE TITLE
Create year barchart facet

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#975]
Work on the year facet https://github.com/inspirehep/inspire-next/pull/883 should be resumed. This time using the new Angular JS application - https://github.com/inspirehep/inspirehep-search-js

**Comment by jacquerie** [comment]
Done in https://github.com/inspirehep/inspire-next/pull/1256. Some pending issues in https://github.com/inspirehep/inspire-next/issues/1827.
