### ISSUE TITLE
Create brief results in AngularJS

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#997]
Currently, the search results for the HEP collection are implemented in [this template](https://github.com/inspirehep/inspirehep-search-js/blob/master/src/inspirehep-search-js/templates/literature/results.html).

The [parent template](https://github.com/inspirehep/inspire-next/tree/invenio3/inspirehep/modules/search/templates/search) (implemented in Jinja2) for each collection needs to be modified so that the the right [results template](https://github.com/inspirehep/inspire-next/blob/invenio3/inspirehep/modules/search/templates/search/search.html#L105) is used.

- [ ] Brief results for authors (@jacenkow)
- [ ] Brief results for data
- [x] Brief results for conferences
- [x] Brief results for journals
- [x] Brief results for institutions
- [x] Brief results for jobs
- [x] Brief results for experiments

**Comment by eamonnmag** [comment]
Data is an unknown but can investigate today.
Authors is nearly there, but I would like to create simple graphs for each author showing the number of papers and citations timeline. But the latter can arrive later :)

**Comment by eamonnmag** [comment]
Prototype now getting all the data back from hepdata directly. I have some small things to fix with the user of post filters in ES, but apart from that and some small JS additions, it works. Screenshots attached. Can show live on Monday @suenjedt.

![screen shot 2016-04-29 at 14 49 14](https://cloud.githubusercontent.com/assets/282396/14924732/40bd63c8-0e44-11e6-8470-fb8f3007a3a6.png)
![screen shot 2016-04-29 at 14 50 23](https://cloud.githubusercontent.com/assets/282396/14924733/40da18a6-0e44-11e6-9ea2-ec132519ed77.png)

**Comment by suenjedt** [comment]
Looking forward to it @eamonnmag !

**Comment by jmartinm** [comment]
Done.
