### ISSUE TITLE
Cite functionality UI

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#999]
The UI for the cite functionality needs to be ported.

* [x] Cite an individual record both in brief and detailed record - initial work [here](https://github.com/inspirehep/inspirehep-js). The same code should be used in both.

* [x] Cite multiple records.

**Comment by kaplun** [comment]
@ioannistsanaktsidis was there a PR already for this?

**Comment by ioannistsanaktsidis** [comment]
@kaplun yes I forgot to add the issue in the commit message. Will add it tomorrow morning ;)

**Comment by jmartinm** [comment]
Done.
